### ISSUE TITLE
Traslate to Spanish

### ISSUE THREAD

**Issue by AsRoyals** [DiscordSRV/DiscordSRV#1001]
Hi, just a little question, would you or somebody (like me :D) would to traslate the plugin to spanish and put it in the Official languages? 

Thank you :3

Ps: I don't know if this platform was the well way to say that.

**Comment by Vankka** [comment]
DiscordSRV has already been translated to spanish, if you would like to switch to it you can use `/discordsrv setlang es -confirm`. The "Languages Supported" section on Spigot is outdated, which is probably why this might be confusing
