### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Nunya-9018** [DiscordSRV/DiscordSRV#1002]
![image](https://user-images.githubusercontent.com/73594766/106147805-4cdba480-6146-11eb-840e-723c5db187eb.png)

**Comment by Nunya-9018** [comment]
i got an dns error

**Comment by Vankka** [comment]
This is a issue with your DNS configuration or server not being able to resolve `gateway.discord.gg`. You may want to check out https://1.1.1.1/dns/ for a more reliable DNS server, the site contains installation instructions for windows if you scroll far enough. But this isn't a DiscordSRV issue

**Comment by Nunya-9018** [comment]
um i use cloud 9 but it was just working

**Comment by Vankka** [comment]
The DNS server you are using might have gone offline or something faulted in it

**Comment by Nunya-9018** [comment]
but im using it right now but okay thx for the help im new to this plugin
