### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Nunya-9018** [DiscordSRV/DiscordSRV#1003]
how do i update the plugin

**Comment by Vankka** [comment]
1. Remove the old jar
2. Put in the new jar
3. Restart
4. Check over the config files for stuff that didn't get converted over in migration

**Comment by Nunya-9018** [comment]
okay and will stuff be saved

**Comment by Vankka** [comment]
yes

**Comment by Nunya-9018** [comment]
thank you
