### ISSUE TITLE
Minecraft color hex codes

### ISSUE THREAD

**Issue by H4zlq** [DiscordSRV/DiscordSRV#1004]
![image](https://user-images.githubusercontent.com/76235095/106218868-30596e00-6213-11eb-8456-e6937d219fb0.png)

this happens when i use color hex codes in the server

**Comment by c1oneman** [comment]
I also have an issue with hex codes on my server. I have currently had to use the old style as close to my servers colors

**Comment by Vankka** [comment]
Kyori's hex format is now supported on latest development builds. If you're having issues (that aren't bugs, eg. errors) with hex join https://discordsrv.com/discord
