### ISSUE TITLE
Problem with %bungee_total% from PAPI 

### ISSUE THREAD

**Issue by ZielonyQ** [DiscordSRV/DiscordSRV#1006]
I have problem with papi, in serwer is alredy 3 players and its not showing them in DiscordGameStatus on bot and bot dont changing in discord channel the theme
![image](https://user-images.githubusercontent.com/75615714/106369774-779b4800-6354-11eb-9a16-35967be8d965.png)

**Comment by Vankka** [comment]
Try parsing the placeholder with `/papi parse me %bungee_total%`

Related to https://github.com/DiscordSRV/DiscordSRV/issues/977.

**Comment by ZielonyQ** [comment]
for looking like that? DiscordGameStatus: "/papi parse me %bungee_total%" ?

**Comment by Vankka** [comment]
No. Run that command in-game

**Comment by ZielonyQ** [comment]
![image](https://user-images.githubusercontent.com/75615714/106369878-5edf6200-6355-11eb-9ab3-c341d26abdd2.png)

**Comment by ZielonyQ** [comment]
ok :O

**Comment by ZielonyQ** [comment]
i see there is a problem

**Comment by Vankka** [comment]
Yeah that's not a DiscordSRV issue then
