### ISSUE TITLE
Server Down/Up status in a different channel

### ISSUE THREAD

**Issue by St3llarYT** [DiscordSRV/DiscordSRV#1011]
Hi, first time on Github so sorry if I get this wrong. I love the DiscordSRV plugin and am grateful that it meshes so cleanly with Minecraft. Just a quick query: Is it possible to display messages about the server like up status, player count or even server messages on a different channel to the channel used for chat? Many thanks

**Comment by Sunni05** [comment]
You can display some things separately, check out [THIS](https://gist.github.com/q220/70bc8694631d66e87c7a5b6061ed767f) link. Check right above the “Channels:” part.

**Comment by Dinty1** [comment]
There's now a channel called `status` which can be used to display server start/stop messages.
