### ISSUE TITLE
API: Sending message as webhook

### ISSUE THREAD

**Issue by kangarko** [DiscordSRV/DiscordSRV#1012]
Hey there,

I wonder how I can send a message from Minecraft to Discord using your API as webhook? Tried TextChannel#sendMessage but it just sends it through the universal bot. My players requested something like this:

<img width="802" alt="Screenshot 2021-02-03 at 11 50 46" src="https://user-images.githubusercontent.com/1918426/106736682-0f7b8900-6616-11eb-9b91-ee407243a4f0.png">

Thanks so much!

**Comment by Vankka** [comment]
You can make use of the `sendMessage` methods in our `WebhookUtil`

Also if you get a chance, take a look at https://github.com/kangarko/ChatControl-Red/issues/603 - the user is still having the issue and it apparently only happens with messages from DiscordSRV, though I haven't spotted anything obviously wrong on our side. I also believe they might be on our development builds which introduced RGB (see `develop` branch or version `1.22.0-SNAPSHOT`)

**Comment by kangarko** [comment]
Thanks so much, of course I'll help him out and thanks to you for your instructions :)
