### ISSUE TITLE
Commands from CMI

### ISSUE THREAD

**Issue by nisemup** [DiscordSRV/DiscordSRV#1013]
I have a **problem with commands**. As I understand DiscordSRV only uses **standard Minecraft commands** as a trigger. (I'm pretty sure I'm wrong)
Is there any way I can use commands from **another plugin** in alerts.yml (**CMI** in my case)? I just need to get arguments from other commands.

**Comment by Vankka** [comment]
Alerts is not limited to Minecraft's commands, you can use the commands of any plugins in alerts.

**Comment by mrfloris** [comment]
Let me know if you've figured out a way to get cmi commands for alerts. I am trying to see if I can build a collection for github.
