### ISSUE TITLE
MCDiscordReserializer translates user pings to <@!userid| instead of @nickname

### ISSUE THREAD

**Issue by saboooor** [DiscordSRV/DiscordSRV#1016]
This still happens in the latest snapshot build
![image](https://user-images.githubusercontent.com/42164502/107301265-6929ec00-6a38-11eb-9d2d-36dff4a03ce5.png)
#935

**Comment by Vankka** [comment]
Fixed on latest snapshot - https://snapshot.discordsrv.com
