### ISSUE TITLE
The bot doesn't have the "Manage Permissions" permission in the voice lobby (Lobby)

### ISSUE THREAD

**Issue by jbax1899** [DiscordSRV/DiscordSRV#1017]
In my Discord console room, "The bot doesn't have the "Manage Permissions" permission in the voice lobby (Lobby)"

This message prints hundreds of times per minute and is maxing out the CPU (as far as I can tell, I couldn't even restart it).

I gave the bot administrator permissions so that can't be it. I am running the latest version, 1.21.3

**Comment by Vankka** [comment]
If it's saying it doesn't have permission, it doesn't. If it did have Administrator it would also have Manage Permissions. The message is sent every voice tick, which by default is 4 times a second - nothing that should cause a CPU to be fully utilized unless it's a poor one
