### ISSUE TITLE
Placeholder breaks when a discord message is split into two due to uploading an image.

### ISSUE THREAD

**Issue by mibby** [DiscordSRV/DiscordSRV#1018]
DiscordSRV-Build-1.22.0-SNAPSHOT-1612889149

Player uploaded an image with a message. 
![link](https://i.imgur.com/QA3Di84.png)

How it showed in-game.
![link2](https://i.imgur.com/lQOFoMN.png)

How it showed on console.
![link3](https://i.imgur.com/HwUF41o.png)

```
DiscordToMinecraftChatMessageFormat: "&8<&7Discord&8> %toprolecolor%%username%&f: %message%"
DiscordToMinecraftChatMessageFormatNoRole: "&8<&7Discord&8> %toprolecolor%%username%&f: %message%"
```

``%toprolecolor%`` placeholder text only shows for messages that are split with a discord attachment link. It does not show in console for normal bridged discord messages.

**Comment by Vankka** [comment]
Fixed on latest development build - https://snapshot.discordsrv.com

**Comment by mibby** [comment]
Thanks.
