### ISSUE TITLE
question about the alert function

### ISSUE THREAD

**Issue by Blueeyestar** [DiscordSRV/DiscordSRV#1028]
Good day,
We discovered that DiscoredSRV also has an alert function.
Now we would like to receive a message in the channel report if, for example, someone writes the command / gamemode creative in the chat or a staff member throws a user from the server. So that we have an automatic log.
But now I have a problem with connecting alert with the channel report.
in the line channel should the name report or the channel ID?
```

- Trigger: /gamemode
    Channel: report 
    Conditions:
      - '#player.hasPermission("cmi.command.gm") == true'
    Embed:
      Color: "#ff0000"
      Author:
        ImageUrl: "{embedavatarurl}"
        Name: "{username} changed gamemode to ${#args.get(0)}" 
```

**Comment by granny** [comment]
The channel specified in the alert should be the channel name listed in the `Channels` option in `config.yml`. Feel free to ask for help in our discord server next time for the reason specified below.
