### ISSUE TITLE
Discord Replies support

### ISSUE THREAD

**Issue by DerpDerpling** [DiscordSRV/DiscordSRV#1029]
sometimes players of my server gets confused when someone on discord replies to someone else, cause it just shows what they said and not the fact that they were replying to someone... i feel like it should be a feature so that people would know your replying to someone without checking the discord. heres an example of how i feel it should work
![unknown](https://user-images.githubusercontent.com/57187871/108210719-ea007c00-70f9-11eb-87cb-b4649eee5f83.png)

**Comment by Dinty1** [comment]
Added by #1114
