### ISSUE TITLE
Idea: You could add prefix options

### ISSUE THREAD

**Issue by AndrewTheProdigy** [DiscordSRV/DiscordSRV#1031]
For example, in the Minecraft server, and this option was chosen, the host can choose a prefix for the message to show in the selected discord channel. If someone types in the Minecraft server "Hello" it wont show on the discord channel, but if they put "!hello" It'll show in the discord channel.

**Comment by Vankka** [comment]
`DiscordChatChannelPrefixRequiredToProcessMessage`
