### ISSUE TITLE
LuckPerms cache request failed when LP is using MySQL storage

### ISSUE THREAD

**Issue by Gamerz261** [DiscordSRV/DiscordSRV#1033]
Honestly, this probably won't matter too much for us since LuckPerms has a good placeholder API library, but this may affect other people

debug link- (https://bin.scarsz.me/3ec5d490-d194-4ec2-a35c-0fb1540e80b3#243TZziFVp0V6eF9rx6YmgjXhrIsKq2W)

**Comment by Vankka** [comment]
Probably fixed already, but download is unavailable rn

**Comment by Gamerz261** [comment]
Okie
