### ISSUE TITLE
VentureChat + Bungeecord permission issue

### ISSUE THREAD

**Issue by ThaCrash** [DiscordSRV/DiscordSRV#1034]
When setting
VentureChatBungee: true

Any messages send from discord to minecraft, is shown to all players even if the player isn't subscribed to said channel and/or has permission to see said channel

I have read the top bungeecord post, just wondering if it is known and if i am missing something obvious to fix it.

**Comment by Vankka** [comment]
That's handled on VentureChat's side, contact VentureChat's developer
