### ISSUE TITLE
Force to link doesnt work properly

### ISSUE THREAD

**Issue by CraftedVortex** [DiscordSRV/DiscordSRV#1039]
When you enable force players to link their discord account, it blocks them from joining the server and it tells them to dm the bot with the code to link, but you can't get the code unless you have access to chat which you don't if you aren't linked. I ask for when force to link is enabled players will be able to join but not move and get the code.

**Comment by Vankka** [comment]
You can include a Discord server invite in the disconnect message

**Comment by CraftedVortex** [comment]
i know that but to link the minecraft account you need to type in minecraft chat

**Comment by Vankka** [comment]
you do not
