### ISSUE TITLE
Vanilla Team Colors don't display in chat (1.16.5)

### ISSUE THREAD

**Issue by heyimspook** [DiscordSRV/DiscordSRV#1043]
When creating a team with a custom color, the colored name shows up when players join, on the TAB list, and using /me commands, but remains white when actually speaking in chat. I've already tested this without DiscordSRV and it works fine using only Paper. 

I have "use-vanilla-world-scoreboard-name-coloring:" in paper.yml set to "true", as it should be, so I'm not quite sure where the issue lies or if there's another option in the config files I need to change. 

Similar to https://github.com/PaperMC/Paper/issues/3676 and https://github.com/PaperMC/Paper/issues/4142, but these issues only seemed to be resolved by new version releases. Running 1.21.3 and still having this issue.

**Comment by PureVanillaFrance** [comment]
Same issue on my side ! Paper 529 and latest discordSRV

**Comment by Vankka** [comment]
Paper issue https://github.com/PaperMC/Paper/issues/5307

**Comment by PureVanillaFrance** [comment]
Hi,
Why a paper issue ? it works when I don't have discordSRV on.
As soon as I put the plugin I don't have colors anymore
