### ISSUE TITLE
Player skin won't show up as the bot's image [BUG?]

### ISSUE THREAD

**Issue by WolfyRed** [DiscordSRV/DiscordSRV#1044]
In this screenshot, you can see the Minecraft chat bot replicating messages the players are sending, and the players have their Minecraft skin's face as the bot's profile picture.

![image](https://user-images.githubusercontent.com/66114400/110266871-ba23f600-7f8c-11eb-8cac-1194978a6363.png)

In this next screenshot, you see the Minecraft chat bot sending messages, replicating messages the players send in the server, yet the bot does not have the ability of having the player's skins as it's profile picture.

![image](https://user-images.githubusercontent.com/66114400/110267305-85646e80-7f8d-11eb-99bb-dd2b38b35c07.png)

I'm not sure how both servers have a chat bot difference, so I'm wondering if I can fix it.

**Comment by Scarsz** [comment]
Enable `Experiment_WebhookChatMessageDelivery`

**Comment by WolfyRed** [comment]
robot
