### ISSUE TITLE
Vanilla chat colors

### ISSUE THREAD

**Issue by PureVanillaFrance** [DiscordSRV/DiscordSRV#1047]
Hi ! 
Paper fixed the issue with chat colors. But I don't understand now the vanilla scoreboard makes the chat colored and not white.
Any idea how to fix this ? 
Thanks for your help :)

![image](https://user-images.githubusercontent.com/76930233/110505511-810b9300-80fe-11eb-9183-944a4699e251.png)
 
It should be:

![image](https://user-images.githubusercontent.com/76930233/110505546-89fc6480-80fe-11eb-999e-24eae36fc8b4.png)

Thanks :)

**Comment by Vankka** [comment]
This issue is caused by the fix paper added for the last issue, there is a new Paper issue for this at https://github.com/PaperMC/Paper/issues/5327
