### ISSUE TITLE
Vanilla Chat scoreboard bug 542 #5336

### ISSUE THREAD

**Issue by PureVanillaFrance** [DiscordSRV/DiscordSRV#1048]
hat behaviour is expected:
< PLAYER > text with PLAYER in color only

What behaviour is observed:
< PLAYER > text with all white. No scoreboard colors with vanilla to true

Steps/models to reproduce:
build 542 with discordSRV

Plugin list:
DISCORDSRV

Paper version:
542

![image](https://user-images.githubusercontent.com/76930233/110678916-2134eb00-81d7-11eb-963b-daefea3273a9.png)

It should be like this.

But now everything is white (the player name is white eventhought he is in vanilla scoreboard team).

![image](https://user-images.githubusercontent.com/76930233/110678925-242fdb80-81d7-11eb-8875-814268535e57.png)

I already put to true vanilla scoreboard in paper.yml.
It worked before :)

Paper says this issue comes from you https://github.com/PaperMC/Paper/issues/5336

Thanks for your help !

**Comment by Vankka** [comment]
Alright let me talk to paper then because DiscordSRV doesn't modify chat

**Comment by PureVanillaFrance** [comment]
Thank you very much ! :)

**Comment by Vankka** [comment]
Since Paper reopened the issue, I'm closing this out
