### ISSUE TITLE
Suggestion: Add an option to Sync groups without including parents

### ISSUE THREAD

**Issue by R4z0rX** [DiscordSRV/DiscordSRV#1051]
Hi!
There's this option:
```
# GroupRoleSynchronizationPrimaryGroupOnly: if true, only the player's primary group is counted for synchronization,
#                                           otherwise, group sync counts all groups the player is in, including parent groups
```

We'd like to sync all groups the players are in, but excluding parent groups.
If you could add this, that would be awesome for our server.
Thanks in advance!

**Comment by Vankka** [comment]
You can make use of deny permissions (you need to enable `GroupRoleSynchronizationEnableDenyPermission` for this)

so if you have say vip and mvp, and mvp has a parent of vip, you can give mvp `discordsrv.sync.deny.vip` so then mvp won't get vip

**Comment by R4z0rX** [comment]
Ooh, I did see this, but I wasn't sure how to implement it.
So, every time there's a rankup, the player should get those permissions to avoid syncing the previous rank. Am I right?

**Comment by Vankka** [comment]
that's right, so if groups went in order one, two, three. two would have deny for two, and three would have deny for two

**Comment by R4z0rX** [comment]
Oh, wait, but can I do that directly to theLuckPerm groups? Or should I do that to every player eveytime they get a rankup?

**Comment by Vankka** [comment]
you can give the permission to the group, yes

**Comment by R4z0rX** [comment]
Awesome! Thanks a lot.

**Comment by R4z0rX** [comment]
Works like a charm! 😍
Thanks again! 👍
