### ISSUE TITLE
The bot does not create webhooks for avatars.

### ISSUE THREAD

**Issue by Shark-vil** [DiscordSRV/DiscordSRV#1053]
Everything worked fine before. However, the avatars stopped working after updating to an undefined version (I don't remember which one)

### Bot privileges
![Discord_YlpW8urdUs](https://user-images.githubusercontent.com/13109606/111085458-84e94c00-8528-11eb-9e23-584d95048545.png)

### Plugin config
![Code_ccYHGUQOK8](https://user-images.githubusercontent.com/13109606/111085463-89156980-8528-11eb-9af3-402594739c63.png)

### What displays in the chat
![Discord_AOJ49hQ0XJ](https://user-images.githubusercontent.com/13109606/111085469-8b77c380-8528-11eb-8034-e51d6db40085.png)

### An example of the server successfully displaying an avatar
Existing player:
https://mc.itpony.ru/resources/server/skinRender.php?vr=0&hr=0&headOnly=true&ratio=24&user=Shark_vil
Non-existent player:
https://mc.itpony.ru/resources/server/skinRender.php?vr=0&hr=0&headOnly=true&ratio=24&user=

### Server info
Version - 1.16.5
Core - Paper 1.16.5-R0.1-SNAPSHOT
Plugins:
- PlaceholderAPI 2.10.9
- PlugMan 2.1.7
- SkinsRestorer 13.8.9
- ViaVersion 3.2.1
- LightAPI 3.4.6
- LuckPerms 5.2.76
- OpenInv 4.1.5
- ClearLag 3.2.2
- ProtocolLib 4.6.0
- MVdWPlaceholderAPI 3.1.1
- Brider 1.2
- ServerRestorer 1.0.39
- Vault 1.7.3-b131
- GMusic [2.5.4.1]
- BKCommonLib 1.16.5-v2
- MobArena 0.105
- dynmap 3.1-beta7-449
- Essentials 2.18.1.0
- PlayerWarps 1.5.1
- FastAsyncWorldEdit 1.16-622,bc64eaf
- DragonSlayer 0.10.5_Jeppa
- EssentialsChat 2.18.1.0
- WorldGuard 7.0.4+f7ff984
- EssentialsXMPP 2.18.1.0
- MythicMobs 4.11.0-BETA-79e173ec
- EssentialsProtect 2.18.1.0
- EssentialsGeoIP 2.18.1.0
- GSit [5.1.0.1]
- EssentialsSpawn 2.18.1.0
- WorldGuardExtraFlags 4.1.5-SNAPSHOT
- WorldEditSUI 1.7.1
- Citizens 2.0.27-SNAPSHOT (build 2275)
- CustomStructures 1.5.6.2
- WG-GUI 1.5.3
- mcMMO 2.1.175
- SuperVanish 6.2.0
- AngelChest 2.22.2
- AdvancedRegionMarket 3.3.4
- AuthMe 5.6.0-SNAPSHOT-b2425
- Denizen 1.1.9-SNAPSHOT (build 1726-REL)
- Jobs 4.17.0
- DiscordSRV 1.21.3
- UltimateTimber 2.2.1
- FurnitureLib 2.4.0
- DiceFurniture 3.4.6
- FurnitureMaker 2.0.2
- FurnitureLib-GUI 1.3
- ProtectionLib 1.0
- LightCleaner 1.16.5-v1
- Kingdoms 1.10.16.1.2
- CraftBook 3.10.3,4680-f1ee2df

What could be the problem?

**Comment by Vankka** [comment]
I'm pretty sure this is caused by Kingdoms, reproduce the issue without Kingdoms installed

**Comment by Shark-vil** [comment]
> I'm pretty sure this is caused by Kingdoms, reproduce the issue without Kingdoms installed

Lol. This is really because of the "Kingdoms" plugin. Is there an assumption about the cause of the conflict? Chat priority?

**Comment by Shark-vil** [comment]
### Decision:
In the config "**chat.yml**" of the "**Kingdoms**" plugin need:
- Change priority to - _MONITOR_
- Change cancel to - _false_
