### ISSUE TITLE
Feature Request: Whitelister 

### ISSUE THREAD

**Issue by Fedefar1** [DiscordSRV/DiscordSRV#1057]
Hello there I saw on spigot a plugin that alow u to white list and unwhitelist people from discord. The plugin is called https://www.spigotmc.org/resources/discord-whitelister.69929/ .
My request is to add this feature to discordsrv. It would be so cool to have it.

**Comment by Scarsz** [comment]
Outside the scope of DiscordSRV

You can already whitelist the server by Discord roles with linking.yml & you can already run console commands through a linked chat channel with `!c <command>`

**Comment by Fedefar1** [comment]
> a

well it would be cool to have a cool looking embed answer, like that plugin
