### ISSUE TITLE
Feature Request: Discord Economy Bridge + Add-ons Folder

### ISSUE THREAD

**Issue by Fedefar1** [DiscordSRV/DiscordSRV#1059]
I know you can use !c for commands or directly use the console text chanel. I know that this feature is going to add new dependencis, but I think there is a way to not have dependencis on DiscordSRV. You could create a add-on for the plugin, like Discordsrv is still the same but in the Discordsrv folder there is a new folder called add-on. This would allow Discordsrv to remain the same but whit an extra folder. That would mean that if u add the addon there are going to be dependencis. This add-on / feature would add 3 commands, 1 eco add, 2 eco remove 3 eco view, I think that this is a cool idea. Not only for this feature, but also for the flexabiliti this thing is going to give. The community will be able to create their own add-ons for the plugin. Let me know about thease 2 ideas. Discord economy bridge and add-ons folder.

**Comment by Scarsz** [comment]
There is no reason to have an "addons" folder for DiscordSRV because plugins can just depend on DiscordSRV and use the already existing plugin system of the server

**Comment by Fedefar1** [comment]
oh, I diden`t know, thats cool! But what do you think about the economy bridge idea? There is alerady a plugin for this, but you would have then 2 bots and not 1 thats why I`m suggesting the discord economy bridge.

**Comment by Scarsz** [comment]
There's already plans to allow for something *like* this but it's not going to be implemented anytime soon

Other plugins are free to integrate into DiscordSRV and use it's bot instance to do whatever

**Comment by Fedefar1** [comment]
How do I integrate plugins into DiscordSRV? Do i put the same bot token?

**Comment by Scarsz** [comment]
No. The plugin would need to do that integration in it's code. DiscordSRV doesn't support running other bots on the same token.

**Comment by Fedefar1** [comment]
Last question. Do you have a listo of Other plugins that are free to integrate into DiscordSRV?

**Comment by Scarsz** [comment]
There are no restrictions on plugins that "can" integrate with DiscordSRV. It's up to any plugin's developer to add Discord functionality with DiscordSRV.

**Comment by Fedefar1** [comment]
ok thx, do you know some?

**Comment by Scarsz** [comment]
https://github.com/DiscordSRV/DiscordSRV/wiki#plugins-that-use-our-api
