### ISSUE TITLE
DiscordSRV connection timed out

### ISSUE THREAD

**Issue by TNTobsidian** [DiscordSRV/DiscordSRV#1060]
DiscordSRV version: 1.21.3

Minecraft Version: 
[Server] [19:34:21] [Server thread/INFO]: This server is running CraftBukkit version 3028-Spigot-79d53c2-7eb3564 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[Server] [19:34:21] [Server thread/INFO]: Checking version, please wait...
[Server] [19:34:22] [Thread-37/INFO]: You are running the latest version

Plugins (24): CoreProtect, InventoryRollback, PlayerGUI, GlobeMarket, OpenInv, GroupManager, PlaceholderAPI, AMSender, AmazingBot, AMReloader, ViaVersion, IPAPI, Vault, ViaBackwards, CometWelcome, Essentials, EssentialsGeoIP, EssentialsChat, ImageReplacer, AdvancedBan, EssentialsSpawn, DiscordSRV, AuthMe, AMWhiteList

LOG: https://pastebin.com/RWx5LAi7

DEBUG: 
[debug-1616671497825.zip](https://github.com/DiscordSRV/DiscordSRV/files/6204281/debug-1616671497825.zip)

It is working but on Wednesday it started repeating : [星期四, 25. 三月 2021 18:44:35 CST ERROR] [DiscordSRV] [JDA] There was an I/O error while executing a REST request: Connection reset

Then it cannot send any messages.

**Comment by Vankka** [comment]
Your server's internet connection is failing. It failed to both connect to discord.com & upload a debug report to bin.scarsz.me
