### ISSUE TITLE
Option for custom webhook message formats

### ISSUE THREAD

**Issue by diademiemi** [DiscordSRV/DiscordSRV#1063]
The webhook messages currently only display the message contents. It would be good to have that be customizable too, just like the usernames. This would allow for various improvements. One idea is to have an invisble embed `[ZeroWidhCharacter](%username%)` so you could still search by usernames for messages. But of course it's just a good feature to have anyway. 

Allowing for custom message formats would make the plugin a lot more flexible, so I'd like to see this change.

**Comment by Scarsz** [comment]
Implemented
