### ISSUE TITLE
My skin icon didn't update.

### ISSUE THREAD

**Issue by Thedoczek** [DiscordSRV/DiscordSRV#1065]
It shows my outdated icon.
![Issue.](https://user-images.githubusercontent.com/69758777/112859321-02799400-90b3-11eb-865e-b0608fe8d23c.png)
I changed my skin to this:
![Doczek](https://user-images.githubusercontent.com/69758777/112859691-5b492c80-90b3-11eb-817f-755e7bcb1c84.png)

Note that this only occurs where I joined before skin change, on servers played later everything is fine.

**Comment by diademiemi** [comment]
I'm pretty sure images in those embeds are cached locally on your discord install. To clear them remove:
On Linux:
`~/.config/discord/Cache`
`~/.config/discord/GPUCache`
On Windows:
`C:\Users\youruser\AppData\Roaming\discord\Cache`
`C:\Users\youruser\AppData\Roaming\discord\GPUCache`
On Mac:
`~/Library/Application Support/discord/Cache`
`~/Library/Application Support/discord/GPUCache`

**Comment by Thedoczek** [comment]
and just clear these folders?

**Comment by diademiemi** [comment]
Yeah, clear or delete them. Discord will recreate them

**Comment by Thedoczek** [comment]
Now it's steve
![obraz](https://user-images.githubusercontent.com/69758777/112871276-63a76480-90bf-11eb-979a-d917a3f80c93.png)

**Comment by Thedoczek** [comment]
I'll try not launching discord, launching minecraft and launching discord again

**Comment by Thedoczek** [comment]
Didn;t work

**Comment by diademiemi** [comment]
It won't be related to Minecraft. Delete the folders (Maybe with Discord closed, and then start Discord after you've done that). If it still shows steve, maybe something is wrong with your config.yml that it's not getting the correct images. but I doubt that, I've had this too and clearing cache fixes it.

**Comment by Thedoczek** [comment]
Well, i had to delete files with Discord closed, because I got error that I couldn't delete file because it's already used.

**Comment by ANutley** [comment]
Iirc, you can either wait for the Discord cache to clear, or add '?{timestamp}' to the end of your avatarurl to force it to update.

**Comment by Thedoczek** [comment]
where to add this timestamp?

**Comment by ANutley** [comment]
' AvatarURL: ' in config.yml

**Comment by Vankka** [comment]
{timestamp} doesn't exist anymore. Use `{texture}` & get latest snapshot (https://snapshot.discordsrv.com)

**Comment by TheAIguy-dev** [comment]
> I'm pretty sure images in those embeds are cached locally on your discord install. To clear them remove: On Linux: `~/.config/discord/Cache` `~/.config/discord/GPUCache` On Windows: `C:\Users\youruser\AppData\Roaming\discord\Cache` `C:\Users\youruser\AppData\Roaming\discord\GPUCache` On Mac: `~/Library/Application Support/discord/Cache` `~/Library/Application Support/discord/GPUCache`
Yes, this issue appears to be client-side. I cleared the cache on my phone and now I see the right skin, however, I can't find the cache folder on desktop.
I use Ubuntu 22.04 and the directories `~/.config/discord/Cache` `~/.config/discord/GPUCache` don't exist. I also did not find any discord cache in `~/.cache`.

**Comment by TheAIguy-dev** [comment]
So I contacted discord support and they said that you can't clear the cache on Linux. Not sure if this is true, but for now I just uninstalled it and then installed the portable version.
