### ISSUE TITLE
Feature requests 

### ISSUE THREAD

**Issue by HurricaneDancer** [DiscordSRV/DiscordSRV#1067]
- When a user replies to a minecraft message on discord, the mention in game chat should be @mc_username 
- Bot messages should be ignored. Seeing level up messages in game chat is annoying, or at least make it an option to ignore bots. 
- Add an option to force discord account linking on join
- have an option to give a user a role when they link their accounts so they can use the discord chat as an incentive.

**Comment by Vankka** [comment]
> When a user replies to a minecraft message on discord, the mention in game chat should be @mc_username
  
What? If you meant showing replies in-game, that's already been requested https://github.com/DiscordSRV/DiscordSRV/issues/1029

> Bot messages should be ignored. Seeing level up messages in game chat is annoying, or at least make it an option to ignore bots.

`DiscordChatChannelBlockBots` in the config.yml

> Add an option to force discord account linking on join

linking.yml

> have an option to give a user a role when they link their accounts so they can use the discord chat as an incentive.

`MinecraftDiscordAccountLinkedRoleNameToAddUserTo` in the config.yml

**Comment by HurricaneDancer** [comment]
Thanks!
