### ISSUE TITLE
Store copies of yml files in separate folder

### ISSUE THREAD

**Issue by Andre601** [DiscordSRV/DiscordSRV#1074]
## Idea
DiscordSRV should have the option to store copied YAML files in its own directory, to keep the main directory of the plugin more clean.

## Example
Upgrading from 1.21.3 to 1.22.0 would make DiscordSRV store a copy of `config.yml` as `config.yml-build-1.21.3.old` in `/plugins/DiscordSRV/backups`, or since it would no longer be in the same directory, perhaps as just a yaml file directly (Why does it even turn them into a .old file?)?

## Why
The migration, as I call it, causes a lot of old files to pile up, if you don't keep the folder clean.
With the current amount of files DiscordSRV provides will there be at least 13 different files when an update happens, which can be a bit annoying.
Having those old files in their own folder would help to keep the current folder cleaner.

**Comment by Vankka** [comment]
This is already at https://github.com/DiscordSRV/DiscordSRV/issues/873, similar idea it's just compressing it instead - doesn't have the word "migrate" so it would've been though to find
