### ISSUE TITLE
DiscordChatChannelColorTranslations gone in latest update

### ISSUE THREAD

**Issue by Thornbush42** [DiscordSRV/DiscordSRV#1080]
This feature was needed so we could have a nicely formatted chat in-game, no word of it being removed in change-log but any mention of it was removed in the config :(

**Comment by Scarsz** [comment]
What do you mean "nicely formatted" chat? If you were (mis)using the color translation table for formatting, the role alias config option exists now for that reason

**Comment by Thornbush42** [comment]
I was using it to display the discord role colours in the appropriate mc colour in-game, is this not what it was used for?

**Comment by Vankka** [comment]
Support for RBG colors was added, should the client not support rbg the closest legacy color would be used.
But you can still override that color with role aliases if you wanted to, aswell
