### ISSUE TITLE
Time zone issues

### ISSUE THREAD

**Issue by joeyk710** [DiscordSRV/DiscordSRV#1087]
In the **config.yml** where it gives you the option for `TimeZone` does not work properly. I changed it to EDT and my console is showing GMT.

**Comment by Scarsz** [comment]
Java doesn't have an EDT timezone defined for some reason, use `America/New_York` as an alternative

**Comment by Cat5TV** [comment]
I was having this same issue. Thanks for the solution @Scarsz - that worked perfectly for me, and even shows EDT correctly as the timezone in the console channel. Cheers!
