### ISSUE TITLE
Filter out nicknames/discord names

### ISSUE THREAD

**Issue by FluxedScript** [DiscordSRV/DiscordSRV#1090]
DiscordSRV would work better if it escaped the user's name or nickname. In cases where it's `JohnDoe <:)` this would break what happens after it such as `[Discord | Owner] JohnDoe <:) <reset> >> Hello all`. 

Trying chat filter works on only messages and an option to filter out the nickname/username. 

It may seem easier to tell them to change their name or to use their username instead but it doesn't work if the person has both set to the same things or the person is another moderator/admin/owner.

**Comment by Vankka** [comment]
What? I have no clue what you're trying to say or what the problem is

**Comment by FluxedScript** [comment]
Basically Having any form of `<` or `>` can destroy the formatting of the discord to minecraft chat

**Comment by Vankka** [comment]
I pushed some code for this that should cover it, snapshot is available at https://snapshot.discordsrv.com though next release is coming out soonish
