### ISSUE TITLE
Discord direct message

### ISSUE THREAD

**Issue by burgersarefat** [DiscordSRV/DiscordSRV#1094]
So I have the bot installed and working properly, and people are experiencing lag for the bot, and my server members said they have also been spamming the bot's discord direct messages with random things. First, I would like to know what even is the "code" that it wants you to send and how do you use it; and second how to prevent the bot from accepting direct messages.

**Comment by Vankka** [comment]
It's a linking code from `/discord link`, which allows linking Minecraft & Discord accounts together. It's not possible to prevent users from DMing the bot if they are in the same server as the bot
