### ISSUE TITLE
Question: Does DiscordSRV support Rich Presence for players?

### ISSUE THREAD

**Issue by techyboy27** [DiscordSRV/DiscordSRV#1101]
Hi, I'm wondering if DiscordSRV supports Rich Presence for players. 
I'm wanting each player who is a member and has their account linked and active on the server to have rich presence displaying that they are playing on my server and what my port and IP for my server is. 

Thanks :)

**Comment by James-Bennett25565** [comment]
That would be client side, the server can't control the users Discord statuses.

**Comment by techyboy27** [comment]
> That would be client side, the server can't control the users Discord statuses.

Ok. Is there a way I can make this work or is it not happening?

**Comment by James-Bennett25565** [comment]
DiscordSRV doesn't have that feature, but if you wanted to achieve that outside of this plugin, the server members would have to have a client side mod with a plugin on your server to communicate with it.
