### ISSUE TITLE
Question: Do you support BungeeCord?

### ISSUE THREAD

**Issue by techyboy27** [DiscordSRV/DiscordSRV#1102]
Does DiscordSRV support bungeecord?

**Comment by James-Bennett25565** [comment]
BungeeCord is currently unsupported, but will be supported in DiscordSRV 2.0 (ETA: None)
If you would like to use DiscordSRV's functions on all (or multiple) servers
• Install the plugin on every server with each server having it's own bot/token

If you would like linked accounts to be linked across all your servers:
• Use a MySQL/MariaDB database with the Experiment_Jdbc... options in the config.yml

**Comment by Scarsz** [comment]
https://github.com/DiscordSRV/DiscordSRV/issues/34
