### ISSUE TITLE
invite link problems

### ISSUE THREAD

**Issue by elaineandsparky** [DiscordSRV/DiscordSRV#1104]
The discord link ingame isn't the same on as on the config. I've tried changing it a few times and included the /https and without but it just wont change ingame.

Config:
Invitation link shown to players when using /discord and on the message shown to unlinked players when linking is enforced
DiscordInviteLink: "https://discord.gg/32wKHUJu3G"

![image](https://user-images.githubusercontent.com/69724087/116694832-aa86c380-a9b7-11eb-9de3-777a6e1c3ea1.png)

**Comment by Vankka** [comment]
The link is probably set in `DiscordCommandFormat` in the messages.yml instead of using `{INVITE}`
