### ISSUE TITLE
Full stop in default value for DiscordCommandFormat breaking invite link

### ISSUE THREAD

**Issue by Dinty1** [DiscordSRV/DiscordSRV#1105]
The full stop after `{INVITE}` causes the link to redirect to the Discord homepage.
https://github.com/DiscordSRV/DiscordSRV/blob/master/src/main/resources/messages/en.yml#L359

**Comment by Vankka** [comment]
Confirmed fix, https://github.com/DiscordSRV/DiscordSRV/commit/774f846d8a520d6f97fb064df123063c4716ad96

Additionally added https:// to the default `DiscordInviteLink`, https://github.com/DiscordSRV/DiscordSRV/commit/1f2fbf2be904a7b06a5d0b9b9536ec6e5c45fb3f
