### ISSUE TITLE
Message beginning with "#" gets cancelled out

### ISSUE THREAD

**Issue by ItsLynix** [DiscordSRV/DiscordSRV#1106]
If you write the /discord broadcast command with a message starting by a #, the hashtag will, by its nature, hash out and prevent the message from being sent, leaving the command executor with "No text given to broadcast.".

**Comment by James-Bennett25565** [comment]
It probably thinks you are trying to put in a channel, for example `/discord bcast #some thing` it would try to send `thing` to the `#some` channel

**Comment by ItsLynix** [comment]
That is also a possibility.

**Comment by James-Bennett25565** [comment]
Try specifying a channe, for example `/discord bcast #general #something`

**Comment by ItsLynix** [comment]
I just tested it out, I do find that it identifies `#some` in `/discord bcast #some` thing as the channel it tried to send to. You are right about that, this may cause issues in the terms of user experience, its a pretty minor thing, but never under estimate small issues. Perhaps they should add an option to perhaps send things like `/discord bcast #OMGTHISISCOOL >> #some` and it would send `#OMGTHISISCOOL` to `#some` as signified by `>>`, just something setting things apart.

**Comment by Scarsz** [comment]
Having the >> as an alternative to specifying the channel at the beginning would needlessly overcomplicate the code & literally never be used
