### ISSUE TITLE
Discord message will be cut off after < in a username

### ISSUE THREAD

**Issue by cmod31** [DiscordSRV/DiscordSRV#1109]
A Discord user of our Discord tried to comunicate with the Minecraft Chat but her name is anna<3 and everything after the < will be cut off in the Minecraft chat like in the screenshot she sent me
![Screenshot_32](https://user-images.githubusercontent.com/80621863/116882417-b925e280-ac24-11eb-9a13-c5caa40fbd15.png)

**Comment by Scarsz** [comment]
[MiniMessage issue](https://github.com/KyoriPowered/adventure-text-minimessage/issues/93), not in DiscordSRV's control

**Comment by Vankka** [comment]
This is a duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/1090, which should already be fixed on development builds (https://snapshot.discordsrv.com
