### ISSUE TITLE
DiscordSRV error that is probably causing my server not to work (infinite ping)

### ISSUE THREAD

**Issue by tionreal** [DiscordSRV/DiscordSRV#1110]
[15:53:06] [DiscordSRV - JDA Rate Limit/ERROR]: [DiscordSRV] [JDA] There was an I/O error while executing a REST request: null
--
358 | [15:53:06] [DiscordSRV - JDA Callback 0/ERROR]: [DiscordSRV] DiscordSRV encountered an unknown Discord error: -1: java.io.InterruptedIOException

How do I fix and what is this

**Comment by Vankka** [comment]
This error is stating that DiscordSRV's connection to Discord was interrupted, this should not be causing the Minecraft server's connection to not work

**Comment by Vankka** [comment]
Closing for lack of information
