### ISSUE TITLE
Error message possibly causing leave/join messages to not display?

### ISSUE THREAD

**Issue by carstorm** [DiscordSRV/DiscordSRV#1111]
When server is starting up I get this error, unsure if related or not but player joins and leaves aren't displayed in discord.

https://pastebin.com/JKaTwXp7

Edit, realize this error only happens when a player leaves or joins making it more likely it is the cause.

**Comment by Scarsz** [comment]
Helps to try reading error messages instead of just immediately reporting them

`InsufficientPermissionException: Cannot perform action due to a lack of Permission. Missing permission: MANAGE_WEBHOOKS`
