### ISSUE TITLE
Allow for .zip upload through console with plugin & config

### ISSUE THREAD

**Issue by Scot-Survivor** [DiscordSRV/DiscordSRV#1115]
The idea is simple, I hope. 
Through the discord console channel, if enabled in settings, you can upload a plugin to the main server and should you have a plugin manager installed you can quickly enable the said plugin. 

However, it would be nice if you could upload a .zip file, with the plugin say DiscordSRV.jar and its config folder DiscordSRV/

**Comment by Vankka** [comment]
Console plugin uploading is a very unsupported (and insecure) feature, the chances of this seeing the light of day are slim

**Comment by ANutley** [comment]
Closing this as this feature no longer exists.
