### ISSUE TITLE
NicknameUpdater spam

### ISSUE THREAD

**Issue by Fiks75** [DiscordSRV/DiscordSRV#1118]
Spam in console when player join server
https://pastebin.com/EDTM5d59

PaperSpigot 1.16.5
DiscordSRV-Build-1.23.0-SNAPSHOT-1f11e47

**Comment by Dinty1** [comment]
Hey, please join [DiscordSRV's Discord Server](http://discord.discordsrv.com/) and open a support ticket so that your issue can be investigated further.
