### ISSUE TITLE
%channelcolor% placeholder not working with VentureChat

### ISSUE THREAD

**Issue by Dinty1** [DiscordSRV/DiscordSRV#1119]
Instead of giving the colour of the channel, the placeholder is seemingly replaced with nothing. This only occurs on v1.22.0 of DiscordSRV

Tested with VentureChat v2.22.6 and v2.22.8

**Comment by Vankka** [comment]
if it only occurs on one version of the plugin, what version *does it work on*, additionally is this different on development versions

**Comment by Dinty1** [comment]
Works on 1.21.3 so I'm assuming it still works on earlier versions

Admittedly I haven't tested it on the snapshot build so I'll have to check that

**Comment by Dinty1** [comment]
Tested on the latest dev build, doesn't work there either.

**Comment by Dinty1** [comment]
Fixed on the snapshot, will keep this open until the next build is released.
