### ISSUE TITLE
Support for long message splitting

### ISSUE THREAD

**Issue by DerpDerpling** [DiscordSRV/DiscordSRV#1123]
ok, so normally when a message is over 256 characters, it only sends the first 256 characters. i feel like there should be an option that is called `split long messages` that would let messages longer than 256 characters send by splitting into multiple messages in the minecraft chat

**Comment by Vankka** [comment]
The 256 character limit isn't a technical one, it's a config option (`DiscordChatChannelTruncateLength`) and it mainly serves to block big messages from flooding the in-game chat
