### ISSUE TITLE
Discord to Minecraft format messed up when playername contains a dot

### ISSUE THREAD

**Issue by Pirito10** [DiscordSRV/DiscordSRV#1127]
I have this in messages.yml
`DiscordToMinecraftChatMessageFormat: "&8&l»&r &#7289DA[Discord]%toprolecolor%[%toprole%] &f&l%name%&l: &7%message%"`
`DiscordToMinecraftChatMessageFormatNoRole: "&8&l»&r &#7289DA[Discord]&r &l%name%&l: &7%message%"`

When %name% contains a dot, for example, a player is called _Pla.yer_, the output to minecraft is something like `&8&l»&r &#7289DA[Discord]&r &l%name%&7%message%`.
**The ':' and the space are "removed".**

Happens both for `DiscordToMinecraftChatMessageFormat` and `DiscordToMinecraftChatMessageFormatNoRole`.

I have not tested with any charater other than the dot.

I'm not sure if it is needed for this, but just in case, this is the debug report with the issue reproduced: https://bin.scarsz.me/f5d958fe-5f26-48fb-b01d-5ec33ba87cd2#yzAPJdw5mBxcMuAmi1fHWPHCklbf5gfB

Server version: Paper 1.16.5 build 704
DiscordSRV version: 1.22.0

**Comment by Vankka** [comment]
I have confirmed this is indeed a problem, the name is being parsed a link & the `&l` before : is causing issues with Adventure's legacy serializer. Will have to look into a way to solve this

**Comment by Pirito10** [comment]
I have tested this in version 1.23.0 and no longer happens.
Server version: Purpur 1.17 build 1255

**Comment by Vankka** [comment]
Thanks for letting me know
