### ISSUE TITLE
Support for Geyser Servers

### ISSUE THREAD

**Issue by Headlessduck406** [DiscordSRV/DiscordSRV#1128]
Add support for bedrock players in geyser servers by using this api: https://tydiumcraft.tk/docs/skinapi

**Comment by jackson-57** [comment]
This can be done more directly (as far as I understand, Tydium's API gets the player's texture ID from the GeyserMC API, then sends that texture ID to mc-heads): https://github.com/DiscordSRV/DiscordSRV/issues/996#issuecomment-807058209

**Comment by Tydium** [comment]
Yeah my API just makes it a bit more easier for the skins to be gathered. It generally does solve this tho in a very simple way. Pretty much up to discord SRV at this point.

**Comment by GreemDev** [comment]
DiscordSRV is not likely to have Bedrock support anytime soon. In the future maybe, but not now.

**Comment by Tydium** [comment]
Sorry for bumping this, but that API above changed from api.tydiumcraft.tk to api.tydiumcraft.net. (To not bring any confusion)

**Comment by GreemDev** [comment]
Not sure why you felt the need to post on this issue at all anymore but alright.
