### ISSUE TITLE
Remove feature.

### ISSUE THREAD

**Issue by Headlessduck406** [DiscordSRV/DiscordSRV#1131]
Could you please remove the feature that if you @ the bot or reply to it, it responds with the image below. I first thought it was a feature in DiscordSRVUtils but apparently not. It is a very annoying feature.
![image](https://user-images.githubusercontent.com/78724847/119214167-fdabec00-bb07-11eb-9c1e-e8817a2a024a.png)

**Comment by thewilloftheshadow** [comment]
This doesn't look like anything from DiscordSRV, are you sure that's what is causing it?

**Comment by Headlessduck406** [comment]
There was a misundertanding, it was a feature from discordsrvutils.
