### ISSUE TITLE
Add config option for the mention sound

### ISSUE THREAD

**Issue by arts7493** [DiscordSRV/DiscordSRV#1135]
add config option plz
mention sound in minecraft when someone mentioned

**Comment by dani626** [comment]
https://www.spigotmc.org/resources/interactivechat-show-items-inventory-in-chat-custom-chat-keywords-bungee-velocity-support.75870/

**Comment by Dinty1** [comment]
> https://www.spigotmc.org/resources/interactivechat-show-items-inventory-in-chat-custom-chat-keywords-bungee-velocity-support.75870/

...Not really sure what you mean. The mention sound is a part of DiscordSRV.

**Comment by Scarsz** [comment]
Implemented
