### ISSUE TITLE
proximity chat 

### ISSUE THREAD

**Issue by masonispog** [DiscordSRV/DiscordSRV#1136]
so i want to make a server which uses proximity chat using ur plugin but it only has the option to make one in config.
the reason i want 2 is because i want to make a proximity chat which is for staff only and one for members.
thank you for reading this. good luck in the future. i love the plugin <3

**Comment by Scarsz** [comment]
Having an entirely separate, duplicate proximity system just for chat members would be far too wasteful of resources to be feasible. It kind of goes against the entire spirit of proximity chat, too, in my opinion. Maybe one day this could be added but unlikely.
