### ISSUE TITLE
Disabling DiscordConsoleChannelAllowPluginUpload throws uncaught exception when uploading any attachment

### ISSUE THREAD

**Issue by InfoTeddy** [DiscordSRV/DiscordSRV#1138]
When `DiscordConsoleChannelAllowPluginUpload` is set to false in `config.yml`, plugin uploads are disabled. However, what happens instead is that whenever any attachment is uploaded to the console channel, exception errors get printed. Since it's the console channel, the errors also get sent to Discord in the console channel as well, making uploading images in the console channel extremely annoying.

![DiscordSRV uncaught exception](https://user-images.githubusercontent.com/59748578/119945626-91d3e400-bf4a-11eb-97c7-5b2e8b8b83f9.png)
<sup>An example of the extremely annoying current behavior. To be fair, Java's propensity for obfuscalization verbosity does not help matters here.</sup>

This is because if `DiscordSRV.isFileSystemLimited()` is true (which it is when `DiscordConsoleChannelAllowPluginUpload` is false), an `UnsupportedOperationException` gets thrown:

https://github.com/DiscordSRV/DiscordSRV/blob/fa5256f1737a5286e79c71aa023254761b59e852/src/main/java/github/scarsz/discordsrv/listeners/DiscordConsoleListener.java#L110

And it never gets caught.

The correct behavior instead should be to catch the exception and not print any errors at all.

**Comment by ANutley** [comment]
Closing this due to this feature no longer existing.
