### ISSUE TITLE
Event triggers for alerts.yml aren't working

### ISSUE THREAD

**Issue by yourlocalvirgo** [DiscordSRV/DiscordSRV#1142]
Hi! I'm having an issue where, whenever I set up an alert that's triggered by an event, it just... doesn't work. Alerts that are triggered with commands are working just fine, but event-triggered alerts just don't go through, and there's no debug information about it, either. Any help would be greatly appreciated!

Here's one of the event-triggered alerts I'm working on:
  - Trigger: AfkStatusChangeEvent
    Channel: survival
    Conditions: 
      - player.world.name == "survival"
    Embed:
      Color: "#B11515"
      Author:
        ImageUrl: "https://crafatar.com/avatars/${#event.getAffected().getBase().getUniqueId()}?overlay"
        Name: '${#event.getAffected().getName() + " is " + (#event.value ? "now" : "no longer") + " AFK"}'

**Comment by Dinty1** [comment]
This issue is fixed on the snapshot build https://snapshot.discordsrv.com
