### ISSUE TITLE
Enhancement | Local mute instead of moving to a channel

### ISSUE THREAD

**Issue by IvanGodinez21** [DiscordSRV/DiscordSRV#1145]
**THIS IS JUST A SUGGESTION**

I think that moving users to different channels where there are a lot of players could be annoying, so using the local mute could be a better solution for this

Basically all user will be in one channel where everyone can talk, but an authorized app of Discord with the following permissions (maybe less permissions), will do the work of local mute the other users

![image](https://user-images.githubusercontent.com/45635827/120229209-3f2c4d80-c212-11eb-8a4f-c5b15c5d085f.png)

_Volume could also be used for gradual change_

![image](https://user-images.githubusercontent.com/45635827/120228578-09d33000-c211-11eb-890a-7406205060ea.png)

**Comment by James-Bennett25565** [comment]
To be honest, I don't think anyone would want to give the bot access to that kind of stuff.

**Comment by IvanGodinez21** [comment]
> To be honest, I don't think anyone would want to give the bot access to that kind of stuff.

It depends on the user

Some apps use those permissions access, like these:

![image](https://user-images.githubusercontent.com/45635827/120240363-faaaad00-c225-11eb-8aa4-fe51265825b6.png)
![image](https://user-images.githubusercontent.com/45635827/120240379-04ccab80-c226-11eb-9f49-c2fc9ed2f0ed.png)

**Comment by Dinty1** [comment]
These applications that you linked are widely trusted whereas with a DiscordSRV bot you're effectively giving the server owner access to your account, which understandably would not be appreciated.

**Comment by thewilloftheshadow** [comment]
Also, Discord isn’t allowing any new RTC applications right now last I checked

**Comment by Scarsz** [comment]
Closing this because this is extremely unlikely to be implemented into DiscordSRV

In the future, stage channels might be used instead of normal voice channels to get rid of the Discord sounds when changing channels
