### ISSUE TITLE
Chatty Support

### ISSUE THREAD

**Issue by enchig** [DiscordSRV/DiscordSRV#1147]
Chatty is probably one of the most user-friendly chat plugins out there. So I would like to see it on the DiscordSRV compatibility list. Since Brixter recently re-started development of Chatty, I think you can show great results with him that will be useful to many.

Even now it works pretty well, but there is one big drawback. Messages from Discord in Minecraft are not visible, but messages from global chat in Minecraft sent to Discord are working fine.

(Thanks google translator )

**Comment by Scarsz** [comment]
##441
