### ISSUE TITLE
Error 50013

### ISSUE THREAD

**Issue by VaibhavKushwaha** [DiscordSRV/DiscordSRV#1154]
It shows
`DiscordSRV received a permission error response (50013) from Discord. Unfortunately the specific error isn't provided in that response.`
How to fix it

**Comment by James-Bennett-295** [comment]
I think that is the bot not having permission to do some it is trying too do, you could try giving it admin and seeing if the issue goes away.

**Comment by James-Bennett-295** [comment]
Have you managed to fix it?

**Comment by Vankka** [comment]
Discord bot doesn't have some permission to do something
