### ISSUE TITLE
Feature request: pass /me & /say

### ISSUE THREAD

**Issue by kernelpanic3** [DiscordSRV/DiscordSRV#116]
Exactly what it says on the tin - it would be really nice to see the /me command on MC passed to Discord, and Discord's equivalent passed separately from regular chat.

Thanks for an awesome plugin!

**Comment by Scarsz** [comment]
Unfortunately not as easy as it sounds. Discord's `/me` command does the equivalent of putting `_` before and after the message that you give it. To the bot, it's completely indiscernible as being a `/me` command other than the fact it begins and ends with `_`

**Comment by Restitutor** [comment]
Would it still be possible for /me to work just from MC to Discord?

**Comment by acidicchip** [comment]
I would also like to see "* %displayname% is now AFK." and "* %displayname% is no longer AFK." messages relayed from Minecraft to Discord.

**Comment by Vankka** [comment]
#345 @acidicchip

**Comment by Dinty1** [comment]
This is possible with the [alerts feature](https://docs.discordsrv.com/alerts/)
