### ISSUE TITLE
Crucible: Modded Achievements are not triggering (Showing Up on Discord)

### ISSUE THREAD

**Issue by KaneHart** [DiscordSRV/DiscordSRV#1165]
I highly doubt this will be touched mostly for the Fact it's a Thermos issue. Plain Bukkit in 1.7.10 works, but with Thermos modded Achievements sadly are not showing up. Not sure if there is a small chance or too bloating to maybe grab said info. 

I also made a report to Crucible on this. It's a updated version of Thermos being semi active worked on:
https://github.com/CrucibleMC/Crucible/issues/72

Thanks.

**Comment by Vankka** [comment]
This isn't a DiscordSRV issue, but likely isn't fixable either because [Achievement](https://github.com/CrucibleMC/Crucible/blob/master/bukkit/src/main/java/org/bukkit/Achievement.java) is a enum in Bukkit - thus meaning new values cannot be added
