### ISSUE TITLE
JDBC USE MY IP INSTEAD THE CONFIG IP ADDRESS

### ISSUE THREAD

**Issue by Zixasis** [DiscordSRV/DiscordSRV#1166]
When i use JDBC option this thows me this
![2021-06-18_05h41_29](https://user-images.githubusercontent.com/29090346/122549213-da396b80-cff7-11eb-819f-34e1fa307748.png)
fixed-187-189-160-89.totalplay.com it's my ip address reversed with DNS....

Other plugins (Like worldguard) dont have this problem (and its the same config)
![2021-06-18_05h42_24](https://user-images.githubusercontent.com/29090346/122549392-081eb000-cff8-11eb-92ab-37b24f63b3c7.png)

CONFIG (DONT WORRY ABOUT THE PASSWORD. I CHANGE LATER)
![2021-06-18_05h45_40](https://user-images.githubusercontent.com/29090346/122549727-6ea3ce00-cff8-11eb-8624-2b46daa7cbd9.png)

its kinda weird

**Comment by Vankka** [comment]
The first picture (showing DiscordSRV) is printing the authentication error from MySQL - which does not use the address it's trying to connect with, rather it's showing the address that is allowed to connect to that user. The second picture is printing the actual jdbc url.
