### ISSUE TITLE
Mysql migration

### ISSUE THREAD

**Issue by mehmet-27** [DiscordSRV/DiscordSRV#1168]
I want to automatically transfer linkedaccounts.yml data to mysql.
How can i do this?

**Comment by granny** [comment]
This is done automatically when you put in your credentials in the jdbc options and restart the server.

**Comment by mehmet-27** [comment]
I already came from that channel. Thanks for help

**Comment by Scarsz** [comment]
As the bot's response already stated, we do not offer support in GitHub issues. There is no reason to continue this conversation here.
