### ISSUE TITLE
LuckPerms discordsrv:server context for checking linked users + server membership

### ISSUE THREAD

**Issue by trwnh** [DiscordSRV/DiscordSRV#1174]
Is it possible to give people a MC luckperms group based purely on membership within a Discord? I don't want to sync a role to a group, I want to sync membership to a group.

**Comment by thewilloftheshadow** [comment]
There is a context you can use for that, so for a luckperms group named special and a role named Special, you can give the default group the "group.special" permission with the discordsrv-role context set to the Special role

**Comment by trwnh** [comment]
I don't want to use a Discord role, though. As far as I understand your suggestion, this would require me to create a Discord role named Special.

**Comment by thewilloftheshadow** [comment]
@everyone is considered a role o bots (and therefore DiscordSRV), so you can use that

**Comment by Scarsz** [comment]
> @everyone is considered a role to bots (and therefore DiscordSRV), so you can use that

The public role (@everyone) isn't considered a role that members "have," it's always implied. It wouldn't work with group synchronization.

A "user is linked AND user is member of Discord server" LuckPerms context would be useful to have though

**Comment by Dinty1** [comment]
Added by #1179

**Comment by trwnh** [comment]
Sorry for being a year and a half late, but how do I use #1179 to auto-promote anyone who links their Discord to a certain LuckPerms group?
