### ISSUE TITLE
Hex Code Shows Up In Discord

### ISSUE THREAD

**Issue by BobbyMere** [DiscordSRV/DiscordSRV#1176]
If I put hex codes into my nickname, the entire hex code shows up in discord
is there a way to fix this?

paper 1.16.4 with discordSRV v1.23.0

<img width="326" alt="Screenshot_2021-06-27_141730" src="https://user-images.githubusercontent.com/25316276/123559056-69185780-d75f-11eb-8d5b-543ee70bc769.png">

I understand that if you put a '&' before the hex, it solves the problem but I'm also being requested to post this so normal hex also works incase of a future rewrite

**Comment by Vankka** [comment]
You can use `DiscordChatChannelGameFilters` to filter those out, with a pattern such as `#[a-fA-F\\d]{6}`, so the full option would be:
```yaml
DiscordChatChannelGameFilters: {"#[a-fA-F\\d]{6}": ""}
```
