### ISSUE TITLE
Suggestion | Whitelist request

### ISSUE THREAD

**Issue by lolaiq** [DiscordSRV/DiscordSRV#1177]
A user can do !request-whitelist in a channel, because they wanna get whitelisted on the server.
Then, it will send to a staff channel "{user} wants to get whitelisted and there ign is {ign}
On that staff channel message; it will have 2 reactions, a ✅ and ❌.
if the reaction is ✅ - the user will get whitelisted on the SMP and will DM them
if the reaction is ❌ - the user wont get whitelisted and will dm them etc

~lemme know if i should explain more

**Comment by Vankka** [comment]
As is, this would be quite unlikely to be implemented as it only covers one use case. If this could be bundled into a more extensible feature that could do more than just whitelist requests, it might have chance.
