### ISSUE TITLE
Suggestion: Add User Input Capability into Canned Responses

### ISSUE THREAD

**Issue by Legit4K** [DiscordSRV/DiscordSRV#1183]
User inputs will allow canned responses to provide more content based on the parameters that a user includes, below is an example:
```
{"/playtime $1":"%PlayTimes_playtime%"}
```
where $1 is the first arg that a user includes, in this case, it would be the player's name. Example -> /playtime Thanos

For more inputs, the number can simply be incremented like $2 $3 etc

**Comment by Eloujah** [comment]
This is a very interesting feature, and I can't wait to see it!

**Comment by GreemDev** [comment]
Canned responses are not meant to be used as custom commands. They are for showing people information. Use another bot or make one yourself for custom commands.

**Comment by Scarsz** [comment]
#384
