### ISSUE TITLE
Ingame Chat Themes

### ISSUE THREAD

**Issue by DaYeetyBoiCoder** [DiscordSRV/DiscordSRV#1187]
Could you please add themes for the ingame chat? I attached a screenshot example of what Bisect Hosting does. 
![image](https://user-images.githubusercontent.com/68494669/124541731-60153d80-de65-11eb-9cbb-ad96409da530.png)

**Comment by thewilloftheshadow** [comment]
What is themed about this?

**Comment by GreemDev** [comment]
https://github.com/DiscordSRV/DiscordSRV/blob/master/src/main/resources/config/en.yml#L50
