### ISSUE TITLE
Chat colors being downscaled with chat hooks (VentureChat, Chatty, etc.)

### ISSUE THREAD

**Issue by mmeltt** [DiscordSRV/DiscordSRV#1189]
When i set HEX colors in DiscordSRV message format (messages.yml), it converts hex into usual colors. This is same with HEX prefixes as aliases. [&#e9d2ec -> &d and &#FFD700G -> &6]. I wrote ticket in Discord server and staff said me to write ticket here.
DiscordSRV version: 1.23.0
Chatty: 2.19.2 (Supports HEX colors]
![unknown2](https://user-images.githubusercontent.com/87064986/124728632-6ca69e00-df18-11eb-9156-d6abe3657233.png)

**Comment by Vankka** [comment]
Fixed on development builds, https://snapshot.discordsrv.com
