### ISSUE TITLE
Suggestion: Add a possibility for sending chat messages on two or more Discord servers at once.

### ISSUE THREAD

**Issue by TDFPL** [DiscordSRV/DiscordSRV#1191]
It would a neat idea and it's weird it wasn't implemented yet.

**Comment by Dinty1** [comment]
This is planned for the upcoming rewrite & has probably already been suggested somewhere

**Comment by Scarsz** [comment]
Duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/111
