### ISSUE TITLE
DiscordSRV Paper-1.17.1-90 fails to load

### ISSUE THREAD

**Issue by killbots2012** [DiscordSRV/DiscordSRV#1192]
Hi I was wondering if the Alpha quality builds from Paper was 1.17.1+ using DiscordSRV version 1.23.0 if it helps here is my latest startup log 
[latest.log](https://github.com/DiscordSRV/DiscordSRV/files/6792596/latest.log)

**Comment by James-Bennett-295** [comment]
The config syntax is wrong

**Comment by James-Bennett-295** [comment]
If you need help, ask on discord. I think it was you there earlier but if not you can join here: https://discord.gg/Z6fQKZePYc
