### ISSUE TITLE
BungeeCord Support?

### ISSUE THREAD

**Issue by Lucky0888** [DiscordSRV/DiscordSRV#1193]
Can I just drop the plugin into the Plugins Folder in BungeeCord? Or do I have to add it to every single server?

**Comment by James-Bennett-295** [comment]
BungeeCord is currently unsupported, but will be supported in DiscordSRV 2.0 (ETA: None)

If you would like to use DiscordSRV's functions on all (or multiple) servers
• Install the plugin on every server with each server having it's own bot/token

If you would like linked accounts to be linked across all your servers:
• Use a MySQL/MariaDB database with the Experiment_Jdbc... options in the config.yml

**Comment by Dinty1** [comment]
Duplicate of #34
