### ISSUE TITLE
Change UUID to username in linked.json

### ISSUE THREAD

**Issue by giorno420** [DiscordSRV/DiscordSRV#1194]
Basically, how do I change the default format in `linked.json`, from:
```
{
"player UUID": "discord ID"
}
```

to:

```
{
"player username": "discord ID"
}
```

This is a question, and if there's anything regarding this in the `config.yml`, please let me know

**Comment by Dinty1** [comment]
You can't. The entire point of using UUIDs is that if someone changes their name their account stays linked. You're probably running offline mode or something but at the moment only UUIDs are put there.

**Comment by giorno420** [comment]
yep I am, but thanks for the information, I'll try to find a different workaround

**Comment by Vankka** [comment]
no
