### ISSUE TITLE
Custom Channel names are not working properly when using chatcontrol.

### ISSUE THREAD

**Issue by Skizzles** [DiscordSRV/DiscordSRV#1207]
With the below setup here:
![image](https://user-images.githubusercontent.com/30563757/127137008-7792c66a-9546-485d-a81f-b1f3998f6026.png)
You can see Local showing with this being the matched channel in ChatControl-Red. 

However after changing the setup to:
![image](https://user-images.githubusercontent.com/30563757/127137155-6c82b33e-6dec-4bd5-a372-1c85776345bf.png)
The channels work properly. Problem being now the Global chat does not read into discord like it should as the "Local" Server based chat is being considered Global.

https://screenshots.skizzles.me/wAnA3/YajoqOKE49.mp4

**Comment by Dinty1** [comment]
This doesn't seem to be a DiscordSRV issue so please contact ChatControl support with this
