### ISSUE TITLE
Suggestion: make channel selection go by name, not channel id

### ISSUE THREAD

**Issue by HermanGoring** [DiscordSRV/DiscordSRV#1212]
i want it so that you could config the bot to send the chat/console to #global and itll find a channel named #global to send chat/console. this is effective as i could manage my console in another discord server and chat in my community server

**Comment by Vankka** [comment]
You can just specify 2 channel ids that are from different servers, they aren't limited to working in just one server. Changing to channel names wouldn't make any sense
