### ISSUE TITLE
MySQL/ databases

### ISSUE THREAD

**Issue by longtimeno-c** [DiscordSRV/DiscordSRV#1214]
Any plans on adding a MySQL or a form of database so that bungeecord networks can sync linked accounts?

**Comment by ANutley** [comment]
This is already possible. Look for the jdbc options in config.yml

**Comment by longtimeno-c** [comment]
Ah will check now must have missed it :)

**Comment by longtimeno-c** [comment]
Should I repeat the config per server or is a different table necessary?

**Comment by ANutley** [comment]
Repeat it on every config, however this conversation is better suited for #support in our discord server

**Comment by longtimeno-c** [comment]
Sure sorry :)
Any news on the prox bot error?

**Comment by Vankka** [comment]
>  Any news on the prox bot error?

What are you even referring to?

**Comment by longtimeno-c** [comment]
> >  Any news on the prox bot error?
> 
> 
> 
> What are you even referring to?

https://github.com/DiscordSRV/DiscordSRV/issues/1152

**Comment by Vankka** [comment]
If there were updates they would've been posted on that issue
