### ISSUE TITLE
RFE: Support Discord webhooks for Minecraft -> Discord chat for more fluent chat integration

### ISSUE THREAD

**Issue by mooinglemur** [DiscordSRV/DiscordSRV#1215]
This Fabric plugin uses webhooks to send messages from the game to Discord. This allows the messages to appear to come from each player individually rather than from the bot.  The messages in discord show the in-game player name and even show the player head as the avatar.

https://github.com/Selicre/mc-discord-bridge

This style of message presentation would be an impressively good enhancement to DiscordSRV

**Comment by Scarsz** [comment]
`Experiment_WebhookChatMessageDelivery`
