### ISSUE TITLE
A bug occurs when changing the format

### ISSUE THREAD

**Issue by p82183645** [DiscordSRV/DiscordSRV#1219]
When I try to change this string of text, there will be an error
![image](https://user-images.githubusercontent.com/5382252/128656275-88af62ad-9e8b-4ac8-8be5-b6b3cb717574.png)

![image](https://user-images.githubusercontent.com/5382252/128656258-c0ee91f6-9342-4591-800a-f50837c44290.png)

**Comment by Scarsz** [comment]
Not a DiscordSRV error
