### ISSUE TITLE
please add economic system

### ISSUE THREAD

**Issue by worldcho** [DiscordSRV/DiscordSRV#1221]
When you take a specific action on Discord
                    It would be nice to have the ability to give money to users.

For example
When writing the attendance check command,
Given a specific role,
If the chat contains the specified word
If you access the voice channel for more than a certain period of time
For example, when the number of chats exceeds a certain number.

It's also a good idea to include a message for that amount.

And I want to combine this with the economics of the Minecraft Essentials plugin.
Money earned through Discord is linked to Minecraft,
It would be great if you could link the money you earn with Minecraft to Discord.

**Comment by Scarsz** [comment]
While I could definitely see a use case in this, this doesn't fit inside the scope of DiscordSRV's primary goals. DiscordSRV isn't just a plugin to do anything related to Discord with a Minecraft server, it's primary purpose is chat/group/player synchronization with a few other bonuses.

This would be a better idea for a separate plugin that hooks into DiscordSRV.
