### ISSUE TITLE
Ability to Stack/Remove Queued Messages

### ISSUE THREAD

**Issue by Villagers654** [DiscordSRV/DiscordSRV#1224]
If Chat becomes spammy and messages begin to exceed the discord rate limit, they get piled into a message queue. However if chat is exceptionally spammy, or some form of chat bot clogs it, this can cause an extremely long message delay, and a lot of tps lag on the server. In order to prevent this, could it be possible to either disable the message queue by not sending messages that exceed the discord rate limit or (ideally) stack the message queue into one longer message, similar to how console handles this issue? I’ve had numerous complaints about lag or chatbridge backup due to this message queue, so this solution would save me a lot of headaches.

**Comment by Scarsz** [comment]
Queued messages would not be lagging your server. All of that is done asynchronously.

There is no way to "clear" the queued messages, no, and there likely won't be. DiscordSRV doesn't keep track of the messages once they've been queued. It's up to JDA at that point.
