### ISSUE TITLE
It would be nice to have a feature that requires you to have a designated role to get to a specific world.

### ISSUE THREAD

**Issue by pokpong31** [DiscordSRV/DiscordSRV#1230]
If you use other plugins, you can create multiple worlds on one server. It would be nice to be able to add a condition that requires a specific role in order to access the created world. This function seems to be the simplest and most useful.

**Comment by granny** [comment]
What does this have to do with DiscordSRV?

**Comment by Dinty1** [comment]
You can set a permission to enter the world using luckperms contexts https://docs.discordsrv.com/LPContext/
