### ISSUE TITLE
Suggestion: sync of deleted messages with VentureChat

### ISSUE THREAD

**Issue by Nightwielder1** [DiscordSRV/DiscordSRV#1239]
VentureChat has a feature to delete chats in game. It would be very helpful to have these actions mirrored in DiscordSrv messages.

Sorry for the empty ticket a second ago, that was an accidental enter

**Comment by granny** [comment]
DiscordSRV doesn’t keep track of messages once they’re queued to discord, so it'd be difficult to implement on our side.

Talked with the VentureChat dev and he agreed it would be a cool feature to implement. Leave a message on his spigot thread so he can get back to it when he can. https://www.spigotmc.org/threads/venturechat.24005/
