### ISSUE TITLE
How much bandwidth does discord srv need to operate?

### ISSUE THREAD

**Issue by AddictedCoins** [DiscordSRV/DiscordSRV#1240]
Hi, I was thinking of making a proxy for discord SRV since discord is blocked in China, and with internet restrictions, it can not operate normally, and I need to buy the exact amount of bandwidth since I'm planning to buy premium proxy routes for the bot.
Thanks!

**Comment by Vankka** [comment]
We don't really know how much it would take, the amount will vary with the things that need to be transmitted, and how much is being transmitted (for example if lots of messages are being sent in Discord, the amount of bandwidth is increased, although not by much).
You might want to get a bigger amount of bandwidth at the beginning and monitor how much is being used, then adjust the amount accordingly.
