### ISSUE TITLE
Dosen't work well with paper1.17.1 lastest

### ISSUE THREAD

**Issue by leonpano2006** [DiscordSRV/DiscordSRV#1242]
Message cant sent from discord to minecraft
[latest.log](https://github.com/DiscordSRV/DiscordSRV/files/7109844/latest.log)

**Comment by ANutley** [comment]
Hi, the issue tracker is used for bugs. Please ask for support in our discord server https://discord.discordsrv.com

**Comment by leonpano2006** [comment]
> Hi, the issue tracker is used for bugs. Please ask for support in our discord server https://discord.discordsrv.com

i mean this is bug

**Comment by thewilloftheshadow** [comment]
This is not a bug, but most likely a result of an improper configuration, which would be something to ask for support with in the Discord server

**Comment by leonpano2006** [comment]
<#883742717908242513>
#4502-discord-mc
