### ISSUE TITLE
Chinese translation has Simplified and Traditional mixed in it

### ISSUE THREAD

**Issue by WongIong** [DiscordSRV/DiscordSRV#1247]
### Why?

Because the old one is confusing people and not guiding how to use it.

### What and How?
At line 46

注意：佔位符 %reply% 將會被替代成 DiscordToMinecraftMessageReplyFormat 的格式, 即你需要把 %reply% 加入 DiscordToMinecraftChatMessageFormat 裡

### Are there alternatives?

the same

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by granny** [comment]
We don't really have anyone in our team who can reliably translate our configs into Chinese. If you'd like, you can add the changes yourself https://github.com/DiscordSRV/DiscordSRV/blob/master/CONTRIBUTING.md#translating

Read here on how to add your own changes:
https://docs.github.com/en/repositories/working-with-files/managing-files/editing-files#editing-files-in-another-users-repository

**Comment by WongIong** [comment]
It is a comment in .yml file. so i dont think it can be added by this way.
also this issue is base on the helper's request, so.. dont ask me.

**Comment by WongIong** [comment]
i mean, i have went to the file and used ctrl+f but didnt find it.
And i found out that "put(Language.ZH" contains both simplified and traditional chinese. I would like to advise you to change it to zh_cn and zh_tw. cn with simplified and tw with traditional.
My english level is not good enough to contains emotions. so if there are any words' choices made you feel offences, i apologize for it.

**Comment by granny** [comment]
> i mean, i have went to the file and used ctrl+f but didnt find it.

https://github.com/DiscordSRV/DiscordSRV/blob/develop/src/main/resources/messages/zh.yml#L31-L33

> And i found out that "put(Language.ZH" contains both simplified and traditional chinese. I would like to advise you to change it to zh_cn and zh_tw. cn with simplified and tw with traditional.

Excuse our ignorance, but we can't really tell the difference ^-^. The person who originally added translations made it traditional, though, so if you're up to fixing the mistranslations, feel free. We follow [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) which doesn't include zh_cn/zh_tw, so we have to follow one or the other.

> also ah.. my english level is not good enough to contains emotions. so if there are any words' choices made you feel offences or some positive feelings, i apologize for it.

don't worry about it, no one's been offended. No need to apologize.

**Comment by WongIong** [comment]
ok then. it is just an advise, if you cant add it then just ignore it. some people cant read simplified chinese also some cant read traditional one. they both are chinese but using different characters.
this is from google translate:
![image](https://user-images.githubusercontent.com/36799194/132962190-bfaedd14-9ec4-4156-9c5a-4455a6d14e3c.png)

**Comment by Vankka** [comment]
What has happened here is, the original translation was in Chinese traditional (https://github.com/DiscordSRV/DiscordSRV/pull/469), but options added after that translation have been added by translating through Google translate, and most of them have been with Chinese simplified. 

So the files have a both Chinese traditional and simplified in them. There have been a lot of new things added since the initial translation, updating it now would take a lot of time

Apologies for the inconvenience

**Comment by WongIong** [comment]
Yup, as i said in the support ticket before. The sentence i mentioned above looks like a robot translated msg.
It doesnt matter if it is traditional or simplified, it just need to be united to a same version.
also i have to say, there are many people in west-south asia using simplified chinese such as Singapore. East-South asia has Taiwan, Hong Kong and Macau are both using Traditional Chinese and also able to connect to WAN, they dont have GFW controlled.
