### ISSUE TITLE
Add Text Color For error warn and info or separate Info , Warn ,Error console channels

### ISSUE THREAD

**Issue by ZeroOne00001** [DiscordSRV/DiscordSRV#1250]
### Why?

it will be easier to differentiate errors and warnings

### What and How?

like discord text formatting single line block with a colored text or multiline block

### Are there alternatives?

An alternative approach will be separating info , warn and error into 3 channels in which only the info console will accept commands input

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by BoredManCodes** [comment]
Coloured console output is already in the works

**Comment by Vankka** [comment]
This is available in the latest version
