### ISSUE TITLE
Add option for in-game blocks to "muffle" proximity voice chat

### ISSUE THREAD

**Issue by WillyWhitewool** [DiscordSRV/DiscordSRV#1254]
### Why?

This could be an interesting feature to make proximity chat even more dynamic.

### What and How?

Not sure if this is possible, but a way for blocks to reduce the volume or range of proximity chat for players behind solid walls and ceilings would be interesting. One example of how it'd work is that a group of players inside a house would have their own channel while players outside would be put in a different one even if they are technically within range. 

### Are there alternatives?

There could be an option in the voice.yml to enable or disable this behavior. There could maybe even be more advanced options, such as excluding certain types of blocks from this behavior like non-opaque blocks.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by Vankka** [comment]
Probably isn't going to happen, figuring out all the blocks between each 2 players would require a lot of processing, and voice chat with Discord is already quite limiting (already a low priority feature for us)

> volume

Discord doesn't support altering the volume users can hear each other, it's either on or off
