### ISSUE TITLE
Add Discord to Minecraft currency link.

### ISSUE THREAD

**Issue by SgtMajorJohn** [DiscordSRV/DiscordSRV#1255]
### Why?

I think it would be a great idea to implement a way to utilize the bot created for the link to have a current feature that can reward a person $1 in-game for 1 word sent in discord, it will incentivize a community on discord to earn in-game currency while not being active on the server.

### What and How?

It should have a command, for example, !coins would bring up how many coins you've acquired from sending messages on discord, and a !redeem command which will transfer the number of coins you have on discord to in-game currency such as Essentials currency.

### Are there alternatives?

There is a plugin for this exact request but has not been updated in 2-3 years, and it would require a player to link their account to the same bot twice if the server was running DiscordSRV and DiscordCoins. DiscordCoins is on spigot and is outdated and could be incorporated into a currently evolving plugin.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else

DiscordCoins Link: https://www.spigotmc.org/resources/discordcoins-link-discord-and-minecraft-with-coins.57369/

**Comment by Dinty1** [comment]
After some discussion. we've decided that this would be better off as an addon that hooks into DiscordSRV's API rather than a part of the plugin itself. It's unlikely that we will be making that ourselves, so you may need to find someone else who is willing to make such a plugin.
