### ISSUE TITLE
DiscordSRV for PocketMine or Bedrock Edition

### ISSUE THREAD

**Issue by BugPatcher** [DiscordSRV/DiscordSRV#1261]
### Why?

Nukkit already has a java plugins to nukkit plugins translator called Pokkit on GitHub. However, nukkit (or cloudburst) does not support the aquatic update. This really impacts the survival gameplay. PocketMine is very good, but it does not have a java plugins to bedrock plugins translator. 

### What and How?

The plugin should be uploaded to the PocketMine website (this should be easy to convert to bedrock/PocketMine since DiscordSRV really only has to do with text and sound). 

### Are there alternatives?

Someone create a java plugins to bedrock plugins converter, something similar to Pokkit on GitHub  (this may be complicated).

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else

Thank you for considering my suggestion.

**Comment by Vankka** [comment]
It isn't as you put it "easy to convert", PocketMine plugins are written in PHP, unlike DiscordSRV which is written in Java. 
We're not interested in writing a completely different piece of software for PocketMine. A native Nukkit version may come in the future, but as for PocketMine, no.
