### ISSUE TITLE
Make a single sync only do Discord > MC and an option for vice-versa

### ISSUE THREAD

**Issue by srnyx** [DiscordSRV/DiscordSRV#1263]
### Why?

I have a paid rank in Minecraft, a VIP role in Discord, and a Twitch Sub role in Discord.
I want Twitch Subs and VIPs to get the paid rank in-game, but I don't want the Twitch Subs to get the VIP role from having the paid rank in-game.

### What and How?

Maybe something in `synchronization.yml` or some sort of permission, not really sure.

### Are there alternatives?

No

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by Dinty1** [comment]
Duplicate of #1126

**Comment by Dinty1** [comment]
If you *only* want to sync Minecraft->Discord and vice versa you can use GroupRoleSynchronizationOneWay and GroupRoleSynchronizationMinecraftIsAuthoritative

**Comment by BoredManCodes** [comment]
https://support.scarsz.me/transcript/4J5Kd7utQGSogyfuXxR5LA

**Comment by Dinty1** [comment]
> https://support.scarsz.me/transcript/4J5Kd7utQGSogyfuXxR5LA

Gotcha, thanks
