### ISSUE TITLE
You must be logged into a voice channel to play

### ISSUE THREAD

**Issue by GabrielDEV04** [DiscordSRV/DiscordSRV#1264]
### Why?

Hello I come to give you a suggestion which would be really useful for my Roleplay server and for other servers I think too. So here it is:

I saw that you have a vocal system so you master the vocal channels and it would be good to make an option which would be to ensure that if the player is not in a vocal channel (for example in-game) he is kick. This will allow all the players in the game to be in a single voice so it would facilitate Moderation and avoid Metagaming for Roleplay servers

I am French this message comes from Google Translate

### What and How?

.

### Are there alternatives?

.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else

.

**Comment by Scarsz** [comment]
#930
