### ISSUE TITLE
ChannelTopicUpdaterRateInMinutes: 5 not working

### ISSUE THREAD

**Issue by moeboard** [DiscordSRV/DiscordSRV#1265]
### Expected behavior

Discord Channel Topics Update Rate 5 Minutes

### Actual behavior

Discord Channel Topics Update Rate 10 Minutes

### Steps to reproduce

![discordsrv](https://user-images.githubusercontent.com/41667526/134206075-3fc1a661-dbc0-49d0-abe6-588f995581a3.PNG)

### Server software and version

git-Paper-266

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

**Comment by Scarsz** [comment]
10 minutes is the minimum value. This isn't a bug.
