### ISSUE TITLE
Ability to check how many boosts an individual has

### ISSUE THREAD

**Issue by projectaidan** [DiscordSRV/DiscordSRV#1266]
### Why?

It would be useful to reward users who have boosted (x) amount of times in the guild on the server. Having for example,  discordsrv:boosting<2:true, value would be great. 

### What and How?

It would allow you to check for how many boosts a user has and assign them accordingly. 

### Are there alternatives?

N/A

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else

N/A

**Comment by Vankka** [comment]
The Discord API doesn't provide that information
