### ISSUE TITLE
Support for custom Death Messages

### ISSUE THREAD

**Issue by WolfyRed** [DiscordSRV/DiscordSRV#1273]
### Why?

When adding Death Messages plugins, like ones that add custom/configurable death messages, DiscordSRV stops responding to death messages and no longer broadcasts death messages in the Discord channels.

### What and How?

The plugin should send Death Message notifications, even when they are custom. It could try hooking or looking for plugins that add custom Death messages, and then that would work.

### Are there alternatives?

No alternatives. Maybe massive command block stuff, but I can't do that yet.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else

When you die, there is a death message, probably even a death message event too. You could hook to that specific event, and grab the string being sent, and send it through DiscordSRV.

**Comment by WolfyRed** [comment]
Bump: The plugin is named "DeathMessages". Simply.

**Comment by Dinty1** [comment]
Due to the the way DeathMessages (DeathMessagesPrime) is coded, death messages are cleared and cannot be picked up by DiscordSRV. This can be fixed by installing and configuring DMPMonitorCompat, available here: https://www.spigotmc.org/resources/dmpmonitorcompat.67404/
