### ISSUE TITLE
Compatibility with NickNamer

### ISSUE THREAD

**Issue by OsoaGitHub** [DiscordSRV/DiscordSRV#1287]
### Why?

It makes it easier to tell who is who

### What and How?

In the gamechat channel, make the names of players sync with the NickNames from [NickNamer](https://www.spigotmc.org/resources/nicknamer-integrated-api.5341/)

### Are there alternatives?

I don't think so

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by Scarsz** [comment]
This would have nothing to do with DiscordSRV. DiscordSRV already supports display names. Ask that plugin's developer to properly set them.
