### ISSUE TITLE
Chatty [global] issue

### ISSUE THREAD

**Issue by MegaGraphqwe** [DiscordSRV/DiscordSRV#1301]
### Expected behavior

Hi, I need some help.
How can I remove the [global] prefix in Minecraft chat massages from discord?
![Снимок экрана 2021-11-08 в 4 31 52 PM](https://user-images.githubusercontent.com/68541635/140751419-3d63af7e-95d5-4b09-ae8c-81a4dd2749d2.png)

DiscordSRV-Build-1.24.0
Chattiy-2.19.4

### Actual behavior

I need a massage without [global] prefix

### Steps to reproduce

My massages.yml
![Снимок экрана 2021-11-08 в 4 39 37 PM](https://user-images.githubusercontent.com/68541635/140751971-ea269e6b-9a0f-40ae-b2a2-7e58d8005258.png)

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

### Anything else

Tnx

**Comment by lynrayy** [comment]
How do you removed this prefix? Don't just close issue, tell us!
