### ISSUE TITLE
Implementing the Discord username placeholder in webhook chat delivery

### ISSUE THREAD

**Issue by fireFerry** [DiscordSRV/DiscordSRV#1304]
### Why?

This will be handy for when you both want do display the Minecraft username, and the Discord username in the webhook username.

### What and How?

Currently you can use the placeholders `%displayname%` and `%username%`, or enable `UsernameFromDiscord` and have the username of the webhook be the username of the Discord account. With the current configuration, it isn't possible to have both in the same name. My suggestion would be to add the `%discordname%` placeholder to the list of available placholders, so you could use both the Minecraft and the Discord username in the webhook username. The only limitation you could run into is the webhook username length limit (Discord states it's 80, but might be 32), but as the Discord avatar is already fetched, I don't think it would be hard to implement this placeholder.

### Are there alternatives?

You could make another config option to accomplish the same, but with a placeholder you create more customization.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else

If anything is unclear, feel free to ask me about it!

**Comment by Vankka** [comment]
This has been implemented and will be available in the next version, and on current development builds, https://snapshot.discordsrv.com

**Comment by Cronosus** [comment]
i just searched this.. will it contain even other placeholders? like if i want to display ingame group, or perhaps change color of  nickname (displayed name) in discord according to discord role.
in messages.yml are more placeholders, would be nice to be able to use atleast those

**Comment by BoredManCodes** [comment]
Don't necropost, what you want should already be possible, if you need help with it then join the Discord at https://discordsrv.com/discord
