### ISSUE TITLE
Support for version 1.18

### ISSUE THREAD

**Issue by mzrtamp** [DiscordSRV/DiscordSRV#1314]
### Why?

Minecraft has officially released version 1.18, and of course, Spigot has followed suit as well. So I hope to get some clarity for this plugin to support it stably, safe, and sound.

### What and How?

Since Minecraft will release a new version again at 1.18.x, surely many changes happen between 1.17 and 1.18(?). I also have a lot of wishes from users for you to do it soon.

### Are there alternatives?

No, I'm still relying on the latest version for this plugin (which it still doesn't support). And luckily I haven't found any errors in my production server instance yet.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by Vankka** [comment]
Minecraft 1.18 is already supported in the latest version, the next version will be published soon.

**Comment by BrandonT80** [comment]
> Minecraft 1.18 is already supported in the latest version, the next version will be published soon.

As a person who uses 1.18, I can confirm that the latest version does not work in 1.18 and the plugin name is red in the plugin list.

**Comment by Dinty1** [comment]
https://discord.discordsrv.com join here and open a support ticket please. There are over 3000 servers using it on 1.18 according to bStats, so it's unlikely that's the issue.

**Comment by BrandonT80** [comment]
> https://discord.discordsrv.com join here and open a support ticket please. There are over 3000 servers using it on 1.18 according to bStats, so it's unlikely that's the issue.

Maybe another plugin is conflicting it then if that many are using it in 1.18. I will wait for the other plugins to update before I ask for support then.

**Comment by Vankka** [comment]
Locking this thread. 

1.18 is supported, if you can't get it to work join https://discordsrv.com/discord
