### ISSUE TITLE
Messages using webhooks

### ISSUE THREAD

**Issue by Dark-Sou1** [DiscordSRV/DiscordSRV#1329]
### Why?

It would be easier to see who has sent the message if it is in the form a webhook with the avatar of the user or the face of the player.

### What and How?

You can make use of the webhook like how the nqn bot works. You can use the face of the player as the webhook avatar, and the players name as the webhooks name and send messages thru the webhook.

### Are there alternatives?

Im pretty sure this will work since i have worked with discord bots (python).

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by BoredManCodes** [comment]
Hiya! this already exists :D
Config.yml - Line 79:
    Experiment_WebhookChatMessageDelivery = true

Next time please check on the Discord server:
https://discordsrv.com/discord
