### ISSUE TITLE
Visual Bukkit extension for Discord SRV

### ISSUE THREAD

**Issue by shishir9747** [DiscordSRV/DiscordSRV#1330]
### Why?

Visual Bukkit is a plugin maker. If you create a extensions of Visual Bukkit for Discord SRV, people can create public/private addon for discord srv easily.

### What and How?

Doc: https://github.com/OfficialDonut/VisualBukkit/wiki/Extensionsan extension

### Are there alternatives?

There are no alternatives for this

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by Vankka** [comment]
We are not interested in making a extension for it
