### ISSUE TITLE
Your microphone is muted in the discord voice chat, even if there is another player next to you in the game

### ISSUE THREAD

**Issue by artemzheglovds** [DiscordSRV/DiscordSRV#1331]
### Expected behavior

If you use voice chat and log out of the server without leaving the voice chat, and the admin restarts the server, then the next time you log into the server and approach another player, your microphone will be turned on.

### Actual behavior

For all the actions mentioned above, when the player approaches you, your microphone is turned off.

### Steps to reproduce

1. Go to the server with your friend
2. Go to the voice chat associated with discord.
3. Approach your friend in the game.
4. Log out of the server
5. Reboot the server
6. The next time you use voice chat, your microphone will remain muted.

### Server software and version

paper-1.18.1-71.jar

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

### Anything else

A few months ago I contacted your Discord and your staff asked me to do a github report

**Comment by artemzheglovds** [comment]
![image](https://user-images.githubusercontent.com/65168490/145710966-79041e0c-ca13-4b51-b070-6cac6b61c2c7.png)

**Comment by Vankka** [comment]
The players that were muted aren't kept between restarts and the bot cannot unmute users when they aren't connected to a voice channel, so if they leave whilst in the lobby this will happen. 

This feature intentionally only mutes users who can also unmute theirselves, so if this happens they can just unmute theirseves.
Keep in mind that users who do not override speaking permission restrictions in the voice lobby (non-Administrators) will not be server muted and are not effected by this.
