### ISSUE TITLE
Change Discord Usernames to MC Username (Sync)

### ISSUE THREAD

**Issue by Exophobias** [DiscordSRV/DiscordSRV#1333]
### Why?

I am doing a roleplay server and I would like people's Discord server usernames to be their Minecraft usernames.
Plus, I use XenForo as my forums and I can make their website usernames the same as their Discord name through Discord integration.

### What and How?

Just like the nickname sync (Discord to Minecraft), have sync for username to Discord nickname.

### Are there alternatives?

N/A

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else

N/A

**Comment by Scarsz** [comment]
Existing nickname synchronization **is** Minecraft to Discord, not the other way around

**Comment by Exophobias** [comment]
> 

Oops, I didn't realize that. Sorry
