### ISSUE TITLE
Certain usernames not processing correctly.

### ISSUE THREAD

**Issue by vintrove** [DiscordSRV/DiscordSRV#1335]
### Expected behavior

Usernames and text to go from discord to minecraft.

### Actual behavior

Text is dismissed when certain characters such as < and > exist within usernames or messages.

### Steps to reproduce

Include < or > in your username in discord.
Send a message from Discord to Minecraft.
Missing text and/or errors will pop up.

### Server software and version

Spigot 1.18.1

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

### Anything else

Love the plugin! Keep up the good work!

**Comment by James-Bennett-295** [comment]
If you are using the latest version then try the latest snapshot from [here](https://snapshot.discordsrv.com) as it works ok for me with no errors on snapshot 109e954

![](https://imgur.com/fyZrb0a.png)

**Comment by Vankka** [comment]
Could not reproduce.
