### ISSUE TITLE
DiscordChatChannelEmojiBehavior 'name' option returns emoji instead of the name.

### ISSUE THREAD

**Issue by mibby** [DiscordSRV/DiscordSRV#1339]
### Expected behavior

``DiscordChatChannelEmojiBehavior: "name"`` returning ``:emojiname:``.

### Actual behavior

Seems to return unicode / emojis, breaking plugins that rely on :name: sent in-game for translating to emoji, such as EmojiChat.

### Steps to reproduce

* Set ``DiscordChatChannelEmojiBehavior: "name"`` in config.
* Send an emoji from bridged discord chat to in-game.
* See emoji / unicode instead of :name:.

### Server software and version

git-Paper-71 (MC: 1.18.1)

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

### Anything else

DiscordSRV-Build-1.24.1-SNAPSHOT-1f74136.jar

Discord ticket 6484-emoji-name-option for reference and full details.

**Comment by Vankka** [comment]
Fixed, will be available in the next version or development builds, https://snapshot.discordsrv.com

**Comment by mibby** [comment]
Confirmed fixed, thanks!
