### ISSUE TITLE
Bungeecord %bungee_total% ping late

### ISSUE THREAD

**Issue by YTiceice** [DiscordSRV/DiscordSRV#1340]
### Expected behavior

The placeholder %bungee_total% ping is too late.
I use %bungee_total% with discordsrv, if players join the server, the number of players will be delayed

### Actual behavior

The placeholder %bungee_total% ping is too late.
I use %bungee_total% with discordsrv, if players join the server, the number of players will be delayed

### Steps to reproduce

The placeholder %bungee_total% ping is too late.
I use %bungee_total% with discordsrv, if players join the server, the number of players will be delayed

### Server software and version

[週五, 17. 12月 2021 20:28:11 TST INFO] This server is running Paper version git-Paper-73 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: df1301b) You are 4 version(s) behind Download the new version at: https://papermc.io/downloads Previous version: git-Paper-66 (MC: 1.18)

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

**Comment by Vankka** [comment]
The `%bungee_total%` placeholder is designed to retrieve the player counts every x seconds (it is set to 30 seconds by default), this is not a DiscordSRV issue.

You might be able to reduce the timer and use the math expansion to get closer to the right player count though.
