### ISSUE TITLE
User mention and channel mention conversion doesn't work.

### ISSUE THREAD

**Issue by kirjorjos** [DiscordSRV/DiscordSRV#1341]
### Expected behavior

I expect it to link the channel in the discord when I do #channel, and ping a user when I do @user.

### Actual behavior

It says #channel or @user with no linking to them.

### Steps to reproduce

[latest.log](https://github.com/DiscordSRV/DiscordSRV/files/7737907/latest.log)

### Server software and version

"This server is running Paper version git-Paper-790 (MC: 1.16.5)"

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

**Comment by Dinty1** [comment]
We're going to need more detail than this, and since it seems all the support transcripts got wiped I can't see what was said in your ticket. Could you please provide us with the output of /discord debug as well as screenshots of you trying to mention a user/channel? You can send the debug report privately on Discord to `Dinty#4988` if you don't wish to show it here.

**Comment by kirjorjos** [comment]
![image](https://user-images.githubusercontent.com/35607697/150614237-cd517cc6-2693-4b34-8f8c-98f5fad26020.png)
![image](https://user-images.githubusercontent.com/35607697/150614256-1859edd8-aaa0-4525-b04a-fd092622780a.png)
https://bin.scarsz.me/af38e6fb-1005-407d-9e57-33d05390dde4#n4X2UArDMALqy7Uy14c8TEfpIootwJp4

**Comment by Dinty1** [comment]
Ok, thanks. Do you have a nickname in the Discord server?

**Comment by kirjorjos** [comment]
I do and it was also breaking with the nickname when I originally made the report, but attempting it now with an update that came out after the initial creation, it does work with the nickname.  Is there a way to make it work with the username rather than nickname I guess?

**Comment by Dinty1** [comment]
Not that I'm aware of. The channel mentions don't seem to work for me either so that certainly needs investigating.

**Comment by kirjorjos** [comment]
Testing channels now that you mentioned that, I can confirm channels also break on my end.

**Comment by sebastianjnuwu** [comment]
hum
