### ISSUE TITLE
Option to ignore bots in console channel

### ISSUE THREAD

**Issue by JasonHorkles** [DiscordSRV/DiscordSRV#1343]
### Why?

So having multiple bots send logs to the same channel doesn't cause the other servers to try to run a log as a command

### What and How?

Add option to ignore bots, pretty easy in JDA

### Are there alternatives?

Ignoring all commands which is basically already possible, but this should be easy enough

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by BoredManCodes** [comment]
Added to release, new config option titled `DiscordConsoleChannelBlockBots`
