### ISSUE TITLE
/discord linked command

### ISSUE THREAD

**Issue by YTiceice** [DiscordSRV/DiscordSRV#1345]
### Why?

Very convenient, no need to wait for players to go online

### What and How?

You can use the /discord linked command to query the linked account of offline players

### Are there alternatives?

Only mysql users can query offline players

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by Vankka** [comment]
Offline players can already be looked up by uuid or username
