### ISSUE TITLE
discord linked command in discord

### ISSUE THREAD

**Issue by YTiceice** [DiscordSRV/DiscordSRV#1346]
### Why?

Don’t use everyone’s mc id to find his discord

### What and How?

Can use the discord linked command in discord

### Are there alternatives?

使用前綴

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by Dinty1** [comment]
Not entirely sure what you mean, but you can already run `/discordsrv linked <discord user id>` from the Discord console or the chat channel console command feature.
