### ISSUE TITLE
DiscordSRV received a permission error response (50013) from Discord.

### ISSUE THREAD

**Issue by andrewkm** [DiscordSRV/DiscordSRV#1350]
### Expected behavior

No error.

### Actual behavior

Error lol.

### Steps to reproduce

1.17.1 Paper Build 408
DiscordSRV built upon https://github.com/DiscordSRV/DiscordSRV/commit/4775ab51fef037f1bd9ade6905682173cbc53a98

Send message from Discord to Minecraft that's too long.
`	Line 2296: [15:46:52] [DiscordSRV - JDA Callback 0/ERROR]: [DiscordSRV] DiscordSRV received a permission error response (50013) from Discord. Unfortunately the specific error isn't provided in that response.`

Example message: https://i.imgur.com/WToTkFd.png
Example output: https://i.imgur.com/G3EvRsp.png

Message goes through, console get's error shot into it.
Normal length messages go through without error.

What's happening here?

### Server software and version

1.17.1 Paper Build 408

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

**Comment by Dinty1** [comment]
By too long, do you mean over the DiscordChatChannelTruncateLength, over 2000 characters or something else?

Also, did you actually ask in the Discord server about this? Your last ticket was in November.

**Comment by andrewkm** [comment]
Oh this has been handled, can be closed.

**Comment by andrewkm** [comment]
Wait nevermind, this one hasn't been handled, the other one was.
Basically if message is too long on Discord, it goes through fine in game, but causes error in console:

https://i.imgur.com/7Dh7gq8.png

**Comment by andrewkm** [comment]
Upping the Truncate limit to something like 2000 removes the error, but then causes abnormally large messages in game, that normally the client would never allow.

**Comment by Vankka** [comment]
Does the bot not have permission to add reactions or view the message history in that channel?

**Comment by andrewkm** [comment]
Looks like not having the add reactions permission was the issue.
