### ISSUE TITLE
Line breaking on Discord causes spam in game.

### ISSUE THREAD

**Issue by andrewkm** [DiscordSRV/DiscordSRV#1351]
### Expected behavior

No Spam.

### Actual behavior

Spam.

### Steps to reproduce

1.17.1 Paper Build 408
DiscordSRV built upon [4775ab5](https://github.com/DiscordSRV/DiscordSRV/commit/4775ab51fef037f1bd9ade6905682173cbc53a98)

Example input: https://i.imgur.com/WSH7j8Q.png
Example output: https://i.imgur.com/I3plb67.png

### Server software and version

1.17.1 Paper Build 408

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

**Comment by Dinty1** [comment]
While potentially problematic, this is intended behaviour. If you wish to filter out the newlines, you can set your [DiscordChatChannelDiscordFilters](https://config.discordsrv.com/config/DiscordChatChannelDiscordFilters) config option (config.yml) to something like this:
```yaml
DiscordChatChannelDiscordFilters: {"\\n": "<newline>"}
```
