### ISSUE TITLE
False-detection of client as Lunar Client

### ISSUE THREAD

**Issue by pseudoforceyt** [DiscordSRV/DiscordSRV#1356]
### Expected behavior

To detect that the client is NOT lunar-client and refrain from sending the incompatibleClientAlert

### Actual behavior

Detects that the client is lunar-client and sends the incompatibleClientAlert

### Steps to reproduce

It happens for random players at random times so I have no idea how to reproduce this but you can try these steps:

1. Join with lunar-client
2. Leave the server and close lunar-client
3. Join the server with any other client
4. See incompatibleClientAlert in chat

### Server software and version

git-Purpur-1521

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

### Anything else

Tested Clients:
- Vanilla
- Fabric
- geyser (bedrock, all devices)

Tested Servers:
`git-Purpur-1521
git-Purpur-1502
git-Purpur-1171`

Tested DiscordSRV version: `1.24.1-SNAPSHOT-6e4d893`

**Comment by Vankka** [comment]
Could **not** reproduce, test versions:

```
LunarClient 1.16.5-fc86f27
This server is running Paper version git-Paper-670 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

LunarClient 1.17.1-fc86f27
This server is running Paper version git-Paper-409 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: c53577e on ver/1.17.1)

LunarClient 1.18.1-fc86f27
This server is running Paper version git-Paper-214 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: bfa50ad)

DiscordSRV a40787f
```

Attempted steps:
 - Login to server with LunarClient
   + Got message (as expected)
 - Login with vanilla client
   + Did not get message

**Comment by pseudoforceyt** [comment]
Cant reproduce on DiscordSRV build f73051f either, will let you know if the problem arises again
