### ISSUE TITLE
Linking by discord command

### ISSUE THREAD

**Issue by Kuba1428CZ** [DiscordSRV/DiscordSRV#1366]
### Why?

It will be easier for players to just write command on the discord server than finding a bot that they have to DM.

### What and How?

Just a discord command that can link minecraft with discord account, so players don't have to DM the bot..... 
They could just write **!link-mc <code>** in some command channel on discord server

### Are there alternatives?

Nope.
I don't use any alternative right now and i don't know how else it could work :shru

### Checks

- [x] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by BoredManCodes** [comment]
So players would do
`!link-mc 957c3421-5c2c-48aa-810d-2bd895804940`?
