### ISSUE TITLE
Daily Motd Channel

### ISSUE THREAD

**Issue by orang3i** [DiscordSRV/DiscordSRV#1367]
### Why?

it is a nice feature to have and i think it will be a easy way to implement with discord srv

### What and How?

A channel where members can send daily motd and a random one is chosen from it and updated every 24 hours

### Are there alternatives?

if this can't be implemented i would just use a normal channel add a 24 cool down and use a rng bot to pick a motd and update manualy but too much work

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by ChristianNewton** [comment]
Agreed, this would be a very good feature and I would definitely utilize it.

**Comment by BoredManCodes** [comment]
I **highly** doubt this would be added since it is such a niche feature

**Comment by orang3i** [comment]
> I **highly** doubt this would be added since it is such a niche feature

true but i suggested it here as discord srv already had the infrastructure to do it and could be easier than to make a seperate plugin from scratch.

**Comment by Dinty1** [comment]
A separate plugin could hook into our API and achieve such a goal.
