### ISSUE TITLE
DiscordSrv + Discord bot

### ISSUE THREAD

**Issue by Andrei12333** [DiscordSRV/DiscordSRV#1372]
### Why?

**This is a optional feature not a required one and will only be used if the user wants to**

I would really really like to be able to make a bot that has discordsrv's features as well as a moderation music, etc

**This is a optional feature not a required one and will only be used if the user wants to**

### What and How?

New config entry (New config option in config.yml of the plugin):
discord-bot-custom: true/false
discord-bot-custom-token: "Token generated by the bot"

The bot should contain the files/folders:
- config.yml (.env for linux)
- server.js
- discordsrv.js
- (Everything else can be decided by the user in the server.js code for the bot that needs them)

server.js:
Shoud contain "const add = require('./discordsrv.js')" at the top of the file code

Discordsrv.js:
Should contain code to generate the token to a token.yml if a token.yml file doesn't exist
Should contain code to send data from discord to minecraft
Should contain code to send data from minecraft to discord
Should contain code to send data from minecraft console to discord
Should contain code to link a minecraft account with a discord account
Should contain variables that can be used in server.js
Should contain code for every core feature in discordsrv to work correctly

### Are there alternatives?

**Well currently no.**

### Checks

- [x] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else

I had this idea becuse some other minecraft servers have bots like this and i would like it too sooo yeah.

Thank you,
ANDREI12333

**Comment by Scarsz** [comment]
DiscordSRV is written in Java, not JavaScript. The two are not compatible with each other, despite the name. We will not be rewriting DiscordSRV in JavaScript.
