### ISSUE TITLE
Config option for console messages to not be wrapped in code block formatting

### ISSUE THREAD

**Issue by ItsDed** [DiscordSRV/DiscordSRV#1375]
### Why?

The console discord channel is used heavily in my server, and having text wrapped in code block makes it incredibly hard to use the discord search feature in the console channel. Text wrapped in code block formatting doesn't get highlighted by search when matching a query.

### What and How?

Console messages are sent in plain text like in previous versions of DiscordSRV, with a config toggle allowing people to choose whether its sent in code blocks or not.

### Are there alternatives?

No alternatives I can think of. Since, from what I read on the discord, the code block feature is hard coded, there's no way around it currently.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else

Having DSRV log to discord makes it incredibly easy to search for specific things that happened on the server. The default discord search highlights any matches to easily search through all the logs available. With the addition of code blocks being mandatory, searches no longer match any highlights. It makes searching a very tedious and annoying task since it forces you to read through huge code blocks for what you're trying to find.

**Comment by jstan425** [comment]
Yea. i would love it as an options for not using code block.

**Comment by Jcodeerd** [comment]
I agree with this
