### ISSUE TITLE
Server sometimes hangs (doesn't get to "Done!") with DiscordSRV installed

### ISSUE THREAD

**Issue by Vankka** [DiscordSRV/DiscordSRV#1376]
### Expected behavior

Server starts up normally

### Actual behavior

Server doesn't get past "Done!"

### Steps to reproduce

- Have DiscordSRV enable
- Have another plugin log something when the plugin is being enabled
- *experience the deadlock*

### Server software and version

n/a

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

### Anything else

Confirmed with Geyser, not easily reproducible due to DiscordSRV loading in asynchronously

Caused by Console Appender trying to figure out if PlaceholderAPI is enabled

**Comment by gamer167** [comment]
ooooooooooooooooooooooooooooooooooooof
