### ISSUE TITLE
Lag spikes due to usage of RestAction#complete in JDAAppender

### ISSUE THREAD

**Issue by mastermc05** [DiscordSRV/DiscordSRV#1377]
### Expected behavior

To make all async so it wouldn't stop the main thread

### Actual behavior

it stopes main thread so there are some lag spikes  
server when idle, only ticks over 100
1.25.0
![profiler](https://user-images.githubusercontent.com/63639746/158048876-d84da62f-1b3e-4efc-ba0c-96c631fa792b.png)
1.25.1
![profiler](https://user-images.githubusercontent.com/63639746/158050209-ff52c707-9baa-4696-a347-4aed4665067a.png)

### Steps to reproduce

just watch profilers 

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

**Comment by Vankka** [comment]
Fixed in latest snapshot, https://snapshot.discordsrv.com
