### ISSUE TITLE
Prefix for Discord, not only for Minecraft

### ISSUE THREAD

**Issue by Miryex** [DiscordSRV/DiscordSRV#1378]
### Why?

For being able to block links (Gifs, Images etc.) as well as being able to only send certain messages to Minecraft.

### What and How?

![image](https://user-images.githubusercontent.com/93775214/158086103-f6a2235e-9621-4d74-92cb-a9542c330133.png)
Same option just for Discord to Minecraft chat

### Are there alternatives?

Being able to block certain words, for the "blocking function"

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by Scarsz** [comment]
If this just worked based on a prefix, that wouldn't stop people from just adding a `.` before links and they would go through fine

Allowing blocking links going to Minecraft would be much better implemented as it's own dedicated option
