### ISSUE TITLE
Have a message type "Links" for reporting link/unlinking of Minecraft/Discord accounts.

### ISSUE THREAD

**Issue by Wolfie713** [DiscordSRV/DiscordSRV#1382]
### Why?

Being able to have an output of linking/unlinking of accounts could be beneficial to admins to not only keep track of who is who, but prevent potential abuse.

### What and How?

Similar to DiscordConsoleChannelId, if "links" is blank then messages from it are discarded, or perhaps defaulted to the console channel.

Information should include the Minecraft user name and UUID, as well as the Discord name#tag and the long user ID.  Perhaps even the IP address?

As an extra step, if the channel ID is the same as the global/general channel ID, then not show any of the links messages (at least if IP address is included).

### Are there alternatives?

N/A

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else

Only other 'issue' I found that might be similar is #1290, but I have a feeling is actually different.  Sounds like that's to use for linking accounts, vs a channel for logging linking/unlinking activity.

**Comment by BlueTree242** [comment]
well, there is a command called `/discord linked <name or discord id>` isn't this enough

**Comment by Dinty1** [comment]
As this is possible with the [alerts feature](https://docs.discordsrv.com/alerts/) (Listen to [AccountLinkedEvent](https://github.com/DiscordSRV/DiscordSRV/blob/master/src/main/java/github/scarsz/discordsrv/api/events/AccountLinkedEvent.java) and [AccountUnlinkedEvent](https://github.com/DiscordSRV/DiscordSRV/blob/master/src/main/java/github/scarsz/discordsrv/api/events/AccountUnlinkedEvent.java)), it's very unlikely that we will add it as its own message type.
