### ISSUE TITLE
Disable More Features.

### ISSUE THREAD

**Issue by IntelloAuPimentFPVP** [DiscordSRV/DiscordSRV#1395]
### Why?

I want to more customization to the plugin because i want to disable somes features, but i've even search in the config.yml, messages.yml, theses are impossible to disable.

### What and How?

I want to disable the next things :

- When server is stopped
- MinecraftToDiscordChat
- MinecraftToDiscordCommand
- etc.

I want to disable everything but the start of the server.

### Are there alternatives?

Maybe i've bad tried but i've tried to disable theses by leaving their messages blank, maybe do i have bad maked it. But, it doesn't has worked.

Sorry for bad english, i'm french.

### Checks

- [x] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else

If there was a possibility to do that, i'm sorry of disturbing you.

**Comment by BoredManCodes** [comment]
All of these are customisable

**Comment by IntelloAuPimentFPVP** [comment]
How can I make it ? I only want a message when the server is started, I don't want others one.

**Comment by BoredManCodes** [comment]
Join our discord for more assistance https://DiscordSRV.com/discord

**Comment by IntelloAuPimentFPVP** [comment]
Okay
