### ISSUE TITLE
Boost Event for API

### ISSUE THREAD

**Issue by lucian929** [DiscordSRV/DiscordSRV#1397]
### Why?

I'd like to send players specific messages and/or commands when they boost the discord.

### What and How?

When a player boosts the discord, it should fire a PlayerBoostGuildEvent or something along the lines of that. I suppose the plugin could have an option in the config to run events/messages, but from what I could see the only thing that exists is the LP context.

### Are there alternatives?

LP Context, which is not ideal for my usecase.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else

I think that's all!

**Comment by GreemDev** [comment]
https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/events/guild/update/GuildUpdateBoostCountEvent.html

**Comment by Vankka** [comment]
There's already a JDA event for this, [`GuildMemberUpdateBoostTimeEvent`](https://github.com/DV8FromTheWorld/JDA/blob/legacy/v4/src/main/java/net/dv8tion/jda/api/events/guild/member/update/GuildMemberUpdateBoostTimeEvent.java)

**Comment by granny** [comment]
As Vankka said, you can already hook into JDA's [`GuildMemberUpdateBoostTimeEvent`](https://github.com/DV8FromTheWorld/JDA/blob/legacy/v4/src/main/java/net/dv8tion/jda/api/events/guild/member/update/GuildMemberUpdateBoostTimeEvent.java) event if you wanted to, so having an event in DiscordSRV would be redundant. Won't be happening.

If you'd like to send out a message when someone boosts, you can do so through alerts [as shown on the wiki](https://docs.discordsrv.com/alerts/#discord)
