### ISSUE TITLE
Unknown Discord Error

### ISSUE THREAD

**Issue by NixonSiagian** [DiscordSRV/DiscordSRV#1398]
### Expected behavior

[08:40:22 ERROR]: [DiscordSRV] DiscordSRV encountered an unknown Discord error: 20001: Bots cannot use this endpoint

### Actual behavior

the plugin doesn't crash just issues a log warning

### Steps to reproduce

![image](https://user-images.githubusercontent.com/72014408/166649841-367f145a-1af8-4cee-9172-f439ed277973.png)

### Server software and version

This server is running Paper version git-Paper-317 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: e5da93a) You are running the latest version

### Checks

- [x] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

**Comment by BoredManCodes** [comment]
This is due to an add-on you have for DiscordSRV, not by DiscordSRV itself.
Update any add-ons you have and restart your server.

For more help join our Discord at https://discordsrv.com/discord
