### ISSUE TITLE
[Suggestion] Config option to blur IP and other sensitive info in discord console

### ISSUE THREAD

**Issue by PhoenixCodingStuff** [DiscordSRV/DiscordSRV#1400]
### Why?

I would like my server Devs to know about errors and other stuff in console but also don't want to reveal other player's IPs and other info

### What and How?

Instead of displaying the IP and other info it should just say "REDACTED" or something else (just like debug report stuff)

### Are there alternatives?

There may not be any alternatives

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by Vankka** [comment]
That option already exists, it's called `DiscordConsoleChannelFilters`. And the exact use case you wanted is even [documented in the FAQ of our wiki](https://docs.discordsrv.com/FAQ/#example-3-replace-the-ip-address-of-those-that-join-the-game)
