### ISSUE TITLE
Possible to config certain messages to default ones / remove long discord Picture image link messages inside Minecraft

### ISSUE THREAD

**Issue by JinjaFormbi** [DiscordSRV/DiscordSRV#1403]
### Why?

While playing minecraft other members sometimes post images in the linked discord chat. That results in long chat messages without any usefull information for the player.
![2022-05-16_16 20 33](https://user-images.githubusercontent.com/81318107/168614402-bb876345-346b-429c-a9b7-4b3159447c5f.png)
 As seen, it clutters the chat messages.

### What and How?

By adding a config option that filters certain phrases / messages with common parts and replaces them. 
e.g. every message that starts with https:// is replaced by "sender posted a link"

### Are there alternatives?

Maybe a hard coded replacement would work too, but that would probably hamper other features. 

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by James-Bennett-295** [comment]
You can use the [`DiscordChatChannelDiscordFilters`](https://github.com/DiscordSRV/DiscordSRV/blob/master/src/main/resources/config/en.yml#L255) option to stop them going through.

**Comment by James-Bennett-295** [comment]
> You can use the [`DiscordChatChannelDiscordFilters`](https://github.com/DiscordSRV/DiscordSRV/blob/master/src/main/resources/config/en.yml#L255) option to stop them going through.

Setting that line to this should work: `
DiscordChatChannelDiscordFilters: {".*Online players\\(.*": "", ".*\\*\\*No online players\\*\\*.*": "", "https?:\\/\\/cdn\\.discordapp\\.com\\/([^ ]+)": "[File]"}`

**Comment by chrissamael** [comment]
The suggested Filter works if the image is sent as a link (as a text message), but the filter does not get applied to image uploads via the client
