### ISSUE TITLE
config to switch whether OGP is enabled

### ISSUE THREAD

**Issue by KisaragiEffective** [DiscordSRV/DiscordSRV#1407]
### Why?

It is un-controllable that a minecraft-user pastes a random URL. If the URL's [OGP](https://ogp.me/) (this is automatically shown on Discord client) contains image which is might not be seen (e.g. cockroach), what can we do currently?

### What and How?

Add config to switch this behavior. This feature should be opt-in, as current users shouldn't be confused by this setting.

This behavior can be disabled by surrounding URL with angle brackets.
Example: `https://example.com/` to `<https://example.com>`

### Are there alternatives?

Regex replacement could be alternative, but [matching regex is too complex](https://stackoverflow.com/a/3809435/14900042) and is not so clear.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by granny** [comment]
You can disable the "Embed Links" permission for the bot in whichever channel it's relaying to. This stops the bot from displaying a preview whenever a link is sent in whatever channel it's relaying to.
