### ISSUE TITLE
Typing indication

### ISSUE THREAD

**Issue by braxtonhall** [DiscordSRV/DiscordSRV#1412]
### Why?

When a player begins typing in the Minecraft chat, have the bot begin typing in the main chat channel.

### What and How?

With 1.19's addition of `previews-chat` in the server properties, if enabled and agreed to by players, everything the player types is sent to the server before the player actually finishes the message.

On receiving these events, a the server may enqueue a typing indication for discord.

### Are there alternatives?

For 1.16-1.18.2 I had been using a tiny plugin that listens for "typing" event on a custom channel, and also made a tiny fabric mod that sent that same "typing" event for every player keypress where the chat text entry is not empty and isn't a command. This alternative worked out alright but of course required players to actually install the fabric mod to participate.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by Vankka** [comment]
Seems quite limited since it'll only ever show that *the bot* is typing instead of which specific player is typing

**Comment by braxtonhall** [comment]
I agree it is quite limited, but it's also low effort and _fun_.
We've been using a plugin to recreate this since 1.16, and it still can tell someone having a conversation from discord that _someone_ is paying attention/responding.

**Comment by Taz03** [comment]
close this issue now? coz Chat previewing is being removed in 1.19.3
