### ISSUE TITLE
Default config causes issues on a Turkish machine

### ISSUE THREAD

**Issue by okunamayanad-zz** [DiscordSRV/DiscordSRV#1416]
### Expected behavior

It would work fine with the default values.

Heres the values that causes problems:
`DiscordConsoleChannelLevels: [info, warn, error]`
209 in config.yml

### Actual behavior

It gives out an error
![image](https://user-images.githubusercontent.com/77172909/174418965-36a6b6d7-e82a-46a4-8cd6-d2362fa9d7c6.png)

### Steps to reproduce

Run the plugin in a devive that has the language selected 

### Server software and version

git-Paper-794 (MC: 1.16.5)

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [x] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

### Anything else

In Turkish capital `i` is `İ` so when plugin tries to convert this `i` value to its capital version it gets the `İ` value so `info` in capital letters turns into `İNFO`

I tried to fix it by changing the letter `i` with `ı`
Because of capital `ı` is `I` in Turkish and it fixed the problem!

**Comment by okunamayanad** [comment]
Solution to this is using `variable.toUpperCase(new java.util.Locale("en"))` instead of `variable.toUpperCase()`
