### ISSUE TITLE
Chat message unlinks accounts

### ISSUE THREAD

**Issue by RobinRMC** [DiscordSRV/DiscordSRV#1418]
### Expected behavior

The bot just ignores the message or sends that you are already linked.

### Actual behavior

The bot sends a message stating that the given code is wrong and unlinks your accounts.

### Steps to reproduce

Link your account, send a random message to the bot, look if you are still linked.

### Server software and version

git-CatServer-1.12.2-4837c74 (MC: 1.12.2)

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [ ] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

**Comment by BoredManCodes** [comment]
In future please check on the Discord server before making an issue, the relinking on message can be controlled with this setting
https://github.com/DiscordSRV/DiscordSRV/blob/master/src/main/resources/config/en.yml#L295

However you shouldn't really be DMing the bot once you've linked accounts. We do not support nor recommend running multiple programs on the same bot account.

**Comment by RobinRMC** [comment]
Oh.. it's very weird though. Also, I was not DMing the bot. Someone else did and had their accounts unlinked. Thanks for the answer though!
