### ISSUE TITLE
Console log memory leak filling gigabytes of ram

### ISSUE THREAD

**Issue by CptDinosaur** [DiscordSRV/DiscordSRV#1420]
### Expected behavior

When a console channel is not configured, console messages are not stored into ram in a queue

### Actual behavior

If a console channel isnt configured, the plugin stores every console message in an ever growing linked list in memory.

Over time (and with my dynmap having a bug which spams errors) this fills up gigabytes of memory (example images are after a restart, I noticed this because it was using much more than this before)

![image](https://user-images.githubusercontent.com/26852749/177018458-688f0df8-b8dd-460c-9b60-d91ceb6950fd.png)
![image](https://user-images.githubusercontent.com/26852749/177018486-e1acedf0-130c-4b3f-a568-4d81178acfed.png)
![image](https://user-images.githubusercontent.com/26852749/177018489-6238f629-4d98-416d-9d74-54f880f2f56e.png)
![image](https://user-images.githubusercontent.com/26852749/177018491-2e62ac26-a49a-4064-ac96-7c6655d94068.png)

### Steps to reproduce

- Don't set a console channel
- Plugin correctly says its not forwarding console output
- Check a heap dump, its storing console output in ram
![image](https://user-images.githubusercontent.com/26852749/177018529-6be47a33-123d-47ec-9a72-e92d40fae82f.png)

### Server software and version

git-Paper-34

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

### Anything else

Reported via discord too, Scarsz confirmed it looks like a bug

**Comment by Scarsz** [comment]
Fixed in v1.26.0
