### ISSUE TITLE
When uploading an image to linked Discord channel, %toprolecolor% format is broken in game.

### ISSUE THREAD

**Issue by andrewkm** [DiscordSRV/DiscordSRV#1429]
### Expected behavior

Not sure how to explain this so I'll just give an example.

My config looks as such:
`DiscordToMinecraftChatMessageFormat: "[%channelcolor%Discord <white>|</white> %toprolecolor%%toprolealias%<reset>] %toprolecolor%%name%<reset>%reply% » %channelcolor%%message%"
DiscordToMinecraftChatMessageFormatNoRole: "[<aqua>Discord</aqua>] %name%%reply% » %message%"
DiscordToMinecraftAllRolesSeparator: " | "
DiscordToMinecraftMessageReplyFormat: " (replying to %name%)"`

When posting into the relevant channel on Discord, messages in game look as such. (**Correct functionality**)

Discord Post test: https://i.imgur.com/RRr7EeU.png
In-Game Result: https://i.imgur.com/2aShhqh.png

Discord Post with link test: https://i.imgur.com/a7hbbEy.png
In-Game Result: https://i.imgur.com/CRM1WzS.png

Now, for the bug, when simply dropping an image into the Discord client in the same channel:  (**Incorrect functionality**)

Discord Post via image drop: https://i.imgur.com/M5Mztec.png
In-Game Result: https://i.imgur.com/1FOGdDa.png

Not sure whats going on here, but for some reason during the above action %toprolecolor% simply shows up in game again. I remember we had this problem before https://github.com/DiscordSRV/DiscordSRV/issues/1399, which was fixed recently https://github.com/DiscordSRV/DiscordSRV/commit/d0aa5c62eb72aaecc4d91f5a47594e65cc355fce, perhaps that fix somehow didn't make it into another part of DiscordSRV which handles attachment messages? 

### Actual behavior

Read first section.

### Steps to reproduce

Read first section.

### Server software and version

Paper 1.19 Build 60

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

**Comment by granny** [comment]
fixed as of https://github.com/DiscordSRV/DiscordSRV/commit/8af5e287c2ccbf3b22043527f4eeb903119f59c8

Implemented in the latest development build. https://snapshot.discordsrv.com/

**Comment by andrewkm** [comment]
Thanks!
Can confirm this is now fixed.
