### ISSUE TITLE
Give Discord server role when linking account

### ISSUE THREAD

**Issue by ZeroVizibility** [DiscordSRV/DiscordSRV#1430]
### Why?

Because I only want people who have linked accounts to chat in the Minecraft chat channel to prevent spamming.

### What and How?

Maybe give the role to the linked Discord account?

### Are there alternatives?

I can't think of other alternatives.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by Scarsz** [comment]
Already a thing https://github.com/DiscordSRV/DiscordSRV/blob/master/src/main/resources/config/en.yml#L294=
