### ISSUE TITLE
Make Stickers show up in game chat

### ISSUE THREAD

**Issue by DerpDerpling** [DiscordSRV/DiscordSRV#1435]
### Why?

it would be nice to see some kind of indication that a sticker has been sent on the discord side of things, as atm when someone sends a sticker in the discord relay, it shows nothing in game

### What and How?

it could show that someone sent a sticker in chat, for example, [Discord] Username sent Sticker (Sticker name)

### Are there alternatives?

not that i could think of, it may not even be possible, but i just thought it would be a nice thing to have.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by granny** [comment]
Implemented in the latest development build. https://snapshot.discordsrv.com/
