### ISSUE TITLE
/me messages not appearing in discord chat sync

### ISSUE THREAD

**Issue by samidont0817** [DiscordSRV/DiscordSRV#1443]
### Expected behavior

The expected behavior would be that /me messages appeared in discord chat sync.

### Actual behavior

The plugin does not register /me messages as a chat message.

### Steps to reproduce

https://imgur.com/a/4AFLmUj

You just talk using /me instead of general chat. With a server attached to a chat sync discord channel.

### Server software and version

purpur-1.19.2

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

**Comment by Dinty1** [comment]
/me is not a chat message and therefore should not be passed. If you want it to show up in the channel then you can use the [alerts feature](https://docs.discordsrv.com/alerts/#command-triggers).

In future please follow the instructions when opening a bug report. They are there for a reason.

**Comment by LOOHP** [comment]
Technically Mojang made it a chat message in 1.19.1+, but eh who cares about the chat signing system.
