### ISSUE TITLE
Linked Discord Account can use Discord Commands 

### ISSUE THREAD

**Issue by ralf-jar** [DiscordSRV/DiscordSRV#1446]
### Why?

That can help to the player at keep in minecraft without open the discord applitacion for use commands for bots like music

### What and How?

I think this can be done if the plugin check if the minecraft user is linked and that have the permissions for use the commands in the discord server, if both setences are true then run directly the discord command:

Minecraft User: !play song name

Plugin: [User is Linked?] -> [User have permission] -> Run the Command in Discord

### Are there alternatives?

Actually I dont found other ways to use 

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by GreemDev** [comment]
The majority of good bots ignore other bots (including webhooks).
Chances are, if this was even implemented, the bots would most likely ignore it anyways, unless you run your own music bot
