### ISSUE TITLE
\n, <, > and maybe other things behave strange

### ISSUE THREAD

**Issue by Mr-Jeany** [DiscordSRV/DiscordSRV#1447]
### Expected behavior

I expect that it will just send smth like "Hi!\nHow are you?" or "<3".

### Actual behavior

But it sends:
"Hi!
How are you?" or: "<" (without three)

### Steps to reproduce

Just send in Discord chat that it linked with Minecraft these things

### Checks

- [x] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

**Comment by granny** [comment]
Closing for not following instructions. Please read the checklist carefully and do what it says.
