### ISSUE TITLE
Allow configuration of ServerWatchdog's Discord ping target

### ISSUE THREAD

**Issue by delcake** [DiscordSRV/DiscordSRV#1448]
### Why?

DiscordSRV's current behavior when the ServerWatchdog criteria is met (the time since the server's last tick has exceeded `ServerWatchdogTimeout`), is to ping the Discord server owner with a notice "the server room is on :fire::bangbang:"

However when running a Minecraft server for a Discord community, it's not uncommon for the Discord server owner to be unrelated to the administration of the Minecraft server and thus not be a good notification target. So in these cases, it would be ideal to allow us to configure a Discord user or role as the ping in the event the ServerWatchdog has an alert.

### What and How?

To accommodate this, `config.yml` should be extended with a new `ServerWatchdogNotificationIds` (or similar) array (much like the existing `DiscordChatChannelBlockedIds` property), which would accept the IDs of the Discord user(s) or role(s) to be notified. I expect the default behavior of a null or unconfigured array should be the existing behavior where the Discord server owner is the notification target.

### Are there alternatives?

The only available alternative in cases where we don't want the Discord server owner to be notified is to disable the ServerWatchdog feature, which I don't believe is a prudent idea.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else

Issue #297 started out discussing the idea of this suggestion, but seems to have been derailed by talk of the Watchdog feature's reliability before ultimately being closed. In my particular case the Watchdog alert was completely valid, but its choice of notification target led to me not being aware that an issue had occurred until much later. As I believe the original idea of configurable notification targets has merit, I'm opening this new suggestion to put forward the idea.

**Comment by underscore11code** [comment]
The message (including the ping) is already [configurable](https://github.com/DiscordSRV/DiscordSRV/blob/master/src/main/resources/messages/en.yml#L404).

**Comment by delcake** [comment]
Oh fantastic, thanks for pointing me at that. I had been looking through all the [https://docs.discordsrv.com/config/#serverwatchdog](ServerWatchdog) configuration documentation and totally missed it was in a different location.
