### ISSUE TITLE
Map Discord Roles to separate commands

### ISSUE THREAD

**Issue by Thorkull** [DiscordSRV/DiscordSRV#1450]
### Why?

We'd like to be able to run different commands (specifically, assigning Minecraft users to different LuckPerms groups) depending on the role they have assigned in the Discord server.

### What and How?

Ideally, we would list each role on its own line in the linking.yml and then have sub configurations for each role with a linking console command and an unlinking console command.

### Are there alternatives?

Really, anything that will allow us to assign different LP groups based on the Discord role.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else

Please let me know if what I put in is unclear or if there's another way to handle this that we didn't catch.

**Comment by granny** [comment]
While the feature you're looking for is different from what we have, the solution to your use-case can already be accomplished through our `synchronization.yml` config. Read more here: https://docs.discordsrv.com/Installation/#group-role-sync

If you run into any issues or have any questions, feel free to join our discord server and create a ticket https://discordsrv.com/discord

**Comment by Thorkull** [comment]
Awesome, thanks!
