### ISSUE TITLE
Discord srv creating/deleting channels in voice 

### ISSUE THREAD

**Issue by PirateBeowolf** [DiscordSRV/DiscordSRV#1455]
### Expected behavior

Voice Channel Created: #585ffd1a-170f-4e4d-badb-98d46c2a3d32
ID: 1016841739031543818•Today at 6:46 PM

Voice Channel Deleted: #585ffd1a-170f-4e4d-badb-98d46c2a3d32
ID: 1016841739031543818•Today at 6:46 PM

On repeat non stop 

### Actual behavior

Voice Channel Created: #585ffd1a-170f-4e4d-badb-98d46c2a3d32
ID: 1016841739031543818•Today at 6:46 PM

Voice Channel Deleted: #585ffd1a-170f-4e4d-badb-98d46c2a3d32
ID: 1016841739031543818•Today at 6:46 PM

On repeat non stop 

### Steps to reproduce

updated, changed token
and no idea
was working fine 

### Server software and version

paper  1.19.2

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

**Comment by granny** [comment]
We use the issue tracker exclusively for bug reports and feature requests.
  However, this issue appears to be a support request.
  Please join our Discord at https://discordsrv.com/discord and go to the #support channel for help with installing or configuring DiscordSRV.
