### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by NoFiixx** [DiscordSRV/DiscordSRV#1472]
### Why?

Hello, i know this feature is already for the console command channel, but i would like to ask if there's a chance to add a third channel just for Whitelisting ?, for those who dont want to give permission to the console channel ? ... it would be something like this plugin (discontinued), but with the feature that we dont have to write all the command ? "whitelist add", just write the nickname only. i know that already there's the feature of link, but, i would really appreciate it if u could add this also.. it would be of so much help :) 

Example:

![image](https://user-images.githubusercontent.com/36577126/197536101-9d7911f4-4208-40e3-9559-bfc21746f31e.png)

:) 

### What and How?

.

### Are there alternatives?

.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by granny** [comment]
please fill in the template correctly when issuing feature requests
