### ISSUE TITLE
Allow configurable number of linkable accounts

### ISSUE THREAD

**Issue by purejosh** [DiscordSRV/DiscordSRV#1474]
### Why?

For players who have cam accounts and Java+bedrock players, so they can auth 2 or more Minecraft accounts to one Discord. 

### What and How?

Allow linking of more than one (configurable) Minecraft account to a discord account. 

### Are there alternatives?

Not really. Right now, it only allows one link. Adding more links (2 or more, configurable) is all that could be done. 

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by angerthosenear** [comment]
This may be weird in combination with proximity voice chat for which Minecraft account to track for voice. Just something I thought of to keep in mind.

This feature would also be handy for me.

**Comment by Vankka** [comment]
Duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/1308
