### ISSUE TITLE
blacklist words

### ISSUE THREAD

**Issue by Yukylyu** [DiscordSRV/DiscordSRV#1482]
### Why?

hide ad

### What and How?

Hi,
I would like that the plugin doesn't send certain sentences containing a word, from the server to the discord (for example an ad).

### Are there alternatives?

-

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by James-Bennett-295** [comment]
This is already possible with the `DiscordChatChannelGameFilters` option.
