### ISSUE TITLE
Add ability to block new lines in messages sent from Discord to in-game chat.

### ISSUE THREAD

**Issue by Fruitloopins** [DiscordSRV/DiscordSRV#1488]
### Why?

Players can spam chat like this.
![image](https://user-images.githubusercontent.com/49851457/210296759-1382e322-ffd8-4a77-84ff-d717d5c9462d.png)

### What and How?

I might be missing something obvious but I couldn't find any way to block new lines or remove them with regex in the config, after a change I imagine you should be able to toggle new lines from doing anything or not, I think new lines should be disabled by default.

### Are there alternatives?

Ability to add regex to block messages posted in Discord showing in the in-game chat would work (if that isn't a feature I just haven't noticed) but it has the downside of being harder for users to understand.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by Dinty1** [comment]
Change this option in config.yml:
```yaml
DiscordChatChannelDiscordFilters: {"\\\n": " "}
```
