### ISSUE TITLE
Setting to configure visiblity of proximity chat channels

### ISSUE THREAD

**Issue by ClementJ18** [DiscordSRV/DiscordSRV#1490]
### Why?

When playing, it's handy to be able to see if people are already using the proximity channels. Right now, it's hard for the average user to tell if the people online are using proximity chat or simply not in voice chat since the channels are hidden.

### What and How?

A new setting in the voice.yml called something like "hide-voice-channels" which default to true and hides the channels.

### Are there alternatives?

If possible, use the existing permissions from the category, like this it allows a lot of customisation for the server owner on what users can do in the voice chats.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by Suprais135** [comment]
Without a doubt this function would help a lot, sometimes some of my novice players think that the server is empty because all the channels are private.

**Comment by Scarsz** [comment]
> If possible, use the existing permissions from the category, like this it allows a lot of customisation for the server owner on what users can do in the voice chats.

This is already the existing behavior.

**Comment by Scarsz** [comment]
Implemented in https://github.com/DiscordSRV/DiscordSRV/commit/b61c8bb0e859e48d4171ee4c014d9ecc19edb954, please test
