### ISSUE TITLE
Auto-link the Minecraft name to Discord display_name

### ISSUE THREAD

**Issue by DonKolia** [DiscordSRV/DiscordSRV#1497]
### Why?

It is an option that allows you to more easily identify minecraft server players on the discord server.

### What and How?

In the "Sync Setup" add an option that is:
**link-display-name**: true

Once this setting is set, when the user links his discord account to minecraft, his discord nickname is automatically changed.

### Are there alternatives?

More complicated and **absurd** to program:
link-display-name-placeholder: '%player_name%'

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by BoredManCodes** [comment]
This already exists as an option in the Sychronization.yml
