### ISSUE TITLE
Add the minecraft id please

### ISSUE THREAD

**Issue by DonKolia** [DiscordSRV/DiscordSRV#1498]
### Why?

I have been trying to capture the discord name using the plugin from https://www.spigotmc.org/resources/discordpapistats.87888/
But doesnt work.
![image](https://user-images.githubusercontent.com/55564649/215292540-11c8998a-f166-4232-888c-d315cd82b3d8.png)
My idea is this, add the minecraftname here, a new row:
![image](https://user-images.githubusercontent.com/55564649/215292561-95441281-2e89-4c2f-90f1-9d0a8a71f72e.png)
![image](https://user-images.githubusercontent.com/55564649/215292723-1ac791b6-fa09-4e7f-b3f9-c7a7011604dc.png)

And here, add the minecraftname and user and numbers user#0000
![image](https://user-images.githubusercontent.com/55564649/215292589-6bba3642-fab4-4581-bdc1-2e3b3e5c96ba.png)
![image](https://user-images.githubusercontent.com/55564649/215292691-686e25c3-cfa0-4137-a79e-cc95200236d2.png)

### What and How?

That was my idea.

### Are there alternatives?

I have no alternatives.

### Checks

- [x] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else

This helps us to be able to use your plugin to verify people on web pages also using query and conditions display content.

**Comment by Scarsz** [comment]
Neither Minecraft or Discord username are static. People can link their accounts then a minute later change both names and this data will be completely invalid.

It's up to you to translate Discord and Minecraft IDs into their current display names.
