### ISSUE TITLE
Not working with chatty/global chat

### ISSUE THREAD

**Issue by lynrayy** [DiscordSRV/DiscordSRV#1499]
### Expected behavior

_. i dont like blanks on github, it is annoying to fill required fields_

### Actual behavior

_. i dont like blanks on github, it is annoying to fill required fields_

### Steps to reproduce

_. i dont like blanks on github, it is annoying to fill required fields_

### Server software and version

This server is running Paper version git-Paper-302 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 425baed) You are 5 version(s) behind Download the new version at: https://papermc.io/downloads Previous version: git-Paper-290 (MC: 1.19.2)

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

### Anything else

Not working with chatty.
DiscordSRV have `DiscordChatChannelPrefixRequiredToProcessMessage: "!"`

Chatty global chat settings:
```
    range: -2
    symbol: '!'
```

Discord SRV reacts on messages ONLY when message is like "!!Message"
And not react on "!Message"

If i set `DiscordChatChannelPrefixRequiredToProcessMessage: ""`
DiscordSRV reacts on all messages (also local) and translating in to discord

**Comment by lynrayy** [comment]
If i set DiscordChatChannelPrefixRequiredToProcessMessage: ""
it sends message to discord twice

**Comment by James-Bennett-295** [comment]
What is your discord tag? I haven't seen you ask in the discord server.

**Comment by lynrayy** [comment]
I didnt ask in discord

**Comment by underscore11code** [comment]
> I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com/) to see whether this issue is in fact a bug that needs to be fixed.

Please don't blindly tick boxes. Check with support first, this is most likely not a bug but a misconfiguration.

**Comment by lynrayy** [comment]
No it's not closed
They are not helping me with prefix problem
![image](https://user-images.githubusercontent.com/59417884/216224706-312fc089-4ff8-4d43-9516-b5f6c5569b55.png)

**Comment by GreemDev** [comment]
***GitHub is not for support, go to the Discord***
