### ISSUE TITLE
Not working with chatty/global chat #1499

### ISSUE THREAD

**Issue by lynrayy** [DiscordSRV/DiscordSRV#1500]
### Expected behavior

. i dont like blanks on github, it is annoying to fill required fields

### Actual behavior

. i dont like blanks on github, it is annoying to fill required fields

### Steps to reproduce

. i dont like blanks on github, it is annoying to fill required fields

### Server software and version

This server is running Paper version git-Paper-302 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 425baed) You are 5 version(s) behind Download the new version at: https://papermc.io/downloads Previous version: git-Paper-290 (MC: 1.19.2)

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

### Anything else

**Do not close until resolved, and this is a BUG**

Anything else
Not working with chatty.
DiscordSRV have DiscordChatChannelPrefixRequiredToProcessMessage: "!"

Chatty global chat settings:

    range: -2
    symbol: '!'
Discord SRV reacts on messages ONLY when message is like "!!Message"
And not react on "!Message"

If i set DiscordChatChannelPrefixRequiredToProcessMessage: ""
DiscordSRV reacts on all messages (also local) and translating in to discord

**Comment by lynrayy** [comment]
I will close it by myself when will be resolved

**Comment by GreemDev** [comment]
No, that's not how this works. You get help in Discord when you get it. You can't be a nuisance and demand support this instant on a place in which we ***DON'T OFFER SUPPORT***.
