### ISSUE TITLE
Allow up to two linked Minecraft accounts per Discord account

### ISSUE THREAD

**Issue by codingreg** [DiscordSRV/DiscordSRV#1512]
### Why?

I run a server using Velocity with GeyserMC as proxies, and Pufferfish as the game server. Because of the way Floodgate works when taking Bedrock Edition players, even when logging in from the same Microsoft account, the accounts are identified differently from Java, and some players enjoy gaming on both versions - but they are unable to link their Discord account to two 'different' Minecraft accounts, and I've made account linking a requirement to join my server. As of now I'm just putting those people in the bypass list, but it would be better for player management if the bot could allow two Minecraft accounts linked to the same Discord account.

### What and How?

Plugin should remain about the same, just allowing two Minecraft accounts per Discord ID instead of just one. 

### Are there alternatives?

I don't think so, but I'm open to suggestions.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by thewilloftheshadow** [comment]
Or you could have your users link their Java and Bedrock accounts together
https://link.geysermc.org

**Comment by codingreg** [comment]
> Or you could have your users link their Java and Bedrock accounts together https://link.geysermc.org

That was a real life saver, and it works even if you have them through Game Pass! Thank you very much. I hope other people looking for it find this topic.

**Comment by codingreg** [comment]
> Or you could have your users link their Java and Bedrock accounts together https://link.geysermc.org

That was a real life saver, and it works even if you have them through Game Pass! Thank you very much. I hope other people looking for it find this topic.
