### ISSUE TITLE
Lag with luckperms

### ISSUE THREAD

**Issue by SladeHazard** [DiscordSRV/DiscordSRV#1516]
### Expected behavior

No lag

### Actual behavior

Causing lag

### Steps to reproduce

use discordsrv with luckperms installed on the server

### Server software and version

Paper 1.12.2

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

### Anything else

![image](https://user-images.githubusercontent.com/45261094/226742829-b3d0c24c-d4b0-46e4-9217-8226c748df77.png)

https://spark.lucko.me/TMGTKvkN9q

**Comment by underscore11code** [comment]
0.83% of a tick is absolutely nothing. If you're encountering performance issues, the culprit is something else.

**Comment by Vankka** [comment]
![Untitled](https://user-images.githubusercontent.com/20226336/226747907-242487f0-7f20-4574-beaf-9ab54993fb96.png)
Most of the time is spent in the green box, which is LuckPerms (or specifically Java) code (~128ms of ~180ms), leaving ~52ms for DiscordSRV code (over the entire sampling period). 

There is nothing to optimize on DiscordSRV's end, everything is already coming from caches.

If you don't want to use DiscordSRV's LuckPerms contexts, you can add `LuckPerms-Contexts` to `DisabledPluginHooks`
