### ISSUE TITLE
When we have to send message from discord to minecraft we have to ping the discord bot and type the message 

### ISSUE THREAD

**Issue by ayan-afk** [DiscordSRV/DiscordSRV#1518]
### Expected behavior

we expect that we do not have to ping the bot again and again while sending the message

### Actual behavior

we always have to ping the bot and then type the message and send it . it does not work if we haven't pinged it

### Steps to reproduce

yes . it again and again happens there is no way to stop it

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

**Comment by BoredManCodes** [comment]
You didn't ask in the Discord server.
We don't provide support over GitHub.
Create a ticket in our Discord to receive help.

**Comment by Scarsz** [comment]
You need to enable the message content intent in the Discord developer portal, as per the instructions.
