### ISSUE TITLE
matrix.org bridge

### ISSUE THREAD

**Issue by 42Willow** [DiscordSRV/DiscordSRV#1542]
### Why?

Thanks for the great plugin!

Currently, I'm using t2bot to bridge discord <--> matrix.org 

It works flawlessly, but matrix.org --> minecraft doesn't work.

### What and How?

minecraft <--> matrix.org bridge. And an optional discord <--> matrix.org bridge.

This way the chats on Minecraft, Discord, and matrix.org would all be bridged.

https://github.com/matrix-org/matrix-appservice-discord

Here is the repo for the matrix appservice bridge to discord.

### Are there alternatives?

Option to pick up webhooks and send them to Minecraft too.

**A:** The `DiscordChatChannelBlockWebhooks` option in config.yml can be set to false to allow webhook messages to go from Discord to Minecraft.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by James-Bennett-295** [comment]
The `DiscordChatChannelBlockWebhooks` option in config.yml can be set to false to allow webhook messages to go from Discord to Minecraft.

**Comment by 42Willow** [comment]
Ok, thanks! I think a matrix.org bridge would still be beneficial though because it's a great way to bridge to other platforms, secure, and decentralised. I'll update the main comment with your solution.

**Comment by James-Bennett-295** [comment]
It is possible to create an addon for Matrix using this plugin's API, but I highly doubt a Matrix bridge would ever be added to DiscordSRV itself.

**Comment by 42Willow** [comment]
Ok, I can't be bothered making one - I'll close this issue as won't fix unless someone else wants it too. It works fine with the webhooks.
