### ISSUE TITLE
Advancements with "announce-to-chat": false show up in chat (Paper Unaffected)

### ISSUE THREAD

**Issue by CubedTemp** [DiscordSRV/DiscordSRV#1546]
### Expected behavior

Advancements with `"announce-to-chat": false` don't appear in Discord.

### Actual behavior

Advancements with `"announce-to-chat": false` are sent to discord
(Does not affect PaperMC)

### Steps to reproduce

1. Download BuildTools
2. Build latest spigot
3. Download latest version/snaphot of DiscordSRV
4. Get a datapack that has an advancement with `"announce-to-chat": false`
5. Place DiscordSRV in "`plugins`" folder.
6. Place datapack in the datapacks folder (inside the world folder)
8. Start the server
9. Configure DiscordSRV
10. Restart the server
11. Join
12. Grant advancement 
13. Advancement shows in Discord

### Server software and version

CraftBukkit version 3811-Spigot-c62f4bd-85b89c3 (MC: 1.20.1)

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

### Anything else

This issue only affects spigot. 
(correct me if I am wrong, but it is as DiscordSRV is hooking into the paper advancement api in #1502 
[add support for Paper advancements api for checking if advancements should be hidden](https://github.com/DiscordSRV/DiscordSRV/pull/1502/commits/02a8b99e254ed3ffc6cc13f3ca7fe87103eb1e1e)

**Comment by Scarsz** [comment]
Was able to reproduce this on Paper as well

**Comment by Scarsz** [comment]
Unable to reproduce after https://github.com/DiscordSRV/DiscordSRV/commit/fb3294e689205aeaf0072957260122b609fe2796
