### ISSUE TITLE
Save linked accounts on a timer

### ISSUE THREAD

**Issue by Vankka** [DiscordSRV/DiscordSRV#1548]
### Why?

Linked accounts are currently only saved when the server shuts down correctly, so if the server crashes linked accounts will not be saved.

Some external applications may also be reading the linked_accounts.json file directly for linked accounts

### What and How?

There should be (possibly configurable) timed task for saving linked accounts, they should also not be saved if there haven't been any changes since the last time they were changed.

### Are there alternatives?

No

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by Dinty1** [comment]
Should have been closed by the PR
