### ISSUE TITLE
%name% does not use discords new display names.

### ISSUE THREAD

**Issue by TwoPointInfinity** [DiscordSRV/DiscordSRV#1550]
### Expected behavior

in config with the default "DiscordToMinecraftChatMessageFormat" %name% shows a person's effective name on Discord (nickname if present, username otherwise)
This should now go in priority order of Server Nickname -> Display Name -> Username
in game you should see a players display name if they dont have a nickname. 

### Actual behavior

A discord users display name is skipped, if no server nickname is present the username is shown in game. 

### Steps to reproduce

User has discord's new username system and has a username and a display name present, but no nickname in the server. chat in discord bridge channel and view it from in game. 

### Server software and version

git-paper-49 (1.20.1)

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

### Anything else

i made a ticket in discord, not sure which place is better to get the attention of a bug or at least show the public its exists. ion case anyone else has this issue they can see here its been reported but discord tickets are private.

**Comment by Dinty1** [comment]
Global nicknames are only supported on the v5 version of JDA, which we can’t update to without a ton of breaking changes. It is very much planned to do this, but will require significant rewriting of the plugin.

For now, you should set a server nickname.

**Comment by TwoPointInfinity** [comment]
Thank you for the clarification, i didnt know if this was reported anywhere. i look around for a bit and didnt find anything on it. My server does have set nicknames from IGN names, but i thought if this was unnoticed i should report it. Thanks .

I genguinly cant imagine the amount of work that would need to be done to update to jda 5 and i dont expect it to happen soon either.

**Comment by Dinty1** [comment]
Actually upon further investigation server nicknames don’t work either. I’m going to reopen this for visibility

**Comment by Dinty1** [comment]
This is implemented in the next release through a custom fork of JDA, which will not require any rewriting.
