### ISSUE TITLE
Player Count

### ISSUE THREAD

**Issue by jedicarlisle** [DiscordSRV/DiscordSRV#1560]
### Expected behavior

The player count should look like this.

[Tue 20:03:21 INFO  ]  There are 0 out of maximum 1,337 players online.

### Actual behavior

On June 13, 2023, The player count started to look like this.

[Tue 20:10:33  INFO  ]  ?[33mThere are ?[33m out of maximum  ,337?[33m players online.

And the question marks are in little square boxes.
These are commands that Essentials issues with  /list

### Steps to reproduce

The problem looks this way when it gets to my Discord via DiscordSRV. On the Apex Hosting Server, in the Console, everything looks normal. I'm pretty sure that I mentioned this in your Discord, but I can't remember. It's been a long time.

### Server software and version

paper_1.20.1.jar

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

### Anything else

Thank you

**Comment by James-Bennett-295** [comment]
This is fixed in the latest snapshot: https://snapshot.discordsrv.com/
