### ISSUE TITLE
Use EventPriority.HIGH instead of EventPriority.MONITOR for ChatEvents

### ISSUE THREAD

**Issue by kugge** [DiscordSRV/DiscordSRV#1562]
### Why?

Moderation/misc plugins that cancel chat events using `EventPriority.HIGHEST` don't work with DiscordSRV.  
Deleted messages are still broadcasted to Discord.

### What and How?

Use EventPriority.HIGH or HIGHEST instead of EventPriority.MONITOR for ChatEvents

### Are there alternatives?

-

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by Vankka** [comment]
That's not how that works, listeners are processed in this order:
```
LOWEST
LOW
NORMAL
HIGH
HIGHEST
MONITOR
```
meaning, cancelling at anything other than MONITOR gurantees that the event will be cancelled at MONITOR unless a listener uncancels it between the two listeners.
Moderation plugins should aim to cancel events at LOWEST or LOW to ensure other plugins aren't processing blocked events.
