### ISSUE TITLE
Change ChatControlPro to ChatControlRed

### ISSUE THREAD

**Issue by kangarko** [DiscordSRV/DiscordSRV#1566]
### Why?

ChatControlPro is listed at https://modrinth.com/plugin/discordsrv and https://docs.discordsrv.com/master/#plugins-that-use-our-api while it has been abandoned in favor of ChatControl Red.

(All users who bought Pro at any time can get a free upgrade so it doesn't matter now)

I am simply requesting you to change the link to ChatControl Red to direct to https://mineacademy.org/chatcontrol

Thanks
Matej

### What and How?

.

### Are there alternatives?

.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by Vankka** [comment]
Docs updated @ https://github.com/DiscordSRV/Documentation/commit/779fa82b9cf3a7d7299ee6565b0dfc2d356f4266
Modrinth updated, and I requested @Scarsz to update the Spigot resource page

**Comment by kangarko** [comment]
Thank you very much! :)

**Comment by kangarko** [comment]
@Vankka I made a review video on integrating DiscordSRV: https://www.youtube.com/watch?v=pmqGjRvCyTA

If you want you can post it to the Docs page. At the end of the video I spent 20 seconds mentioning my online class, if that is a problem I can delete that segment.
