### ISSUE TITLE
mysql store id

### ISSUE THREAD

**Issue by sebastianjnuwu** [DiscordSRV/DiscordSRV#1574]
### Why?

Hello, it would be interesting to integrate the plugin to Nlogin the issue of storing the player's discord id in Nlogin there is a table for the player's discord id in addition to Nick and uuid would be interesting implement this!

### What and How?

Make change to save the player's discord id in nlogin's mysql table 

### Are there alternatives?

At the time no 

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else

This would help make web systems and interactions with other plugins easier and thus expand contributions with discordsrv

**Comment by Vankka** [comment]
DiscordSRV isn't going to save data to another plugin's database. There are events available for linking & unlinking as well as a API to get linked accounts available for other plugins to use.
