### ISSUE TITLE
Spamming player events in chat as advancements

### ISSUE THREAD

**Issue by Discount-Milk** [DiscordSRV/DiscordSRV#1575]
### Expected behavior

Not repeat the player actions I made in game to show up in the Discord channel as advancements. 

### Actual behavior

Picking up items or taking damage causes an advancement to be sent in discord channel but not Minecraft.

### Steps to reproduce

Install snapshot version
Pick up dirt
Watch messages show up in discord channel, not minecraft chat

https://i.imgur.com/607V9Yt.png
https://i.imgur.com/RpgKjUT.png
https://i.imgur.com/UFfMZZZ.png
https://bin.scarsz.me/9c91e4ae-a79a-496e-ad74-9dedad1e003d#vFouEffAKgR6y0g7PJcIn46wonsTTqmy (debugger as I did it)

https://mclo.gs/Xacpebp

### Server software and version

git-Purpur-2004 (MC: 1.20.1), DiscordSRV-1.27.0-SNAPSHOT-4fbb7c0

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

### Anything else

(I didn't go to the DiscordSRV discord server for support, but I did ask Shadow for a sanity check before reporting this to you guys. https://i.imgur.com/21C4sYe.png)

**Comment by Dinty1** [comment]
This *should* have been fixed on the latest snapshot

**Comment by granny** [comment]
100% sure it is now fixed on latest snapshot build
