### ISSUE TITLE
Allow running commands on Minecraft through Discord

### ISSUE THREAD

**Issue by Nepahlem** [DiscordSRV/DiscordSRV#1578]
### Why?

It would be fantastic for staff to be able to use moderation commands through the discord chat, plus I don't think it would be too much of an issue to integrate 

### What and How?

The main difference is that it would make it a lot more convenient for players to run commands when  not on. And would make servers a lot safe since mods can always do something about what's going on

### Are there alternatives?

I'd that's not an issue perhaps make some sort of log command that if someone does let's say a /mute command on discord, you will be notified with a reminded that you wanted to run that command as soon as you log on

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else

I adore this plug-in. And I'd hope it can evolve to allow displaying more data than just messages

**Comment by GreemDev** [comment]
Already exists. [By default the prefix is `!c`](https://github.com/DiscordSRV/DiscordSRV/blob/master/src/main/resources/config/en.yml#L226), so for example, `!c give GreemDev diamond 1`.
