### ISSUE TITLE
Make config.yml option MinecraftDiscordAccountLinkedRoleNameToAddUserTo be a list and not string

### ISSUE THREAD

**Issue by TheJoshue** [DiscordSRV/DiscordSRV#1581]
### Why?

Because it would be more flexible, we can have 1 or any amount of roles to grant when someone link their account.

### What and How?

Not a big change, just having an ABILITY to have more than 1 roles to grant to user when he links.

### Are there alternatives?

I really am not sure what to say here.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by Scarsz** [comment]
To be more flexible isn't the purpose of a "why" statement on a feature request... what is your actual use case for this? The reason this hasn't been implemented is because there's no good reason to assign multiple link roles. If you have a use case that's contrary then that would be something to mention.

**Comment by TheJoshue** [comment]
> To be more flexible isn't the purpose of a "why" statement on a feature request... what is your actual use case for this? The reason this hasn't been implemented is because there's no good reason to assign multiple link roles. If you have a use case that's contrary then that would be something to mention.

I understand.

That is actually why i am suggesting this, i need this.
On my server i have roles and only few of them use permissions, most of the roles are for vanity and enhancing server aesthetics.

For my specific use case, when someone link their account, i would like to grant them "Linked" + "Player" role.
Now why i want this, because i want other people who only have "Member" role to be able to see that they have "Linked" role and ask themselves what is it so they will either find out when they join MC server or ask on discord.
I want to give limited access to Member roles until they get linked account, then they are verified as player of the server - because they joined the server and linked their account, they will get "Player" role and also "Linked" role.

I hope this is enough info. Thanks.

**Comment by Scarsz** [comment]
That doesn't explain why you need two roles. From what you're saying, your "linked" role could just not exist and instead be your "player" role. 

There doesn't have to be a role called "linked" in many situations... it can be more context dependent like assigning them a "player" role instead.

Keep in mind too, when a player unlinks their accounts, this role is _also removed_.

You could also just go the group synchronization route instead. Assign people the "linked" role then use the multiple group sync options to give them a "player" role or another suitable rank.

**Comment by TheJoshue** [comment]
So there is a way to give ingame group to a player when he links his account? then that group would sync if i configure it to have congruent role for discord?

**Comment by Scarsz** [comment]
Giving an in-game group to the player isn't mandatory for synchronization. You can give the default group a `discordsrv.sync.rolename` permission and configure a `"rolename": "role id"` entry in your group synchronization config. That will give everyone that corresponding role once they link.

**Comment by Dinty1** [comment]
It doesn’t have to be the role’s name, that’s intended for ingame group names but for the sake of what you’re doing it can be literally anything
