### ISSUE TITLE
Watchdog config options

### ISSUE THREAD

**Issue by Mr-Tech-13** [DiscordSRV/DiscordSRV#1589]
### Why?

This is a great feature, but please give the ability to define the user(s) and/or role(s) to ping. There are ways to fix this by editing messages.yml, but it should be a configuration option. The main reason why is that the guild owner is sometimes not the person who would fix the technical issues with the server, and i have seen quite a few posts about this.

### What and How?

Add an optional watchdog role ping and optional user ping option in config.yml to alert people other than the guild owner that the server is no longer ticking

### Are there alternatives?

Edit messages.yml with <@&roleID> or <@userID> to ping the user

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by Mr-Tech-13** [comment]
Could you explain how?

**Comment by Dinty1** [comment]
You’ve explained it yourself. Edit the mentions into the option in messages.yml.

**Comment by Mr-Tech-13** [comment]
Could that be at least be added to some sort of wiki? While researching this I found unresolved issues that could have benefited from this being in the wiki

**Comment by Dinty1** [comment]
It’s already there. https://docs.discordsrv.com/master/messages/
