### ISSUE TITLE
GroupRoleSynchronization Discord to Minecraft dont work

### ISSUE THREAD

**Issue by DonKolia** [DiscordSRV/DiscordSRV#1593]
### Expected behavior

When i add a role in discord, nothing in Minecraft 

### Actual behavior

When i add a role in discord, nothing in Minecraft - When i remove role in discord, works in Minecraft.
When i add or remove roles in Minecraft, it works.

The Bug = Discord add role > Nothing in Minecraft

### Steps to reproduce

When i add a role in discord, nothing in Minecraft - When i remove role in discord, works in Minecraft.
When i add or remove roles in Minecraft, it works.

### Server software and version

This server is running Paper version git-Paper-167 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 0c0a480) You are 29 version(s) behind Download the new version at: https://papermc.io/downloads/paper Previous version: git-Paper-17 (MC: 1.20)

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

### Anything else

I tried this with **DiscordSRV-1.27.0-SNAPSHOT-fdcb09f** and the **DiscordSRV-Build-1.26.2**

**Comment by DonKolia** [comment]
Is not a request, is a bug- I use DiscordSRV always. Now, this is not working.

**Comment by Dinty1** [comment]
It’s almost certainly not a bug. Join the discord server and open a ticket.
