### ISSUE TITLE
2fa

### ISSUE THREAD

**Issue by Teufel0406** [DiscordSRV/DiscordSRV#1603]
### Why?

for security on not premium Server 

### What and How?

The bot sends a message into a channel where the person can react to it because the bot can register who reacts to it and deletes the message as soon as the right person reacts. As long as there is no reaction, the in-game player is frozen and cannot execute any commands

### Are there alternatives?

i use a second bot but i dont like that new player have to do 2 verifys 

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by thewilloftheshadow** [comment]
This is very much out of scope for DiscordSRV

**Comment by Vankka** [comment]
This has been discussed before, we aren't going that far to supporting cracked servers and this is much better suited to a 3rd party plugin hooking into DiscordSRV
