### ISSUE TITLE
Discord code blocks break console channel

### ISSUE THREAD

**Issue by elijahr2411** [DiscordSRV/DiscordSRV#1604]
### Expected behavior

When a user sends a code block (by surrounding text with 3 backticks) in the minecraft channel, the backticks should be escaped before that message is sent to the console channel, as the console channel already uses a code block

### Actual behavior

The backticks are sent unescaped, which causes the code block in the console channel to end and breaks future logging in that message

### Steps to reproduce

1. Set up discord-srv with a console channel and a general channel
2. In the general channel, send a code block by surrounding the message in 3 backticks. Alternatively, send three backticks in the minecraft server chat.
3. Observe how in the console channel, the code block used for logging breaks

### Server software and version

git-Paper-260 (MC: 1.20.2)

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [x] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

**Comment by James-Bennett-295** [comment]
This is fixed in the latest snapshot: https://snapshot.discordsrv.com/
