### ISSUE TITLE
Message Translator

### ISSUE THREAD

**Issue by Zhou-Shilin** [DiscordSRV/DiscordSRV#1606]
### Why?

I'm hosting a server and my players are from different (two) countries.

### What and How?

Would it be possible to add a *message translation* feature?
When passing messages between Minecraft and Discord, if the text is not in English, attach an English version; if the language is English, attach a <specified language, configurable> version. Thanks!

### Are there alternatives?

no?

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by ANutley** [comment]
Thanks for the suggestion, however this idea would be more suited for an addon as opposed to being in the main plugin.
