### ISSUE TITLE
Please add support for "Chit-Chat"?

### ISSUE THREAD

**Issue by EmanYm** [DiscordSRV/DiscordSRV#1610]
### Why?

Chit-Chat is (yet another) chat formatting plugin, made by `YouHaveTrouble`, for Paper, Purpur and Folia versions 1.20.2-1.20.4 _(as of the writing of this request)_

### What and How?

There wouldn't be any noticeable surface changes, but it sould allow the same level of in-game chat compatibility as every other chat formatting plugin DiscordSRV already supports

### Are there alternatives?

If Chit-Chat can't be supported - _or you just don't want to_ - that's fine.  It's not the end of the world, and there are plenty of up-to-date alternatives that DiscordSRV already support.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else

[Morinth link](https://modrinth.com/plugin/chitchat)
[GitHub Source](https://github.com/YouHaveTrouble/ChitChat)

**Comment by Vankka** [comment]
Enable `UseModernPaperChatEvent` in the config.yml
