### ISSUE TITLE
Link account using channel message instead of DM

### ISSUE THREAD

**Issue by LKits** [DiscordSRV/DiscordSRV#1617]
### Why?

Many Discord users have DM disabled so DiscordSRV is unable to send them DM.

### What and How?

A player can join Discord server and paste 4-number-PIN into link channel. Then DiscordSRV checks that code and links it with MC account.

You could also add message in channel ("Linking successful") and auto delete of messages.

### Are there alternatives?

Haven't seen any.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by Dinty1** [comment]
The Channels option (line 30 of config.yml) allows you to specify a “link” channel for people to send their codes to
