### ISSUE TITLE
warn on shutdown 1.20.4 server

### ISSUE THREAD

**Issue by Tioplaya** [DiscordSRV/DiscordSRV#1622]
### Expected behavior

without warns

### Actual behavior

on disable server - https://logpaste.com/eO0KUmad

### Steps to reproduce

1.install plugin on purpur 
2.disavle server (/stop command )

### Server software and version

git-Purpur-2118 (MC: 1.20.4)*

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.
- [ ] I didn't actually check any of these things

**Comment by PSYCHEER** [comment]
better to give it as code block while these temp log sites hold that just for 90 days, I'm searching for some error on shut down but idk if you have something same

`
![image](https://github.com/DiscordSRV/DiscordSRV/assets/42911029/64961441-449c-4bfb-ba94-b13d9ee6d9a4)
`

**Comment by Tioplaya** [comment]
By the time you answered, I had already lost interest in the plugin and lost the logs, maybe bug on your screen.
