### ISSUE TITLE
[1.20.2] discord srv not showing avatar and being slow

### ISSUE THREAD

**Issue by larrygaming019** [DiscordSRV/DiscordSRV#1623]
### Expected behavior

what i expect is avatar of the player is showing, and that msg's from discord to be accurate.

### Actual behavior

avatar not showing, and minecraft to discord being super slow.

### Steps to reproduce

![image_2024-01-06_215954917](https://github.com/DiscordSRV/DiscordSRV/assets/140148151/91a72955-672a-47a5-95b9-810fbaed9d66)

### Server software and version

(MC 1.20.2)

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.
- [ ] I didn't actually check any of these things

**Comment by Dinty1** [comment]
You need to use a different avatar provider.
The AvatarUrl is at line 88 in your config.yml, just set it to:
```yaml
AvatarUrl: https://heads.discordsrv.com/head.png?texture={texture}&uuid={uuid}&name={username}&overlay
```

Relevant issue on crafatar’s page is here: https://github.com/crafatar/crafatar/issues/322#issuecomment-1879469042
We’ll probably have a permanent solution soonish

**Comment by larrygaming019** [comment]
> ```yaml
> AvatarUrl: https://heads.discordsrv.com/head.png?texture={texture}&uuid={uuid}&name={username}&overlay
> ```

**Comment by larrygaming019** [comment]
thx it works

**Comment by velnias75** [comment]
Just another solution if your machine has an *Apache webserver* running as well:
```
RewriteEngine on
RewriteRule   "avatars/(.+)"  "http://crafatar.com/avatars/$1"  [P,L,E=CravatarUA:true]
<If "%{ENV:CravatarUA} == 'true'">
    RequestHeader set User-Agent "My creative new UserAgent" env=CravatarUA
</If>
```

… and point your `AvatarUrl` to your *Apache webserver*
