### ISSUE TITLE
command /unlink bug

### ISSUE THREAD

**Issue by Australiec** [DiscordSRV/DiscordSRV#1630]
### Expected behavior

The account is unlinked and the player is kicked off the server, because the account link is required.

### Actual behavior

the account is successfully unlink, but the player does not kick from the server and writes an error to the console

### Steps to reproduce

you need to link your account to the discord and use /unlink

there is no such problem in version 1.26.2. But in the latest version and in the snapshot it is there

https://bin.scarsz.me/c3ba699f-1817-4765-b6e8-f18e655dc7af#u6VugFqcgMwtFW56qIM4ux2365Gu3z6r

### Server software and version

Pufferfish version git-Pufferfish-27 (MC: 1.20.1)

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.
- [ ] I didn't actually check any of these things

**Comment by Vankka** [comment]
Fixed in https://github.com/DiscordSRV/DiscordSRV/commit/2e3776714e9d8c9455186372a2644bcb853fa114
