### ISSUE TITLE
Synchronization improvements

### ISSUE THREAD

**Issue by chelminski** [DiscordSRV/DiscordSRV#1632]
### Why?

This will allow you to synchronize player ranks in two directions. Blocks synchronization of administrative ranks [Discord-->Minecraft].

### What and How?

Allow you to choose which ranks should be synchronized in one direction and which in two directions.

### Are there alternatives?

Nope :(

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by Vankka** [comment]
Duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/1126
