### ISSUE TITLE
[Feature Request] Add support for Paper's AsyncChat

### ISSUE THREAD

**Issue by NoltoxGit** [DiscordSRV/DiscordSRV#1633]
### Why?

Because it seems better for users of the latest versions of Paper and other forks

### What and How?

Hello,
Can you add the support for the Paper `AsyncChatEvent` and/or `AsyncChatDecorateEvent` in the configuration of your plugin please?
Because you're currently using an old listener: `org.bukkit.event.player.AsyncPlayerChatEvent`. 

Example for a new configuration:
```yml
# Use Paper's async Chat Event
use-async-chat: true/false
```

Thank you so much if you add this! :)

### Are there alternatives?

Any.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by Dinty1** [comment]
Already exists as UseModernPaperChatEvent
