### ISSUE TITLE
Usernames are removed from accounts.aof with clean save

### ISSUE THREAD

**Issue by J-295** [DiscordSRV/DiscordSRV#1637]
### Expected behavior

When the accounts.aof file is rewritten due to >= 10% of lines being modifications, the comments containing the Discord and Minecraft usernames should remain.

### Actual behavior

Only the identifiers are included in the new file contents, the comments are removed.

### Steps to reproduce

Start the server with an accounts.aof file where 10% or more of the lines are modifications to cause the file to be rewritten.

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.
- [ ] I didn't actually check any of these things

**Comment by Vankka** [comment]
I'm not sure we even should be writing usernames in the aof file. Usernames can be changed so that information will become invalid unless we also update it, which then defeats the purpose of it being a "append only" file

**Comment by Scarsz** [comment]
> I'm not sure we even should be writing usernames in the aof file. Usernames can be changed so that information will become invalid unless we also update it, which then defeats the purpose of it being a "append only" file

I added them in to make ctrl+F'ing to find entries easier but I agree they're not really worth the hassle of maintaining

**Comment by granny** [comment]
Comments in the .aof file have been removed for consistencies sake.
