### ISSUE TITLE
Linked channel not auto deleting bot messages if player deletes their own message

### ISSUE THREAD

**Issue by TomLewis** [DiscordSRV/DiscordSRV#1640]
### Expected behavior

For DiscordSRV to clean up all messages posted in the linking channel, even ones that show the message that someone deleted their original message, as the bot replies to it!

### Actual behavior

![image](https://github.com/DiscordSRV/DiscordSRV/assets/144046/54c68452-e761-4493-9f7f-4535be2894fe)
This message is left in the channel, so players have figured this out already and started spamming comments and deleting their messages to fill this discord channel up with these messages.

### Steps to reproduce

1) Setup `Channels:` to have a `link` channel to `/discord link` send your codes to.
2) Set `MinecraftDiscordAccountLinkedMessageDeleteSeconds` in config.yml to delete messages to 20 seconds
3) Get someone to write a spam message, then delete their own message before the auto delete happens.
4) Discord SRV does not clean up the message left by the bot that the original message was deleted

Within 10 seconds of me posting a changelog I enabled this feature a random player did this as the first message to test the channel.

### Server software and version

PurPur 1.18.2

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.
- [ ] I didn't actually check any of these things

**Comment by granny** [comment]
Unable to reproduce on the latest snapshot build. If you're still struggling with this issue please create a ticket in our discord.
