### ISSUE TITLE
Regex for the obsuring of console info

### ISSUE THREAD

**Issue by AutonomousCat** [DiscordSRV/DiscordSRV#1642]
### Why?

I currently have the Discord minecraft console channel viewable by admins only because I don't want to expose people's IPs to moderators who might not be a good fit in the end. It would be a nice solution to be able to filter IP addresses using regex (since there are multiple areas where someone's IP might be shown, for example in player-joins, as well as plugin output (ie whois). 

### What and How?

It should behave the same, unless regex the regex setting is enabled. 

Maybe it can work something like:
```yml
{
  "regex_here1": "replaced_by1",
  "regex_here2": "replaced_by2",
}
```

### Are there alternatives?

Unsure

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by J-295** [comment]
Regex works fine for IP addresses, ask in our Discord server if you need help setting up filters: https://discordsrv.com/discord
