### ISSUE TITLE
DiscordSRV having a lot of CPU usage

### ISSUE THREAD

**Issue by KhrysAK47** [DiscordSRV/DiscordSRV#1649]
### Expected behavior

It should not consume this much CPU.

### Actual behavior

It consumes a lot of CPU.

### Steps to reproduce

Not sure honestly

https://spark.lucko.me/GxLsObwfGo

### Server software and version

Paper 1.20.4

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.
- [ ] I didn't actually check any of these things

**Comment by Scarsz** [comment]
What part of this makes you think DiscordSRV is leading to high CPU usage? DiscordSRV does little processing to begin with & most all of it is async.
