### ISSUE TITLE
Discord Command Then In game command

### ISSUE THREAD

**Issue by GiantessElsie** [DiscordSRV/DiscordSRV#1655]
### Why?

To make it easier to use the in-game commands on discord without entering minecraft or to your server's dashboard to whitelist, ban or link 

### What and How?

Able to use for example /link or /discordsrv link {username} on discord aswell rather on minecraft only

### Are there alternatives?

Nope

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by Dinty1** [comment]
The `!c` prefix can be used to run Minecraft commands, and can be configured with the `DiscordChatChannelConsoleCommand...` options in config.yml, or you can set a dedicated console channel by setting DiscordConsoleChannelId

In the future there will be options for a global account linking system that negates the need for running /discord link but this will probably still require activity from the minecraft end anyway
