### ISSUE TITLE
Paper Auto Updating

### ISSUE THREAD

**Issue by ReclinesMC** [DiscordSRV/DiscordSRV#1657]
### Why?

This would add the ability for people to update their plugins by simply running a command, such as /discordsrv update, making it a lot easier to update.

### What and How?

Simply, when the command is run, download the plugin to the ../plugins/update folder. After the next server restart, paper will automatically replace the old jar with the new jar, and the server would then be on the latest version 

(More info here: https://docs.papermc.io/paper/updating) 

### Are there alternatives?

Someone could just update by manually uploading the jar and deleting the old one.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by Dinty1** [comment]
This is quite far outside the scope of DiscordSRV. Another plugin could implement this and the command could be made accessible from Discord using the console channel/chat channel console commands

**Comment by SkyKingPX** [comment]
@ReclinesMC I use this plugin:
https://github.com/NewAmazingPVP/AutoUpdatePlugins
