### ISSUE TITLE
Assign role to user in Discord upon joining Minecraft

### ISSUE THREAD

**Issue by thetayloredman** [DiscordSRV/DiscordSRV#1661]
### Why?

I'd like to be able to create a `WMC Members` role which syncs all players who have ever joined in Discord. While it could be possible to do a two-way role sync with the default role, **we do not want two way role sync** besides this role.

### What and How?

Configuration option `playersRole`

### Are there alternatives?

Toggling two-way sync for specific roles?

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by Dinty1** [comment]
This can be achieved with the MinecraftDiscordAccountLinkedRoleNameToAddUserTo option in config.yml

**Comment by thetayloredman** [comment]
Ah, thank you!
