### ISSUE TITLE
DiscordSRV issues roles to peoples as soon as they log into the discord server

### ISSUE THREAD

**Issue by McRa1nY** [DiscordSRV/DiscordSRV#1664]
### Expected behavior

I want the plugin not to give people role for simply joining a discord server.

### Actual behavior

When a person logs into the discord server, the discord bot DiscordSRV gives him a role, which should only be obtained by linking accounts.

### Steps to reproduce

1. A person joins a discord server
2. A person is likely to receive a role, which should only be obtained by linking Minecraft accounts to Discord.

### Server software and version

git-Paper-196 (MC: 1.20.1)

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.
- [ ] I didn't actually check any of these things

**Comment by James-Bennett-295** [comment]
You claim to have asked in the Discord server, what is your Discord ID?

**Comment by McRa1nY** [comment]
> You claim to have asked in the Discord server, what is your Discord ID?

What? Why do people need my Discord ID?

**Comment by underscore11code** [comment]
To look up your ticket transcript of the issue.

**Comment by McRa1nY** [comment]
> To look up your ticket transcript of the issue.

No, I didn’t. I found out about this plugin’s discord when I published this post. But I had to check the box to publish the post. Unfortunately, I didn’t even turn to discord after that, my fault.

**Comment by Dinty1** [comment]
There’s a reason we have that checkbox. Please open a ticket so we can work through potential solutions before opening a bug report.

**Comment by McRa1nY** [comment]
> There’s a reason we have that checkbox. Please open a ticket so we can work through potential solutions before opening a bug report.

Here you tell me to ask for help on discord. Okay, I went to discord. but I can’t even make a ticket there, you can’t write in the channel. I need urgent help with this. Why can't you just help me here?

**Comment by Dinty1** [comment]
Because help is going to be too long-winded to do on a GitHub thread. There’s a discord outage going on at the moment so tickets can’t be created. Either make a thread in #general or wait a bit

**Comment by Dinty1** [comment]
Actually disregard the last part you’ve just opened one so it probably does work

**Comment by McRa1nY** [comment]
> Actually disregard the last part you’ve just opened one so it probably does work

I didn't get any help from discord. Can anyone give me proper help?
