### ISSUE TITLE
the application did not respond

### ISSUE THREAD

**Issue by earlhsjks** [DiscordSRV/DiscordSRV#1679]
### Expected behavior

bot should respond the list of online 

### Actual behavior

the application did not respond.

### Steps to reproduce

discord command:
/list 

### Server software and version

Paper version git-Paper-496 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 7ac24a1 on ver/1.20.4)

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.
- [ ] I didn't actually check any of these things

**Comment by Scarsz** [comment]
DiscordSRV does not have any built-in slash commands.
