### ISSUE TITLE
Join voice

### ISSUE THREAD

**Issue by dre232132** [DiscordSRV/DiscordSRV#1692]
### Expected behavior

I expect the bot to create voice channels when moving in and out of distance and players can speak freely in these channels

### Actual behavior

Everytime a chnnel is create you have to go into discord and press join voice in order to speak or hear anyone

### Steps to reproduce

create a catagorgy and a lobby voice channel

### Server software and version

paper minecraft 1.20.4

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.
- [ ] I didn't actually check any of these things

### Anything else

also its not letting me join the discord server it says something wrong with invite

**Comment by dre232132** [comment]
hi its not letting me join the discord server 
![image](https://github.com/DiscordSRV/DiscordSRV/assets/77330562/1bc4a295-79d8-4ad6-9ece-e4313775672b)

**Comment by Dinty1** [comment]
What’s your discord id? You / another account on your ip might be banned

**Comment by dre232132** [comment]
afroninjasan not too sure why i would be banned I have not been on that discord for years never had an issue with discordsrv until now

**Comment by Dinty1** [comment]
Do you’ve never been on there? What’s the user id? (With the numbers)

**Comment by dre232132** [comment]
no i have been on there to help with initially setup maybe 2/3/4 years ago but I was not aware of any ban user id 696604543345229834

**Comment by dre232132** [comment]
afroninjasan#2814

**Comment by Dinty1** [comment]
You were banned for advertising your server twice. I’ll go ahead and unban you but don’t do it again

**Comment by dre232132** [comment]
Oh no apologies i dont advertise
