### ISSUE TITLE
Download service gives 502 Bad Gateway

### ISSUE THREAD

**Issue by SkyKingPX** [DiscordSRV/DiscordSRV#1700]
### Expected behavior

The latest version of the plugin should start downloading

### Actual behavior

![image](https://github.com/DiscordSRV/DiscordSRV/assets/95442431/1779123c-a4c5-4a99-a926-194bfaf9d1eb)
![image](https://github.com/DiscordSRV/DiscordSRV/assets/95442431/3daa1d38-fd6d-4e16-966a-fdc11808fedf)

### Steps to reproduce

Visit https://get.discordsrv.com or https://download.discordsrv.com/v2/DiscordSRV/DiscordSRV/release/download/latest/jar

### Server software and version

-

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.
- [X] I didn't actually check any of these things

### Anything else

Well. The checks from above are unnecessary.

**Comment by SkyKingPX** [comment]
I am using a AutoUpdatePlugins plugin and there always has to be the link for the latest version. So „get.discordsrv.com“ was perfect, but now…

**Comment by Dinty1** [comment]
Our download service is experiencing an outage. The latest development build is available to download from <https://github.com/DiscordSRV/DiscordSRV/actions/runs/9623200234/artifacts/1627157696> (`DiscordSRV-1.28.0-SNAPSHOT-aa2c8d4.jar` inside the zip) in the mean time. Sorry for the inconvenience

**Comment by Vankka** [comment]
The download service is going to come back at some point

**Comment by granny** [comment]
If you're trying to grab the latest release, you can do so through modrinth: https://modrinth.com/plugin/discordsrv/version/1.27.0

Latest snapshot build can be retrieved from this link: https://nightly.link/DiscordSRV/DiscordSRV/workflows/snapshots/develop

**Comment by Dinty1** [comment]
Issue resolved
