### ISSUE TITLE
Sql error

### ISSUE THREAD

**Issue by KIRUYXAN** [DiscordSRV/DiscordSRV#1701]
### Expected behavior

launch without errors

### Actual behavior

this is the error on startup [23:08:23 ERROR]: [STDERR] [com.mysql.jdbc.Driver] Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.

### Steps to reproduce

start the server

### Server software and version

Paper 1.21

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.
- [ ] I didn't actually check any of these things

**Comment by KIRUYXAN** [comment]
The genius transferred me to #1678 where they transfer me to #1685, but it was impossible to go straight to #1685

**Comment by KIRUYXAN** [comment]
Even more brilliantly, they are duplicates of each

**Comment by J-295** [comment]
You failed to spot that #1685 is a closed duplicate that was mentioned by the user who created it. The issue you were directed to (#1678) is the single open issue for this problem. Consider paying more attention in future to avoid looking foolish.

**Comment by KIRUYXAN** [comment]
It's foolish that #1685 mentions #1678
