### ISSUE TITLE
2fa through Discord and for permission to give out a role in Discord, please!!

### ISSUE THREAD

**Issue by vancorl** [DiscordSRV/DiscordSRV#1709]
### Why?

Please add 2fa protection with a code or confirmation button to this plugin and a feature where for a certain right a player is given a certain role in discord

### What and How?

.

### Are there alternatives?

.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else

.

**Comment by Vankka** [comment]
Duplicate, https://github.com/DiscordSRV/DiscordSRV/issues/487

**Comment by vancorl** [comment]
> Дубликат, [№ 487](https://github.com/DiscordSRV/DiscordSRV/issues/487)

Did anyone write about synchronizing the minecraft rights with the roles???
