### ISSUE TITLE
for permission to give out a role in Discord

### ISSUE THREAD

**Issue by vancorl** [DiscordSRV/DiscordSRV#1710]
### Why?

 feature where for a certain right a player is given a certain role in discord

### What and How?

bruh

### Are there alternatives?

bruh

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else

bruh

**Comment by Dinty1** [comment]
This is possible using the discordsrv.sync.<group> permission where <group> is synchronised with a role in synchronization.yml. See https://docs.discordsrv.com/permissions

**Comment by vancorl** [comment]
> Это возможно с помощью разрешения discordsrv.sync., где синхронизируется с ролью в synchronization.yml. См. https://docs.discordsrv.com/permissions

I need to issue a role for a certain right, not issue a right so that it counts as a right that gives some group. I NEED TO GRANT A ROLE FOR A PLAYER'S EXISTING PERMISSION.

**Comment by Dinty1** [comment]
Why? Surely there is another way to get the same result…

Explain your use case and we might be able to offer an alternative solution

**Comment by vancorl** [comment]
> Почему? Наверняка есть другой способ получить тот же результат…
> 
> Объясните свой вариант использования, и мы, возможно, сможем предложить альтернативное решение.

I have privileges working by means of a custom command and granting rights to a player in that very command. For example, I have the privilege "Rare" and it has the right discord.rare, for the role in discord. I want the player with the discord.rare right to get the role "Rare" in Discord, I have privileges are not groups, but a set of rights.

**Comment by Dinty1** [comment]
If it’s a custom command can’t you also grant another node?

**Comment by vancorl** [comment]
> If it’s a custom command can’t you also grant another node?

It's going to be a little hard to give out the role to people who have already bought the privilege :(
