### ISSUE TITLE
Removing Luckperms Formatting for Webhook Embeds

### ISSUE THREAD

**Issue by Sentinaut** [DiscordSRV/DiscordSRV#1720]
### Why?

When you enable embeds for the achievements, welcome messages, etc. You will notice that, if you have a coloured prefix, it will return the formatting codes you have in luckperms. For example &1 or &r

It should act the same way that webhook messages work. 

### What and How?

It should not show the formatting at all, just the text.
 
![image_2024-07-07_162355959](https://github.com/DiscordSRV/DiscordSRV/assets/161860536/ad1ebce7-1f62-46b2-a7ae-1dc2ac9bba17)

![image](https://github.com/DiscordSRV/DiscordSRV/assets/161860536/ece5f217-95ef-463b-8080-79fef186e823)

### Are there alternatives?

The only alternative is to not have prefixes for the welcome messages, achievement messages, etc. by removing the luckperms placeholder. But I think you should be able to have everything the same.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by granny** [comment]
Fixed on the latest snapshot build. https://snapshot.discordsrv.com/
