### ISSUE TITLE
Synchronizing mutes

### ISSUE THREAD

**Issue by Hycyntria** [DiscordSRV/DiscordSRV#1747]
### Why?

We have a survival chat channel in the discord, allowing players to see the ingame chat and talk in it when linked. Though players use this to evade their mutes given ingame since they don't get muted in the discord. If they get muted in the discord as well I don't have to worry about mute evasions through the discord survival chat channel

### What and How?

The plugin would need to mute the player in the discord server when they get muted in-game, and remove the muted status when they are no longer muted in-game, and vise versa.

### Are there alternatives?

If it is not possible to have Discord mutes be synced to be dealt out in-game as well, only syncing in-game mutes to discord is fine as well as this solves the main problem I'm having.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by thewilloftheshadow** [comment]
If you're using a role to mute, then you can just sync with that role ID context to a chat permission.
If you're using native timeouts, you can follow #1656
