### ISSUE TITLE
Cannot use PAPI placeholders in leave messages

### ISSUE THREAD

**Issue by Ruasus** [DiscordSRV/DiscordSRV#1748]
### Expected behavior

![image](https://github.com/user-attachments/assets/41ce31a6-0f0e-4523-89db-5e5c88ee1413)

the latest embed sent my group as these embeds above did

### Actual behavior

![image](https://github.com/user-attachments/assets/41ce31a6-0f0e-4523-89db-5e5c88ee1413)

i have an image containing the embeds below, each embed is a case, respectively:
- i Joined my server
- i used /vanish to vanish myself
- i used /vanish to stop vanishing myself
- i left my server

the problem is the latest embed didnt send my group as these embeds above did

### Steps to reproduce

https://discord.com/channels/135634590575493120/1269706365505634355/1269916071666782268

*sorry for the inconvenience but i dont want to leak my server plugins. If you have permissions, you can check them in your discord server

### Server software and version

paper-1.21-109

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

### Ticket number or message link to where you asked in DiscordSRV's Discord server about this

18939

### Anything else

- im using SuperVanish and it works fine when i use /vanish
- when the player joins, it works fine, but this happens the opposite when they leave (whether they have OP or not)

**Comment by ANutley** [comment]
This is an issue with PAPI, as placeholders that require a player cannot be parsed when a player leaves the server, as technically this player no longer exists. You should remove the prefix from all leave messages to avoid being able to distinguish between real and fake leaves.
