### ISSUE TITLE
Unexpected An unknown error occurred building JDA situation

### ISSUE THREAD

**Issue by RICE0707** [DiscordSRV/DiscordSRV#1753]
### Expected behavior

Build successful

### Actual behavior

`An unknown error occurred building JDA` error was generated

### Steps to reproduce

This seems to be a sporadic event, but I don't know 100% how to reproduce it,
Because I only have the discordsrv plug-in enabled normally,
No other adjustments were made.

### Server software and version

git-Purpur-2095 (MC: 1.20.2)*

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

### Ticket number or message link to where you asked in DiscordSRV's Discord server about this

I did not find any questions about An unknown error occurred building JDA situation in the support community of discordsrv

### Anything else

DiscordSRV-Build-1.28.0.jar

**Comment by J-295** [comment]
"Ticket number or message link to where you asked in DiscordSRV's Discord server about this"
This is for where *you* asked, which you didn't.
