### ISSUE TITLE
Make chat to discord different group by group

### ISSUE THREAD

**Issue by KikyoC** [DiscordSRV/DiscordSRV#1757]
### Why?

Imagine that you have 1 rank. In config.yml -> Experiment_WebhookChatMessageFormat you can make something like %luckperms_prefix% %displayname% %message% but Imagine that a guy have 2 ranks and I want to show them. I will need a different format

### What and How?

A regular player can be formatted as 
[Prefix] Qwerty1234 --> Hello world
[Helper] [Prefix] Qwerty123 --> Hey

### Are there alternatives?

I don't find something on google

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else

I didn't say Hello

**Comment by Dinty1** [comment]
This is very unlikely to be something that we would implement given that it can already be achieved through features such as Luckperms’ prefix stacking and meta. 

The meta feature is explained [here](https://luckperms.net/wiki/Prefixes,-Suffixes-&-Meta). What you could do is set a meta value of "helper" to [Helper] to your helper rank then access this through %luckperms_meta_helper% (should be blank for other ranks).

[Prefix stacking](https://luckperms.net/wiki/Prefix-&-Suffix-Stacking) is equally valid (and easier) but might mess with your ingame setup
