### ISSUE TITLE
Circular Load Order - Server won't start

### ISSUE THREAD

**Issue by knepyt** [DiscordSRV/DiscordSRV#1762]
### Expected behavior

What's expected is the server to start.

### Actual behavior

Circular load error, not allowing the server to start. Oraxen is also causing this issue, I have reached out to the dev there.

https://mclo.gs/ZnUvAxI

### Steps to reproduce

Starting the server back up.

### Server software and version

PurPur latest, MC 1.21.1

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

### Ticket number or message link to where you asked in DiscordSRV's Discord server about this

19345

**Comment by thewilloftheshadow** [comment]
Asking ≠ make a ticket and not give us time to respond

**Comment by knepyt** [comment]
Sorry, I meant no disrespect. New to this stuff and a lot of devs keep telling me to ask on GitHub, I apologize.
