### ISSUE TITLE
Achievements are awarded to players several times

### ISSUE THREAD

**Issue by Mirik9724** [DiscordSRV/DiscordSRV#1764]
### Expected behavior

Achievements are awarded to players once

### Actual behavior

Achievements are awarded to players several times

### Steps to reproduce

Getting an achievement

### Server software and version

newest paper1.20.2

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

### Ticket number or message link to where you asked in DiscordSRV's Discord server about this

19363

**Comment by thewilloftheshadow** [comment]
Asking in the server ≠ make a ticket and not give us time to respond

**Comment by Mirik9724** [comment]
no this is  bag

**Comment by Mirik9724** [comment]
*bug
