### ISSUE TITLE
Send messages repeatedly

### ISSUE THREAD

**Issue by zwqwei** [DiscordSRV/DiscordSRV#1767]
### Expected behavior

[23:47:11 ERROR]: [DiscordSRV] [JDA] Encountered cloudflare rate limit! Retry-After: 0 s
![image](https://github.com/user-attachments/assets/a5a8b525-9ff8-4f64-b5af-cf037379ceb2)

### Actual behavior

[23:47:11 ERROR]: [DiscordSRV] [JDA] Encountered cloudflare rate limit! Retry-After: 0 s

### Steps to reproduce

[23:47:11 ERROR]: [DiscordSRV] [JDA] Encountered cloudflare rate limit! Retry-After: 0 s

### Server software and version

Paper version 1.21.1-69-master@925c3b9 (2024-09-07T20:43:21Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### Checks

- [X] I am __not__ using an outdated version of DiscordSRV.
- [X] I asked in [DiscordSRV's Discord server](https://discord.discordsrv.com) to see whether this issue is in fact a bug that needs to be fixed.

### Ticket number or message link to where you asked in DiscordSRV's Discord server about this

0

**Comment by Dinty1** [comment]
```Encountered cloudflare rate limit```
This means the IP address your server is on has made too many requests to Discord, meaning the plugin needs to wait before sending any more requests.
If there are other servers on the same IP as yours making requests to Discord, these will be contributing towards the same rate limit.
Try contacting your server host to see if you can switch to a different node.
