### ISSUE TITLE
Extra features

### ISSUE THREAD

**Issue by SkeloD** [DiscordSRV/DiscordSRV#1779]
### Why?

Because it sounds interesting and more accessible

This was not an original ideas I took inspiration from ( https://modrinth.com/plugin/discordsrvutils ) and ( https://modrinth.com/plugin/interactivechat-discordsrv-addon), no I'm not being paid to do this or I'm not the owner i just want this feature to be added to DiscordSRV

### What and How?

1. Punishment Sync and Messages
![image](https://github.com/user-attachments/assets/7a467c23-adb8-41bf-95f5-0f8459e7ea15) 

2. Leveling System 
![image](https://github.com/user-attachments/assets/76418f53-85ea-4790-a117-ded74177762d)

3. Suggestions System
![image](https://github.com/user-attachments/assets/dcb72454-a922-46b2-969b-1f1fa6874e29)

4. Invite Tracking System
![image](https://github.com/user-attachments/assets/b5a1ae01-50c8-4b11-922a-b5fab6b6490c)

5.  See peoples inv or ender chest in discord
![image](https://github.com/user-attachments/assets/385a0dc0-0db5-45a6-ba66-d78d9cb54810)

6. See what things are in there items like tooltips
![image](https://github.com/user-attachments/assets/77727361-4bff-46ae-9c7c-6bd8ead0d441)

7. Convert Attachments from Discord into Pretty Clickable and Hoverable Messages
![image](https://github.com/user-attachments/assets/30e09267-f249-4606-b4a9-26ab337ae3e3)

8. Be able to see your inv or enderchest thru discord!
![image](https://github.com/user-attachments/assets/b9de142a-7e70-4158-b970-e3f5319ec4f6)

9. Be able to put placeholder in discord ( ingame and in discord )
![image](https://github.com/user-attachments/assets/a1aa7668-7d01-4a53-a64c-10b44d839c75)

### Are there alternatives?

Add a embed command where it shows all your online servers its only for network servers, make it so we can make custom message or embed with command in discord ( not with a prefix of ! ,? or anything else i like it better if its like / with the new discord update  if not then its ok), have a system where it check for new uploads from a influencer ( Youtube, Twitch, Tiktok)

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else

Good Luck if you do decide to add these features :D

**Comment by J-295** [comment]
Instead of suggesting we add a list of features from an addon, why not just use the addon?

No. 1 can be achieved using alerts.yml
No. 4 is nothing to do with Minecraft, and 2 and 3 are potentially the same. This is a plugin for bridging messages and not a general purpose Discord bot. The same goes for your suggestion to have social media upload detection, very out of scope.

**Comment by SkeloD** [comment]
As for your question why don't i just download the addon is just that i like it when its all in one plugin, i did not really explore DiscordSRV so i did not even know alerts so im gonna check that out, sorry i miss out the purpose of this plugin is that it bridges mc messages to discord.
