### ISSUE TITLE
SQL backend for linked accounts

### ISSUE THREAD

**Issue by Scarsz** [DiscordSRV/DiscordSRV#189]

**Comment by Shigbeard** [comment]
Bit of a bump, but what's the progress on this? The most recent mention of this is #265 in which you closed the issue and referred back to here. Is this a backburner feature; something that won't be worked on until next stable release?

I really like DiscordSRV but this one missing feature is preventing me from implementing it into my server.

**Comment by elstur** [comment]
@Scarsz 
Just another bump. Suggested this over a year ago (the day before you created this ticket) and have been hoping it would see light. Are you in need of collaborators to help knock out some of these requests?

**Comment by Scarsz** [comment]
DiscordSRV development is on pause from me currently. v1 is not really being developed anymore with v2 on my todo list. Other projects have a higher priority for me currently.

**Comment by elstur** [comment]
To be sure I understand, you are working on a v2 of DiscordSRV, but even v2 is on hold as you are working on other things atm?

**Comment by Scarsz** [comment]
Yes. I'm not working on v2 currently but it's on my todo list.

**Comment by Scarsz** [comment]
https://github.com/DiscordSRV/DiscordSRV/pull/479

**Comment by Scarsz** [comment]
@Shigbeard @elstur ![https://lol.scarsz.me/CSAmzc/Discord_d46Ro1jbia.png](https://lol.scarsz.me/CSAmzc/Discord_d46Ro1jbia.png)

https://cdn.discordapp.com/attachments/282730821960597504/595684692582203412/DiscordSRV-Build-1.17.0-JDBC-SNAPSHOT.jar

**Comment by TheRed2399** [comment]
a
