### ISSUE TITLE
Some values not being copied over to new config

### ISSUE THREAD

**Issue by bladen** [DiscordSRV/DiscordSRV#212]
When the plugin rewrites the updated config all the changed values except for the DiscordChatChannelColorTranslations are copied over. Can this be included please?

**Comment by Scarsz** [comment]
Config migration doesn't effect multi-line values

**Comment by lazaroblanc** [comment]
This issue is 3 1/2 years old. Any fix in the near future to not have to redo the configs every update?

**Comment by Scarsz** [comment]
As is linked, there is a pull request open to resolve this. https://github.com/DiscordSRV/DiscordSRV/pull/972

**Comment by Scarsz** [comment]
Implemented
