### ISSUE TITLE
Option to use display name for name sync instead of username

### ISSUE THREAD

**Issue by KarlOfDuty** [DiscordSRV/DiscordSRV#227]
It would be nice if the nickname syncing worked for essentials nicknames rather than just syncing the username to discord. 

We give our donators access to the /nick command and would like that to carry over into discord so they are locked into using the same nickname in discord as on the server so you know who they are still.

**Comment by james090500** [comment]
This would be a great feature. Hoping to bump this again

**Comment by Vankka** [comment]
Added, will be in a future version. Dev build: https://cdn.discordapp.com/attachments/509491993035014154/650075109708791830/DiscordSRV-Build-1.18.3-SNAPSHOT.jar
