### ISSUE TITLE
DeluxeChat support

### ISSUE THREAD

**Issue by Ironic8b498** [DiscordSRV/DiscordSRV#233]
I would like a hook into Deluxechat or change how the chat is set to the server so most chat plugins and filters will work proper. I use pwnfilter and it uses AsyncPlayerChatEvent to filter the chat,like 99% of all the filters out there.

**Comment by artfcl-intlgnce** [comment]
+ 1 -- NarcoWars also uses DeluxeChat. DiscordSRV shows entry, exit, deaths, etc -- but does not show game chat.

**Comment by Vankka** [comment]
It appears that DeluxeChat works fine with DiscordSRV, now
