### ISSUE TITLE
Advancement internal IDs are echoed to chat, not their names.

### ISSUE THREAD

**Issue by GiovanH** [DiscordSRV/DiscordSRV#244]
Minecraft advancements have internal IDs used to build the advancement tree. Those internal IDs are the filename of the json advancement, and also referenced in the parent field:
`
    "parent": "minecraft:root",`

Instead of using display.title, which determines localized strings, DiscordSrv is grabbing the filename only.

**Comment by GiovanH** [comment]
DiscordSRV should parse the file then, and localize strings as needed to the language configured in DiscordSRV. That's assuming there aren't any hooks for advancements, [which there are.](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/UnsafeValues.html#loadAdvancement-org.bukkit.NamespacedKey-java.lang.String-)

**Comment by GiovanH** [comment]
This may have to wait until bukkit updates its API with better advancement support.

**Comment by Scarsz** [comment]
This has been implemented for a while
