### ISSUE TITLE
Report channel

### ISSUE THREAD

**Issue by renzotom** [DiscordSRV/DiscordSRV#257]
Can you add report channel, something as that plugin has https://www.spigotmc.org/resources/discordmc-take-your-server-to-the-next-level.44575/updates ? When players use /report command, it will be printed to the Report channel with good looking styled message.

**Comment by Dinty1** [comment]
This is possible with the [alerts feature](https://docs.discordsrv.com/alerts/) though you will need to register the command somehow (maybe in commands.yml with no aliases)
