### ISSUE TITLE
Add target to /discord bcast

### ISSUE THREAD

**Issue by AlexMCool** [DiscordSRV/DiscordSRV#264]
It would be really useful to be able to specify what channel to broadcast to. This can be achieved by doing the following:
- A new parameter for the `/discord bcast` command to address the channel the message is sent to
   - Parameter should be in a user friendly way like channelName or category#channelName instead of channelID
   OR:
   - You could specify the channel in the config like so: `Channels: {"global": "000000000000000000", "channel1": "000000000000000001", "channel2": "000000000000000002"}` Which you can then use in `/discord bcast channel2 This is the second channel!`
Optional:
- a permission system per channel like discordsrv.bcast.<channelid> with * for all channels

**Comment by RobotoRaccoon** [comment]
This there any update on whether this is going to be added?
