### ISSUE TITLE
Request: DeathMessagesPrime support

### ISSUE THREAD

**Issue by SXRWahrheit** [DiscordSRV/DiscordSRV#274]
https://www.spigotmc.org/resources/deathmessagesprime.3789/

Currently, DiscordSRV does not parse messages properly from DeathMessagesPrime. It would be much more amusing if we could have our custom death messages also function on Discord.

Thanks for all your work!

**Comment by Chewsterchew** [comment]
Any update on this?

**Comment by TheWranger** [comment]
Any new news on this? Any chance we can see this in v2?

**Comment by Vankka** [comment]
This has not been worked on yet, it will be in v2

**Comment by Vankka** [comment]
Temporary fix: (i've sent a message to the dev for a possible *better* solution)
```
death-message-compat-mode: true
death-listener-priority: MONITOR
```

**Comment by Vankka** [comment]
Propper fix: https://www.spigotmc.org/resources/dmpmonitorcompat.67404/
