### ISSUE TITLE
DM Users from Game Command / Auto DM to Inactive Users

### ISSUE THREAD

**Issue by sgort87** [DiscordSRV/DiscordSRV#280]
I'd very much like to be able to DM all, all online, and specific linked users in cases of announcements and inactive user reminding. It would be convenient if the full inactive user function was added, but I can handle scripting that to work, as long as there is a command to interface DMing a specific user, all users, and all online users. Others have also expressed interest in this feature. Thanks! -Gort

**Comment by granny** [comment]
Won't be implemented by DiscordSRV. Another plugin is free to hook into DiscordSRV to accomplish this task, one that is more suited for managing player retention.
