### ISSUE TITLE
Automatic inspection with /discord debug

### ISSUE THREAD

**Issue by Scarsz** [DiscordSRV/DiscordSRV#287]
Automatically yell at people when `/discord debug` is ran before the link is given about issues

Warnings:
- `DebugLevel` == 0
- `Channels` pair key matching a Discord text channel name

Suggestions welcome

**Comment by Androkai** [comment]
Warnings:
- `Channels`.size > 1  &&  `hooks`.size == 0 (including hooks via api if possible to detect)
- (`DiscordChatChannelPrefix`.length != 0)
- `GroupRoleSynchronizationRoleIdsToSync` ids can not be found

**Comment by Scarsz** [comment]
if any `Channels` pair value references a TextChannel ID that is unknown

**Comment by VankkaGithub** [comment]
if there is no channel pair for active chat plugin's default channel eg. "global", "general"
