### ISSUE TITLE
Announce player bans

### ISSUE THREAD

**Issue by lukeeexd** [DiscordSRV/DiscordSRV#298]
Would it be possible to have DiscordSRV announce bans from ingame to a specific channel?

**Comment by BillyGalbreath** [comment]
The ban plugin would have to hook into DiscordSRV. Or a "middleman" plugin would have to listen for the bans and forward to DiscordSRV.

An example of a middleman appraoch would be my private chat plugin. It listens to Advanced bans plugin and forwards to DiscordSRV. https://bitbucket.org/BillyGalbreath/pl3xchat/src/2a877bfe423276219d13ff3a4083cb8763902cc5/src/main/java/net/pl3x/bukkit/chat/listeners/AdvancedBanListener.java?at=master&fileviewer=file-view-default

**Comment by lukeeexd** [comment]
Is my suggestion currently possible with your private plugin?

**Comment by RealEthanovich** [comment]
I would love to see this if anyone can make it.

**Comment by ANutley** [comment]
Closing this as it is now possible with alerts.
