### ISSUE TITLE
Sponge

### ISSUE THREAD

**Issue by tenten8401** [DiscordSRV/DiscordSRV#30]
We need sponge support! Preferably API 5

**Comment by Eufranio** [comment]
soon™

**Comment by Androkai** [comment]
Some possible helpful documentation for start implementing this feature:
- [Instructions for building with Maven](https://docs.spongepowered.org/master/en/plugin/project/maven.html):
```
<repositories>
    <repository>
        <id>sponge</id>
        <url>http://repo.spongepowered.org/maven</url>
    </repository>
</repositories>

<dependencies>
    <dependency>
        <groupId>org.spongepowered</groupId>
        <artifactId>spongeapi</artifactId>
        <version>5.0.0-SNAPSHOT</version>
        <scope>provided</scope>
    </dependency>
</dependencies>
```
- [The Main Plugin Class](https://docs.spongepowered.org/master/en/plugin/plugin-class.html)
- [Documentation about message channels](https://docs.spongepowered.org/master/en/plugin/text/messagechannels.html)
- [Documentation about commands](https://docs.spongepowered.org/master/en/plugin/commands/index.html)
- [VanishNoPacket for Sponge](https://forums.spongepowered.org/t/vanish-api-4-0-0/10581) - very limited functionality
- No official Essentials/SuperVanish/all known chatplugins clone/support for Sponge available

**Comment by Scarsz** [comment]
Closing this cause it's not going to happen for a while

**Comment by Eufranio** [comment]
Forge has quite a lot of limitations, I don't think DSRV would be useful (there are other mods like DiscordIntegration that works well). Sponge would be better since it has chat channels to support, rank synchronization, etc.

**Comment by fcpwiz** [comment]
@Scarsz Do you plan on doing this any time soon? I, and many others, would love to see this plugin available for Sponge servers.

**Comment by Eufranio** [comment]
MagiBridge :smile:

**Comment by fcpwiz** [comment]
@Eufranio How similar is MagiBridge to DiscordSRV?

**Comment by Eufranio** [comment]
Enough

**Comment by fcpwiz** [comment]
@Eufranio And how does MagiBridge compare to https://github.com/axle2005/DiscordBridge?

**Comment by Eufranio** [comment]
It's not right talk about other plugins here, I suggest you taking a look at the release notes of them and see if it fits your needings...

**Comment by Vankka** [comment]
Sponge is basically dead at this point, we're going to focus our efforts on supporting Fabric (https://github.com/DiscordSRV/DiscordSRV/issues/908) and Forge instead (https://github.com/DiscordSRV/DiscordSRV/issues/1496)
