### ISSUE TITLE
Automatically updating server/channel name

### ISSUE THREAD

**Issue by Flavourized** [DiscordSRV/DiscordSRV#301]
Hey there. My suggestion would be to have the ability to update the name of the server with the online player count / max player count. Currently we can do this inside a channel. I asked in the srv server, and was replied that it couldnt be done currently. 

http://prntscr.com/i7ytrj
This feature would affect the option which the red arrow is pointing to. 

I would say let the server owner decide how the server name update would look with an option in the config that supports placeholders. 

Some examples: 
"ServerName" could turn into:
- "ServerName [%online%/%max%] -> "ServerName [25/100]"
- "ServerName - %online% online" -> ""ServerName - 25 online"
- etc.

**Comment by VankkaGithub** [comment]
Possible, but it would only be able to be updated every 5 or so minutes due to rate limiting

**Comment by Sephiths** [comment]
+1, would really like the ability to change a voice channel's name to display my mc-server's player count

**Comment by scottyboii** [comment]
Is there any update on this implementation - We use a bot for this atm, but it's super unreliable?

**Comment by Dinty1** [comment]
#1257. The bulk of the work on it is done, just need to iron out some small issues and do the config part of it.
