### ISSUE TITLE
Suggestion : Detecting words send from discord and replacing them ingame

### ISSUE THREAD

**Issue by DevilScarlet** [DiscordSRV/DiscordSRV#305]
Like detecting web adress sent, emojis... and replacing them with something of our choice

**Comment by Scarsz** [comment]
An example of this?

**Comment by DevilScarlet** [comment]
emojis sent from discord appears like this ingame :smile: so it would be grat to automatically replace it with a :-) 
but not limiting it to emojis but being able to add anything we want to replace in a file like replacing a discord invite link to censure it or name of another minecraft server...

**Comment by Scarsz** [comment]
This would require far too much manual work. There are far, far too many emojis. The character being conveyed with the name alone is good enough in my opinion.

**Comment by DevilScarlet** [comment]
I don't ask for something you prepare yourself, just the possibility for server owner to add blocked words and rewrite them by adding them to a config file (I would add emojis in my server but maybe someone else would add censure for keywords like discord invite, website link...)

**Comment by LoociM00** [comment]
@DevilScarlet We use VentureChat and it both Discord > MC chat & MC > Discord chat (we use it for swears, but could be used to the emoji's as well).

**Comment by Vankka** [comment]
DiscordSRV will probably never edit Minecraft chat messages, that's off to other plugins, DiscordSRV just relays messages to Discord.

Could try something like EmojiChat (supports DiscordSRV) though requires a resource pack, https://www.spigotmc.org/resources/emojichat.50955/ (for displaying emojis in-game)

https://github.com/DiscordSRV/DiscordSRV/issues/507 also seems relevant, in this case
