### ISSUE TITLE
Add a way to make custom discord commands

### ISSUE THREAD

**Issue by ReportCardsMC** [DiscordSRV/DiscordSRV#313]
This is a suggestion to add a way to make custom commands to certain roles or @everyone and it will use in game commands like (!stats <name>) would show the result of /stats UserName

**Comment by LagHD** [comment]
Maybe try Canned Commands? You can edit them in config and add more
Using this format
"!(command)":"(response)" to add more simply place a ## ,
And then use same format "!(command)":"(response)"

**Comment by Scarsz** [comment]
Merging with #384
