### ISSUE TITLE
Ability to disable mentions

### ISSUE THREAD

**Issue by LosTigeros** [DiscordSRV/DiscordSRV#318]
It would be nice to have option to completely disable mentions or allow only specific ones.

And mentions are a little broken. It should check entire name not only few chars to find the user
![image](https://user-images.githubusercontent.com/6253928/37214517-9d722efe-23b5-11e8-9536-0154217f86d1.png)

**Comment by Greeem** [comment]
what are the crossed out values

**Comment by Scarsz** [comment]
Configuring mention conversion is going to be a thing in DiscordSRV2. Mentioning people with a space in their name isn’t doable because DiscordSRV splits your message by spaces to find names to match.

**Comment by LosTigeros** [comment]
They have written:
- @Skywipf
- @Lostigeros
- @Kamitsu
without any spaces in these names and it mentioned other people.

**Comment by Scarsz** [comment]
Interesting. Thanks for the repoty.

**Comment by Scarsz** [comment]
https://github.com/DiscordSRV/DiscordSRV/commit/d57b1c38cc53b115a37034236fac4f8e8246cd18
