### ISSUE TITLE
Possibly add the option to format each channel separately

### ISSUE THREAD

**Issue by cliffness** [DiscordSRV/DiscordSRV#323]
In the plugin we define our channels to link, like so:
Channels: {"global": "404148539879587841", "admin": "420633838935343123"}

Then the formatting part works for all channels using this:
DiscordToMinecraftChatMessageFormat: " &r⦑%toprolecolor%%toprole%&r⦒ %username%: %message%"
DiscordToMinecraftChatMessageFormatNoRole: "[&bD&r][%username% » %message%"

Not sure if its possible to add more formatting like how you did with NoRole, but for more channels, like so:
DiscordToMinecraftChatMessageFormat**Global**: " &r⦑%toprolecolor%%toprole%&r⦒ %username%: %message%"
DiscordToMinecraftChatMessageFormat**Admin**: " &r⦑%toprolecolor%%toprole%&r⦒ %username%: %message%"
DiscordToMinecraftChatMessageFormatNoRole: "[&bD&r][%username% » %message%"

Hopefully I was clear enough for you. Sorry if not.

**Comment by Dinty1** [comment]
This was added by #1054
