### ISSUE TITLE
Non synced phrases

### ISSUE THREAD

**Issue by jamesxsc** [DiscordSRV/DiscordSRV#330]
A feature to have a section in the config file for phrases or words that are not sent from discord to minecraft or vice versa.

**Comment by Scarsz** [comment]
What's wrong with `DiscordChatChannelBlockedPhrases`?

**Comment by 615283** [comment]
Does it stop them from sending to mc?

**Comment by Scarsz** [comment]
That is the entire point of the option, yes.
