### ISSUE TITLE
Toprole Initial placeholder

### ISSUE THREAD

**Issue by 2beFlo** [DiscordSRV/DiscordSRV#333]
Hey there, 
thanks a lot for this awesome plugin. 
One thing I do miss is the ability to just show the first letter of the top role when a message is transmited to the minecraft chat. Right now our regular ingame chat shows messages by a user as <[U]Nickname>, messages from Discord are shown as <[User]Nickname>. It works, but it's not very pretty.

Therefore it would be grate if there was a placeholder like %toprole_initlial%, with would joust show the "U" and not the whole groupname.

I've allready tried to work with papi and javascript, but placeholders from vault or luckperms are only availabe if the player is online at the same time. A discordsrv papi module does not exists as far as I can tell (at least the placeholders listed on the Papi-Wiki do not work and in the Papi ecloud is no extention I could download to make them work).

If you clould implement this feature it would be awesome. And if I've missed anything in Papi feel free to tell me just als well. 

Thanks a lot!

Florian

**Comment by Scarsz** [comment]
@extendedclip is just lazy and hasn't released the DiscordSRV PAPI module yet, thought I don't even know if it would be useful in this case.

**Comment by 2beFlo** [comment]
Ah, okay. I don't know that either. What I though of was building a javascript-placeholder. Can't realy tell if that would work, but I'd recon chances would be at around 80%.

**Comment by 2beFlo** [comment]
Just wanted to push this and ask if there is a chance that there will be a placeholder that will only show the first letter of the users top role?

**Comment by Scarsz** [comment]
It's planned for the next major version but I'll throw this in as a bonus in 1.16.8 just for you
