### ISSUE TITLE
Better DiscordToMinecraft Formatting

### ISSUE THREAD

**Issue by TheWranger** [DiscordSRV/DiscordSRV#344]
We need some sort of way to show if a person from Discord is using a nickname (for DiscordToMinecraft chat).
Either
1. Have an alternate message format for when somebody has a nickname on Discord
or
2. Split %username% into %username% and %displayname%

Right now, somebody can nickname themselves as somebody else and use it for malicious purposes

**Comment by VTCAKAVSMoACE** [comment]
Why not just use the name of the MC player that was registered with Discord?

**Comment by VankkaGithub** [comment]
Using nicknames for malicious purposes? Just make a rule about impersonating and ban users who break it

**Comment by TheWranger** [comment]
@VankkaGithub I already have made a rule and I already do ban people but I would appreciate an automated system for something like this (I don't see why there shouldn't be one). It's like suggesting a server doesn't need an AntiCheat as long as they have a rule saying "Do not hack"
@VTCAKAVSMoACE Assuming you're referring to the `MinecraftDiscordAccountLinkedSetDiscordNicknameAsInGameName` option: I should still be able to give people the permission to change their nicknames without having to worry about something like this.

**Comment by Vankka** [comment]
This was added in 1.19.0
