### ISSUE TITLE
TranslateMentions conflicting with CutPhrases

### ISSUE THREAD

**Issue by Votyn** [DiscordSRV/DiscordSRV#346]
I have "[@]daniel" as a CutPhrases phrase, and "testercle" as another one. ([@] = @)
CutPhrases successfully cuts the normal word, but, as there is a person with the nickname "daniel" in the server, and we have TranslateMentions activated, the bot will mention "daniel" when someone says "[@]daniel" in the minecraft chat, even when that phrase is a part of CutPhrases. As shown in the debug snippet below, the plugin appears to think it deletes the phrase, but the bot still mentions the person.

This is not expected behaviour.

```bash
# The following is the type of console message that would pop up with debug 1 mode, sending either of the CutPhrases.
[Tue, 29. May 2018 10:16:32 EDT INFO] [DiscordSRV] [DEBUG] Chat message received, canceled: false
[Tue, 29. May 2018 10:16:32 EDT INFO] [DiscordSRV] [DEBUG] Tried looking up primary group for player Votyn but the Vault plugin hook wasn't enabled
[Tue, 29. May 2018 10:16:32 EDT INFO] <Votyn>

# This is a normal message.
[Tue, 29. May 2018 10:17:53 EDT INFO] [DiscordSRV] [DEBUG] Chat message received, canceled: false
[Tue, 29. May 2018 10:17:53 EDT INFO] [DiscordSRV] [DEBUG] Tried looking up primary group for player Votyn but the Vault plugin hook wasn't enabled
[Tue, 29. May 2018 10:17:53 EDT INFO] <Votyn> hello
```

**Comment by Scarsz** [comment]
Mind retesting this with 1.16.8
