### ISSUE TITLE
Make more messages translatable

### ISSUE THREAD

**Issue by Strvm** [DiscordSRV/DiscordSRV#349]
Could you make these messages configurable?: 

-"You Minecraft account is already assocaited with a Discord (...) account with /discord unlink
-/discord unlink (You Minecraft account is no longer associated with player.
-And maybe also the /discord ?

**Comment by VankkaGithub** [comment]
/discord is already configurable https://github.com/Scarsz/DiscordSRV/blob/master/src/main/resources/messages/en.yml#L183

**Comment by Strummm** [comment]
Sorry I meant /discord ?/help

**Comment by Scarsz** [comment]
`/discord help` is far too dynamic for there ever to be a customizable option for it

**Comment by Strummm** [comment]
And for others?

**Comment by train21** [comment]
Upvoting this, it should be added.

**Comment by Floef** [comment]
Upvoting

Also the other bot text:
"Are you sure that's your code? Link codes are 4 numbers long."
"I don't know of such a code, try again."

Thank you

**Comment by RobustSoul** [comment]
I also agree with that. Hopefully detailed message translation will be added soon.

**Comment by Vankka** [comment]
Available on development builds, https://snapshot.discordsrv.com
