### ISSUE TITLE
[FeatureRequest] Command to send <X> to discord channel

### ISSUE THREAD

**Issue by GrimPod** [DiscordSRV/DiscordSRV#360]
Would be nice if there was an ingame command that would send <X> to the discord channel
E.g. /discordsrv say <Insert what you want it to say here>

This way we could add things like when someone donates to run that command and put 
"<USERNAME> just donated the the server" or something like that, just a nice little touch

**Comment by Scarsz** [comment]
#264

**Comment by GrimPod** [comment]
Thank you guys, idk how i missed this
