### ISSUE TITLE
Getting update message in the latest build

### ISSUE THREAD

**Issue by axemwa** [DiscordSRV/DiscordSRV#361]
[22:10:59 WARN]: [DiscordSRV] This build of DiscordSRV is ahead of master but behind develop. Update your development build!

**Comment by VankkaGithub** [comment]
Use the latest release of DiscordSRV (https://github.com/DiscordSRV/DiscordSRV/releases/tag/v1.16.3) or update your dev. build https://ci.scarsz.me/job/DiscordSRV/

**Comment by axemwa** [comment]
I am using the latest build as I said in the title
DiscordSRV-Build-1.16.4-SNAPSHOT-223.jar 
Source: https://ci.scarsz.me/job/DiscordSRV/

**Comment by axemwa** [comment]
But I'm using 1.16.4 or is that different to the build you referred me to?

**Comment by VankkaGithub** [comment]
The build server probably didn't build the last few commits

**Comment by Scarsz** [comment]
Correct, the build server didn't run for some reason http://ci.scarsz.me/job/DiscordSRV/224/artifact/target/DiscordSRV-Build-1.16.4-SNAPSHOT-224.jar
