### ISSUE TITLE
Make Discord -> Minecraft messages appear in the correct channel instead of the global one

### ISSUE THREAD

**Issue by KarlOfDuty** [DiscordSRV/DiscordSRV#363]
So one could have several synced discord channels and only members with access to those channels could see the messages being sent through them. 

As it is now, any message coming from discord is sent to the global channel instead of the one the discord channel is linked to.

**Comment by Scarsz** [comment]
Closing because DiscordSRV already does this. Send a `/discord debug` report to https://scarsz.me/discord #support.
