### ISSUE TITLE
Skript integration

### ISSUE THREAD

**Issue by Scarsz** [DiscordSRV/DiscordSRV#37]
I know very little about Skript so if any other developer wants to help out for this one I'd appreciate it

**Comment by Androkai** [comment]
Collected some documentation about:
- [Skript on BukkitDev](https://dev.bukkit.org/bukkit-plugins/skript/)
- [original old version on GitHub](https://github.com/Njol/Skript)
- [Actual maintained version on GitHub](https://github.com/bensku/Skript)
- [(Popular addon for Skript)](http://skunity.com/SkQuery)
- [official documentation about what Skript is and what you can do with](http://njol.ch/projects/skript/doc/)
- [official documentation about API](http://njol.ch/projects/skript/API/)
```
<dependencies>
	<dependency>
		<groupId>ch.njol</groupId>
		<artifactId>skript</artifactId>
		<version>2.2-SNAPSHOT</version><!-- 2.2 is from 2014, maybe switching to maintained version by adding to own repo -->
		<scope>provided</scope>
	</dependency>
</dependencies>
<repositories>
	<repository>
		<id>njol-repo</id>
		<url>http://maven.njol.ch/repo/</url>
	</repository>
</repositories>
```
"Skipt integration" means adding functions for easy use within Skript so the question is what functions are needed? Skript is also totally new for me but here are some idea I get from reading through the documentation:
- Add `Discord` to [Command Sender](http://njol.ch/projects/skript/doc/classes/#commandsender)
- Add `On DiscordChat` to [Events](http://njol.ch/projects/skript/doc/events/#chat)
- Add `On DiscordJoin` to [Events](http://njol.ch/projects/skript/doc/events/#join)
- Add `On DiscordQuit` to [Events](http://njol.ch/projects/skript/doc/events/#quit)
- Add `On DiscordMention` to Events + `DiscordMentionType` to Expressions/Types
- Add `DiscordSender` to [Expressions](http://njol.ch/projects/skript/doc/expressions/#ExprCommandSender)
- Add `Is in DiscordGroup` to Conditions
- Add `Has DiscordPermission` to Conditions
- Add `Edit/Remove <Discord-message>` to Effects

**Comment by Scarsz** [comment]
Impossible to do because DiscordSRV doesn't utilize Bukkit's events system which for some **fucking** reason is a requirement. Lovely.

**Comment by thecenters** [comment]
Can this be revisited? DiscordSRV is using Bukkit's event system and has new hooks into functions/commands that don't work with Skript currently.

**Comment by Vankka** [comment]
> DiscordSRV is using Bukkit's event system

This is not the case, DiscordSRV is still using a custom event system

**Comment by thecenters** [comment]
Is there any way to do Skript integration with it based on events in their alerts.yml file? I've tried using a number of Skript events and it doesn't work. When I try to use the normal player command event from bukkit, it excludes Skript commands/results.
