### ISSUE TITLE
MC chat isn't sent to discord other than using /discord broadcast

### ISSUE THREAD

**Issue by riftens** [DiscordSRV/DiscordSRV#371]
debugs -
https://pastebin.com/fMaugkiX
https://pastebin.com/pz0kGRZC
https://pastebin.com/vu61d83c
https://pastebin.com/xb2d0WJ2
https://pastebin.com/N92fXuwN
https://pastebin.com/H0dsYqEQ
https://pastebin.com/EbmjQzUZ
https://pastebin.com/Qjd00Jbg

**Comment by Scarsz** [comment]
https://scarsz.me/discord #support
