### ISSUE TITLE
Option to make webhook only show the actual message

### ISSUE THREAD

**Issue by Miclebrick** [DiscordSRV/DiscordSRV#373]
Right now it redundantly shows the username.
Example:
![image](https://user-images.githubusercontent.com/6323125/43676995-f9dd637a-97c8-11e8-9b36-474678d7c045.png)

**Comment by VankkaGithub** [comment]
Are you using some chat plugin? from what I could tell, DiscordSRV just takes the message from the chat event, maybe your chat plugin is adding that to the message?

**Comment by Miclebrick** [comment]
Yeah I'm using a chat plugin, maybe it's adding to the message instead of the format or something

**Comment by VankkaGithub** [comment]
as far as i could tell, no format was applied to webhook chat messages

could you create a debug? using: /discord debug

**Comment by Miclebrick** [comment]
https://debug.scarsz.me/a28cb41e-9909-419a-983f-70d25becf41a

**Comment by Miclebrick** [comment]
The cause was my chat plugin, I fixed it. Thanks
