### ISSUE TITLE
Suggestion - use Discord usernames instead of guild nicknames

### ISSUE THREAD

**Issue by HeyBanditoz** [DiscordSRV/DiscordSRV#374]
There should be a config option to use Discord usernames instead of guild nicknames, in messages and pinging.

**Comment by Scarsz** [comment]
Why?

**Comment by HeyBanditoz** [comment]
Some people are far too memey with nicknames. Since I do not own the guild, I cannot disable it.

On August 10, 2018 2:14:32 PM MDT, Austin Shapiro <notifications@github.com> wrote:
>Why?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/DiscordSRV/DiscordSRV/issues/374#issuecomment-412193673

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Scarsz** [comment]
It would cause confusion though. The bot would be referring to people as they don’t actually appear in Discord. You have larger problems to deal with.

**Comment by Vankka** [comment]
This has been added. 1.19.0+ (Currently only development builds: https://snapshot.discordsrv.com)
