### ISSUE TITLE
Text formatting auto-convert to markdown.

### ISSUE THREAD

**Issue by burturt** [DiscordSRV/DiscordSRV#383]
Request by someone in support: Convert &l, &m, &n, &o, and &r to the proper markdown format for discord viewing. Mainly for /discord broadcast.

**Comment by Scarsz** [comment]
This is a lot harder than you'd think to implement.

**Comment by Vankka** [comment]
https://ci.scarsz.me/guestAuth/app/rest/builds/id:98/artifacts/content/DiscordSRV-Build-1.17.0-SNAPSHOT-116.jar / upcoming 1.17.0+
