### ISSUE TITLE
Works only one way

### ISSUE THREAD

**Issue by M4rtyn4** [DiscordSRV/DiscordSRV#386]
Hello.
I cant get Minecraft to Discord chat to work.
I use CMI maybe it has something to do with it?
CMI version 8.0.9.0
ConfigVersion: 1.16.4
Spigot 1.13.1R0.1-SNAPSHOT
I have no idea how to make it work. Please help.

**Comment by Scarsz** [comment]
`ClickHoverMessages: false` in CMI config
