### ISSUE TITLE
[Suggestion] Mute or lock channels during server restart

### ISSUE THREAD

**Issue by mercurialmusic** [DiscordSRV/DiscordSRV#388]
I'm sure this isn't going to be very high priority, but I've noticed that several players like to hop on Discord during server restarts and carry on the conversation or continue to ask asinine questions ("is the server restarting!?"). I've also noticed that when DiscordSRV has loaded but the server hasn't finished startup, these chats tend to pause or delay, or in rare cases of spam even hang the server (this probably only happened once). 

I wonder if it's possible to add a configurable delay/mute/channel lock during startup where DiscordSRV just ignores any incoming chats from Discord to let the rest of the machine catch up? Would make things go slightly smoother. Thanks!

**Comment by Scarsz** [comment]
Discord messages don’t create any lag when the server hasn’t finished initialization yet. They’re placed into Bukkit’s internal queue
