### ISSUE TITLE
1.13.1 server isn't connecting to Discord

### ISSUE THREAD

**Issue by Guddina-tim** [DiscordSRV/DiscordSRV#389]
I get an error in the console on server restart and the bot is not sending any messages to or from the chat channel in Discord. The bot was working perfectly until just the last couple of days. 

Using PaperSpigot 1.13.1 and DiscordSRV 1.16.4

https://pastebin.com/5M7rwEDD

`6.09 23:35:52 [Server] ERROR [JDA] There was an exception while executing a REST request
26.09 23:35:52 [Server] ERROR An unknown error occurred building JDA...
26.09 23:35:52 [Server] WARN github.scarsz.discordsrv.dependencies.jda.core.exceptions.ErrorResponseException: -1: java.net.SocketException
26.09 23:35:52 [Server] WARN at github.scarsz.discordsrv.dependencies.jda.core.exceptions.ErrorResponseException.create(ErrorResponseException.java:148)
26.09 23:35:52 [Server] WARN at github.scarsz.discordsrv.dependencies.jda.core.requests.Request.onFailure(Request.java:91)
26.09 23:35:52 [Server] WARN at github.scarsz.discordsrv.dependencies.jda.core.utils.SessionControllerAdapter$1.handleResponse(SessionControllerAdapter.java:89)
26.09 23:35:52 [Server] WARN at github.scarsz.discordsrv.dependencies.jda.core.requests.Request.handleResponse(Request.java:178)
26.09 23:35:52 [Server] WARN at github.scarsz.discordsrv.dependencies.jda.core.requests.Requester.execute(Requester.java:219)
26.09 23:35:52 [Server] WARN at github.scarsz.discordsrv.dependencies.jda.core.requests.Requester.execute(Requester.java:112)
26.09 23:35:52 [Server] WARN at github.scarsz.discordsrv.dependencies.jda.core.requests.Requester.execute(Requester.java:95)
26.09 23:35:52 [Server] WARN at github.scarsz.discordsrv.dependencies.jda.core.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:312)
26.09 23:35:52 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
26.09 23:35:52 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
26.09 23:35:52 [Server] WARN at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
26.09 23:35:52 [Server] WARN at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
26.09 23:35:52 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
26.09 23:35:52 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
26.09 23:35:52 [Server] WARN at github.scarsz.discordsrv.dependencies.jda.core.requests.RateLimiter$RateLimitThreadFactory.lambda$newThread$0(RateLimiter.java:129)
26.09 23:35:52 [Server] WARN at java.lang.Thread.run(Thread.java:748)`

**Comment by Scarsz** [comment]
Join https://scarsz.me/discord #support and mention this issue
