### ISSUE TITLE
console channel issues

### ISSUE THREAD

**Issue by Noob1917** [DiscordSRV/DiscordSRV#392]
![default](https://user-images.githubusercontent.com/39665944/46539287-46bfbb00-c8e0-11e8-8c4e-99f2d98fb4fb.png)
digital consoles marked in red appear by themselves in the channel discord how to remove them ?

**Comment by Scarsz** [comment]
Something in your server is doing dumb stuff with colors. Change these values in your config.

```
DiscordConsoleChannelRegexFilter: "\\[[0-9]+m"
DiscordConsoleChannelRegexReplacement: ""
```
