### ISSUE TITLE
I tried to start this up on 1.13.1 server. Won't start.

### ISSUE THREAD

**Issue by TIMEISINTHEFUTURE** [DiscordSRV/DiscordSRV#393]
I made sure I had everything updated, and it won't create the config file I need. Also I tried the 6.4 version and 6.5. Even tried on 5 different runs on separate bungeecord servers. If there is a fix, I would love to have it. Thanks. Also tried it on 1.12 and it didn't enable either. So I have no clue.
  Error message: [WARNING] Error enabling plugin DiscordSRV

![untitled](https://user-images.githubusercontent.com/16778505/46565316-98ae1400-c8d3-11e8-94c9-307d686f2dbf.png)

**Comment by Scarsz** [comment]
..........DiscordSRV isn’t a Bungee plugin.

**Comment by TIMEISINTHEFUTURE** [comment]
Ohh haha. Guess, I'll redo the code to bungee with the original code.
