### ISSUE TITLE
Extra space in token

### ISSUE THREAD

**Issue by burturt** [DiscordSRV/DiscordSRV#395]
For some reason, a space at the end of a bot token like "NDg3MDQ0NjkwOTk1MDUyNTQ1.DqFugA.pm8BaT1cPVvI9stRMu1dJi_PXL8 " (No that bot token is invalid) errors out like:
[DiscordSRV] [JDA] WebSocket connection was closed and cannot be recovered due to identification issues
CloseCode(4004 / The account token sent with your identify payload is incorrect.)
instead of the normal "Bot token is invalid".

Along with this, maybe add detection for invalid characters (not numbers, letters, or periods) and say like "That bot token has invalid characters (LIST THEM HERE). Are you sure that is a bot token?"

**Comment by Vankka** [comment]
Shouldn't be neccasery as the token should always be copied from the developer portal
