### ISSUE TITLE
VentureChat Hook: Include global Bungee chats from other servers

### ISSUE THREAD

**Issue by Brickery** [DiscordSRV/DiscordSRV#396]
Hi,

Currently am using DiscordSRV 1.16.4 with VentureChat 2.12.5 on Spigot 1.12.2 with BungeeCord.

I have VC set up such that there is a global channel with `bungee: true` so every server will receive chats on the global channel. However, on the DiscordSRV side, where I have set up the global channel to broadcast on a text channel on Discord on the Hub server side, it only sends global messages by players on the Hub server, and does not send global messages from players on the other servers. However, players present in the actual Hub server can still see global messages from other servers.

I am unsure whether this is an API limitation on VentureChat's part or it is not programmed on DiscordSRV, hence I am enquiring here.

**Comment by Vankka** [comment]
This has been added, latest VentureChat + DiscordSRV 1.19.0+ (currently only development builds: https://snapshot.discordsrv.com)

**Comment by Brickery** [comment]
Thanks for adding this feature, and also for replying to such an old issue.

**Comment by Vankka** [comment]
Was actually the VentureChat dev that changed the API + PR'd the change, and I just so happened to notice this ticket, so I thought I'd close it rather than keep gathering dust
