### ISSUE TITLE
Warnings during server startup

### ISSUE THREAD

**Issue by WELTEINZ** [DiscordSRV/DiscordSRV#403]
Hi,

as described in the title I have warnings in the console while starting the server.
Can you tell me what this is? 

My environment:

Paper 1.13.2 dev 417
Dynmap v3.0-beta-2
DiscordSRV 1.16.4
Fedora 29
8 GB RAM and 4 Cores for a guest of an Intel Xeon X5690 in a KVM environment.

Looks like java:

![2018-11-08 12_03_17- screen 0_ jerome srv105_ _mc](https://user-images.githubusercontent.com/44711940/48194848-6e29fd80-e34e-11e8-802e-5b912b3639d1.png)
![2018-11-08 12_03_31- screen 0_ jerome srv105_ _mc](https://user-images.githubusercontent.com/44711940/48194850-6ff3c100-e34e-11e8-9193-2ac4adb3e1f4.png)

**Comment by Vankka** [comment]
For support join Discord here: https://scarsz.me/discord
