### ISSUE TITLE
Notify when user joins Voice Channel

### ISSUE THREAD

**Issue by LividJava** [DiscordSRV/DiscordSRV#405]
essentially the bot monitors the activity of a voice channel (Specified in the config) of when a user joins or leaves said channel.

Also a command to list the active users in said voice channel?

Just a small feature i'd like to see implemented!

**Comment by Scarsz** [comment]
What would be the purpose of this though? Seems like it wouldn't have much of a use.

**Comment by Vankka** [comment]
DiscordSRV doesn't do anything with voice, it would just be weird if it just started sending notifications when voice channels are left/joined

**Comment by Vankka** [comment]
Out of scope for DiscordSRV
