### ISSUE TITLE
MobArena isolated chat

### ISSUE THREAD

**Issue by SaitDev** [DiscordSRV/DiscordSRV#408]
MobArena https://www.spigotmc.org/resources/mobarena.34110/

When player is inside arena which enable isolated chat, message should not be sent to discord.

I can make a pull request for this if its welcome

**Comment by Vankka** [comment]
this should be done on mobchat's side by cancelling the message, `event.setCancelled(true);` for chat messages (when in a isolated chat)

**Comment by SaitDev** [comment]
@Vankka there are reason why we dont really wanna cancel the event. MobArena is not a chat plugin, while stuff was done by chat plugins like formatting, anti spam, anti words.... MobArena only changes recipients of message. If we cancel event, we will need to do same chat stuff as a chat plugin from a arena/minigame plugin

**Comment by Vankka** [comment]
Maybe you could hook into [this](https://github.com/DiscordSRV/DiscordSRV/blob/master/src/main/java/github/scarsz/discordsrv/api/events/GameChatMessagePreProcessEvent.java) event using `DiscordSRV.api.subscribe(new DiscordSRVEventListener())` [example event class](https://github.com/DiscordSRV/DiscordSRV-ApiTest/blob/master/src/main/java/github/scarsz/discordsrv/apitest/DiscordSRVListener.java) and cancel it if the message is from a player in a isolated chat

**Comment by SaitDev** [comment]
thank for pointing out the solution
