### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by Ghost-chu** [DiscordSRV/DiscordSRV#409]
All we know, Discord was blocked in China, but we still can use proxy to bypass firewall and use discord.
But unlucky, Discord cannot use HTTP/HTTPS/SOCKS5 proxy, could add support in DiscordSRV?

Thanks.

**Comment by Scarsz** [comment]
Sounds like a good idea. Currently DiscordSRV forcefully uses no proxy so it shouldn't be hard to modify.

**Comment by Scarsz** [comment]
I'd recommend looking at https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html to set proxy parameters for the JVM yourself. I tried implementing this directly into DiscordSRV and I can't get it to work so this is probably the next best thing.
