### ISSUE TITLE
Discord bot goes offline while the server is still running

### ISSUE THREAD

**Issue by marvinej** [DiscordSRV/DiscordSRV#410]
i'm not sure what the issue is here but this is the debug log i took while the bot was appearing offline.
https://debug.scarsz.me/e338290e-93b3-4c03-b694-d9b7a1ad2f3c

**Comment by marvinej** [comment]
Restarting the server does bring the bot back online.

**Comment by Vankka** [comment]
Join Discord for support, https://scarsz.me/discord

**Comment by Scarsz** [comment]
Would need a non-rotated log file to be able to really help with this. Part of the code is [here](https://github.com/DV8FromTheWorld/JDA/blob/master/src/main/java/net/dv8tion/jda/core/requests/ratelimit/BotRateLimiter.java#L384) which just indicates that an exception was thrown but your report doesn't show an exception

**Comment by marvinej** [comment]
I found this while searching my logs for that day
https://pastebin.com/jXwCS7Ng

I also noticed these web-socket disconnect issues. The server was still running and up but discordsrv lost its connection for some reason:
https://pastebin.com/bdgHuBXm

**Comment by GreemDev** [comment]
@marvinej https://paste.greemdev.net/ezobuhafujatifeyeqasezawigitih.sql

Says in the error.
