### ISSUE TITLE
role colors does not work

### ISSUE THREAD

**Issue by HeberonYT** [DiscordSRV/DiscordSRV#414]
Hello
The discord role colors are not sent to minecraft correctly, they were already assigned in the configuration file, but they are still ignored.
I discovered that this only happens when you use a custom color code, for example, the color green (# 04e000).
And if I use the colors suggested by Discord, if they are sent to minecraft.
![screenshot_4](https://user-images.githubusercontent.com/13698597/50190671-c65e0300-02ef-11e9-968c-b392bd0e66a9.png)

Minecraft 1.7.10
DiscordSRV-Build-1.16.5.jar

**Comment by Scarsz** [comment]
Because you need to define the colors in your config.
