### ISSUE TITLE
UltimateChat does not work with DiscordSRV

### ISSUE THREAD

**Issue by MisterSheeple** [DiscordSRV/DiscordSRV#424]
It just says CONSOLE in gold text in chat. I get this error in console when I type things in Discord:

[JDA] One of the EventListeners had an uncaught exception

I am using the latest build of UltimateChat from their Jenkins.

**Comment by Scarsz** [comment]
We need the rest of the error to even do anything with this

**Comment by Scarsz** [comment]
Well, as you can see, there's no info to go off of for this. Maybe try enabling DebugMode and try reproducing the issue but I can't do anything about this without stack traces. Literally all this tells me is that *something* went wrong- no information about *what* went wrong.
