### ISSUE TITLE
Force users to link Discord 

### ISSUE THREAD

**Issue by darg367** [DiscordSRV/DiscordSRV#427]
Is it possible to have an option that can be turned on and off that disables users who have not linked their account to Discord the ability to type in Minecraft chat? Maybe even make the chat fully invisible where they can't see other peoples messages unless they are linked to Discord, and any time they try to chat an error message like "Please use "/discord link" to attach your Minecraft account with our Discord before you can type in chat."

I know this is not for everyone, and I fully understand that. But managing the forum, Discord and Minecraft and then trying to ban them in all three places is really repetitive. If you could use the `BanSynchronizationDiscordToMinecraft: true` and `BanSynchronizationMinecraftToDiscord: true` then have them apply for a ban appeal on the forums. I think it would help minimize and help server administrators.

**Comment by Bysokar** [comment]
You want this config option: DiscordChatChannelRequireLinkedAccount: true

**Comment by Scarsz** [comment]
`DiscordChatChannelRequireLinkedAccount` controls whether people can send messages to the  Discord channel and have the messages sent to MC, not the other way around. It's planned to have better link enforcement options in v2.

**Comment by Bysokar** [comment]
My bad :)

**Comment by darg367** [comment]
@Scarsz Will the v2 have something like I mentioned above. If so thank you very much even if you are taking the idea or already planned it. Either way thanks for the plugin!

**Comment by burturt** [comment]
https://github.com/DiscordSRV/RequireLinked4Gameplay/releases/download/v1.0.0/RequireLinked4Gameplay.jar This is the current solution, chat is shown but when not verified the player can't move, chat, or run commands (depending on config).

**Comment by darg367** [comment]
Closing this. I got what I needed. Thank you!

**Comment by Steev93** [comment]
> https://github.com/DiscordSRV/RequireLinked4Gameplay/releases/download/v1.0.0/RequireLinked4Gameplay.jar This is the current solution, chat is shown but when not verified the player can't move, chat, or run commands (depending on config).

Doesn;'t work?

**Comment by pkrok01** [comment]
`RequireLinked4Gameplay` is integrated into DiscordSRV. Check `linking.yml`
