### ISSUE TITLE
Request: Automatically Sync MC Whitelist with Discord Role

### ISSUE THREAD

**Issue by equilateral** [DiscordSRV/DiscordSRV#433]
We have a Twitch sub-only Discord server, with a Minecraft server where we currently manually whitelist subs only. I was curious to see if it could be done in a way where subs, who get a role automatically on (Discord-synced) join, could then have access to the MC server (execute a whitelist add command), but then lose that access (execute a whitelist remove) if/when they lose access to the sub discord.

Thanks!

**Comment by burturt** [comment]
While syncing to whitelist isn't currently possible, https://github.com/DiscordSRV/RequireLinked4Gameplay/releases/download/v1.0.0/RequireLinked4Gameplay.jar is an extension where you can set it up so that you need a certain role and be linked to discord to move or do anything.

**Comment by Vankka** [comment]
role to whitelist would only be possible w/ a external link server or with the whitelist kick message containing the link code

**Comment by Scarsz** [comment]
Closing this, see the `plugins/DiscordSRV/linking.yml` file for requiring roles to play on the server
