### ISSUE TITLE
Request: Disable Emojis for Discord -> Minecraft

### ISSUE THREAD

**Issue by VeeExEight** [DiscordSRV/DiscordSRV#434]
Disable emotes in the Discord -> Minecraft feature.

**Comment by mibby** [comment]
Also would be nice to disable emojis in player discord nicknames being sent to minecraft. Usually just returns [][] in chat.

**Comment by Scarsz** [comment]
https://github.com/DiscordSRV/DiscordSRV/commit/fec6da4c18d128348bb014086ce3131f0d7c261a
