### ISSUE TITLE
Default value of PrintGuildsAndChannels & user privacy

### ISSUE THREAD

**Issue by redg3ar** [DiscordSRV/DiscordSRV#440]
I own a discord bot with many guilds, most of which I am not involved in. While it may be my bad for not checking the config file completely and not noticing the PrintGuildsAndChannels, some sensitive channel names appeared in my logs which I did not expect. If you think that this is an issue like I do, I believe there are a few different ways which this could be solved.

* Heuristic with "auto" setting
    *  detect if this is a personal bot with one guild or a large bot with many linked guilds, and dont print if many
    * or just check if the channel id in the config is valid, and if so dont print channel names list
* Just set the default value to false and add instructions on enabling it or copying channel ids with discord tools to guide
* Move the config value much higher in the file and hope more people notice it

**Comment by Vankka** [comment]
DiscordSRV should always run with a bot in 1 guild, it was never intended for public bots. The bot must be in those 'sensitive' channels (have the read messages permission), that's more worrying to me than it printing them out in your console.

**Comment by redg3ar** [comment]
Makes sense, I know my bots in sensitive channels but I take care to not expose myself to users data unless absolutely necessary. Anyways, thanks for the quick response.
