### ISSUE TITLE
Chatty support

### ISSUE THREAD

**Issue by ghost** [DiscordSRV/DiscordSRV#441]
Hi. I use Chatty https://www.spigotmc.org/resources/chatty-lightweight-universal-bukkit-chat-system-solution-1-5-2-1-13-2.59411/ for chat formatting. In this plugin i can configure different channels, for example, global-channel, trade-channel, donate-channel, including Local channel. But DiscordSRV redirects messages to Discord from every channels, including Local.

I want DiscordSRV to forward messages only from the global chat, but it seems impossible, because it seems that DiscordSRV does not support Chatty.
I tried to configure DiscordSRV in various ways, but nothing happened.

DiscordSRV version: 1.16.7
Chatty version: 2.15.1
Server core: PaperSpigot 1.13.2

P.S. Sorry for my bad English. :)

**Comment by Vankka** [comment]
https://github.com/Brikster/Chatty/issues/49

**Comment by Vankka** [comment]
I've added this in via the API available in [Chatty's dev builds](https://github.com/Brikster/Chatty/suites/1045542822/artifacts/13997635) in [DiscordSRV's dev builds](https://snapshot.discordsrv.com)

**Comment by OstriySous-dev** [comment]
How's it going?"

**Comment by Vankka** [comment]
The feature is in - but a couple users are reporting that Discord->Minecraft messages don't seem to be delivered to players for some reason. I'm waiting for extra details from them for now

**Comment by Cwae0926** [comment]
Is there a solution for this now? I have the same problem.
I checked the console and it shows this:
`17.06 07:00:31 [Server] JDA MainWS-ReadThread/INFO [Discord | 無薪工頭] cwae:thinking: » Test
17.06 07:00:31 [Server] JDA MainWS-ReadThread/INFO Chat: [Discord | 無薪工頭] cwae:thinking: > Test`

But I can't see the message in game for some reason.

**Comment by MinersStudios** [comment]
In fact, everything works great, it's just that the young admins themselves do not want to look at the documentation (like me), namely: "* range * - chat range. -1 to world-wide chat, -2 to server-wide, -3 to BungeeCord -wide chat. "
As a result, they have -1 in the Global chat settings and messages from the discord to the global chat are not sent. I solved this problem with the help of: "range: -2"

**Comment by Cwae0926** [comment]
Where can I find that configuration? I looked all .yml files but I did not see where the chat range is.

**Comment by Cwae0926** [comment]
I literally checked everywhere and still cannot find it. : (

**Comment by P0lskun** [comment]
/plugins/Chatty/config.yml :
![Screenshot_119](https://user-images.githubusercontent.com/74924188/122540735-96fbee80-d031-11eb-8ef6-69630491c09f.jpg)

**Comment by Cwae0926** [comment]
SOLVED. Thank you!!

**Comment by lynrayy** [comment]
NOT solved!

**Comment by lynrayy** [comment]
Discord SRV not see messages with !. Only !! retranslated to discord

**Comment by Dinty1** [comment]
Chatty 2.x is supported. Any [confirmed] problems with the integration should be reported in another issue
