### ISSUE TITLE
Link does not exist?

### ISSUE THREAD

**Issue by EsGibtKeineMitte** [DiscordSRV/DiscordSRV#444]
Hi!
Well I don't know, if this is an bug, but when I click the Link 
>  https://discordapp.com/developers/applications/me/create
shown in the description on the spigotmc page it just shows that and after thinking about it
1/2h I've not found a walk around so maybe you could help me.

![application](https://user-images.githubusercontent.com/45098796/56470659-20f79f00-6449-11e9-9a90-bacbeb7c2b4d.png)

MfG
EsGibtKeineMitte

**Comment by Vankka** [comment]
you're using an old guide, see up-to-date instructions here: https://github.com/DiscordSRV/DiscordSRV/wiki/Installation
