### ISSUE TITLE
Unlink Roles - Give role on unlink.

### ISSUE THREAD

**Issue by w1nst0nDEV** [DiscordSRV/DiscordSRV#446]
**Hello!** I have a default role on my discord server - For example, Dyno gives the role on join. If this role is removed from a member and they have no roles, the discord bugs out for that member. The member role is synced to members on my Minecraft server with the latest DiscordSRV build running. When they unlink their account, their member rank is taken away, which bugs them in the discord server and makes their experience on my discord server horrible. Hopefully, there are other server owners with this same issue. There are two very simple solutions to this issue, and they shouldn't be very hard to add:

- Just a simple configuration which gives a role to the discord account that unlinked would work! The role would be removed when the discord account is linked to another discord account again!
- The discord bot kicks discord accounts that recently unlinked. When they join back, they will be given the autojoin role. There would be a setting in the configuration to toggle this. This is the easier option of the two!

Thanks for reading my issue! :D

**Comment by LemmoTresto** [comment]
Why are you giving a role on join?
This is not smart and useless. It stops verification levels from working and discord already gives a role on join called ``@everyone``

**Comment by w1nst0nDEV** [comment]
> Why are you giving a role on join?
> This is not smart and useless. It stops verification levels from working and discord already gives a role on join called `@everyone`

Giving a role when someone joins isn't useless. Giving every member a specific role allows every member to have a specific color and a name in the member list, making your server more clean and comfortable.

I don't use a verification level in my discord server... I have a bot that restricts messages towards new members. I can't use the @everyone during permissions as I have a discord settings system that allows you to hide specific announce channels and categories. If I use the @ everyone permission to allow everyone to read the category, I can't assign a role to players to hide specific channels as @ everyone has permission to view the channel. I really wish there was an alternative, but because of my unique settings system on my server, there really isn't.

Because of this, I would love it if you could assign a role on unlink, or possibly kick discord accounts that unlink! Thanks! :D

**Comment by Scarsz** [comment]
> Just a simple configuration which gives a role to the discord account that unlinked would work! The role would be removed when the discord account is linked to another discord account again!

This would require making thousands of extra calls to the API to give everyone that role. Not very practical.

> The discord bot kicks discord accounts that recently unlinked. When they join back, they will be given the autojoin role. There would be a setting in the configuration to toggle this. This is the easier option of the two!

That sounds like an abysmal user experience, having to constantly rejoin.

**Comment by w1nst0nDEV** [comment]
> This would require making thousands of extra calls to the API to give everyone that role. Not very practical.

I apologize for this misunderstanding. I’m not a developer, so I wouldn’t know. I thought simply getting a role ID from a config, checking to make sure it’s valid, looking up the player’s last discord name, and assigning that role would be simple to add. I guess not.

> That sounds like an abysmal user experience, having to constantly rejoin.

It’s better than the experience my players are currently having when they unlink their accounts: The default role is removed from them, and their discord permissions bug out to have access to nothing.

Seeing as this feature won’t be added, I will be closing this issue.

**Comment by Scarsz** [comment]
I'd suggest just having another bot to give people the non-linked role when they don't have the linked one
