### ISSUE TITLE
The bot can ping everyone and roles on discord

### ISSUE THREAD

**Issue by Jonasslv** [DiscordSRV/DiscordSRV#447]
You can ping @everyone or @role by typing @every@everyoneone for example.
The bot will supress @everyone and will ping the chat.

**Comment by Scarsz** [comment]
Set `DiscordChatChannelTranslateMentions` to `false`

**Comment by mfnalex** [comment]
IMHO this should be disabled by default or at least be restricted to single users

**Comment by Vankka** [comment]
This has already been solved, and everyone/role mentions are already disabled by default. Refrain from posting on already closed issues from years ago.
