### ISSUE TITLE
Unable to catch first couple players joining

### ISSUE THREAD

**Issue by sammypanda** [DiscordSRV/DiscordSRV#450]
Since players are able to join before plugins have been loaded, it means that DiscordSRV is unable to mark them as joined since the login event happens before loading the plugin. 

_This means some players who leave the server haven't been marked as joining_

**Comment by Scarsz** [comment]
Can be "fixed" but the `%message%` placeholder wouldn't work for those player joins that happened before the plugin started.

**Comment by zeuzi** [comment]
there is a option in the spigot.yml file called: Late-bind: set this to true.
This will disable  players connecting before all plugins are loaded.

**Comment by Vankka** [comment]
DiscordSRV loads async, late bind might not work.

**Comment by sammypanda** [comment]
inactive
