### ISSUE TITLE
(1.16.7) server warn

### ISSUE THREAD

**Issue by Cronosus** [DiscordSRV/DiscordSRV#454]
hello
we have on kettle server this warn, after adding ftbutils
https://paste.ee/p/R1bfn

**Comment by Vankka** [comment]
what version of Minecraft?

**Comment by Cronosus** [comment]
1.12.2

**Comment by Scarsz** [comment]
Give the output of `/version`

**Comment by Cronosus** [comment]
ingame or in console `/version` command says its unknown command

**Comment by Scarsz** [comment]
...you're not using Bukkit then
