### ISSUE TITLE
Sync minecraft rank to discord rank

### ISSUE THREAD

**Issue by zackeek** [DiscordSRV/DiscordSRV#462]
So, i have tried for about a hour to figure out how to sync the minecraft rank to discord so that the rank u have in minecraft puts you in the same rank in discord, what am i doing wrong? 

GroupRoleSynchronizationRoleIdsToSync: ["575779817560211456", "577698574218035210", "000000000000000000"]
GroupRoleSynchronizationCycleTime: 1
GroupRoleSynchronizationRemoveRolesOnUnlink: true

**Comment by Vankka** [comment]
See https://cdn.discordapp.com/attachments/429908345567313932/429908783297331220/DiscordSRV_-_Diagnosing_Role_Synchronization_2.png 

Discord invite: https://scarsz.me/discord
