### ISSUE TITLE
Event listener exception

### ISSUE THREAD

**Issue by masonmanley** [DiscordSRV/DiscordSRV#464]
When sending a chat message in Discord in the DiscordSRV channel for it to be sent to the Minecraft server, I get the following error:

JDA MainWS-ReadThread/ERROR [DiscordSRV] [JDA] One of the EventListeners had an uncaught exception

Thanks,
Mason

**Comment by Vankka** [comment]
Get the latest dev build from here:
https://ci.scarsz.me/viewLog.html?buildId=116&buildTypeId=DiscordSRV_Build&tab=artifacts&guest=1

If you need further assistance, please join Discord here: https://scarsz.me/discord
