### ISSUE TITLE
[DiscordSRV] [JDA] There was an error in the WebSocket connection

### ISSUE THREAD

**Issue by Victor75007** [DiscordSRV/DiscordSRV#467]
Hello,

I get this error spam in the console.
`[DiscordSRV] [JDA] There was an error in the WebSocket connection`

It's new to me.
I use two plugins, what connected to discord, but is have two bots for these plugins.
The new plugins is zAuctionhouse.
This plugin use Discord support too, but this plugin connected other DC-bot. 
So, both plugins use a separate DC-bot.

When i installed the zAuctionHouse plugin on my servers, and I configured ir, then the DiscordSRV started this error message spam in console.

I use "old" DiscordSRV plugin
DiscordSRV version: DiscordSRV-Build-1.16.7.jar
Server version: This server is running Paper version git-Paper-566 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

I use BungeeCord.

I have 4 servers in the BungeeCord. All servers use the DiscordSRV plugin. 
But the error is have one server. On the 1.13.2 paper spigot. This is the single 1.13 server. 

https://i.imgur.com/dRYL9ci.jpg

Can you help me?

Thank you very much your help
Have a nice day

Best regards,
Victor

**Comment by Scarsz** [comment]
Use https://scarsz.me/discord #support for support with the plugin
