### ISSUE TITLE
Players cant logon after server startup.

### ISSUE THREAD

**Issue by comonier** [DiscordSRV/DiscordSRV#476]
**DiscordSRV 1.16.9 | Server version: 1.14.1-R0.1-SNAPSHOT git-Spigot-03bd4b0-17da342 (MC: 1.14.1)**

Log: https://paste.ofcode.org/36T4AZgjpXRyApNRYpkBQpb

Problem: Since I updated the last version of the plugin I have had this problem every time the server restarts.

It finishes starting and already shows that message in the discord:
The server is on fire.

Nobody can login and the console usually appears discord messages, so the server is online the plugins are working, but neither appears in the console the attempt of the player to connect, as if the connection of all were being blocked by a firewall.

Without the plugin the server starts normally and everyone connects without making an error.

The problem is intermittent, only 90% of attempts occur.

26.05 13:05:50 [Server] Server thread/INFO CONSOLE issued server command: /ess version
26.05 13:05:51 [Server] Server thread/INFO Server version: 1.14.1-R0.1-SNAPSHOT git-Spigot-03bd4b0-17da342 (MC: 1.14.1)
26.05 13:05:51 [Server] Server thread/INFO EssentialsX version: 2.16.1.180-mc114-b95
26.05 13:05:51 [Server] Server thread/INFO PermissionsEx version: 1.23.4
26.05 13:05:51 [Server] Server thread/INFO Vault version: 1.7.2-b107
26.05 13:05:51 [Server] Server thread/INFO EssentialsXChat version: 2.16.1.180-mc114-b95
26.05 13:05:51 [Server] Server thread/INFO EssentialsXGeoIP version: 2.16.1.180-mc114-b95
26.05 13:05:51 [Server] Server thread/INFO EssentialsXSpawn version: 2.16.1.180-mc114-b95
26.05 13:05:51 [Server] Server thread/INFO You are running unsupported plugins!

**Comment by Vankka** [comment]
Last thing on the `Server thread` is from Jobs, DiscordSRV loads async, thus doesn't effect player connections in any meaningful way
