### ISSUE TITLE
JDA stalls when setting status to invisible on shutdown

### ISSUE THREAD

**Issue by smellyonionman** [DiscordSRV/DiscordSRV#477]
Hi folks, I just updated to the newest DiscordSRV and was told in the changelog it fixes an issue I've never had before - and a few other things.  Now I'm having that issue!
In my console:

26.05 16:35:51 [Server] ERROR [DiscordSRV] [JDA] Interrupted while trying to add request to queue
26.05 16:35:51 [Server] INFO [DiscordSRV] Saved linked accounts in 4ms
26.05 16:35:51 [Server] INFO [DiscordSRV] Saved metrics in 1ms
26.05 16:35:51 [Server] INFO [DiscordSRV] Shutdown completed in 36994ms

I am running 1.16.9 on Paper build 623.

**Comment by Vankka** [comment]
The issue in the changelog is about the plugin never disabling, and a maximum treshold of 30 seconds was introduced. The underlying cause is JDA's fault

**Comment by Scarsz** [comment]
Join https://scarsz.me/discord #general, trying to get a thread dump for this issue for JDA devs
