### ISSUE TITLE
An option to disable channel topic updater

### ISSUE THREAD

**Issue by ledlamp** [DiscordSRV/DiscordSRV#480]
We don't want to use the channel topic updater and the bots don't have permission to do so, but as far as I can find there is no way to disable the feature, so these warnings constantly print to the console ![img](https://i.imgur.com/J4JZere.png)

Based on [this](https://github.com/DiscordSRV/DiscordSRV/issues/79#issuecomment-254021357) I tried setting `ChannelTopicUpdaterRateInMinutes` to nothing, commenting it out, or setting it to 0 but it still logs every 5 minutes. I can only set it to an extremely high value to prevent it filling the console, but there should just be an option to disable the feature.

**Comment by Scarsz** [comment]
Set the format to be blank string in messages.yml

**Comment by ledlamp** [comment]
Ok well, thanks for that, but I still think there should be an option to disable the feature in config.yml, as this is unintuitive because one would expect messages.yml to only hold strings and not enable/disable features, and there is no documentation covering this. And it's inconsistent as there is an option to disable the channel topic updater and shutdown in config.yml without blanking the string in messages.yml. At least setting the interval to 0 or blank should disable the feature.

**Comment by Scarsz** [comment]
While I see your concern, that’s how we’ve always done it. Whenever someone wants to disable a given message, they’re told to make the message blank. In that way, it’s consistent. Sure a config option wouldn’t be a terrible idea, but it would add another step for us to provide support when someone wants to disable a message (is the user asking about a message that has a dedicated option to toggle it’s behavior?)

**Comment by Agrrox** [comment]
I would like to see this feature.

**Comment by Sunsplace** [comment]
Hi, i have the same issue, but where do i put the message blank option, i cant find it. Thanks for helping

**Comment by James-Bennett-295** [comment]
> Hi, i have the same issue, but where do i put the message blank option, i cant find it. Thanks for helping

[These options](https://github.com/DiscordSRV/DiscordSRV/blob/master/src/main/resources/messages/en.yml#L366-L370) are what need to be set to `""`.
