### ISSUE TITLE
Feature Request: Automatically updating messages with useful information, similar to the topic updater

### ISSUE THREAD

**Issue by NoManaSendHelp** [DiscordSRV/DiscordSRV#481]
Allowing the option in the config to switch the Status that's shown in the channel's description to be placed inside a embedded message on a chat channel that auto-updates. Should show all stats provided in Channel description.

**Comment by Scarsz** [comment]
Closing because I don't see any purpose to do this as opposed to having a dynamic voice channel name as in #301

Configuring this would be less than trivial as well
