### ISSUE TITLE
Updating bot status with online player count

### ISSUE THREAD

**Issue by EnderShadow** [DiscordSRV/DiscordSRV#483]
This feature would allow the status of the bot to display the number of players online in the status of the bot. This is currently doable in a channel description, but this would remove the audit log spam that causes.

Example: "%online%/%max% players online" -> "25/100 players online"

One way this could be implemented is to allow placeholders in the bot status and whenever a placeholder in the status is changed the bot will update the status.

**Comment by underscore11code** [comment]
Closed by #579

**Comment by pewienanonimowy** [comment]
Placeholder "%max%" isn't working
