### ISSUE TITLE
Bot removes roles granted after account is successfully linked. 

### ISSUE THREAD

**Issue by devinjdawson** [DiscordSRV/DiscordSRV#486]
The role I assign for players once they link their account with discord disappears after a few minutes of gameplay. Is this normal? is there a way to keep the role?

**Comment by Scarsz** [comment]
You have role synchronization which is removing the role. You can't use it at the same time as the `LinkedRoleName`.

**Comment by devinjdawson** [comment]
I removed the role from role synchronization. Is there a way to resync the linked role name list?

also, how does role synchronization sync within MC? Is it just by name? I would liek to sync roles, but how would Minecraft know which role to sync if it is just a number? do I name the role the number in game?

**Comment by Scarsz** [comment]
> Is there a way to resync the linked role name list?
Players can re-link their accounts but otherwise no

> how does role synchronization sync within MC?
https://cdn.discordapp.com/attachments/429908345567313932/429908783297331220/DiscordSRV_-_Diagnosing_Role_Synchronization_2.png
