### ISSUE TITLE
Suggestion - 2FA Feature

### ISSUE THREAD

**Issue by Duoquote** [DiscordSRV/DiscordSRV#487]
I think it would be cool if we could join the server and then typed 4 char code to log in completely. I mean besides coolness, it would be a great security feature for non-premium servers.

**Comment by Leo-Alexa** [comment]
I've been using another plugin for a while that does exactly this functionality and uses DiscordSRV as a dependency so should be quite compatible. If it is something looking to implement directly into the main plugin, may be worth reaching out to that developer and discussing merging code? May save unnecessary duplication of work if they are willing to contribute.

Link to Spigot page:
https://www.spigotmc.org/resources/discord2fa-staff-accounts-are-now-safe-1-7-1-16-3.75451/

**Comment by shardeex** [comment]
This is really the opportunity that I would really like to see as soon as possible, because now I had to ask players link their accounts **twice**, this is very unfriendly.

bump

**Comment by Vankka** [comment]
I'm not sure if this is all that useful anymore since Minecraft accounts became linked to Microsoft accounts which offer software token, email and sms/phone call 2FA

**Comment by shardeex** [comment]
@Vankka I mean, it should be something like **_"oh, you are joining the server? so, please, tap on the message reaction in your DM's to play"_**. Also, it still will be very useful for cracked servers. I understand you may not to like them, but they exists.

**Comment by Scarsz** [comment]
Closing as this would be better implemented as it's own plugin that hooks into DiscordSRV
