### ISSUE TITLE
Feature request: Better support for emojis on minecraft chat

### ISSUE THREAD

**Issue by iGabyTM** [DiscordSRV/DiscordSRV#507]
Add an option to either stop the bot from displaying the emojis at all (having `:name:` in chat it's kinda annoying) or an option to replace certain parts of the role name with something else. For example, if you got a ⭐️ on the role name you can set the bot to replace it with a symbol that would render on the minecraft chat instead to type it as it is (`:star:`).

**Comment by Vankka** [comment]
Minecraft doesn't display many modern emojis, you could have a look at https://www.spigotmc.org/resources/emojichat.50955/

**Comment by iGabyTM** [comment]
That's not what I meant @Vankka, for example you can replace the ⭐️ with one of [these](https://fsymbols.com/signs/stars/) (if you add a manual way to do it) or remove the emoji from the role name before render it (if the plugin will handle this part). Example: `⭐️ Admin` will be displayed as `Admin` instead of `:star: Admin`.

**Comment by Vankka** [comment]
i'm fully aware that's not what you meant, it's just a alternative idea, that you could concider

**Comment by Vankka** [comment]
#549 could be a decent solution for this

**Comment by Andre601** [comment]
There could be a config section to enable/disable removal of all appearances of `:emoji_name:` in messages, roles, etc.
When enabled would the plugin check for any `:emoji_name:` (I would say using some regex like [this one here](https://regex101.com/r/GnpRXW/1) to check if it is `:emoji_name:`. Downside is that this one also triggers on custom emotes.)

**Comment by pkrok01** [comment]
like i said in #549,
> Improve upon ChannelRegex to have multiple pairs of regex.
> ["regex1":"replacement1","regex2":"replacement2"]
this would help close two issues with one solution

**Comment by Vankka** [comment]
`ParseEmojisToNames` (in releases) or https://github.com/DiscordSRV/DiscordSRV/issues/549 (in dev)
