### ISSUE TITLE
DiscordSRV Tries to Set Topic of Channel even with ChannelTopicUpdater Set to False

### ISSUE THREAD

**Issue by Rvby1** [DiscordSRV/DiscordSRV#511]
Hey! Running DiscordSRV 1.7.1 on a Paper-131 1.14.3 server. 

I have `ChannelTopicUpdaterChannelTopicsAtShutdownEnabled` set to `false` in the Config file. However, DiscordSRV still tries to update the channel info randomly and throws the warning
`[11:01:53 WARN]: [DiscordSRV] Could not set topic of channel TC:mc-server-chat(CENSORED) because the bot does not have the "Manage Channels" permission`. 

I don't think DiscordSRV should check if it has the `Manage Channels` permission unless it needs it. I think this would fix the bug.  

Here is a pastebin of my config in case it's something else causing the problem that I'm just missing: https://pastebin.com/PTUc4jvU

**Comment by Vankka** [comment]
`ChannelTopicUpdaterChannelTopicsAtShutdownEnabled` only disables setting the topic on **shutdown** as the config option implies, you can disable the topic updater completely by setting these messages.yml options:  `ChannelTopicUpdaterChatChannelTopicFormat` & `ChannelTopicUpdaterConsoleChannelTopicFormat` blank. (while keeping the shutdown option in the config `false`)
