### ISSUE TITLE
Webhook profile pictures not updating

### ISSUE THREAD

**Issue by TheyuGin** [DiscordSRV/DiscordSRV#513]
After a player changes his skin, webhook profile picture doesn't update, even after server restart. Options for webhooks I am using are:
`Experiment_WebhookChatMessageDelivery: true
Experiment_MCDiscordReserializer: true
WebhookAvatarsAre3d: true`

**Comment by Vankka** [comment]
The avatar api probably cached the avatar/skin, not DiscordSRV's fault

**Comment by TheyuGin** [comment]
So, there is no way of fixing it on my side? Just waiting for cache to become old enough for it to update, correct?

**Comment by Vankka** [comment]
Not sure what version you're on but the url is configurable in latest builds (available in Discord #builds, https://scarsz.me/discord ), but other apis will probably have similar levels of caching.

There's probably little you can do unfortunetly

**Comment by TheyuGin** [comment]
Alright, thanks for quick reply, will close it then.
