### ISSUE TITLE
Feature Request: Haven an option to use Webhooks in Discord

### ISSUE THREAD

**Issue by MadamFoxyCoxy** [DiscordSRV/DiscordSRV#514]
You can use a Webhook to send messages to Discord. The advantages of this is that you can set the icon and username on every message. So when a Minecraft user sends a message in the server, if they have linked their accounts, it will show their Discord username and avatar. Otherwise their Minecraft head and current nickname/username.

The disadvantages with Webhooks is that you cannot send messages as quickly as a bot can.

**Comment by Androkai** [comment]
Thx for your request. You can already test webhook delivery by enabling "[Experiment_WebhookChatMessageDelivery](https://github.com/DiscordSRV/DiscordSRV/blob/master/src/main/resources/config/en.yml#L29)" in config.yml. We actually always use the ingame (nick)name. Maybe we will also add an option to use the Discord (nick)name if linked.

**Comment by Vankka** [comment]
I'm sure there's already a issue about Discord names in MC -> DC, either everyone needs to be linked (*RequiredLinked4Gameplay*) or it will be confusing to users with Minecraft names mixed in

**Comment by MadamFoxyCoxy** [comment]
Welp I'm blind xD. Thanks for telling me about that.

It don't think it'll be confusing but I don't know. I think it'll be nice
