### ISSUE TITLE
Convert Discord markdown formatting to Minecraft § formatting

### ISSUE THREAD

**Issue by ledlamp** [DiscordSRV/DiscordSRV#516]
I noticed [this Forge mod for discord bridging](https://github.com/Chikachi/DiscordIntegration) converts formatted text from Discord to Minecraft's formatting. It would be nice to have the same functionality on our Bukkit servers.

I see [the opposite](383) is closed but that's far less useful as you can't send formatted chat without plugins. Hopefully Discord to Minecraft is easier to do, as this mod has already done it and it doesn't seem as sophisticated.

**Comment by Scarsz** [comment]
It's already both ways.

**Comment by Vistril** [comment]
Err, no. 
![image](https://user-images.githubusercontent.com/38549907/61938996-8c24a600-af4f-11e9-9c40-4a0eda2fd241.png)

**Comment by Vistril** [comment]
I'm not quite sure it works properly. 
![image](https://user-images.githubusercontent.com/38549907/61939107-c2622580-af4f-11e9-868c-1966c2d25319.png)

**Comment by Vistril** [comment]
Tested on another server that wouldn't have any conflicts with chat messages
![image](https://user-images.githubusercontent.com/38549907/61939587-d9554780-af50-11e9-9dc0-771e554f0880.png)

**Comment by Vankka** [comment]
enable `Experiment_MCDiscordReserializer` in the config.yml

**Comment by Vistril** [comment]
![image](https://user-images.githubusercontent.com/38549907/61943239-46201000-af58-11e9-901f-6f40163bd74a.png)
This worked. Thanks
