### ISSUE TITLE
Color Issue

### ISSUE THREAD

**Issue by RedBusters** [DiscordSRV/DiscordSRV#520]
I am unable to put chatcolor on minecraft, However when sending color &4 for exemple from Discord to Minecraft It works.

**Comment by Vankka** [comment]
Discord doesn't have colors

**Comment by RedBusters** [comment]
are you sure you correctly read ? I said that when i type a colorcode in discord, the color shows correctly in Minecraft, however if i try to type a color code directly in Minecraft, it doesn't work anymore since i installed DiscordSRV.

**Comment by Scarsz** [comment]
DiscordSRV doesn't modify vanilla chat behaviour

**Comment by RedBusters** [comment]
But when i remove the plugin, chat colors are working fine
