### ISSUE TITLE
1.12.2 Spigot/Paper hanging when internet returns.

### ISSUE THREAD

**Issue by Juesto** [DiscordSRV/DiscordSRV#523]
While #515 is annoying me too I am experiencing a worse issue.
For some reason the server appears to hang completely and no longer respond to console commands when the internet connection returns, sometimes the watchdog appears to work but the server is not responsive,
I am not sure at which version this started happening but fairly recent.
Running on Windows.

**Comment by Vankka** [comment]
@Juesto do you have a thread dump/ crash report?

**Comment by Juesto** [comment]
I'll reopen this when I get a dump.
