### ISSUE TITLE
DiscordChatChannelCutPhrases not working webhooks

### ISSUE THREAD

**Issue by moom0o** [DiscordSRV/DiscordSRV#528]
I have my config like this `DiscordChatChannelCutPhrases: ["@everyone", "@here"]`

Without webhooks, you can't ping everyone.
With webhooks enabled anyone can ping everyone.

**Comment by Vankka** [comment]
Webhook messages aren't fully polished, it's just a experiment after all

**Comment by GreemDev** [comment]
@MooMooYT, try setting `DiscordChatChannelTranslateMentions` to `false` in your config.

**Comment by Vankka** [comment]
Added in dev builds, download @ https://snapshot.discordsrv.com
