### ISSUE TITLE
bug or incorrect towny setup?

### ISSUE THREAD

**Issue by BeeRando** [DiscordSRV/DiscordSRV#530]
I have the plugin set up on my towny server. Everything works fine. The console channel works, it sends all the server messages like join/leave, start/stops, etc. Speaking from discord to the server sends the chat, but speaking in the server doesnt send messages to discord. I tried following what you said in this post here. https://github.com/DiscordSRV/DiscordSRV/issues/5

Here's the error.
https://pastebin.com/uusnCq92

Discord config
https://pastebin.com/r51dFvNv

Here's my towny channels.yml
https://pastebin.com/udSygqJy

**Comment by Scarsz** [comment]
Update your TownyChat version
