### ISSUE TITLE
Feature Request: Ability to Disable Channel Topic Updates

### ISSUE THREAD

**Issue by robargarthan** [DiscordSRV/DiscordSRV#533]
I'd love to have a toggle in the config to be able to turn off the channel topic update feature altogether. We like to put our server info for multiple games in there, and the bot keeps wiping that every time it updates.

**Comment by pkrok01** [comment]
https://github.com/DiscordSRV/DiscordSRV/wiki/FAQ#how-can-i-disable-a-featuremessage
