### ISSUE TITLE
DiscordSRV / McMMO Chat

### ISSUE THREAD

**Issue by ZEROOblivious** [DiscordSRV/DiscordSRV#542]
Greetings,

DiscordSRV is detecting /a (Admin Chat) in the McMMO Plugin. This has been reported to that DEV as well. 

DiscordSRV does not detect party-chat at all, but whenever /A is toggled on, it logs everything and players can see the admin chat.

Can this be patchable?

**Comment by Vankka** [comment]
Admin & Party chat *should* already be ignored

**Comment by burturt** [comment]
Cannot replicate on test, please verify both mcmmo and discordsrv is on latest version and that config is as default as possible for mcmmo, for discordsrv do /discord debug and send the debug link here (includes config with redacted portions)

**Comment by ZEROOblivious** [comment]
Ran a lot of tests and it seems that the /a toggled is not being logged into the discord chatroom. 

Going to close report.
