### ISSUE TITLE
Multiple Guild Integration

### ISSUE THREAD

**Issue by aprilfooldude** [DiscordSRV/DiscordSRV#544]
I manage a few servers for friends, and some other clients, and use a separate discord guild from their server's main guild to manage relations between owners. Is it possible to add a second bridge to another discord channel for console purposes?

**Comment by Scarsz** [comment]
...what? You can already make the console channel be in a different server than the chat channels, if that's what you're asking

**Comment by aprilfooldude** [comment]
I'm asking if I can have two separate console channels

**Comment by Vankka** [comment]
Not currently

**Comment by Scarsz** [comment]
Not doing that
