### ISSUE TITLE
When changing language in config, automatically run the config migration thing

### ISSUE THREAD

**Issue by burturt** [DiscordSRV/DiscordSRV#545]
Exactly what the title says: instead of having to delete the config/messages.yml when changing language, run the same thing that migrates config options upon version upgrade.

**Comment by gekkedev** [comment]
What is supposed to happen if the automatically (incorrectly) detected langauge is different than the language of the currently used `messages.yml`? Will the new messages be in the right language?

**Comment by Vankka** [comment]
the values will stay the same, apart from new values & comments. You can set `ForcedLanguage` to the right language

**Comment by Vankka** [comment]
`/discord setlang <language>` was added a while back, which accomplishes the same thing, except it generates completely new files & saves a backup of the old ones
