### ISSUE TITLE
[Request] Rich Presence

### ISSUE THREAD

**Issue by konsyr11** [DiscordSRV/DiscordSRV#546]
Hello,
I know that variants of this topic have been opened before, but here I kinda have a described request, not just a request title.
So, Discord bots are part of an application. This application is connected to DiscordSRV using the Client ID. In the application there is an option to enable rich presence. What I am suggesting is use the Discord or other API (like the one used in [EasyRP](https://github.com/Pizzabelly/EasyRP/)) and make it so the player can have "Playing {server_name}". This would help big servers, such as Hypixel, HermitCraft, MilkyMC and others make their presence... well... richer. It is a feature that users would love seeing implemented.
Thank you for your time.

**Comment by Scarsz** [comment]
Doesn’t matter how differently you’ve described it, you can’t. Bots aren’t allowed to use rich presence. This will never happen in any flavor until Discord decides to allow RPC for bots.
