### ISSUE TITLE
Feature request: One MC server, multiple Discord servers

### ISSUE THREAD

**Issue by cjariebs** [DiscordSRV/DiscordSRV#547]
My brother and I co-own a Minecraft server and we want to be able to use DiscordSRV on both Discord servers. Is there any way to do this? I invited the bot to both discords, set both channels in the config, but now the bot joins the second server and can't pipe any chat, and will not join the first server.

Is there a work around or should I start working on a pull request? :)

**Comment by Scarsz** [comment]
Channel pairs are a one-to-one link; you can't have the `global` channel, for example, going to/from two Discord channels.

See https://github.com/DiscordSRV/DiscordSRV/issues/111

**Comment by cjariebs** [comment]
Is there a technical reason on the Minecraft side for that, or is it simply a limitation of DiscordSRV? If it's the latter, I'd be happy to contribute code to make this happen.

**Comment by Scarsz** [comment]
DiscordSRV was just never designed to be able to do multiplexing. It would be a very major task to transition DiscordSRV into a state where it's possible. I'd rather have any contributions go towards the codebase for DiscordSRV2, https://github.com/DiscordSRV/Iris though. DiscordSRV v1 is more/less on it's last limb.

**Comment by Vankka** [comment]
#111
