### ISSUE TITLE
console channel translate mentions

### ISSUE THREAD

**Issue by dosluke** [DiscordSRV/DiscordSRV#548]
this would be useful

**Comment by Vankka** [comment]
what

**Comment by pkrok01** [comment]
you didn't explain anything at all

**Comment by dosluke** [comment]
https://puu.sh/EnN9d/6e13a15c60.png
this but for the console channel

**Comment by Vankka** [comment]
what's the use case?

**Comment by dosluke** [comment]
I want to make a helpop command using mycommand and discordsrv without downloading another plugin. to do this, i want to have a command /helpop which sends a command to the minecraft console channel with @staff in its message. im doing it this way instead of sending a message in the public channel because i want the helpop command to be private so other players cant see

**Comment by Vankka** [comment]
isn't going to happen, you can *probably* do this though, with `<@&role id>`
