### ISSUE TITLE
Suggestion - Link account through Discord (i.e. /discord link via DM)

### ISSUE THREAD

**Issue by RalphORama** [DiscordSRV/DiscordSRV#552]
Would it be possible to link accounts the opposite direction, i.e. via DMing the bot a UUID or (case sensitive) username?  

I'd like to use a feature like this to easily whitelist players on my server: I invite them to my Discord server, they link their Minecraft account by DMing the bot, then the bot runs `whitelist <username>` once the account is linked.

Thanks

**Comment by LemmoTresto** [comment]
Have a look at RequiredLinked4Gameplay
https://github.com/DiscordSRV/RequireLinked4Gameplay
