### ISSUE TITLE
MC Username Bot Name Sync

### ISSUE THREAD

**Issue by PenguinsWillLickYou** [DiscordSRV/DiscordSRV#553]
I'm wondering how to do this on my own discord server... Sorry i'm pretty new to this

![Screen Shot 2019-10-20 at 7 32 51 PM](https://user-images.githubusercontent.com/32959775/67172515-7ec16100-f370-11e9-8e1f-759d1abae1eb.png)

**Comment by pkrok01** [comment]
https://github.com/DiscordSRV/DiscordSRV/blob/master/src/main/resources/config/en.yml

**Comment by pkrok01** [comment]
well that didn’t work

Experiment_WebhookChatMessageDelivery in the config

**Comment by PenguinsWillLickYou** [comment]
thank you so much
