### ISSUE TITLE
Prevent debug bot token leaks with patterns

### ISSUE THREAD

**Issue by burturt** [DiscordSRV/DiscordSRV#554]
Sometimes stuff happens and the bot token/database info  isn't redacted. In addition to what normally happens, either regex out the bot token or just replace any line that contains the string "bot token", and repeat for jdbc setting

**Comment by Vankka** [comment]
Already a thing coming up in v1.18.0, https://github.com/DiscordSRV/DiscordSRV/commit/2bbd2820751324cf3e9dec60e4e0600e6e71fb57#diff-0ad22d382c20fe65fee64bbce9d8d345
