### ISSUE TITLE
Disable plugin from sending updates

### ISSUE THREAD

**Issue by Evansania** [DiscordSRV/DiscordSRV#555]
The idea is to stop specific plugins from relaying messages to the Console channel in Discord, e.g EnjinMinecraftPlugin, where debug is off, yet still sends debug info to the console channel (but not the console itself).

**Comment by Vankka** [comment]
use `DiscordConsoleChannelDoNotSendPhrases` or update the Enjin plugin (we pushed a pr to it fixing said issue not that long ago; keep in mind it may not be available just yet)
