### ISSUE TITLE
[ Add Message to message.yml / Add to the function ]

### ISSUE THREAD

**Issue by Erensisman09** [DiscordSRV/DiscordSRV#556]
**[CMD]**
> You can add translation commands: **/discord help, /discord linked, /discord unlink,**
> What is this for? So that you can change the text!

**[DiscordSRV add to the function]**
> Add so that it is possible not only 1 account can be invoked, but several, like so:
DiscordAccountsNumbersMinecraft: 5

**(Sorry for the curve translation)**

**Comment by Scarsz** [comment]
https://github.com/DiscordSRV/DiscordSRV/issues/556

I'm not going to be supporting multiple Minecraft accounts linked to the same Discord account
