### ISSUE TITLE
Make more messages translatable

### ISSUE THREAD

**Issue by TheNety** [DiscordSRV/DiscordSRV#561]
Possibility to translate message that discord bot sends to a dm, like "no permission" or "command is not able to be used".

**Comment by RedyAu** [comment]
+1 on this, also account linking DMs like `Are you sure that's your code? Link codes are 4 numbers long.` or `I don't know of such a code, try again.`

**Comment by Patendo** [comment]
Can you add that you can change all the messages that are output in Minecraft and on Discord? Messages such as /discord unlink, /discord linked, the help page /discord help, and any messages the bot sends you on Discord?

**Comment by Scarsz** [comment]
Merging to #349
