### ISSUE TITLE
Possibility to edit messages after command unlink and linked

### ISSUE THREAD

**Issue by Nety01** [DiscordSRV/DiscordSRV#562]
Possibility to edit/translate messages "Your Minecraft account is no longer associated with <user>." and "Your Minecraft account isn't associated with a Discord account." after command /discord unlink and /discord linked.

**Comment by pkrok01** [comment]
Translations for ["Your Minecraft account is no longer associated with ."](https://github.com/DiscordSRV/DiscordSRV/blob/master/src/main/java/github/scarsz/discordsrv/util/LangUtil.java#L770) and ["Your Minecraft account isn't associated with a Discord account."](https://github.com/DiscordSRV/DiscordSRV/blob/master/src/main/java/github/scarsz/discordsrv/util/LangUtil.java#L781) are hardcoded. To switch to a supported language, use the [ForcedLanguage ](https://github.com/DiscordSRV/DiscordSRV/wiki/Config-options#forcedlanguage-server-restart-required) option in [`config.yml`](https://github.com/DiscordSRV/DiscordSRV/blob/master/src/main/resources/config/en.yml).

**Comment by Scarsz** [comment]
https://github.com/DiscordSRV/DiscordSRV/issues/562
