### ISSUE TITLE
1.18.0 java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by FlashLight34** [DiscordSRV/DiscordSRV#565]
`23:01:24: [DiscordSRV] =================================================================
23:01:24: java.lang.ExceptionInInitializerError
23:01:24: > at github.scarsz.discordsrv.DiscordSRV.init(DiscordSRV.java:377)
23:01:24: > at java.lang.Thread.run(Thread.java:748)
23:01:24: > Caused by: java.security.AccessControlException: access denied ("java.io.FilePermission" "/etc/resolv.conf" "read")
23:01:24: > at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
23:01:24: > at java.security.AccessController.checkPermission(AccessController.java:886)
23:01:24: > at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
23:01:24: > at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
23:01:24: > at java.io.File.exists(File.java:814)
23:01:24: > at org.minidns.dnsserverlookup.UnixUsingEtcResolvConf.isAvailable(UnixUsingEtcResolvConf.java:98)
23:01:24: > at org.minidns.DnsClient.addDnsServerLookupMechanism(DnsClient.java:395)
23:01:24: > at org.minidns.DnsClient.<clinit>(DnsClient.java:55)
23:01:24: > ... 2 more`

**Comment by FlashLight34** [comment]
https://bin.scarsz.me/4ad784f1-9aa0-4826-8e1a-1a50486c9553#rOOeZAih5vM5kULztKbfzUfng720U9fN

**Comment by FlashLight34** [comment]
but but my config worked in 1.17.1 before update to 1.18.0 :|

**Comment by Scarsz** [comment]
https://github.com/MiniDNS/minidns/issues/99

**Comment by Scarsz** [comment]
@FlashLight34 try using https://lol.scarsz.me/cLsmbO/DiscordSRV-Build-1.18.0-SNAPSHOT.jar
