### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by Relaxing9** [DiscordSRV/DiscordSRV#568]
When using the latest Spigot build released today [1.18.1] the plugin returns a startup error, the previous build 1.18.0 released on Spigot had no previous issues.

https://pastebin.com/ZQm41k03

Plugin Version: [DiscordSRV-Build-1.18.1](https://www.spigotmc.org/resources/discordsrv.18494/update?update=305121) 
Server Version: git-Spigot-56f8471-56118c6

**Comment by Vankka** [comment]
Cause: https://github.com/DiscordSRV/DiscordSRV/commit/f7f7f892d223d3308c921dffa2d92e7402c87256#diff-fe87a54b8a447527b3d7a6f66f470e92L152-L159

**Comment by Relaxing9** [comment]
> Cause: [f7f7f89#diff-fe87a54b8a447527b3d7a6f66f470e92L152-L159](https://github.com/DiscordSRV/DiscordSRV/commit/f7f7f892d223d3308c921dffa2d92e7402c87256#diff-fe87a54b8a447527b3d7a6f66f470e92L152-L159)

If the issue is resolved in a commit, can the Spigot resource be updated with a bug free version?

**Comment by Vankka** [comment]
DiscordSRV is 100% free, this will be publicly available for free once committed. And most likely will require a update ASAP due to completely blocking DiscordSRV from starting in specific cases (such as yours)

**Comment by Relaxing9** [comment]
Anyway will use the Spigot released, 1.18.0 for now, I know it is free Vankka, its just a pain to open up eclipse and build the project manually.

**Comment by Vankka** [comment]
We have development builds through GitHub actions CD

**Comment by Vankka** [comment]
@Relaxing9 Dev build available at: http://nexus.scarsz.me/service/local/artifact/maven/redirect?r=snapshots&g=com.discordsrv&a=discordsrv&v=LATEST issue should be resolved

**Comment by Relaxing9** [comment]
Invalid link, would like to try it but...
https://prnt.sc/pwl753

**Comment by Scarsz** [comment]
https://lol.scarsz.me/SpDMZN/DiscordSRV-Build-1.18.1-SNAPSHOT.jar

**Comment by Relaxing9** [comment]
issue is resolved thanks @Vankka, for the support.
