### ISSUE TITLE
Voice module moves people from outside of voice category

### ISSUE THREAD

**Issue by HerobrainGamer** [DiscordSRV/DiscordSRV#570]
It works great except it pulls people from other vcs that are not in the proximity voice channels/category

**Comment by Scarsz** [comment]
Known issue, don't have the time to fix right now

**Comment by Vankka** [comment]
Dev build: https://cdn.discordapp.com/attachments/393152728043487243/647497575628537876/DiscordSRV-Build-1.18.3-SNAPSHOT.jar
