### ISSUE TITLE
Channel topic doesn't get updated, even when text is available and under Discord text limit.

### ISSUE THREAD

**Issue by Andre601** [DiscordSRV/DiscordSRV#571]
DiscordSRV: 1.18.1
Server: PaperMC 1.14.4 (Build 225)

Discord debug:
https://bin.scarsz.me/ef460ac9-6d82-4f71-be9b-7481c8c2dbb3#F1Il15HT3W8aqX43enMQJ18XZORzLvDh

Other notes:
The topic is under the max character limit Discord gives (888 characters remaining) and the bot has permissions to manage the channel and therefore the channel topic.
The topic did update before version 1.18.1

**Comment by Vankka** [comment]
Please set `DebugLevel` to `1`, run `/discordsrv reload`, wait until the topic updater goes through a cycle (~5 minutes (as per configuration)) & make a new debug report

**Comment by Andre601** [comment]
Here's the new debug with your requested changes
https://bin.scarsz.me/73588ede-318b-43cc-88ad-3843daa0be52#7H0ao670RDcHcPlDL2cTI5XPrqYbi8Xk

**Comment by Scarsz** [comment]
I'm able to reproduce this, no clue why, might be something within JDA

**Comment by Scarsz** [comment]
Hopefully fixed with https://github.com/DiscordSRV/DiscordSRV/commit/2cb358aa17201d9d2d98afb69cec01ea2698bc7e

**Comment by Andre601** [comment]
I assume the latest dev build would contain this change to test it?
If that's the case then I would appreciate if you could provide a link as the CI link on the resource page returns a 522 error.

**Comment by Scarsz** [comment]
https://lol.scarsz.me/ngRgEA/DiscordSRV-Build-1.18.2-SNAPSHOT.jar

**Comment by Andre601** [comment]
I added latest release and now have this error on startup:
```
[03:17:51 WARN]: Exception in thread "DiscordSRV - Channel Topic Updater" java.lang.NullPointerException
[03:17:51 WARN]:        at github.scarsz.discordsrv.objects.threads.ChannelTopicUpdater.applyPlaceholders(ChannelTopicUpdater.java:75)
[03:17:51 WARN]:        at github.scarsz.discordsrv.objects.threads.ChannelTopicUpdater.run(ChannelTopicUpdater.java:45)
```

Also, this message is send too:
```
[03:17:51 WARN]: [io.sentry.dsn.Dsn] *** Couldn't find a suitable DSN, Sentry operations will do nothing! See documentation: https://docs.sentry.io/clients/java/ ***
[03:17:51 WARN]: [io.sentry.DefaultSentryClientFactory] No 'stacktrace.app.packages' was configured, this option is highly recommended as it affects stacktrace grouping and display on Sentry. See documentation: https://docs.sentry.io/clients/java/config/#in-application-stack-frames
```

**Comment by Scarsz** [comment]
First error should be fixed with https://github.com/DiscordSRV/DiscordSRV/commit/8b3f84b00c47def390fe5c2ea07e2097fc15cd21, https://lol.scarsz.me/cJToWw/DiscordSRV-Build-1.18.3-SNAPSHOT.jar

As for the second... I don't think that's related to DiscordSRV. Sentry isn't depended on by any of DiscordSRV's dependencies and those packages don't exist in the jar.

**Comment by Andre601** [comment]
The error is fixed.
Also, I thought it could (at least) be related to DiscordSRV, since the error does no longer appear after the topic updater was fixed.

**Comment by Scarsz** [comment]
The topic updater being fixed surely has nothing to do with Sentry. There are no internal dependencies to Sentry, as I mentioned.

**Comment by Andre601** [comment]
I found this smaller warning when stopping the server:
`[12:17:46 ERROR]: [DiscordSRV] Broke from Channel Topic Updater thread: sleep interrupted`

**Comment by Vankka** [comment]
That is to be expected; Java interrupts all threads when the JVM shuts down
