### ISSUE TITLE
Exception REST request and weird no error

### ISSUE THREAD

**Issue by GITVenox** [DiscordSRV/DiscordSRV#573]
When loading DiscordSRV, I get 2 errors, one that looks like this:
`16.11 09:04:03 [Server] WARN [DiscordSRV] `

And another like this:
`16.11 09:14:04 [Server] ERROR [DiscordSRV] [JDA] There was an exception while executing a REST request`

**Comment by Vankka** [comment]
not even full errors

**Comment by srnyx** [comment]
@Vankka That's the thing, the first error had nothing after it, and the second one, idk about that

**Comment by srnyx** [comment]
Alright, I'm sure the errors were nothing, they probably didn't affect anything.
