### ISSUE TITLE
I really need help

### ISSUE THREAD

**Issue by Simonk02** [DiscordSRV/DiscordSRV#574]
I dont know why but the console gave me this link

https://bin.scarsz.me/de57db84-d760-4c1e-957f-2d8ab4c2ab78#n3UfZ3g9EjyUlfYsy4bo6aioqEaSoFzM

when i send a message from discord to my discordsrv in my minecraft server, it shows in my server but when i type something in minecraft, it doesnt show up in discord. even join message aswell.

**Comment by Vankka** [comment]
get dev build from here: https://cdn.discordapp.com/attachments/509491993035014154/645682523673853952/DiscordSRV-Build-1.18.1-SNAPSHOT.jar
