### ISSUE TITLE
Request: %date% %time% and adjustable formats

### ISSUE THREAD

**Issue by FangsMcWolf** [DiscordSRV/DiscordSRV#584]
(Copy/paste from the spigot forum...)

Great plugin. It's a wonderful way to be notified of someone joining when you have a mostly quiet game server running, and to be able to look at and read while playing the game without having to bring up the chat in-game to look at something. Simple but very effective concept.

That said, I have some requests here...

%date% - first, separate into %date% and %time% so that one or the other or both can be used, instead of it always being a full date/time.

%date% (and %time) - allow the format to be defined. Some people like weird formats like "date/month/year" or "date (abbrev month) year" etc. Same with times, where some people prefer am/pm vs 24hr, or .'s instead of :'s, etc.

Make %date% and %time% available at all times.

Since Discord combines messages that are within a certain period of time, and only show the time of the first message, I like seeing an actual timestamp on everything, include when the server shuts down and starts up. Others may feel the same way. Separating date/time into separate (and customizeable) variables, it allows for someone to have the date show up once a day for reference purposes, while showing only the time to cut down on how much space is used (for readability).

**Comment by pkrok01** [comment]
Since DiscordSRV supports PlaceholderAPI in most messages, that's possible with [PlacholderAPI's Server Placeholders](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#server)  
what you're looking for is PAPI's `%server_time_<SimpleDateFormat>%`

**Comment by FangsMcWolf** [comment]
Just tried it but no good unless I'm doing something wrong...

`MinecraftPlayerJoinMessageFormat: "`%server_time_HH:mm:ss%` :heavy_plus_sign: **%displayname% joined the server**"`

produces...
`%server_time_HH:mm:ss% :heavy_plus_sign: ~Wolfie joined the server`

**Comment by FangsMcWolf** [comment]
Okay, changing request to be that the API vars be supported with server start/stop and watchdog messages.

**Comment by pkrok01** [comment]
make a new issue for that request
