### ISSUE TITLE
/discord bcast does not respect vanilla target selectors (@p @a @e @r)

### ISSUE THREAD

**Issue by gvarados1** [DiscordSRV/DiscordSRV#585]
We can't use player names in bcasts activated by command blocks.

Let's assume Gvarados, Notch, and Herobrine are in the server. Gvarados stands on a pressure plate to activate a command block:

 `/say @p Yo Ho Ho! @a ` outputs: `Gvarados Yo Ho Ho! Gvarados, Notch, Herobrine`

`/discord bcast @p Yo Ho Ho! @a ` outputs: `@p Yo Ho Ho! @a `

**Comment by Vankka** [comment]
Added. Available on dev builds (https://snapshot.discordsrv.com) & the next version
