### ISSUE TITLE
Social Spy

### ISSUE THREAD

**Issue by Tina-King** [DiscordSRV/DiscordSRV#593]
Hello,

We use DiscordSRV for staff to moderate in-game chat from our discord.

Would it be possible to have a setting to enable social spy so that we can see social spy in discord?

Thanks,
Tina

**Comment by pkrok01** [comment]
How is this different from having the console channel enabled?

**Comment by Tina-King** [comment]
Console channel is flooded with all kinds of data, the social spy would only be in-game chat messages and /msg, /r, etc.

The idea is to be able to easily moderate a server without being online constantly.

**Comment by Chesvin1** [comment]
This should be doable already with alerts.yml

**Comment by Dinty1** [comment]
This is possible with the alerts feature https://docs.discordsrv.com/alerts/#social-spy. You could also use [Essentials' private message event](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/main/java/net/ess3/api/events/PrivateMessageSentEvent.java) to catch replies.
