### ISSUE TITLE
Option to get the raw username

### ISSUE THREAD

**Issue by haeiven** [DiscordSRV/DiscordSRV#596]
Hi,

Since the 1.18.4 version DiscordSRV is getting the player's display name instead of the raw username.

I don't think everyone want to get the Display name, so, is it possible to add an option to select if we want the display name or the raw username?

Best regards,

**Comment by Vankka** [comment]
Added in https://github.com/DiscordSRV/DiscordSRV/commit/0d20c902d03f9acc1afec9ab2ca8b98626eac2c0

Dev build: https://discordsrv.com/discordsrv-snapshot
