### ISSUE TITLE
Could not pass event PlayerJoinEvent to DiscordSRV v1.18.4

### ISSUE THREAD

**Issue by SimmsRyan97** [DiscordSRV/DiscordSRV#597]
19.12 23:39:02 [Server] ERROR Could not pass event PlayerJoinEvent to DiscordSRV v1.18.4
19.12 23:39:02 [Server] INFO github.scarsz.discordsrv.dependencies.jda.api.exceptions.InsufficientPermissionException: Cannot perform action due to a lack of Permission. Missing permission: MANAGE_ROLES
19.12 23:39:02 [Server] INFO at github.scarsz.discordsrv.dependencies.jda.internal.entities.GuildImpl.checkPermission(GuildImpl.java:1215) ~[?:?]
19.12 23:39:02 [Server] INFO at github.scarsz.discordsrv.dependencies.jda.internal.entities.GuildImpl.modifyMemberRoles(GuildImpl.java:1008) ~[?:?]
19.12 23:39:02 [Server] INFO at github.scarsz.discordsrv.util.DiscordUtil.modifyRolesOfMember(DiscordUtil.java:564) ~[?:?]
19.12 23:39:02 [Server] INFO at github.scarsz.discordsrv.util.GroupSynchronizationUtil.reSyncGroups(GroupSynchronizationUtil.java:110) ~[?:?]
19.12 23:39:02 [Server] INFO at github.scarsz.discordsrv.util.GroupSynchronizationUtil.reSyncGroups(GroupSynchronizationUtil.java:42) ~[?:?]
19.12 23:39:02 [Server] INFO at github.scarsz.discordsrv.listeners.PlayerJoinLeaveListener.onPlayerJoin(PlayerJoinLeaveListener.java:48) ~[?:?]
19.12 23:39:02 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor568.execute(Unknown Source) ~[?:?]
19.12 23:39:02 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-175]
19.12 23:39:02 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-175]
19.12 23:39:02 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-175]
19.12 23:39:02 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-175]
19.12 23:39:02 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerList.a(PlayerList.java:191) ~[patched_1.14.4.jar:git-Paper-175]
19.12 23:39:02 [Server] INFO at net.minecraft.server.v1_14_R1.LoginListener.c(LoginListener.java:174) ~[patched_1.14.4.jar:git-Paper-175]
19.12 23:39:02 [Server] INFO at net.minecraft.server.v1_14_R1.LoginListener.tick(LoginListener.java:65) ~[patched_1.14.4.jar:git-Paper-175]
19.12 23:39:02 [Server] INFO at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:256) ~[patched_1.14.4.jar:git-Paper-175]
19.12 23:39:02 [Server] INFO at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:139) ~[patched_1.14.4.jar:git-Paper-175]
19.12 23:39:02 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1232) ~[patched_1.14.4.jar:git-Paper-175]
19.12 23:39:02 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-175]
19.12 23:39:02 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1075) ~[patched_1.14.4.jar:git-Paper-175]
19.12 23:39:02 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919) ~[patched_1.14.4.jar:git-Paper-175]
19.12 23:39:02 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

**Comment by Scarsz** [comment]
Read the error
