### ISSUE TITLE
Disable channel description updater

### ISSUE THREAD

**Issue by fourteevee** [DiscordSRV/DiscordSRV#599]
I would like an option to disable the feature that updates my #general-chat channel and #server-console channel descriptions with server info, as I would like to give them my own descriptions, in addition, the channel updating is clogging my #logs channel, and removing the bot's ability to edit those channels makes it very unhappy in my console.  I can provide any other help as needed.

**Comment by pkrok01** [comment]
[FAQ#how-can-i-disable-a-featuremessage](https://github.com/DiscordSRV/DiscordSRV/wiki/FAQ#how-can-i-disable-a-featuremessage)
