### ISSUE TITLE
Unlink inactive players automatically

### ISSUE THREAD

**Issue by sdcaptains** [DiscordSRV/DiscordSRV#602]
so if the player is offline in-game for a specific number of days his role will be removed in discord or his account in-game will be unlinked to his discord account

**Comment by kakd** [comment]
Why would you want that? It would be annoying for any player who takes a break from the game and returns later. Could also be annoying if one of the players are active on discord but not so much in game. I just don't see any benefit to unlinking

**Comment by sdcaptains** [comment]
its optional tho but i really want that feature since theres so much inactive in-game but still active in discord they join giveaways yet they dont even play anymore and who knows some server might want this feature cuz no one likes discord full of people but some are not even playing in your server anymore..

**Comment by Scarsz** [comment]
Merging into #715
