### ISSUE TITLE
Server Crash - NoClassDefFoundError: github/scarsz/discordsrv/dependencies/jda/core/requests/CloseCode

### ISSUE THREAD

**Issue by ProsperCraft** [DiscordSRV/DiscordSRV#604]
I don't know if Discordsrv caused the original crash, but it had a stacktrace in console.

DiscordSRV-Build-1.16.4
https://ci.codemc.io/job/Mohist-Community/job/Mohist-1.12.2/
https://www.curseforge.com/minecraft/modpacks/towncraft

Crash log- 
java.lang.NoClassDefFoundError: net/minecraft/world/World$3
https://gist.github.com/ProsperCraft/f1a9b7b295b66244e6df81155c7d261e

**java.lang.NoClassDefFoundError: github/scarsz/discordsrv/dependencies/jda/core/requests/CloseCode**
https://gist.github.com/ProsperCraft/30d90915f8655064b2872548151b18c9

Server log-
[latest.log](https://github.com/DiscordSRV/DiscordSRV/files/4013296/latest.log)

**Comment by pkrok01** [comment]
DiscordSRV Build 1.16.4 is an extremely old version of the plugin. Please download https://get.discordsrv.com/ and try again. All it requires is a drag&drop replacement of the plugin. If a crash happens again, go to the #support channel in our Discord server. 
*Disclaimer: Color Translations get reset on config migration.*

**Comment by Vankka** [comment]
So the crash itself has nothing to do with DiscordSRV.
The error on shutdown usually happens when the jar gets changed whilst the server is running

**Comment by ProsperCraft** [comment]
@pkrok01 I can't run the latest version with 1.12.2 or it doesn't show achievements in discord because newer minecraft uses advancements.

**Comment by Vankka** [comment]
@ProsperCraft Both achievements and advancements are supported on the latest version.

**Comment by ProsperCraft** [comment]
ok thank you, I will update then report the bug if it still exists.
