### ISSUE TITLE
DiscordSRV for Modpack Aternos Servers

### ISSUE THREAD

**Issue by jos3s** [DiscordSRV/DiscordSRV#605]
Would it be possible to add a way to check server status, number of active players, backup status and some other information for servers using modpacks or forge?

**Comment by Vankka** [comment]
Server status is technically already a thing as the bot is only online when the server is online, number of *online* (not necessarily "active") players can be displayed on the playing status or topic of console/chat channel. Digging into forge information is probably never going to happen

**Comment by jos3s** [comment]
Wouldn't it be possible to get this information directly from the website no?

**Comment by Vankka** [comment]
..what website?

**Comment by jos3s** [comment]
The Aternos site, it provides free servers, could they provide this information directly to DiscordSRV, overcoming this limitation of forge with the plugin?

**Comment by Vankka** [comment]
That's much more unlikely to happen

**Comment by Scarsz** [comment]
Certainly won't be implemented
