### ISSUE TITLE
Acheivements are not displaying in Discord when updating 

### ISSUE THREAD

**Issue by ProsperCraft** [DiscordSRV/DiscordSRV#606]
Going from 
DiscordSRV-Build-1.16.4
to 
DiscordSRV-Build-1.18.4

Chat went from this nice graphical pretty(including achievements for 1.12.2)-

![ea79b3878eb1174f8a5cf755822d8eed](https://user-images.githubusercontent.com/4427684/71636463-db04f480-2bed-11ea-8260-76b86d49a416.png)

To this- non graphical, missing all achievements for 1.12.2

![a2d4805021d83613336422fad205982d](https://user-images.githubusercontent.com/4427684/71636486-3a630480-2bee-11ea-9d53-75dc733c373a.png)
![2019-12-31_16 54 07](https://user-images.githubusercontent.com/4427684/71636489-42bb3f80-2bee-11ea-9b03-d32aed9974ed.png)

**Comment by pkrok01** [comment]
Ping `@granny` in the support channel

**Comment by ProsperCraft** [comment]
The dev build you released for this fixed the issue thank you.
