### ISSUE TITLE
Ability to specify players that can use the reserializer

### ISSUE THREAD

**Issue by burturt** [DiscordSRV/DiscordSRV#607]
Exactly as title says, allow defining a role id in discord and a permission for minecraft when dealing with who can use the reserializer

**Comment by Scarsz** [comment]
What purpose does this really serve? I don't see much of a point to preventing which people can use formatting in MC -> Discord messages when anyone can just go to a channel in Discord and use formatting all they want without restriction

**Comment by granny** [comment]
Won't be implemented
