### ISSUE TITLE
Reserializer seems inverted

### ISSUE THREAD

**Issue by SylveonBottle** [DiscordSRV/DiscordSRV#610]
![image](https://user-images.githubusercontent.com/17802843/72199131-568c5000-33fd-11ea-98e3-283c0598840e.png)
![image](https://user-images.githubusercontent.com/17802843/72199142-74f24b80-33fd-11ea-8279-ef0a98ad22af.png)
![image](https://user-images.githubusercontent.com/17802843/72199145-7a4f9600-33fd-11ea-84db-28b1b807cb9d.png)

`Experiment_MCDiscordReserializer_ToMinecraft: true` ENABLES discord -> minecraft formatting
`Experiment_MCDiscordReserializer_ToDiscord: true` DISABLES minecraft -> discord formatting

See what I'm getting at?

**Comment by Vankka** [comment]
Is there something wrong or do you just think the config options should be the other way around?

**Comment by Vankka** [comment]
Reserializer from MC -> Discord converts Minecraft formatting codes (with section signs) to Discord, not ** -> Bold, if that's what you're thinking

**Comment by SylveonBottle** [comment]
> Reserializer from MC -> Discord converts Minecraft formatting codes (with section signs) to Discord, not ** -> Bold, if that's what you're thinking
yeah but who in minecraft uses section signs? Everyone I know uses discord formatting codes in minecraft.

**Comment by Vankka** [comment]
Section signs are what Minecraft uses to display actual colors, & characters are converted to section signs as they are much easier to type in most cases. (and as you said section signs are blocked by the game to prevent players from displaying colors where they shouldn't)

eg. EssentialsChat will convert & color codes to section sign color codes. The reserializer system was **not** designed for in-game players to type section signs for colors. And imo having a bunch of stars, underscores etc. in chat makes it look like a mess; and DiscordSRV isn't going to convert them

**Comment by SylveonBottle** [comment]
Ah, okay. So I guess I've got to install a second plugin just to fix the
functionality of the first. Gotcha.

You should probably list EssentialsChat as a dependency required to use
Reserializer MC -> Discord.

**Comment by Vankka** [comment]
There's many plugins that do the conversion, essentialschat is just one of them. And isn't *neccaserily* required to use the option
