### ISSUE TITLE
Add option for copy the code from Chat (1.15+ only)

### ISSUE THREAD

**Issue by Andre601** [DiscordSRV/DiscordSRV#619]
1.15 added a new JSON option, which allows to directly copy text into your clipboard when clicking a text having the JSON action.

I think it would be beneficial to implement support for clicking the code to copy it into your clipboard.

For 1.14 and lower could it be putting the code as a "command suggestion" into your chat bar, so that you can select and copy it.

**Comment by Vankka** [comment]
Not sure if that would really be useful

**Comment by Andre601** [comment]
It would probably only be useful for lazy people, or people that are (somehow) unable to remember a 4-digit code...

**Comment by Vankka** [comment]
Oh the link code, well it'd be a nice touch

**Comment by Andre601** [comment]
What other "code" did you expect? xD

**Comment by Vankka** [comment]
Code block / code string
