### ISSUE TITLE
Cannot filter out console lines with regex

### ISSUE THREAD

**Issue by Malbeth81** [DiscordSRV/DiscordSRV#621]
Your examples in https://github.com/DiscordSRV/DiscordSRV/wiki/Configuration-examples#block-special-console-output-from-appearing-in-console-channel seem to show that we can use 
DiscordConsoleChannelRegexFilter with a blank DiscordConsoleChannelRegexReplacement to remove lines that match a certain regex, but in practice that is impossible because there is an "isBlank" check done on the replacement: https://github.com/DiscordSRV/DiscordSRV/blob/2502506a1ae526df46c101156389ed9eebc196e5/src/main/java/github/scarsz/discordsrv/objects/log4j/ConsoleAppender.java#L131

Please remove that isBlank check so we can use it to filter out lines by regex and not just with certain words.

Thanks!

**Comment by Vankka** [comment]
Latest dev build @ https://snapshot.discordsrv.com
