### ISSUE TITLE
Define server admin in config.yml and refer to it as a placeholder

### ISSUE THREAD

**Issue by metalshark** [DiscordSRV/DiscordSRV#630]
Being able to define the primary server admin in config.yml then refer to it in:

messages.yml
ServerWatchdogMessage

with it having a default of `%guildowner%` may cut down on future support requests. Admins can still bespoke the ServerWatchdogMessage or add more than one server admin (using the <@123> format).

**Comment by Vankka** [comment]
Sounds a bit uneccasery, it's just 2 places.

> with it having a default of %guildowner% may cut down on future support requests. 
What?

**Comment by metalshark** [comment]
May be unnecessary, however, I asked the question when starting out and so did another user. I am using the Placeholder API to send a few more messages and would be nice to be able to define the Discord admin in one place to use elsewhere. Means more of the config is portable between systems and all the Discord stuff is defined in the Discord configs.

**Comment by pkrok01** [comment]
> I'm not particularly a fan of this or the reason provided for the change. Having an entire configuration option that is only utilized in one message as opposed to just being in the message is unnecessary. While I can see the point of view that the config and messages files can be separated, realistically, it's not necessary for such a small use.
https://github.com/DiscordSRV/DiscordSRV/pull/645#issuecomment-590138771
