### ISSUE TITLE
Enhancement: Allow mapping and enforcement of Discord roles to Minecraft groups

### ISSUE THREAD

**Issue by metalshark** [DiscordSRV/DiscordSRV#631]
Would like Discord roles to configure Minecraft groups using a mapping system.

It looks like the VaultAPI allows for adding/removing users from groups http://milkbowl.github.io/VaultAPI/. If a mapping of Minecraft groups to roles in Discord could be created, then adding/removing a role from a user would add/remove the respective group from them in Minecraft.

**Comment by Vankka** [comment]
Duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/326
