### ISSUE TITLE
Sync nicknames on the same schedule as group sync.

### ISSUE THREAD

**Issue by TheReverend403** [DiscordSRV/DiscordSRV#635]
Just an idea to keep Discord display names synced with in-game nicks like roles are. :)

**Comment by Vankka** [comment]
A timer to update nicknames has been added to 1.18.0 (dev builds; https://snapshot.discordsrv.com), though it runs on it's own (but can be set to the same time as group sync)

**Comment by TheReverend403** [comment]
That works, but when a nick is set, the bot doesn't seem to send %toprolecolor% to Minecraft.

```
DiscordToMinecraftChatMessageFormat: "%toprolecolor%%username% &9» &r%message%"
DiscordToMinecraftChatMessageFormatNoRole: "&7%username% &9» &r%message%"
```

**Comment by Vankka** [comment]
Join https://discordsrv.com/discord and go to #support regarding that

**Comment by TheReverend403** [comment]
For future readers, the issue was my colour translation map was reset after an update for the following reason:

![discord](https://dev.pste.pw/f/9j8.png)

**Comment by pkrok01** [comment]
When the config is migrated, the original config is saved in a separate file in the plugin folder. For those who run into this situation, your color translations are easily accessible for reimplementation.
