### ISSUE TITLE
Linked role isn't added back after leaving/joining Discord server

### ISSUE THREAD

**Issue by skielred** [DiscordSRV/DiscordSRV#637]
After leaving and joining back the Discord server associated with the bot, the nickname is correctly applied back after the `NicknameSynchronizationCycleTime` is hit, however, the role provided in `MinecraftDiscordAccountLinkedRoleNameToAddUserTo` is not given back to the user on Discord.

**Comment by Scarsz** [comment]
https://snapshot.discordsrv.com

**Comment by skielred** [comment]
I'm using the snapshot build already and the role was not added automatically

**Comment by Vankka** [comment]
The role should be given back if the user leaves the Discord server and then joins back
