### ISSUE TITLE
Error 503 when i try wo download the .jar file

### ISSUE THREAD

**Issue by michaeldai7** [DiscordSRV/DiscordSRV#652]
i am using ssh to remote control a server and i used wget command to download
![Screenshot from 2020-02-26 18-40-44](https://user-images.githubusercontent.com/43862422/75398420-9af97f80-58c7-11ea-81fa-652c6675a4b3.png)

**Comment by Scarsz** [comment]
1. This is not an issue with DiscordSRV
2. Spigot doesn't support direct download links of resources
3. Use https://get.discordsrv.com

**Comment by michaeldai7** [comment]
> 1. This is not an issue with DiscordSRV
> 2. Spigot doesn't support direct download links of resources
> 3. Use https://get.discordsrv.com

this link does not link directly to resources too, it downloads a html file
