### ISSUE TITLE
Integrate ChatItem [enhancement]

### ISSUE THREAD

**Issue by bqstnm** [DiscordSRV/DiscordSRV#655]
A feature I think would be cool would be to have the chat item plugin have the placeholder replaced with the item not only in game but in the discord chat. Currently, the plugin sends the text the player types even if it's a placeholder for the plugin.

**Comment by Vankka** [comment]
This is probably unlikely to happen, that plugin makes use of packets

**Comment by Scarsz** [comment]
This is something that that plugin needs to implement support for DiscordSRV for, not the other way around
