### ISSUE TITLE
Dynmap Chat Integration

### ISSUE THREAD

**Issue by Scarsz** [DiscordSRV/DiscordSRV#66]
see https://github.com/webbukkit/dynmap/blob/v3.0/DynmapCoreAPI/src/main/java/org/dynmap/DynmapCommonAPI.java#L28 for API usage

**Comment by Androkai** [comment]
Github: https://github.com/webbukkit/dynmap
Maven-repo: http://repo.mikeprimm.com/us/dynmap/dynmap/

**Comment by david50407** [comment]
@Androkai Discord --> Dynmap is possible, and the method you mentioned is here https://github.com/webbukkit/DynmapCoreAPI/blob/master/src/main/java/org/dynmap/DynmapCommonAPI.java#L28
I used the method a long time, and it works well. :smile:

**Comment by Blitheness** [comment]
Hello! Just wondering if you've had any joy with the dynmap integration? Thank you

**Comment by crizyx** [comment]
Hello, do you have news about that ?

**Comment by Vankka** [comment]
This isn't going to be added.

**Comment by ledlamp** [comment]
@Vankka why not? @Androkai and @david50407 suggest that both directions are possible to do. It sucks to only see one side of a conversation that happened between minecraft and dynmap. Is this just too low of a priority?

**Comment by Vankka** [comment]
@Scarsz remember the reason you closed & marked this as `no`?  Or should this be reopened & done in the future?

**Comment by Scarsz** [comment]
Dynmap’s API requires a Player instance to send a chat message to the web chat, that isn’t available when people are on Discord while not
on Minecraft

**Comment by ledlamp** [comment]
yeah @david50407 said you can send to web without a player object; the method he linked only needs two strings. (and that file was last updated in 2014...)

**Comment by Vankka** [comment]
Out of date repo, the most current api is under the main repo, still has the same method, though; https://github.com/webbukkit/dynmap/blob/v3.0/DynmapCoreAPI/src/main/java/org/dynmap/DynmapCommonAPI.java#L28

**Comment by r3dmc** [comment]
When this will be add ?

**Comment by EOT3000** [comment]
PR #702

**Comment by Vankka** [comment]
This has been added to development builds @ https://snapshot.discordsrv.com
If there are any issues let us know on Discord @ https://discordsrv.com/discord

**Comment by JeffaloBob** [comment]
thanks for the update, i have an issue.

discord --> dynmap works great

but

dynmap --> discord does not.

is there something to config to get this to work?

**Comment by Vankka** [comment]
> is there something to config to get this to work?
No, join Discord
