### ISSUE TITLE
Message bodys are not sanitized

### ISSUE THREAD

**Issue by Eoghanmc22** [DiscordSRV/DiscordSRV#663]
When you send a message in game with mark down characters in discord the formatting gets messed up.

![Example](https://cdn.discordapp.com/attachments/689985738800103460/690010705654579208/unknown.png) supposed to be Xx__gg_ok__xX

**Comment by MattyHD0** [comment]
you can use `Xx__gg_ok__xX` or ```Xx__gg_ok__xX```

**Comment by pkrok01** [comment]
download latest dev build https://snapshot.discordsrv.com/ and set `Experiment_MCDiscordReserializer_ToDiscord` to 'true` in `config.yml`
