### ISSUE TITLE
Add Way to Store Token Outside of Main config.yml

### ISSUE THREAD

**Issue by md-5** [DiscordSRV/DiscordSRV#673]
Reckon you could please add a way to keep the token outside of config.yml?
Cause we store the entire server in git https://github.com/SpigotMC/SpigotCraft

Just token.yml or even token.txt would be cool

**Comment by pkrok01** [comment]
added in latest dev build: https://snapshot.discordsrv.com/ bd6db589c94a08bf38c8c58563b38f4f608c155a
