### ISSUE TITLE
Sync Server Stats to a status catergory.

### ISSUE THREAD

**Issue by cal3432** [DiscordSRV/DiscordSRV#674]
No clue what im talking about?

Here is an example:
![image](https://user-images.githubusercontent.com/57721560/78159610-b01f7c00-743a-11ea-9f00-5a0f1680f518.png)

You could edit the channel once every editChannelEvery seconds and use placeholder api placeholders or discord-srv ones used in the minecraft chat => discord channel, some configurations you could have:

```yaml
statuses:
       1: "{playersOnline}/{playerlimit} Online"
       2: "%averagePing%ms Average Ping"
       3: "{uniquePlayers} Unique Players"
editChannelEvery: 60 
```

**Comment by Scarsz** [comment]
Merging with https://github.com/DiscordSRV/DiscordSRV/issues/301
