### ISSUE TITLE
Rare double chat with ChatControlPro

### ISSUE THREAD

**Issue by mibby** [DiscordSRV/DiscordSRV#675]
ChatControlPro v8.6.6
DiscordSRV v1.19.0-SNAPSHOT (DiscordSRV-Build-1.19.0-SNAPSHOT-1585835031.jar)
```
[07:25:37] [DiscordSRV - Initialization/INFO]: [DiscordSRV] This build of DiscordSRV is identical to develop. [latest public dev build]
```

![link](https://i.imgur.com/L0AMOTL.png)

DiscordSRV seems to sometimes cause double chat output to occur. It only happens for one line, rarely two if it's at the same time, and then goes back to the standard formatting set by ChatControl. Removing DiscordSRV seems to resolve the issue. The issue is relatively rare, only happens a couple of times.

Downgrading to DiscordSRV 1.18.4 also seems to solve the issue (from short tentative testing), but has an issue with DiscordSRV sometimes displaying messages multiple times in a discord channel. That issue is not present with the SNAPSHOT build.

**Comment by Vankka** [comment]
Checked the changes in dev builds, there's nothing that would effect this from what I could tell. My best guess was if ChatControl somehow ended up on the hooked plugins list, would be about the only way it would have a effect.

ChatControl controls the DiscordSRV integration between the two plugins, I'd get in touch with their team.

**Comment by Vankka** [comment]
Marking as invalid & closing but can be reopened later if it turns out to be a DiscordSRV issue
