### ISSUE TITLE
Builds broken: HTTPS required for fetching Maven artifacts from Bintray

### ISSUE THREAD

**Issue by jgeboski** [DiscordSRV/DiscordSRV#677]
As of January 13, 2020, Bintray now *requires* HTTPS when accessing their Maven repository ([post](https://jfrog.com/blog/secure-jcenter-with-https)). There is no HTTP -> HTTPS redirection anymore either, unfortunately. The JDA artifact comes from this repository. This is breaking builds where the local Maven repository does not have the artifact cached already.

The URL for Bintray's jcenter ([source](https://github.com/DiscordSRV/DiscordSRV/blob/2502506a1ae526df46c101156389ed9eebc196e5/pom.xml#L255)) needs to be updated to `https://jcenter.bintray.com`.

HTTP URLs are not redirected:
```
$ curl -I http://jcenter.bintray.com/net/dv8tion/JDA/4.0.0_56/JDA-4.0.0_56.pom
HTTP/1.1 403 Forbidden
Server: nginx
Date: Sat, 04 Apr 2020 16:59:01 GMT
Content-Type: text/html
Content-Length: 524
Connection: keep-alive
ETag: "XXXXXXXX-XXX"
```

But HTTPS works fine:
```
$ curl -I https://jcenter.bintray.com/net/dv8tion/JDA/4.0.0_56/JDA-4.0.0_56.pom
HTTP/1.1 200 OK
Server: nginx
Date: Sat, 04 Apr 2020 17:18:44 GMT
Content-Type: application/x-maven-pom+xml
Content-Length: 2081
Connection: keep-alive
Last-Modified: Sun, 03 Nov 2019 13:47:19 GMT
ETag: 080a32b9eeab3e0e2b3faa35705d6fcfc488db8c9d8854450330c643472fe01d
X-Checksum-Sha1: 7ce017d0b804586bd9160d6330df85f301bc13a9
X-Checksum-Sha2: 080a32b9eeab3e0e2b3faa35705d6fcfc488db8c9d8854450330c643472fe01d
Accept-Ranges: bytes
```

I would send a PR, but I have obligations making it a convoluted process for a one-liner.

**Comment by Vankka** [comment]
This has been changed on the `develop` branch where you would need to make the change anyway, according to our [contributing guidelines](https://github.com/DiscordSRV/DiscordSRV/blob/master/CONTRIBUTING.md)
