### ISSUE TITLE
Add PAPI Support to Broadcast Command

### ISSUE THREAD

**Issue by NotGeri** [DiscordSRV/DiscordSRV#679]
Hey.
As of right now `/discordsrv:discord broadcast` does not support any kind of placeholders. In my opinion this is a great and really easy way to send messages on discord without using any other plugin or modification but this is also quite limited this way. In my opinion adding PAPI support could be beneficial. For example server owners could set it up so the server TPS or playerlist get monitored every 5 minutes by sending a message to discord with `/discordsrv:discord broadcast <channel> %server_tps`. This is just two of many things that could be possible. 

I hope you will consider my suggestion.

**Comment by Vankka** [comment]
Added, dev builds @ https://snapshot.discordsrv.com
