### ISSUE TITLE
Multiverse Hook error on non multiverse worlds

### ISSUE THREAD

**Issue by Nextopi** [DiscordSRV/DiscordSRV#680]
I've got this error when talking on a non multiverse world

https://paste.gg/p/anonymous/9db02316da6643ae8bed02324ab4ca2c/files/4c859197d75f4daf96e85babd49880c9/raw

from dungeonsxl

**Comment by pkrok01** [comment]
set a World Alias for the world you're in through Multiverse:
[Multiverse/Multiverse-Core/wiki/World-properties#alias](https://github.com/Multiverse/Multiverse-Core/wiki/World-properties#alias)

or add `Multiverse` to our `DisabledPluginHooks` option in config.yml:
```yml
DisabledPluginHooks: ["Multiverse"]
```

**Comment by Vankka** [comment]
Fixed in https://github.com/DiscordSRV/DiscordSRV/commit/459dbf2fb57a924786447e92f67287ab9b47e4fd Dev build @ https://snapshot.discordsrv.com
