### ISSUE TITLE
Ability to changing DNS settings.

### ISSUE THREAD

**Issue by jev217** [DiscordSRV/DiscordSRV#689]
Hello, so there is times where my server gets a brief few seconds of internet disconnect and in those seconds the discord plugin loses connection and thinks it has to fall back to the other DNS server due to it not resolving the hostname.  But when it does fall back to the other DNS (1.1.1.1) is that DNS can't resolve discordapp.com for some odd reason.  What I'm wondering here is if we could possibly get the ability in the config.yml to change the following DNS settings:

- How long the timeout to change to the fallback DNS.
- The DNS server it'll fallback to.

I believe the change for timeout would fix my issue the most here.

Thanks.

**Comment by Vankka** [comment]
Added the ability to only switch to fallback after X amount of requests, or force it to always (-1)/never (0) use fallback dns via the config option `MaximumAttemptsForSystemDNSBeforeUsingFallbackDNS`  
In commit https://github.com/DiscordSRV/DiscordSRV/commit/f1e67a3e25018621012f5443ce94b7da39db35e1 (available in development builds @ https://snapshot.discordsrv.com).
