### ISSUE TITLE
Minecraft chat cooldown is enabled, but messages still being sent to Discord

### ISSUE THREAD

**Issue by WouterNoordhof** [DiscordSRV/DiscordSRV#690]
Some Minecraft servers have a chat cooldown of sorts which prevents users to spam messages, but for example only lets them send 1 message every 5 seconds.

I've noticed that when this is the case, and when a player sends a message in that cooldown period in the minecraft chat, the message will get blocked to be sent to the minecraft chat, but will still be sent to the synced Discord channel. 

The other way around has an easy workaround to enable chat slowmode on the discord channel with the same cooldown as the ingame chat, but the MC->DC seems to have some issues.

How it looks on Discord:
![image](https://user-images.githubusercontent.com/36151792/79219503-afcbab80-7e52-11ea-957e-79edf01588dc.png)

How it looks on Minecraft:
![image](https://user-images.githubusercontent.com/36151792/79219547-c70a9900-7e52-11ea-944a-04a6014b12fd.png)

**Comment by Vankka** [comment]
Issue with the plugin limiting chat
