### ISSUE TITLE
Option to disable update checks / message on login.

### ISSUE THREAD

**Issue by mibby** [DiscordSRV/DiscordSRV#691]
Would it be possible to add an option to disable update checking or at least the message on login? I use the development builds from https://snapshot.discordsrv.com/ but it seems it doesn't always receiving the latest branch changes.

![link](https://i.imgur.com/gjZcCpB.png)

Which leads to this message occurring, despite no newer builds being available.

From console;
```
[01:09:43] [DiscordSRV - Initialization/WARN]: [DiscordSRV] This build of DiscordSRV is ahead of master but behind develop. Update your development build!
```

DiscordSRV-Build-1.19.0-SNAPSHOT-1586940538.jar 
Downloaded 04/15 01:49 AM PST

**Comment by Vankka** [comment]
snapshot.discordsrv.com has the latest development builds within a couple minutes of a push, you can use the `discordsrv.updatenotification` permission for disabling the join message. `UpdateCheckDisabled` can be added to the config but is **not recommended** for **security** reasons

**Comment by mibby** [comment]
Ah, I see it's because the newest commit didn't build. 
https://github.com/DiscordSRV/DiscordSRV/runs/586966971

It is still checking for newer commits and saying outdated despite that. Is it possible to check against existing build numbers instead of if newer commits exist?

**Comment by Vankka** [comment]
It does check the latest commit even if it didn't build, building a check that checks for the latest that did build would be very very complicated, thus it will stay this way
