### ISSUE TITLE
Feature Request: Add %discordnickname% to link/unlink command placeholders

### ISSUE THREAD

**Issue by ttamttamS** [DiscordSRV/DiscordSRV#694]
The link/unlink commands are very useful, but on my discord server I have people who use nicknames. I would like to be able to use these nicknames when using link/unlink commands.
For example, a player could go by the username "username123" on discord and then be nicknamed "Alice" because it's more legible. When "Alice" links their minecraft account I would like to be able to use the nicknamer plugin to change their in game display name to "Alice", but instead it is changed to "username123" because there is no nickname placeholder, just a username one.

**Comment by Vankka** [comment]
Added. Development build available at https://snapshot.discordsrv.com
