### ISSUE TITLE
Randomly Disconnects

### ISSUE THREAD

**Issue by Macintosh-Fan** [DiscordSRV/DiscordSRV#697]
I have a Minecraft Server running on my Raspberry Pi 4 with all the requirements and I have DiscordSRV setup. But the Console channel unexpectedly stopped for whatever reason...

Is there a new version that specifically fixed the bug? I am running Minecraft 1.15.2

**Comment by Scarsz** [comment]
No such thing as a "random" disconnection. Look at your log.

**Comment by Macintosh-Fan** [comment]
@Scarsz Why did you just close the issue?

**Comment by Scarsz** [comment]
Because it's not a valid issue.

**Comment by Macintosh-Fan** [comment]
Meaning I am the only one with the bug @Scarsz?

**Comment by Scarsz** [comment]
Once again, it's not a bug. Disconnects don't randomly happen. They always have a reason. Go look at your console.
