### ISSUE TITLE
Error, console does not show messages on discord server.

### ISSUE THREAD

**Issue by DeathSmurf** [DiscordSRV/DiscordSRV#699]
Hi, I'm with **DiscordSRV version 1.18.4** and I have a server with **magma-based** mods.

The problem I have is that the channel I defined where the server console is only shows a verse and then no longer show any content from the console.

The console on discord does not freeze since I can write commands but the texts are not displayed.

In the following image I will demonstrate the problem

**when a message is displayed:**

![ejemplo](https://user-images.githubusercontent.com/63019055/80781340-f9e5aa00-8b3f-11ea-8a28-e479e9fe7c02.png)

**message displayed on the console**:

![linea que se muestra](https://user-images.githubusercontent.com/63019055/80781363-09fd8980-8b40-11ea-9329-4274f27e36cc.png)

**the console if it reacts with discord messages**:

![la consola funciona](https://user-images.githubusercontent.com/63019055/80781453-547f0600-8b40-11ea-9b93-ea0eba061af3.png)

Minecraft mods 1.12.2 magma fundation: https://magmafoundation.org

Plugin DiscordSRV version 1.18.4: https://www.spigotmc.org/resources/discordsrv.18494/

**Comment by Scarsz** [comment]
The errors you provided aren't for DiscordSRV.

**Comment by DeathSmurf** [comment]
@Scarsz 
If I understand that the problem in red is not from the DiscordSRV plugin, I have that problem from long before **(it has always been there)**, what I was referring to was that this problem is the only line of text that is seen in the discord console.

**Comment by Vankka** [comment]
Am I understanding this correctly that some messages appear in the console channel but some don't?
This could be a problem where a different logger is used, DiscordSRV's console channel relies on log4j's appenders

**Comment by DeathSmurf** [comment]
Already, I tried downloading the latest version of magma and did the basic configuration procedures and started the server, I did not put any mod on it and I only put the DiscordSRV plugin.

The message channel works properly, the problem happens with the channel where the server console is, it does not show any line of text but it does react to the commands that I write in the channel.

Taking into account the previous test I did with the server I use, it only showed me an error line in the console channel, which makes me think that it only shows those lines of text error and not the others.

**Comment by DeathSmurf** [comment]
@Vankka 
**I wouldn't know if server magma is based relies on log4j's appenders**

**Comment by DeathSmurf** [comment]
I really like your plugin and I would like to implement it on my server, don't you have a solution or give me a recommendation?

**Comment by Vankka** [comment]
Issue might be with the server software, based on these details. Unless you've changed any of the console settings that would filter messages sent in the console channel

**Comment by AsesinaGatitos** [comment]
I have a magma server I present the same problem and I don't know how to solve it, i**t only shows me some lines of text**. :(
