### ISSUE TITLE
Error when stopping the server

### ISSUE THREAD

**Issue by TheoRetisch1** [DiscordSRV/DiscordSRV#703]
When the server stops, the following error always appears in the log: https://pastebin.com/s5TZ1bTp
What could be the reason for that?
What other information can I provide?

Paper 1.15.2 232 
DiscordSRV - 1.19.0-SNAPSHOT-1588401892

**Comment by Vankka** [comment]
This has been fixed, development builds available @ https://snapshot.discordsrv.com

**Comment by TheoRetisch1** [comment]
Thanks :)
