### ISSUE TITLE
Suddenly stopped loading

### ISSUE THREAD

**Issue by chickenmcjesus** [DiscordSRV/DiscordSRV#710]
DiscordSRV was working fine on one of my spigot servers up until just recently I began to get this error:

DiscordSRV failed to load properly: Expected a github.scarsz.discordsrv.dependencies.google.gson.JsonObject but was github.scarsz.discordsrv.dependencies.google.gson.JsonPrimitive. See https://bin.scarsz.me/ba95a6a5-ff72-4366-aed5-4a11af4b6822#7edUNrIOVAVndZM2YaRoLpiHXkF9ZOP0 for more information.

I'm running a Bungeecord network and DiscordSRV works on all of my other spigot servers.

Debug report:
https://bin.scarsz.me/43c28b36-8479-4f00-ae8d-323406649437#Hk9LShHu1CVR8XeDyYyw8ZWypVNlZqsI

Any ideas?

**Comment by Vankka** [comment]
your linked_accounts.json is broken
