### ISSUE TITLE
Webhook pings everyone

### ISSUE THREAD

**Issue by Heath123** [DiscordSRV/DiscordSRV#712]
When `Experiment_WebhookChatMessageDelivery` is set to `true` is it possible to ping @everyone from Minecraft chat. `DiscordChatChannelCutPhrases` seems to be ignored. It should use the Allowed Mentions object to block this:
https://discord.com/developers/docs/resources/webhook#execute-webhook-jsonform-params

**Comment by Vankka** [comment]
Already fixed in development builds. https://snapshot.discordsrv.com

**Comment by Vankka** [comment]
Duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/528

**Comment by Heath123** [comment]
Ah, thank you! I assumed that any issue about this would still be open so that's why I added a duplicate, sorry.
