### ISSUE TITLE
Discord to Minecraft Console Error

### ISSUE THREAD

**Issue by comonier** [DiscordSRV/DiscordSRV#713]
https://pastebin.com/eZ7PB3m2

**Comment by comonier** [comment]
the owner of ultimatechat give a solution

old:
br/net/fabiozumbi12/UltimateChat/Bukkit/UltimateFancy

new:
br/net/fabiozumbi12/UltimateChat/Bukkit/util/UltimateFancy

can update pls ?

the rook discordsrv > ultimatechat

**Comment by Vankka** [comment]
*sigh* this is just a big mess

**Comment by Vankka** [comment]
https://snapshot.discordsrv.com

**Comment by comonier** [comment]
> https://snapshot.discordsrv.com

ty very muth 😍
