### ISSUE TITLE
Ability to move linked players in voice channels using commands

### ISSUE THREAD

**Issue by diskotekastar** [DiscordSRV/DiscordSRV#716]
Good day,

please add the command "/discord (mc nick) (voice chanel id)", if the player was linked to a discord, it would move over his ID.

Thanks for reading, it would help me a lot if it was added.

PS. I am sorry for my English

**Comment by Vankka** [comment]
what do you mean by "move over his ID"

**Comment by diskotekastar** [comment]
I mean move that user

**Comment by PCelestia** [comment]
seems like they want a command ingame to move people to/from voice channels in discord

**Comment by diskotekastar** [comment]
yes

**Comment by diskotekastar** [comment]
Demonstration:

player with MC named TonyasCZ and DC named ᴛᴏɴʏ:
executes the command: "/discord link"
-> his account will be linked to DC "{" 378866709282553866 ":" 8b83990a-4f3e-4a44-b775-5552cc8088ee "}"
-> TONY joins a voice room

user in the game with "discordsrv.voice.move" permission:
executes command: "/discord moove <MC username / UUID> <voice room ID>"

**Comment by Scarsz** [comment]
Won't be implemented
