### ISSUE TITLE
Plugin holds up shutdown

### ISSUE THREAD

**Issue by ice-fly** [DiscordSRV/DiscordSRV#717]
Hello, it is my belief that the way your plugin is coded that sometimes the server fails to restart. I'm running `git-Paper-321` and `DiscordSRV v1.18.4`.
I notice I often have to interact with the console for the server to fully shutdown.

<details>
  <summary>Plugins</summary>
    
  ```
  Plugins (22): AsyncWorldEdit, AutoRestart*, ChopTree2, ClaimslistClassifier, DiscordSRV, dynmap*, Dynmap-GriefPrevention*, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsProtect, EssentialsSpawn, GriefPrevention, LuckPerms, MineableSpawners, OreAnnouncer, ProtocolLib, SnowDrift*, SnowierSnow, Vault, WorldEdit, WorldGuard
  ```
  
</details>

<details>
 I'll issue the stop command... 
  <summary>Console</summary>

  ```
  (world saves)
  ...
  [19:56:20 INFO]: Flushing Chunk IO
  [19:56:20 INFO]: Closing Thread Pool
  [19:56:20 INFO]: Closing Server
  ```
  
  The server then hangs until I interact with the console...
  Only after interacting does it show:

  ```
  [19:56:41 ERROR]: [DiscordSRV] Could not send message to channel TC:server(690273186977153191): The Requester has been shutdown! No new requests can be requested!
  ```

  ...Then it proceeds to restart.

</details>

**Comment by Vankka** [comment]
Is it on a panel like Multicraft or Pterodactyl?
By "interact" do you mean like sending a command or?

**Comment by ice-fly** [comment]
This isn't a cpanel but rather a command line console window. *(in this case powershell)*
`java -Xms21000M -Xmx21000M -jar paper.jar -nogui --nojline`
By interact I mean if i type a command or just hit enter the console proceeds. It's like java isn't closing until it's prodded.

**Comment by Vankka** [comment]
That to me sounds like the powershell window is in "select mode" (or "QuickEdit Mode") (when you click inside the window it tries to select characters), and pressing a key is taking it out of select mode

**Comment by ice-fly** [comment]
Just disabled... Will re-open if issue doesn't resolve itself
