### ISSUE TITLE
Chat not sending 

### ISSUE THREAD

**Issue by kiozix** [DiscordSRV/DiscordSRV#718]
hello i use discordsrv and townychat 

i try to restart my server 
i use this build DiscordSRV-Build-1.18.4
i turn debug mode on 2 debug+log
my debug log https://bin.scarsz.me/90e8651d-0c89-4611-bbb5-a6766c67d922#JZibYJW0DvKAzvkB5CDaNEvqSAm86bfw

if lack of information I will send you well

Thanks

**Comment by Vankka** [comment]
`global` -> `general` in `Channels`
