### ISSUE TITLE
warning that gets spammed

### ISSUE THREAD

**Issue by Duivelbryan** [DiscordSRV/DiscordSRV#721]
[OkHttp https://discordapp.com/.../WARN]: [DiscordSRV] [JDA] Encountered 429 on route /channels/(mychannel number)

this gets spammed alot. it used to work fine a month? ago

nothing changed in the server files other then a update to the latest spigot.

it still works though. it still sends messages to discord

**Comment by Scarsz** [comment]
https://github.com/DiscordSRV/DiscordSRV/issues/719
