### ISSUE TITLE
Warning message spammed in console.

### ISSUE THREAD

**Issue by Weasel-Beans** [DiscordSRV/DiscordSRV#723]
I've been getting this message spammed in my server console lately:

`>.... [03:01:07 WARN]: [github.scarsz.discordsrv.dependencies.jda.internal.requests.RateLimiter] Encountered 429 on route /channels/567206235355611139`

https://timings.aikar.co/?id=9a3556ff8f1f408d8972a44ff08b6dc3

**Comment by Scarsz** [comment]
https://github.com/DiscordSRV/DiscordSRV/issues/719
