### ISSUE TITLE
New error. Spamming 429 on console

### ISSUE THREAD

**Issue by Louploup31** [DiscordSRV/DiscordSRV#724]
It's not a duplicate, 
it starts again
[WARN github.scarsz.discordsrv.dependencies.jda.internal.requests.RateLimiter - Encountered 429 on route /channels/]

I delete discordsrv from my server, this spam my channel.

**Comment by underscore11code** [comment]
Yes, this is a duplicate. See #719, specifically [this](https://github.com/DiscordSRV/DiscordSRV/issues/719#issuecomment-636137387) comment for a solution.

**Comment by Louploup31** [comment]
I did what there is to mark but it does not fix the problem

**Comment by Louploup31** [comment]
it's not a solution, 
it's just to hide the problem

**Comment by Scarsz** [comment]
This is a duplicate.
