### ISSUE TITLE
Warn Message on Server

### ISSUE THREAD

**Issue by Chaosvanguard** [DiscordSRV/DiscordSRV#727]
My console is constantly getting spammed with these messages.

> [12:24:57] [OkHttp https://discordapp.com/.../WARN]: [OkHttp https://discordapp.com/...] WARN github.scarsz.discordsrv.dependencies.jda.internal.requests.RateLimiter - Encountered 429 on route /channels/711374536603598849

> [12:24:57] [OkHttp https://discordapp.com/.../WARN]: [OkHttp https://discordapp.com/...] WARN github.scarsz.discordsrv.dependencies.jda.internal.requests.RateLimiter - Encountered 429 on route /channels/711374496547864686

**Comment by Vankka** [comment]
Duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/719
