### ISSUE TITLE
429 Warning keeps happening.

### ISSUE THREAD

**Issue by tytech038** [DiscordSRV/DiscordSRV#729]
Hello. This [OkHttp https://discordapp.com/.../WARN]: [DiscordSRV] [JDA] Encountered 429 on
 route /channels/713582437728256082 keeps happening. Is it bad? If so. how do I fix it? Thank you!
![Screen Shot 2020-05-30 at 3 29 03 PM](https://user-images.githubusercontent.com/62194272/83338465-5399db00-a28a-11ea-9f7b-5657f3542cc6.png)

**Comment by Scarsz** [comment]
https://github.com/DiscordSRV/DiscordSRV/issues/719, update to dev builds
