### ISSUE TITLE
UnexpectedCharacterException: null

### ISSUE THREAD

**Issue by Jochyoua** [DiscordSRV/DiscordSRV#730]
![image](https://user-images.githubusercontent.com/37064093/83344042-aa71d580-a2c7-11ea-816a-1c80690435dc.png)
ran into this issue with build 1.19.0, what could this mean?

**Comment by granny** [comment]
Change your `ConfigVersion` to `1.19.0-SNAPSHOT` without `/<hash>`, so that the line looks like this:
```yml
ConfigVersion: 1.19.0-SNAPSHOT
```
then restart your server. This is fixed in 1.19.1, which will be released relatively soon. Will close this issue once that happens.

**Comment by Jochyoua** [comment]
That's perfectly fine, thank you very much! I didn't expect that to be the reason of all things :)

**Comment by Vankka** [comment]
1.19.1
