### ISSUE TITLE
Multi Discord Bot will send message duplicated (new VentureChat hook, intended behavior)

### ISSUE THREAD

**Issue by jackyjhih** [DiscordSRV/DiscordSRV#733]
I set 5 discord bot for 5 servers, and put them into the same channel to talk to each other
And I use this value: DiscordChatChannelBlockedIds and DiscordChatChannelBlockBots to block other server's bot to prevent duplicated talk

Chat plugin: venture chat

In version 1.18.4, everything is fine
In the new version 1.19, I use the same settings but got wrong

If i type any word in discord channel, then in the game I will receive 5 duplicated sentence

for example:
if I have 3 bot named A, B and C
In 1.18.4, I type Hello in discord, then In server A will only received sentence from bot A
but in 1.19, I will receive 3 same sentence in games from BOT A, B and C

Thanks a lot

**Comment by Vankka** [comment]
Is the VentureChat channel in "BungeeCord mode"?

**Comment by jackyjhih** [comment]
Yes it is
If you need all setting file
I can paste it

Thank you

**Comment by Vankka** [comment]
The VentureChat hook now supports BungeeCord channels in a way that all the messages are forwarded to each server, just as you described

**Comment by jackyjhih** [comment]
yeah
but in 1.18.4, i can use both venturechat with bc mode and discordsrv
message can broadcast to every server and discordsrv will not duplicated sent the message

**Comment by Vankka** [comment]
We've added a way to 'revert' to the old system, please grab the latest development build from https://snapshot.discordsrv.com & add `VentureChat-Bungee` to `DisabledPluginHooks` @jackyjhih

**Comment by jackyjhih** [comment]
Thanks a lot, I will try it
