### ISSUE TITLE
long error dump

### ISSUE THREAD

**Issue by FenrisWheel** [DiscordSRV/DiscordSRV#739]
Hello, I'm having an issue where every few minutes this error repeats in console. I am using the latest build.

https://pastebin.com/7niEUmed 
Pastebin link to the error message from logs above.
Any help or input is appreciated.

**Comment by Vankka** [comment]
did you reload DiscordSRV?

**Comment by FenrisWheel** [comment]
I did, before doing some research and realizing such was not the right thing to do. I've uninstalled and reinstalled the plugin and done all I can think of to try to fix it. Do you have any ideas of what else I can do?

**Comment by Vankka** [comment]
you can stop reloading & restart..?
