### ISSUE TITLE
JDA executing requests after plugin has been disabled

### ISSUE THREAD

**Issue by BboyZeroOne** [DiscordSRV/DiscordSRV#743]
Not too sure what this is, but I'm using the latest version of DiscordSRV 1.19.0 on PaperSpigot 1.15.2 (328). Please take a look.

https://pastebin.com/xU9VNWRZ

**Comment by Vankka** [comment]
Full log please

**Comment by BboyZeroOne** [comment]
I believe this is the full log.

https://pastebin.com/tb0KS3uA

**Comment by Scarsz** [comment]
should be fixed now, test with https://snapshot.discordsrv.com
