### ISSUE TITLE
multiple chat channels for one server

### ISSUE THREAD

**Issue by soshimee** [DiscordSRV/DiscordSRV#744]
Is there a way to have multiple linked chat channels on one server? I'm making a network of servers and it's so frustrating when I can't make multiple chat channels for one server.

**Comment by Scarsz** [comment]
Didn't mean to close the issue, my bad, but yes. It's supported if you have a chat plugin that supports multiple channels.

**Comment by soshimee** [comment]
What do you mean by "a chat plugin that supports multiple channels?"

**Comment by Scarsz** [comment]
...I mean a chat plugin that supports multiple channels. Exactly as it sounds. [VentureChat](https://www.spigotmc.org/resources/venturechat.771/) is one.
