### ISSUE TITLE
Request.

### ISSUE THREAD

**Issue by Turbojcat** [DiscordSRV/DiscordSRV#746]
Hei im here to requesting a new DiscordSRV plugin. 
im looking for a plugin like this so only send out to the discord bot online players ex: survival: 100 of 1000 online. or cusrom orline/offline message
im usind discordSRV on all servers for concole log on discord and to send out IP on the bot. 
and its need to be able to have a bot token. i'll need trhis type plugin asap if its posible. 
and a join and leave chat for discord where it only send join and leave message on players so joins and leaves. 
Pleace contact me on discord Dreamie#6038

**Comment by Scarsz** [comment]
I have no idea what to make of this besides having a customizable status. You can use PlaceholderAPI in the bot status just fine.
