### ISSUE TITLE
DiscordSRV Chat not working

### ISSUE THREAD

**Issue by Terran31** [DiscordSRV/DiscordSRV#748]
OK so i talked to _11 on the Discord Support channel and we can find any issues or problems but Minecraft to Discord works, Discord ot minecraft does not work i get a error sent in chat saying "Unknown command. Type "/help" for help." The Staff chat does not work either. I am getting 0 error's in the console and when debug is turned on and the Discord Support Bot shows that the debug is working perfectly.  I dont know what to do i was instructed to post this as a issue, ive attempted to to run on the lastest release and dev build but nothing works ive disabled and removed CMI but nothing works, and i dont have any other plugins that alter the chat beside CMI, DiscordSRV StaffChat, and PlacholderAPI.

**Comment by underscore11code** [comment]
Allright you just said "it wasn't working", not that it was responding with `Unknown Command`, which would have been good info to share. That means you've linked the console channel to your chat channel.

**Comment by Terran31** [comment]
I did say that it is responding with unknown command

**Comment by Terran31** [comment]
![ha told you](https://user-images.githubusercontent.com/66493095/83917756-095aa300-a73d-11ea-8a0f-417f331102c8.png)

**Comment by granny** [comment]
`DiscordChatChannelConsoleCommandPrefix` was set to `""` which meant that all messages they sent was being registered as a console command.
