### ISSUE TITLE
[1.19.0] DiscordSRV avatar bug

### ISSUE THREAD

**Issue by fathomscript** [DiscordSRV/DiscordSRV#750]
I've already configured the plugin here, but unfortunately when it comes to entering the server and showing your name and your minecraft avatar, only steve appears, and I don't know how to fix it

Print: https://prntscr.com/suvtct

My minecraft is original!

**Comment by fathomscript** [comment]
Sorry, but your discord server is a puzzle

**Comment by fathomscript** [comment]
If you can help me, I really don't know what I need to do

**Comment by Scarsz** [comment]
You’re running a cracked servers. By default the avatars use UUIDs. Change it to usernames.

**Comment by enfie01s** [comment]
Same issue fr me. No error messages to show you. My server is default as is my client (no cracks in sight)

**Comment by Scarsz** [comment]
> Same issue fr me. No error messages to show you. My server is default and I have the fabric client installed. No cracks though.

https://discordsrv.com/discord #support
