### ISSUE TITLE
DiscordSRV failed to load properly - Expected JsonObject but was JsonPrimitive

### ISSUE THREAD

**Issue by falkke** [DiscordSRV/DiscordSRV#753]
`[mar., 9. juin 2020 16:58:08 CEST INFO] [DiscordSRV] Not using JDBC, one of host/port/database was default
[mar., 9. juin 2020 16:58:08 CEST WARN] github.scarsz.discordsrv.dependencies.google.gson.JsonSyntaxException: Expected a github.scarsz.discordsrv.dependencies.google.gson.JsonObject but was github.scarsz.discordsrv.dependencies.google.gson.JsonPrimitive
[mar., 9. juin 2020 16:58:08 CEST WARN]     at github.scarsz.discordsrv.dependencies.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:897)
[mar., 9. juin 2020 16:58:08 CEST WARN]     at github.scarsz.discordsrv.dependencies.google.gson.Gson.fromJson(Gson.java:927)
[mar., 9. juin 2020 16:58:08 CEST WARN]     at github.scarsz.discordsrv.dependencies.google.gson.Gson.fromJson(Gson.java:892)
[mar., 9. juin 2020 16:58:08 CEST WARN]     at github.scarsz.discordsrv.dependencies.google.gson.Gson.fromJson(Gson.java:841)
[mar., 9. juin 2020 16:58:08 CEST WARN]     at github.scarsz.discordsrv.dependencies.google.gson.Gson.fromJson(Gson.java:813)
[mar., 9. juin 2020 16:58:08 CEST WARN]     at github.scarsz.discordsrv.objects.managers.AccountLinkManager.<init>(AccountLinkManager.java:56)
[mar., 9. juin 2020 16:58:08 CEST WARN]     at github.scarsz.discordsrv.DiscordSRV.init(DiscordSRV.java:584)
[mar., 9. juin 2020 16:58:08 CEST WARN]     at java.lang.Thread.run(Unknown Source)
[mar., 9. juin 2020 16:58:09 CEST ERROR] [DiscordSRV] DiscordSRV failed to load properly: Expected a github.scarsz.discordsrv.dependencies.google.gson.JsonObject but was github.scarsz.discordsrv.dependencies.google.gson.JsonPrimitive. See https://bin.scarsz.me/d6e8da76-94b9-42e9-afd4-b5cd75c417d9#byYge0al5BTeZExd7uuIO7f0Rq6HXMRE for more information.`

**Comment by falkke** [comment]
I just update from 1.18.4 to 1.19.0 and this happened

**Comment by Vankka** [comment]
delete linked_accounts.json & restart
