### ISSUE TITLE
Console Error on server shutdown. Paper 346

### ISSUE THREAD

**Issue by DiegoDaniel** [DiscordSRV/DiscordSRV#755]
11.06 04:00:23 [Server] ERROR Nag author: 'Scarsz' of 'DiscordSRV' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.

**Comment by Vankka** [comment]
Related patch in paper: https://github.com/PaperMC/Paper/blob/e224f0bdabd2d8d8591a8fb2566debe44d17a5ae/Spigot-Server-Patches/0516-Wait-for-Async-Tasks-during-shutdown.patch

**Comment by Vankka** [comment]
Should be fixed in development builds, https://snapshot.discordsrv.com
