### ISSUE TITLE
DeluxeChat

### ISSUE THREAD

**Issue by Encon192** [DiscordSRV/DiscordSRV#760]
Our server has had to swap from Venturechat to Deluxechat due to the factions plugin we are using not being supported by Venturechat(Or any other chat plugins). I was hoping to ask you to look into Deluxechat and any ability to get DiscordSRV to work with it. Currently, I am still able to use the console and start/stop/watchdog but I would like to get some functionality back for server chat and network chat. I am going to try to gerry rig it a bit, but there are no "channels" in the chat plugin so I doubt I will be able to get any of the chat working.

**Comment by Vankka** [comment]
Duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/233 / support
