### ISSUE TITLE
Radius Voice chat

### ISSUE THREAD

**Issue by StoneMcYT** [DiscordSRV/DiscordSRV#767]
Im thinking of you have to be in a certain radius of like an area. Could use a command like
/DiscordSrv set voicechat ~ ~ ~ voiceChatName r=2

**Comment by Vankka** [comment]
This doesn't make sense

**Comment by HelveticaToast** [comment]
> Im thinking of you have to be in a certain radius of like an area. Could use a command like
> /DiscordSrv set voicechat ~ ~ ~ voiceChatName r=2

??????????????????????????
