### ISSUE TITLE
View a snippet of a channel via in-game command

### ISSUE THREAD

**Issue by TomLewis** [DiscordSRV/DiscordSRV#772]
Ahoy

I would love for a way to show my discord changelogs in-game in the form of either a command/chat and/or opening up in a book.

Something like;
`/discord viewchannel ID` which we can bind to an alias in commands.yml to have /changelogs to display our changelogs in-game and announcements.

**Comment by Vankka** [comment]
I feel like this would be quite limited,
- Discord channels consist of many messages, that can be up to 2000 characters, which would fill up a Minecraft client's chat veryy fast
- Discord messages aren't colored, they might look out of place shown in-game (being black/white/gray)

**Comment by FrozenBeard** [comment]
> 
> 
> I feel like this would be quite limited,
> 
>     * Discord channels consist of many messages, that can be up to 2000 characters, which would fill up a Minecraft client's chat veryy fast
> 
>     * Discord messages aren't colored, they might look out of place shown in-game (being black/white/gray)

- Same as every blog post thats ever been made, you have an "excerpt" of the full message, either clicking the message to open up the full message in chat/book, very easily solved. 
- Allow colour formatting upto the server owner, I personally have a colour scheme throughout all my chat that should be standard, I hate it when plugins force you to use their colour system without being able to change it.

Ive been keep changelog channel for years, Ive noticed a lot of other servers started doing this too. its very useful.

**Comment by Scarsz** [comment]
Closing because this is out of the scope of DiscordSRV

This would be better done by a plugin specifically for managing changelogs like this
