### ISSUE TITLE
Compiling problems as dependency

### ISSUE THREAD

**Issue by AlessioDP** [DiscordSRV/DiscordSRV#773]
Hello, I am trying to implement DiscordSRV into my plugin but I have some compile problems:
1. I am using Gradle v6.5
2. The module has been added with compileOnly
3. Normal building only works if I manually add `vankka` & `jcenter` repositories into my `build.gradle`
4. Test cases don't work at all

The error is (this appear when I execute a test case):
`Could not find net.dv8tion:JDA:4.1.1_155`

**Comment by Vankka** [comment]
Paste your repositories here just like they are in your build file please

**Comment by AlessioDP** [comment]
I solved the problem by excluding these packages:
```groovy
compileOnly (group: 'com.discordsrv', name: 'discordsrv', version: project.ext.discordsrv) {
    exclude module: 'MCDiscordReserializer'
    exclude module: 'JDA'
}
```

Now just the DiscordSRV repository is required :)

**Comment by Vankka** [comment]
That isn't a proper solution considering you're going to need JDA for a lot of things, but whatever.

**Comment by AlessioDP** [comment]
Feel free to re-open the issue, I would like to help to fix it because I just solved it with a workaround.

I can let you see the source/more information on Discord if you want :)
