### ISSUE TITLE
Exception on resync

### ISSUE THREAD

**Issue by mben42** [DiscordSRV/DiscordSRV#774]
Hi,

I have an exception on resync in 1.16.1: https://pastebin.com/cm3RXNKC

**Comment by Vankka** [comment]
The mysql driver on your server isn't compatible with DiscordSRV, the probably isn't much that can be done about that

**Comment by mben42** [comment]
What are MySQL requirements? I have MariaDB 10.3.22, that is the last version available in Debian 10 (newly installed a few days ago).

**Comment by Vankka** [comment]
by driver I mean the JDBC driver for Java, not the database itself, some plugin may be including a ancient mysql jdbc driver thus causing this error

**Comment by Scarsz** [comment]
Relocated JDBC classes @ https://github.com/DiscordSRV/DiscordSRV/commit/90ecab9c6d8cc187690ae6af07008e388a03b1d4, try again with https://snapshot.discordsrv.com
