### ISSUE TITLE
Version does not indicate which MC version it pertains to

### ISSUE THREAD

**Issue by Lost-Feight** [DiscordSRV/DiscordSRV#775]
as title, so should be simple, the discordSRV version e.g. 1.19.0 doesn't mention in any of the docs which minecraft version e.g. 1.16.1

**Comment by Scarsz** [comment]
Because 1.19.0 wasn't built for 1.16.

**Comment by Lost-Feight** [comment]
and yet, none of the builds mention ANY version of minecraft that they pertain to, is a user supposed to guess, or annoy the community constantly with questions?

**Comment by granny** [comment]
https://get.discordsrv.com/ will give you the latest release
https://snapshot.discordsrv.com/ will give you the latest dev build
That's all the information a user needs. They should always be on the latest build.

**Comment by Lost-Feight** [comment]
so discordsrv is compatible with the newest version of minecraft? or is it untested? or being worked on? these are important details a user needs to know

**Comment by Vankka** [comment]
Yes it does work. The latest version works on MC versions 1.7.9 through 1.15.1 and onwards. There is nothing in DiscordSRV preventing it from working in new versions (usually)
