### ISSUE TITLE
"&" Symbol in usernames bugs out chat.

### ISSUE THREAD

**Issue by KaloHG** [DiscordSRV/DiscordSRV#779]
It seems that having the "&" symbol in your name on discord and typing to In-Game on PaperSpigot 1.16.1 causes your name to be bugged out. 

Example Below: 
In-Game https://media.discordapp.net/attachments/676227440380608574/728413528620269679/unknown.png 
Discord https://i.imgur.com/u6R4LCf.png

Hopefully this is a spigot issue? If so, sorry to bother you guys. Thanks!

**Comment by Scarsz** [comment]
It’s being interpreted as a color code, which the user doesn’t have permission for, thus being removed.
