### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by Fiopon** [DiscordSRV/DiscordSRV#783]
java.lang.NoClassDefFoundError: github/scarsz/discordsrv/dependencies/jackson/annotation/JsonFormat

https://bin.scarsz.me/d029990b-3de0-4825-9d26-65c7aa53769a#PozC1AtQez0RHt2DM2BERiN8qpzcTnWT

DiscordSRV claims that no bot token is supplied, despite the fact there is a live bot token in the config.yml

**Comment by Vankka** [comment]
I've downloaded a jar & contained the class in the error, please try downloading another jar from https://snapshot.discordsrv.com & trying again
