### ISSUE TITLE
Startup and shutdown notification do určitého kanálu

### ISSUE THREAD

**Issue by diskotekastar** [DiscordSRV/DiscordSRV#789]
Hello,

it would be good to add the option to start and shut down notifications to a specific channel.

**Comment by Scarsz** [comment]
All notification messages go to the first defined channel which doesn't necessarily have to be your main chat channel

**Comment by diskotekastar** [comment]
So how do I set up a different channel for power-on and power-off notifications?

**Comment by Scarsz** [comment]
Server start, stop, player advancement/achievement, player join, and player death all go to the same channel. Distinct channels per event isn't something that's implemented.

**Comment by diskotekastar** [comment]
And how do I choose that channel?

**Comment by Scarsz** [comment]
It's the first channel pair that you have in your `Channels` option.
