### ISSUE TITLE
Allow one way group synchronization

### ISSUE THREAD

**Issue by Jozznak** [DiscordSRV/DiscordSRV#791]
Hello, 
For security reasons, it would be very useful if you make possible to disable Discord as authoritative. In this way we only allow Minecraft Sync with Discord roles and they can only be managed through MC. This prevents a lot of possible ways we can be fucked up, but to resume I'll point 2 things: 

First, if a staff get hacked or something, In our mc server, roles can only be managed through the console. But in Discord, as we have admin role, we can actually modify roles, so if a staff gets hacked (It really happens) the hacker could make a real mess and fuck us up.
 
Second and most probable thing to happen. We never really finish to know people. And it could be that a staff decides to fuck up the server giving ranks to all people through discord before leaving or what ever reason he has. Of course, this 2 aspects are not DiscordSRV fault, but if you add this option, it could really help us to prevent this and more things that could happen. Human errors and stupidity... Yeah, we have trust issues now days. And that's why we limit so much how roles are administrated in game. If something happens in Discord with the roles, is not really that bad as there is no money involved, no special items or cosmetics (at least in our case). So it can be easily fixed. But if this happens in our mc server, it would break a lot of things.

So I hope this can be integrated, because it would be really useful for does who have the same concerns than us.
Thanks.

**Comment by Vankka** [comment]
You *could*, put the wrong group names in the config and then grant the actual groups the permission `discordsrv.sync.<wrong group name>`, then group sync would effectively become one-way, thought that's obviously not the cleanest solution

**Comment by Jozznak** [comment]
I will try that, but is there a posibility you take this in consideration?

**Comment by Vankka** [comment]
Considering that there is a valid solution for now, no. In the future there will likely be a way to configure if specific synchronization pairs should be one way

**Comment by Vankka** [comment]
Available on development builds, https://snapshot.discordsrv.com
