### ISSUE TITLE
Option to set primary group rather than secondary groups with LuckPerms

### ISSUE THREAD

**Issue by LewisTehMinerz** [DiscordSRV/DiscordSRV#794]
The current behaviour of DiscordSRV's group synchronization makes it so that a secondary group is assigned to a user based on role sync. However, this is the opposite for the booster sync where it is the primary group that gets set. Is there a possibility for an option to have the primary group of a user be set for roles, just like booster sync, and have them reset to `default` if they lose the role?

**Comment by Vankka** [comment]
use `GroupRoleSynchronizationPrimaryGroupOnly` & configure LP properly with weights or switchprimarygroup

**Comment by LewisTehMinerz** [comment]
I already did and it always sets secondary.

**Comment by Vankka** [comment]
Nope. If it does you've configured LuckPerms wrong

**Comment by LewisTehMinerz** [comment]
`GroupRoleSynchronizationPrimaryGroupOnly` is on and LuckPerms is configured correctly.

![image](https://user-images.githubusercontent.com/8019327/87252169-e7092300-c468-11ea-90d2-d6c4ee18957a.png)

**Comment by Vankka** [comment]
Assuming you haven't changed the configuration for luckperms, that screenshot only shows that you have**n't** configured it correctly

**Comment by LewisTehMinerz** [comment]
If you're talking about the group weights and how LuckPerms determines a primary group, they're configured correctly. What I'm referring to is that `default` is still present. I would've expected that the option would've just set the parent to `sub` and overwrite `default`. DiscordSRV does it for boosters, just not for role sync.

**Comment by Vankka** [comment]
Unless you can prove the Vault is infact returning the right group as the primary, this still stands as a issue that isn't with DiscordSRV.

**Comment by LewisTehMinerz** [comment]
How would you like me to do this? I don't have a plugin on hand that deals with Vault debugging, but I guess I could write one for this purpose.
