### ISSUE TITLE
EntityDeathEvent does not trigger alerts

### ISSUE THREAD

**Issue by donwayo** [DiscordSRV/DiscordSRV#795]
I have been testing a few events to trigger alerts, and I can't get `EntityDeathEvent` to trigger. Bukkit's documentation states that this event should be "[Thrown whenever a LivingEntity dies](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/EntityDeathEvent.html)". In contrast, I tested `EntityDamageEvent` and it does trigger. With my alert code in `alert.yml`:

```
Alerts:
  - Trigger: EntityDeathEvent
    Channel: global
    Embed:
      Enabled: true
      Color: "#ff0000"
      Author:
        Name: "Entity death:  ${entity.name}"
```
My objective with this is to have an alert when Villagers die, but I can't even get the event triggered without conditions. 

Debug output: https://bin.scarsz.me/625d8c22-c1ee-4085-8680-ddeb1c223b36#NhnGqwGB32eUI1r4wtJSd2LS2tZtoY82

**Comment by Vankka** [comment]
Please try again on the latest snapshots - https://snapshot.discordsrv.com

**Comment by donwayo** [comment]
Snapshot works. Thanks @Vankka !

**Comment by v4rl1** [comment]
> I have been testing a few events to trigger alerts, and I can't get `EntityDeathEvent` to trigger. Bukkit's documentation states that this event should be "[Thrown whenever a LivingEntity dies](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/EntityDeathEvent.html)". In contrast, I tested `EntityDamageEvent` and it does trigger. With my alert code in `alert.yml`:
> 
> ```
> Alerts:
>   - Trigger: EntityDeathEvent
>     Channel: global
>     Embed:
>       Enabled: true
>       Color: "#ff0000"
>       Author:
>         Name: "Entity death:  ${entity.name}"
> ```
> 
> My objective with this is to have an alert when Villagers die, but I can't even get the event triggered without conditions.
> 
> Debug output: https://bin.scarsz.me/625d8c22-c1ee-4085-8680-ddeb1c223b36#NhnGqwGB32eUI1r4wtJSd2LS2tZtoY82

Hello, did you manage to make that alert with villagers ? and if so would you be willing to share it ?
