### ISSUE TITLE
Reaction command

### ISSUE THREAD

**Issue by diskotekastar** [DiscordSRV/DiscordSRV#797]
Hello,
I would like the possibility of reaction commands to be added

DiscordReactionCommand: {"'!reaction": "response": "command"}

DiscordReactionCommand: {"'!test Player007 hello": "Telling %arg1% to% arg0%": "msg% arg0%% arg1%"}

**Comment by granny** [comment]
Aka you want [DiscordCannedResponses](https://config.discordsrv.com/config/DiscordCannedResponses) to have additional functionality

That's not even valid yaml btw, so it wouldn't work in the first place

**Comment by diskotekastar** [comment]
And somehow it would not be possible to implement in the plugin?

**Comment by Vankka** [comment]
This would be possible, doesn't sound something that many people would use though

**Comment by diskotekastar** [comment]
In my opinion, it would be used by a lot of people, because it would be enough to write "! Setrank <mc nick> rank" on the discord and it would execute the command "/ pex user% arg0% group set% arg1%" example:! Setrank tonysek administrator "and execute this would be the command "/ pex user tonysek group set administrator" The example in the config would look like this: "DiscordReactionCommand: {" '! setrank ":" pex user% arg0% group set% arg1% "}"

**Comment by granny** [comment]
How is this different from the available [DiscordChatChannelConsoleCommand . . .](https://github.com/DiscordSRV/DiscordSRV/blob/master/src/main/resources/config/en.yml#L152-L174) options? e.g. `!c pex user tonysek group set administrator` 
Your first example is also accomplished with this, `!c msg Player007 hello`

Expanding on [DiscordCannedResponses](https://config.discordsrv.com/config/DiscordCannedResponses) is definitely a good idea, but what you want is kinda already doable with the features we have available.

**Comment by Scarsz** [comment]
Closing, something similar to this might be implemented in the future
