### ISSUE TITLE
Allow 257+ character messages to be sent at a time from discord

### ISSUE THREAD

**Issue by Lilithvia** [DiscordSRV/DiscordSRV#801]
Often in discord, you end up being much more inspired to write about a topic that's currently in discussion in the server chat.
Currently, you have to end up checking to see if your message exceeded 256 characters and manually break it up, which takes up time and effort that is unnecessary on the user's side.

You might be able to store each word in a variable, and detect when the letter count exceeds 256, then break at the space before the word that exceeds the count, then reset the letter counter, continue testing the rest of the message to see if it also exceeds 256, rinse and repeat until the whole message has been sent.

**Comment by Vankka** [comment]
Where are you getting this 256 number?

**Comment by Vankka** [comment]
`DiscordChatChannelTruncateLength` in the config.yml
