### ISSUE TITLE
Unexpected packet received during server login process/paper

### ISSUE THREAD

**Issue by Spildunky** [DiscordSRV/DiscordSRV#804]
Got this bug when we updated to the latest update of discord. Had to remove it and go to the second newest version of the plugin for it to work.
![2020-07-20_13 13 34](https://user-images.githubusercontent.com/30461082/87905873-d843f100-caa4-11ea-869d-73e9b7410923.png)

**Comment by Spildunky** [comment]
Happened to everyone when trying to join the server.

**Comment by Scarsz** [comment]
Need specific plugin versions

**Comment by Spildunky** [comment]
1.19.1 produces that error

**Comment by Vankka** [comment]
Please try again with a dev build - https://snapshot.discordsrv.com

**Comment by Vankka** [comment]
Fixed in release 1.20.0
