### ISSUE TITLE
SuperVanish hook doesnt show join message.

### ISSUE THREAD

**Issue by HelveticaToast** [DiscordSRV/DiscordSRV#805]
not sure if this would be a bug or a suggestion.

i have AutoVanishOnJoin enabled in my supervanish config, when i join the server, it doesnt show the join message in discord srv, however, when i unvanish, it also doesnt show the join message, but when i leave, it does show the join message.

**Comment by HelveticaToast** [comment]
just disabled the plugin hook, it is still doing the same thing.

**Comment by granny** [comment]
Please join the discord server for more help with your issue.
https://discordsrv.com/discord

**Comment by Vankka** [comment]
Fake join/leave messages aren't supported currently, https://github.com/DiscordSRV/DiscordSRV/issues/220
DiscordSRV will not broadcast join/leave messages if you're vanished when you join/leave. If you have the `discordsrv.silentquit` / `discordsrv.silentjoin` permissions it will also not broadcast them
