### ISSUE TITLE
Suggestion (If not already implemented): Separate MC to Discord chat and server event logs like joining and leaving and achievements

### ISSUE THREAD

**Issue by Shadownite64** [DiscordSRV/DiscordSRV#808]
This would be a nice feature to have, so that you can have a discord channel where only the chat is logged. If it is already implemented can you please tell me how to do it.

**Comment by granny** [comment]
[Already a thing. Read comments, they are useful.](https://github.com/DiscordSRV/DiscordSRV/blob/master/src/main/resources/config/en.yml#L12)
```yml
# The first channel pair specified in this config option will be the "main" channel, used for sending player joins/quits/deaths/achievements/etc
#
Channels: {"global": "000000000000000000"}
```
Example below:
```yml
Channels: {"events": "000000000000000000", "global": "000000000000000000"}
```

**Comment by Shadownite64** [comment]
So, will it put MC-to-Discord chat in a different channel then if I set it up like that?
