### ISSUE TITLE
[BUG] Players get DC roles removed and get it again (same role).

### ISSUE THREAD

**Issue by broken1arrow** [DiscordSRV/DiscordSRV#812]
It remove and set same roll time and time again (and the player is online ).

I try on DC, but get no replay. So i put it up in GitHub, because it a serious bug. 

https://bin.scarsz.me/5a6c29cd-0a4a-44ff-bc5d-76e87a8e75c1#MBNHkIj3MDWanw6JvYWs97x6mlDz6o6T

**Comment by GreemDev** [comment]
What?

**Comment by broken1arrow** [comment]
> 
> 
> What?

We have a "player" roll in DC and discordSRV remove the roll and give the roll again (and dont stop do it). 

even if the player not change group in minecraft.

**Comment by GreemDev** [comment]
This seems like a support issue. Ask in the support channel in the Discord.

**Comment by broken1arrow** [comment]
I try 

> 
> 
> This seems like a support issue. Ask in the support channel in the Discord.

I try, but get no replay. I guess Github is when it confirm it is a bug. report it on Github.
