### ISSUE TITLE
Set Main Discord

### ISSUE THREAD

**Issue by Bbro122** [DiscordSRV/DiscordSRV#813]
Whenever you setup DiscordSRV it automatically sets the main discord to whatever the first logging channel is in, however when using chat logs in a staff-only discord, and wanting the bot to change nicknames and apply roles in the main server discord, its not possible and causes issues with the entire discord linking setup

simply adding a guild id option to the config would make this plugin much easier to work with

**Comment by Scarsz** [comment]
Nothing stops you from having a dummy first channel pair in your `Channels` config to accomplish the same task.

**Comment by Bbro122** [comment]
"The first channel pair specified in this config option will be the "main" channel, used for sending player joins/quits/deaths/achievements/etc"

**Comment by Scarsz** [comment]
I see what you're getting at with that comment but I fail to see the use case. Can you explain a bit more why this would be beneficial to you?

**Comment by Bbro122** [comment]
My server uses the 2 separate discords both the staff server and the main discord, we use the chat logs in our staff server to make sure that if a problem occurs that we can go back and check the logs of the incident, however we also want to be able to link discord accounts for verification and for donor ranks, with the way its setup we wouldn't be able to see join/leave/server status updates with both the staff server and the main server getting logs, and it would be extremely inconvenient to have to go to a completely different discord server just to see information that should be available in the main chat logs
