### ISSUE TITLE
Team colors no longer showing on the chat on Paper because of the sync PlayerChatEvent being listened to by alerts

### ISSUE THREAD

**Issue by MIGI10** [DiscordSRV/DiscordSRV#815]
Hi, before installing DiscordSRV, player names in the chat and in the tab player list were coloured with /team but now they all appear white in the chat. In the tab player list they are still colored but not anymore in the chat... Is there a solution?

Thank you!

**Comment by Vankka** [comment]
DiscordSRV does not alter chat.

**Comment by Prof-Bloodstone** [comment]
It looks like it alters chat - and also puts chat into sync mode. See https://github.com/PaperMC/Paper/issues/4142#issuecomment-676702592

**Comment by Vankka** [comment]
> It looks like it alters chat

It does not.
> and also puts chat into sync mode. his seems to be caused by the alert system implemented.

Is correct however

**Comment by Vankka** [comment]
This should be fixed on the latest development build, https://snapshot.discordsrv.com
