### ISSUE TITLE
Error on latest snapshot

### ISSUE THREAD

**Issue by mihionmc** [DiscordSRV/DiscordSRV#817]
Hi!

I get this on start up after update: 
https://pastebin.com/m1Zim7ia

I use java 11 - papermc 1.16.1

**Comment by Scarsz** [comment]
Reproduce with snapshots https://snapshot.discordsrv.com

**Comment by Vankka** [comment]
Please test this with the latest snapshot, I made a change that might fix it - https://snapshot.discordsrv.com
