### ISSUE TITLE
Username Not Escaped in Advancement Messages

### ISSUE THREAD

**Issue by delbertina** [DiscordSRV/DiscordSRV#823]
Join, leave, first join, death, and chat msgs have underscores in the username escaped. The advancement messages do not for some reason. This has been a 'bug' for a while, just haven't been able to get an instance and report before the next plugin update. Currently running 1.19.1 on 1.16.1 Paper : )

Config Value
> MinecraftPlayerAchievementMessagesFormat: ":medal: **%username% earned advancement %achievement%!**"

Result
![image](https://user-images.githubusercontent.com/6349928/89133145-5362c980-d4df-11ea-9adc-d817dea4a39d.png)

**Comment by Vankka** [comment]
Fixed in development build, https://snapshot.discordsrv.com
