### ISSUE TITLE
Pass /say

### ISSUE THREAD

**Issue by phemmer** [DiscordSRV/DiscordSRV#824]
Messages sent from the console (using `/say ...`) don't show up in Discord.

Note that I'm not referring to the one configured by `DiscordConsoleChannelId`, but the normal chat channel.

**Comment by Vankka** [comment]
This could be done with alerts or a alias in commands.yml

**Comment by ryantheleach** [comment]
It could be, but I think it's a pretty fair expectation that things said as chat messages, in chat, get linked.

**Comment by Vankka** [comment]
Easier said than done

**Comment by Vankka** [comment]
Merging with https://github.com/DiscordSRV/DiscordSRV/issues/116
