### ISSUE TITLE
Messages from players with nicknames that are formatted with code blocks have random backslashes in them.

### ISSUE THREAD

**Issue by partyp770** [DiscordSRV/DiscordSRV#825]
![image](https://user-images.githubusercontent.com/31494143/89195762-3aa5f280-d577-11ea-8586-6ed3df4f3bef.png)
Attached is what I'm referring to. I believe this is an issue with DiscordSRV, as there are no backslashes in any config entries from what I can see. This is what is written in messages.yml:

![image](https://user-images.githubusercontent.com/31494143/89196719-991fa080-d578-11ea-94b4-17e20c2bb0ab.png)

The build of DiscordSRV I'm using is DiscordSRV-Build-1.19.0-SNAPSHOT-1590803498.jar
This build may be fairly outdated, since I haven't started the server in a while.

![image](https://user-images.githubusercontent.com/31494143/89196882-d5eb9780-d578-11ea-9b16-8b80416ce3a8.png)

**Comment by Scarsz** [comment]
Make sure this is reproducible on the latest dev builds

**Comment by Vankka** [comment]
Yes it would be since the usernames sre always escaped & stuff inside of code blocks doesn't need to be escaped

**Comment by Vankka** [comment]
On the latest dev build (https://snapshot.discordsrv.com) use %displaynamenoescapes% or %usernamenoescapes%

**Comment by Vankka** [comment]
Added in release 1.20.0
