### ISSUE TITLE
How to Make New Command with variables

### ISSUE THREAD

**Issue by DaeHyeoNi** [DiscordSRV/DiscordSRV#827]
Hello i'm trying to create a new discord command
in config.yml files DiscordCannedResponses section

I type it in "!uptime": "%uptimemins% Min"
However, the variable is not supported for message display.
Is there a way to make this possible?

I want to make it possible if it's impossible.
You'll be able to do a little more variety of moves.

**Comment by underscore11code** [comment]
1. Install PlaceholderAPI if you haven't already

2. Run `/papi ecloud download server` and `/papi reload`

3. Use `%server_uptime%`

**Comment by DaeHyeoNi** [comment]
@underscore11code It really helped me a lot of help.
Using PlaceholderAPI implement many different actions.

Thank you very much.
