### ISSUE TITLE
Split voice strength to vertical & horizontal in the config

### ISSUE THREAD

**Issue by JaHollYT** [DiscordSRV/DiscordSRV#828]
I want to request 2 config Options for the Voice Strenght:
One Option for the X&Z Value and one for the Y Value.

So that you can say for example players can talk ok one floor in a 12 Block range but only 4 Blocks up/down -- so not on 2 floors.

**Comment by Vankka** [comment]
This will be added in the next version, and is available on our snapshots right now, https://snapshot.discordsrv.com
