### ISSUE TITLE
Option in the config to disable linking feature completely

### ISSUE THREAD

**Issue by CWKevo** [DiscordSRV/DiscordSRV#831]
I'd need this feature because I use the bot DM's for notes and stuff, and it's annoying to always get the message that the "code" is invalid. There should, therefore, be an option in the config to completely turn the linking off because I don't really need it. Or at least the ability to not reply with "Are you sure that's your code? Link codes are 4 numbers long." every time I DM anything to the bot.

Could also be relevant to #348, since it'd be handy to use a channel instead of DMs.

**Comment by GreemDev** [comment]
You're not supposed to run another bot under DiscordSRV's token. There should be no reason you're DMing the bot other than for linking.

**Comment by CWKevo** [comment]
Ah, I see. Thank you.
