### ISSUE TITLE
Problem private chat / discord 

### ISSUE THREAD

**Issue by istarengwa** [DiscordSRV/DiscordSRV#833]
Hello, I have a little problem, the guild channel is displayed on discord, it doesn't do it with any other plugin, I tried to put "Guilds" in the hooks but it didn't change anything, if you ever did an idea to help me I am a taker because the guild chat is a private chat between the players of the same guild

https://zupimages.net/viewer.php?id=20/34/10mn.png

**Comment by istarengwa** [comment]
For me it's a bug, your plugin shouldn't display a private channel on the discord channel, it only does that with this plugin specifically, all my other private channels are not sent to discord by your plugin, why this one if ?

**Comment by Scarsz** [comment]
This isn't a bug. DiscordSRV doesn't *intentionally* send your private channels. The chat messages are not being handled correctly by the other plugins.
