### ISSUE TITLE
Conflicts with McMMO

### ISSUE THREAD

**Issue by Jaynator495** [DiscordSRV/DiscordSRV#834]
When you level up with McMMO with this plugin enabled it kicks the player with an error like this:
![image](https://user-images.githubusercontent.com/13039635/90437277-f2aec180-e086-11ea-907a-44e9e6696a5e.png)

The server was not reloaded, and was only restarted. There is nothing in the console when this happens

**Comment by granny** [comment]
It's a bug that seems to happen randomly with no clear reproducible steps. https://hub.spigotmc.org/jira/browse/SPIGOT-6056
Temporary fix is to just restart the server.
