### ISSUE TITLE
Failed to send message to channel: SSLHandshakeException

### ISSUE THREAD

**Issue by Feneco** [DiscordSRV/DiscordSRV#839]
This bug happens on DiscordSRV **1.19.1**
Minecraft version **1.16.1**, using **paper-135.jar**
Using java 8

`[ERROR] [DiscordSRV] Failed to send message to channel TC:console(616354677797158932): -1: javax.net.ssl.SSLHandshakeException`
`[ERROR]: [DiscordSRV] [JDA] There was an exception while executing a REST request`
[Part of the console output.](https://pastebin.com/Yf9eUNh0) This report will repeat for every channel my discord has and then loop from the beginning.

This bug usually happens after the server is on for a while. It absolutely floods the console and starts using a considerable quantity of processing power and lags the game a little. I have no clue how to reproduce it other than actually waiting until it happens. 

I didn't test if DiscordSVR still works when this bug is happening and I already removed the plugin. It happened more than once: usually the server starts normally and then randomly starts flooding the server logs. It doesn't stop the server outright, but lags it.

**Comment by Feneco** [comment]
```
openjdk version "1.8.0_262"
OpenJDK Runtime Environment (build 1.8.0_262-b10)
OpenJDK 64-Bit Server VM (build 25.262-b10, mixed mode)
```

I think is this what you want. Updated my first comment anyway.

**Comment by Vankka** [comment]
Unsure of what's causing this, some articles point at the TLS version used by Java, is this still happening?

**Comment by Vankka** [comment]
Closing this out for inactivity, message here if it's still happening

**Comment by Zhou-Shilin** [comment]
@Vankka i have the same problem, using java17(1.20.1)
my plugin can send the message normally *but* cannot register splash command due to ssl handshake error

**Comment by Vankka** [comment]
Open a new issue with the full stacktrace
