### ISSUE TITLE
Compatibility with previously created bot?

### ISSUE THREAD

**Issue by Mr-Smarty** [DiscordSRV/DiscordSRV#843]
Can I use this plugin with a bot I've already created, coded, and am hosting? Will it still work with the already coded bot, or do I need to make a new application and bot? Sorry if this has already been answered, and thanks!

**Comment by GreemDev** [comment]
Yes, you need to make a new bot; DiscordSRV does not support or recommend having a bot other than DiscordSRV itself on the same token as it can cause issues (namely the bot being banned if the API's ratelimits are hit too often.)
