### ISSUE TITLE
DiscordSRV Not sending messages in discord or minecraft

### ISSUE THREAD

**Issue by averwhy** [DiscordSRV/DiscordSRV#844]
So i run a 1.16.1 paper (138) server, and i have set up discord srv appropriately. (Token good, channel ids good) Yet when i send messages in minecraft- it doesnt goto discord. Also doesnt work when i send messages to discord, it doesnt goto minecraft. I have deleted the discordsrv folder and let it regen, then put token and ids in without touching values. Why isnt it working? Lmk if you need more info about the server

**Comment by HittmanA** [comment]
What chat plugin are you using? You need to make sure the channel name associated with a channel id is also set up in your chat plugin.

**Comment by averwhy** [comment]
> 
> 
> What chat plugin are you using? You need to make sure the channel name associated with a channel id is also set up in your chat plugin.

i have essentialsx and townychat.. could that be the issue? Townychat? i have a feeling it is

**Comment by Scarsz** [comment]
Your channel name should be general, not global.
