### ISSUE TITLE
Constant "Server has started" spam

### ISSUE THREAD

**Issue by Yhonay** [DiscordSRV/DiscordSRV#847]
![IMG_20200827_155740](https://user-images.githubusercontent.com/668573/91454450-412b3f80-e881-11ea-9c56-f2c8f3d6a908.jpg)

It usually happens when server is idling, but I've also seen it happen in the middle of a conversation. Server is not crashing. When it happens logs show nothing, even in debug mode.

**Comment by Vankka** [comment]
send your log

**Comment by Yhonay** [comment]
There you go:

debug enabled
![unknown (3)](https://user-images.githubusercontent.com/668573/91543825-17285a80-e91f-11ea-8caf-c1981f6248e0.png)

some marks to know when it happened
![unknown (4)](https://user-images.githubusercontent.com/668573/91543852-1ee7ff00-e91f-11ea-984f-06ae18b890d6.png)

log itself
[2020-08-28-4.log.gz](https://github.com/DiscordSRV/DiscordSRV/files/5141179/2020-08-28-4.log.gz)

**Comment by Vankka** [comment]
run `/discord debug` & paste the url here

**Comment by Yhonay** [comment]
https://bin.scarsz.me/db7481ba-9703-483f-b1e4-d9f8cd830dec#B5jiohxoa845j3YiUgOPdeXXu2h4il0s

**Comment by Vankka** [comment]
First time i've ever seen anything like this, the only time DiscordSRV sends the server has started message is when the plugin is enabled.

**Comment by Yhonay** [comment]
Ok... I'm a moron. I had another test server which had crontab @reboot rule that also started minecraft. It was in disarray and kept crashing so all of those "Server has started" was from that other server.

Thank's for that last message. I'd probably still be clueless without it.
