### ISSUE TITLE
DiscordSRV - Two factor is required for this operation

### ISSUE THREAD

**Issue by iKyzu** [DiscordSRV/DiscordSRV#852]
Hey, everything was okay with the plugin until yestarday afternoon where it just started to pop out the messages about this:

`[08:39:01] [DiscordSRV - JDA Callback 1/ERROR]: [DiscordSRV] DiscordSRV encountered an unknown Discord error: 60003: Two factor is required for this operation`

So it's only not updating the description of the channel that is writing messages from server, but I don't know if it's because of this error or not. Before that everything was working fine.

Do I need to do something with the bot or connect it again to discord server?

**Comment by Scarsz** [comment]
The person who created the Discord bot needs to enable two-factor authentication for their Discord account.
