### ISSUE TITLE
Feature: Announce reconnects to discord.

### ISSUE THREAD

**Issue by ryantheleach** [DiscordSRV/DiscordSRV#853]
The server already announces when it turns on and off. 

It would be further helpful if DiscordSRV announced when the connection was restored after losing connection.

This would mean I could stop having to monitor the server, and announcing to discord when my Australian internet was restored.

**Comment by Vankka** [comment]
I added the ability to listen to [JDA events](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/events/GenericEvent.html) in https://github.com/DiscordSRV/DiscordSRV/commit/30596e00536e03b5c04538eb1ab256593a79ae10 so you can listen to `ReconnectedEvent`, though keep in mind JDA will sometimes reconnect even if the connection to Discord is fully stable & working, for reasons like load balancing.

alerts.yml example:
```
  - Trigger: ReconnectedEvent
    Channel: global
    Embed:
      Color: "#00ff00"
      Author:
        Name: "I have reconnected!"
```

**Comment by ryantheleach** [comment]
Thanks, can a third party plugin also listen to these events? I'd be interested in making support for making support for [my fork](https://github.com/RTLBukkit/Takit-DNS)  of Takit DNS https://dev.bukkit.org/projects/takit-dns

**Comment by Vankka** [comment]
Yes, `DiscordUtil#getJda` (after DiscordSRV's DiscordReadyEvent (not bukkit event bus) is triggered or `DiscordSRV.isReady == true), https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/JDA.html#addEventListener(java.lang.Object...) https://github.com/DV8FromTheWorld/JDA/wiki/1%29-Events#using-the-interfaced-system-default
