### ISSUE TITLE
Formatting Characters in Broadcast Command Not Escaped

### ISSUE THREAD

**Issue by delbertina** [DiscordSRV/DiscordSRV#857]
When using the `/discord broadcast [msg]` command, formatting characters such as underscores are not escaped before sending to the Discord channel.

![image](https://user-images.githubusercontent.com/6349928/92314680-a9c09d80-efa0-11ea-9671-ce0f814d8cee.png)

Paper 1.16.2 Build # 168
DiscordSRV-Build-1.19.2-SNAPSHOT-1596464300 (For a fix to a different issue I was having)

: )

**Comment by Vankka** [comment]
Fixed, https://snapshot.discordsrv.com for a development build

**Comment by delbertina** [comment]
Hummm I realize the flaw in what I said now. Maybe there's a better solution to this potential issue than escaping all formatting characters. 

I'm not sure how possible it is, but maybe there's a way to have a PAPI placeholder that takes in a string to be escaped. I know luckperms does this by having placeholders that accept different permission nodes within the placeholder then output whatever information based on that value passed in. So maybe it'd look something like `/discord broadcast **A message about %discordsrv_escape_Some_Dudes_Username% **`

Maybe it'd be more possible to do the escaping of all characters but have a way to ignore specific characters from this with say a backslash or something. For instance, `/discord broadcast \*\*A message with Some_Dude_Username\*\*` turns into `/discord broadcast **A message with Some\_Dude\_Username**`

**Comment by Vankka** [comment]
> I'm not sure how possible it is, but maybe there's a way to have a PAPI placeholder that takes in a string to be escaped. I know luckperms does this by having placeholders that accept different permission nodes within the placeholder then output whatever information based on that value passed in. So maybe it'd look something like /discord broadcast **A message about %discordsrv_escape_Some_Dudes_Username% **

I don't see why DiscordSRV's extension should do this, the javascript extension for PAPI can do that just fine

**Comment by delbertina** [comment]
Oh wow TIL that exists haha xD tyty <3
