### ISSUE TITLE
Underscores in Names in Discord -> Minecraft Chat Become \_

### ISSUE THREAD

**Issue by Pemigrade** [DiscordSRV/DiscordSRV#860]
https://youtu.be/EjYvV5Y1qG0 should show the bug and how to reproduce it using only the latest Paper and DiscordSRV snapshot.

Debug report: https://bin.scarsz.me/6504e963-e4fa-42aa-97ac-a7301864bcba#DzCCrV5AuuNWyB04eEPw6AC7ycIyMRnt

Skip to 3:45 for the bug. The rest is all setup to show how I reproduced it

**Comment by Vankka** [comment]
My fault, https://github.com/DiscordSRV/DiscordSRV/blob/develop/src/main/java/github/scarsz/discordsrv/listeners/DiscordChatListener.java#L253 will get fixed when I get home

**Comment by Vankka** [comment]
Fixed in the above commit, latest snapshot now contains the fix https://snapshot.discordsrv.com
