### ISSUE TITLE
Add support to block certain roles from having their messages processed and send from Discord to MC

### ISSUE THREAD

**Issue by acollierr17** [DiscordSRV/DiscordSRV#861]
I am proposing to block specific roles from speaking in "bridge" channels defined in the DiscordSRV config. I've noticed that specific [users based on their IDs](https://github.com/DiscordSRV/DiscordSRV/wiki/config#discordchatchannelblockedids) can be blocked, but not roles. An example could be a user with a linked Minecraft account but has been muted in the Discord (user is added to the `Muted` role). They can still send messages just fine in the "bridge" channel, which can pose an issue (this is because of how Discord's permissions system is [set up](https://discordjs.guide/popular-topics/permissions-extended.html#discord-s-permission-system)). I haven't found anything in the Wiki via the search term `role`.

**Comment by Scarsz** [comment]
This should be handled instead by denying the role's write permission to the channel

**Comment by acollierr17** [comment]
> This should be handled instead by denying the role's write permission to the channel

I stated this isn't possible due to Discord's permissions system. For example, if the `@everyone` role globally has `SEND_MESSAGES`, but you have the linked role configured as `Verified` and its permission in the bridge channel, the `SEND_MESSAGES` is explicitly set to true, the user can still send messages, even when the `Muted` role's permission is set to false. Please check the second link in my issue instead of closing it immediately.

**Comment by Scarsz** [comment]
> I stated this isn't possible due to Discord's permissions system.

You didn't explain your situation thoroughly enough for it to be apparent *why* this is a problem with Discord's permission system.

> Please check the second link in my issue instead of closing it immediately.

I'm aware of how Discord permissions work.

After you've given an explanation, I agree that this could be something that's implemented.

**Comment by AlaRubra123** [comment]
> > This should be handled instead by denying the role's write permission to the channel
> 
> I stated this isn't possible due to Discord's permissions system. For example, if the `@everyone` role globally has `SEND_MESSAGES`, but you have the linked role configured as `Verified` and its role added in the bridge channel ith the `SEND_MESSAGES` permission explicitly set to true, the user can still send messages, even when the `Muted` role's permission is set to false. Please check the second link in my issue instead of closing it immediately.
> 
> Edit: Fix some typos and grammatical errors

Honestly, that just sounds like your permissions need to be edited. Like, for a verification role, make `@everyone` have `SEND_MESSAGES` off globally, then have `Verified` have it on globally, and leave channel permissions for both roles neutral.

Then, your muted role will work correctly.

**Comment by acollierr17** [comment]
> > > This should be handled instead by denying the role's write permission to the channel
> 
> > 
> 
> > I stated this isn't possible due to Discord's permissions system. For example, if the `@everyone` role globally has `SEND_MESSAGES`, but you have the linked role configured as `Verified` and its role added in the bridge channel ith the `SEND_MESSAGES` permission explicitly set to true, the user can still send messages, even when the `Muted` role's permission is set to false. Please check the second link in my issue instead of closing it immediately.
> 
> > 
> 
> > Edit: Fix some typos and grammatical errors
> 
> 
> 
> Honestly, that just sounds like your permissions need to be edited. Like, for a verification role, make `@everyone` have `SEND_MESSAGES` off globally, then have `Verified` have it on globally, and leave channel permissions for both roles neutral.
> 
> 
> 
> Then, your muted role will work correctly.

We've already had this discussion. I wouldn't have posted this issue if your comment was the case. Please read into this some more because it sounds to me like you might have missed some important information in this issue.

**Comment by Vankka** [comment]
Implemented in the above PR, available in v1.25.0
