### ISSUE TITLE
Timeout Messages

### ISSUE THREAD

**Issue by king-glitch** [DiscordSRV/DiscordSRV#862]
Please add connecting timeout message instead of error, because my server internet are not that good. the error are spamming.
Thank you!
![ำพพ](https://user-images.githubusercontent.com/58404132/93020643-600f2d00-f608-11ea-8c47-8e75ca694dbc.png)

**Comment by Vankka** [comment]
Made the error much smaller, https://snapshot.discordsrv.com for a dev build
