### ISSUE TITLE
Not Legitimate when used from Minehut

### ISSUE THREAD

**Issue by Jacob77346** [DiscordSRV/DiscordSRV#863]
When installing via Minehut, onto a free server, every 5 minutes console shows
[Sun, 13. Sep 2020 21:13:36 GMT INFO] The installed version of DiscordSRV is illegitimate. Absolutely no support will be provided by the DiscordSRV authors and take no credit for unintended behavior. DiscordSRV is available at https://github.com/DiscordSRV/DiscordSRV. If you paid for this plugin, you've been scammed.

**Comment by Vankka** [comment]
Minehut uses a modified version of DiscordSRV, which we do not support. We aren't going to remove the message
