### ISSUE TITLE
Unfortunately will not work.

### ISSUE THREAD

**Issue by butterflysoup** [DiscordSRV/DiscordSRV#870]
i've set everything up correctly, i've even double checked with youtube videos but unfortunately the bot does not want to work for me.
![image](https://user-images.githubusercontent.com/71014263/95012341-223b7c80-067b-11eb-8fde-b7d1fb2654f5.png)
![image](https://user-images.githubusercontent.com/71014263/95012345-2cf61180-067b-11eb-8561-546c573c8edf.png)
any ideas? server is 1.16.3

**Comment by Scarsz** [comment]
**Bot tokens are supposed to be kept secret. You just exposed yours. Go reset it in the Discord developer panel immediately.**

GitHub issues are for bug reports & feature requests. Go to the Discord server for support https://discordsrv.com/discord
