### ISSUE TITLE
[Solution] To those that are suddenly experiencing the bot not working (Your DiscordSRV bot does not have the Server Members Intent!)

### ISSUE THREAD

**Issue by DereC4** [DiscordSRV/DiscordSRV#871]
I felt the need to put this here due to a sudden occurence of random people making github accounts just to report this issue to the discord api documentation github. 

You most likely received a message like this in the console

```
04.10 21:28:43 [Server] ERROR ==============================================================
04.10 21:28:43 [Server] ERROR Your DiscordSRV bot does not have the Server Members Intent!
04.10 21:28:43 [Server] ERROR DiscordSRV and its API hooks require these intents to function. Instructions:
04.10 21:28:43 [Server] ERROR 1. Go to https://discord.com/developers/applications
04.10 21:28:43 [Server] ERROR 2. Click on the DiscordSRV bot
04.10 21:28:43 [Server] ERROR 3. Click on "Bot" on the left
04.10 21:28:43 [Server] ERROR 4. Enable the "SERVER MEMBERS INTENT"
04.10 21:28:43 [Server] ERROR 5. Restart your server
04.10 21:28:43 [Server] ERROR ==============================================================
```

While the message itself is self explanatory already, if you are still confused then head over to https://discord.com/developers/applications
If you see no bot, then you are most likely not the server admin who set up this plugin so ask them to configure the bot. 
If you do, simply click on it, click "bot", and click the sliders saying "Server Members Intent" underneath "PRESENCE INTENT"

Restart your minecraft server afterward and the bot should be up and running again.

**Comment by GreemDev** [comment]
DiscordSRV already says this, why is there an issue on github for it?
