### ISSUE TITLE
Feature Request: /voicechat <playername>

### ISSUE THREAD

**Issue by DitDitGitHub** [DiscordSRV/DiscordSRV#872]
I think a cool addition to DiscordSRV would be a command a player can execute which puts them in a private voice channel with the other player if they accept. This would only work if both players are in the lobby voice chat. Once they are in a voice channel, they can invite other players to join by doing the same command. To leave the voice channel and return to the lobby channel, the player just does /voicechat without mentioning a player. /voicechat would also have /vc as an alias.

**Comment by Scarsz** [comment]
Sounds neat but in practice this would be no more useful than those users just calling each other
