### ISSUE TITLE
op command not working

### ISSUE THREAD

**Issue by mben42** [DiscordSRV/DiscordSRV#875]
Hello,

`op <nick>` command in Discord console channel does nothing, nor working or returning an error.

Works perfectly both in normal server console and in-game, then it's a plugin problem.

Thanks in advance.

**Comment by Vankka** [comment]
The op command is blacklisted by default, see `DiscordConsoleChannelBlacklistedCommands` in the config.yml

**Comment by mben42** [comment]
Thank you for quick answer!
