### ISSUE TITLE
Webhook names have begun displaying as "DiscordSRV <number> #<number>"

### ISSUE THREAD

**Issue by RalphORama** [DiscordSRV/DiscordSRV#878]
At around 5:22PM EST today, the names in DiscordSRV messages (including the bot itself) seemingly went haywire.

![image](https://user-images.githubusercontent.com/6566104/96051455-8ca5a700-0e49-11eb-925b-ce9ca5e103d3.png)
![image](https://user-images.githubusercontent.com/6566104/96051483-9b8c5980-0e49-11eb-9322-27695deb0671.png)

I see no errors in console relating this (even with debug mode enabled), so I'm not sure what's causing the issue. I have "server members intent" enabled for the bot, and haven't received an email from Discord about any API issues.

Debug info: https://bin.scarsz.me/1e254c5f-c7d8-4c36-afb9-d753c092dfb0#YR7HFO4jIj23z189X74sRIvE4WmbJ7qs

**Comment by Vankka** [comment]
This is a issue on Discord's side, Discord's developers are currently looking into it.

**Comment by RalphORama** [comment]
Ok, thanks very much

**Comment by Scarsz** [comment]
Issue has been resolved
