### ISSUE TITLE
GeyserMC/Floodgate support for account linking.

### ISSUE THREAD

**Issue by kotx** [DiscordSRV/DiscordSRV#879]
DiscordSRV should not kick players that have been already linked with GeyserMC, even if the UUIDs are different.

**Comment by Vankka** [comment]
what?

**Comment by Androkai** [comment]
If I understand you correctly you're using DiscordSRV's "users have to link their accounts to be able to join the server" feature but also using Geyser to allow users with Bedrock Minecraft to join the server and for some reason Geyser is creating random UUIDs for each user on each login resulting in DiscordSRV blocking the user from joining the server. Did I understand that correct or how much of it?

I have no experience with how Geyser works but if it really creates a random UUIDs each time it's not a thing we will fix. In that case please do not use out whitelisting feature by disabling it in linking.yml

**Comment by kotx** [comment]
> If I understand you correctly you're using DiscordSRV's "users have to link their accounts to be able to join the server" feature but also using Geyser to allow users with Bedrock Minecraft to join the server and for some reason Geyser is creating random UUIDs for each user on each login resulting in DiscordSRV blocking the user from joining the server. Did I understand that correct or how much of it?
> 
> I have no experience with how Geyser works but if it really creates a random UUIDs each time it's not a thing we will fix. In that case please do not use out whitelisting feature by disabling it in linking.yml

Yeah, sorry I wasn't being clear. Geyser uses the same UUID for the same Bedrock player IIRC.

**Comment by Scarsz** [comment]
I still fail to see what this issue is actually about

**Comment by kotx** [comment]
> I still fail to see what this issue is actually about

Bedrock players connecting via Floodgate are kicked when the `Player must be linked to Discord to join the server` option is enabled. This is because the UUID for the Bedrock client is different. However, players that have been linked their Java account with Floodgate will join via the correct java UUID. DiscordSRV should not kick players that have been linked with Floodgate.

**Comment by Scarsz** [comment]
Still doesn't make sense to me what the real root of the issue is with this or how this would even be addressed. Please be far more descriptive.

**Comment by Vankka** [comment]
See https://github.com/GeyserMC/Floodgate/blob/development/common/src/main/java/org/geysermc/floodgate/FloodgatePlayer.java#L94

**Comment by kotx** [comment]
> Still doesn't make sense to me what the real root of the issue is with this or how this would even be addressed. Please be far more descriptive.

There should be an integration with Floodgate that allows Bedrock players (that have different UUIDs) to link with DiscordSRV. Alternatively there could be a config option to allow multi-account linking, but that can easily be abused.

**Comment by kotx** [comment]
Closing as this is a very niche feature that probably won't be used often.
