### ISSUE TITLE
DiscordSRV Player Avatar 

### ISSUE THREAD

**Issue by J1n1n** [DiscordSRV/DiscordSRV#880]
Is there a way to change player's avatar by their nicked names instead of actual username/UUID? 

This is what I can find in the config to change avatar, but I don't know if it's possible to make it so it changes avatar according to your nicked name
Experiment_EmbedAvatarUrl: https://minotar.net/helm/{username}/{size}

**Comment by Scarsz** [comment]
What good purpose would this serve?

**Comment by J1n1n** [comment]
> What good purpose would this serve?

Hmm...Now I think about it, yeah, it doesn't do anything. I initially wanted make it so people have the permission to nick can have their avatar hidden. But I guess I could use silent joining permission.
