### ISSUE TITLE
Updated from Build 1.19.1 to Build 1.20.0 and now it is listed as "disabled"

### ISSUE THREAD

**Issue by Goldninja100gn** [DiscordSRV/DiscordSRV#882]
**Server Info:**
MC 1.12.2
Magma 30819922
Modded with the mods from the LostColony modpack (there is 99 mods, but the server doesn't have the client-side mods)
Plugins: BetterSleeping3, DiscordSRV, Dynmap, Essentials, GriefPrevention, LuckPerms, & OpenInv

**What happened:**
I noticed there was an update, so I decided to update to the newer version (as it did say it was compatible)

I started the server and noticed that it wasn't sending any "server has started" message to discord. I checked the configs and nothing was off from them, the only thing I found different was the config version was updated from 1.19.1 to 1.20.0. So I restarted the server thinking it might have just not registered the configs. Same thing. I joined the server and typed in "/discordsrv" and gave back an error saying that the command couldn't be executed cause the plugin DiscordSRV is disabled.
DiscordSRV update was the only thing I changed when I did this. I downgraded back to 1.19.1 and it works perfectly fine, I'm only having this issue in 1.20.0.

Any Ideas?

**Comment by underscore11code** [comment]
Please read console, there will be an error. Additionally, please don't use GitHub for support. We have a [discord](https://discord.discordsrv.com) for that.

**Comment by Goldninja100gn** [comment]
I can't join any more than 100 discord servers. Luckily though, a friend of mine had the exact same issue and they fixed it by have 'server member intent' enabled so I tried that and it works perfectly now.
