### ISSUE TITLE
Wrong UltimateChat formatting

### ISSUE THREAD

**Issue by Katrix** [DiscordSRV/DiscordSRV#888]
Using DiscordSRV 1.20.0 on Paper 1.16.3

When using UltimateChat and sending a message from Discord, the message is formatted wrongly.
![image](https://user-images.githubusercontent.com/11007080/96802312-1ed51e80-13f9-11eb-8fe3-9dcb9a505d93.png)

When disabling the UltimateChat plugin hook, this is what shows, and how I want it to show. Sadly messages from Minecraft to Discord doesn't work when I disable the plugin hook.
![image](https://user-images.githubusercontent.com/11007080/96802362-39a79300-13f9-11eb-9f69-a0c3d6a01d5d.png)

Here are the format strings used
```yaml
DiscordToMinecraftChatMessageFormat: "[&6Yukari&r] O%toprolecolor%%toprole%&rO &a%username%&r: %message%"
DiscordToMinecraftChatMessageFormatNoRole: "[&6Yukari&r] OChildO &7%username%&r: %message%"
```

**Comment by Scarsz** [comment]
The UltimateChat pretty much only contains the code necessary to tell UltimateChat to handle the message, this is likely an issue with UC's `UltimateFancy` class

**Comment by Vankka** [comment]
UltimateChat isn't supported anymore
