### ISSUE TITLE
Advancements don't match up

### ISSUE THREAD

**Issue by bitttttten** [DiscordSRV/DiscordSRV#890]
In-game I got the two advancements Those Were the Days and War Pigs, although in the discord channel the bot reported that I got "Find Bastion" and "Loot Bastion" respectively. It seems that none of the other advancement titles match up either.

**Comment by GreemDev** [comment]
DiscordSRV uses the advancement's internal name. "Those Were The Days" is obtained from finding a Bastion, and War Pigs is obtained from looting a Bastion. That's what they're called internally so we use it, though I don't remember exactly why we don't use the in-game names for advancements but I believe it had something to do with i18n.

**Comment by underscore11code** [comment]
>I don't remember exactly why we don't use the in-game names for advancements but I believe it had something to do with i18n.

iirc advancement names are handled clientside for localization, so the server never knows what the "pretty" name is.

**Comment by GreemDev** [comment]
> 
> 
> > I don't remember exactly why we don't use the in-game names for advancements but I believe it had something to do with i18n.
> 
> iirc advancement names are handled clientside for localization, so the server never knows what the "pretty" name is.

Ah, that's it.

**Comment by bitttttten** [comment]
Makes sense. Thanks all!
