### ISSUE TITLE
UltraChat Hook

### ISSUE THREAD

**Issue by DayDreamerDevs** [DiscordSRV/DiscordSRV#894]
[13:13:47] [DiscordSRV - Initialization/INFO]: [DiscordSRV] No chat plugin hooks enabled 

Here is the problem in the server logs. Ultra Chat cannot integrate with DiscordSRV hence the plugin don't send the Minecraft server chat to discord. Every other function of the plugin works. I receive the logs and game feed as well as sending messages from Discord to the Minecraft server. When I do /discord broadcast then it sends it to Discord. I a using MineHut and they forget the plugin and removed the Debug features. I would like to see Integration for Ultra Chat if possible:)

**Comment by Androkai** [comment]
The UltraChatEvent has a property of type "ChatProperties" which is an interface that can be a "ChannelProperties" or one of four other implementations for that interface. And to emphasize this again, the event has __one__ property, not a list of multiple ones. That is a fascinating concept... You want to get the channel the chat is send in and maybe there is a property including the channel, maybe not. 😄

**Comment by DayDreamerDevs** [comment]
Greetings

So what does this mean it is possible to interface with Ultra Chat or must
additional intergrations or hooks be created?

Kind regards

**Comment by Vankka** [comment]
UltraChat has been abandoned
