### ISSUE TITLE
User color placeholder (of the actual color rather than top role color)

### ISSUE THREAD

**Issue by Speak2Erase** [DiscordSRV/DiscordSRV#899]
In my server, we have pronoun roles that are listed first so people see them first whenever they look at a user. However, these roles don't have any colour, and discordsrv reads them as grey since it takes the top role colour. 
There should be an option to take the actual user's colour and allow for the usage of hex codes in chat (so a user who speaks in the discord to Minecraft chat would have their username colourized as how they are coloured on discord).

**Comment by granny** [comment]
accurate role colors in chat is a feature being tested in the #testing channel of our discord server (https://discordsrv.com/discord). 

The `DiscordChatChannelRolesSelection` option will ignore the roles that you specify from the color translations. I’m guessing that’s what you're looking for.
