### ISSUE TITLE
Change the language

### ISSUE THREAD

**Issue by RakashTv** [DiscordSRV/DiscordSRV#902]
Hello
I have a problem because the plugin informs me on the discord in German. I admit that we are Polish communication and we use the following languages: Polish - English. is it possible to set it? if so, where and how.

**Comment by Vankka** [comment]
the language of the plugin can be changed with `/discord setlang <language> -confirm` eg. `/discord setlang en -confirm`

**Comment by RakashTv** [comment]
I'm sorry, but i'm afraid the problem with the plugin still remains, as you can see on the attached screenshots after entering the command, the plugin doesn't change the currently used language.
Our server is set up in Germany on linux operating system.
I'll also attach these screenshots.


![Screenshot_20201102-195025_Discord](https://user-images.githubusercontent.com/73384904/97925567-eb33b600-1d61-11eb-982a-36e04a6286a1.jpg)
![Screenshot_20201102-195429_Discord](https://user-images.githubusercontent.com/73384904/97925574-ee2ea680-1d61-11eb-87a7-364a4fd17881.jpg)
![nieznane](https://user-images.githubusercontent.com/73384904/97925580-eff86a00-1d61-11eb-890f-a169c89f2164.jpeg)
![Przechwytywanie](https://user-images.githubusercontent.com/73384904/97925585-f25ac400-1d61-11eb-82c0-0f3cb4f9d661.png)

**Comment by Vankka** [comment]
Please check if the messages.yml file's language changed, if it did please restart your server, if it did not please join our Discord server @ https://discordsrv.com/discord for help

**Comment by RakashTv** [comment]
After entering the command again to the console and resetting the server, plugin shut down completely after installing the files in German language, similar things happen after reinstalling the plugin completely
