### ISSUE TITLE
Failed to Register Expansion Class

### ISSUE THREAD

**Issue by ellaira-ash** [DiscordSRV/DiscordSRV#903]
Paper: 1.16.3 (248)
DiscordSRV: 1.20.0

When the server is started, this error message shows up. I have not observed any issues related to it. 

`06.11 16:21:26 [Server] ERROR [PlaceholderAPI] expansion class DSRVExpansion is outdated: 
06.11 16:21:26 [Server] INFO Failed to load due to a [NoClassDefFoundError], attempted to use github/scarsz/discordsrv/dependencies/google/common/collect/ImmutableMap
06.11 16:21:26 [Server] ERROR [PlaceholderAPI] expansion class DSRVExpansion is outdated: 
06.11 16:21:26 [Server] INFO Failed to load due to a [NoClassDefFoundError], attempted to use github/scarsz/discordsrv/dependencies/google/common/collect/ImmutableMap`

**Comment by Vankka** [comment]
The placeholderapi expansion is no longer required, you can remove it from the PlaceholderAPI expansions folder. The expansion is now integrated in DiscordSRV
