### ISSUE TITLE
Config to Prevent Embeds

### ISSUE THREAD

**Issue by QuinnBast** [DiscordSRV/DiscordSRV#907]
Some messages that the bot sends are sent as discord embeds. When the bot sends an embedded messages, notifications on mobile devices are unable to show a preview because of the embed and requires users to go into discord to see the message. A configuration option should be added that can be set that prevents the bot from sending embedded messages and will fallback to just sending the message as text. The specific use case for this is that when players join/leave the server it is sent as an embed. Thus, a player cannot quickly check who is joining the server and say "oh, my friend is online, I can join them".

![image](https://user-images.githubusercontent.com/22599103/99444351-b6873900-28e1-11eb-9cd7-4004970c1151.png)

Looks like this is happening with the `getEmbeds()` call

**Comment by granny** [comment]
https://github.com/DiscordSRV/DiscordSRV/wiki/FAQ#how-can-i-change-a-notification-message-embed-back-to-plain-text
