### ISSUE TITLE
DiscordSRV EventListener exception

### ISSUE THREAD

**Issue by Exarchh** [DiscordSRV/DiscordSRV#909]
Chat messages from Discord to the MC Server are not showing up in game despite messages in game showing up correctly in discord. This issue also applies to commands that are sent from our discord console channel, the following error message displays in our server console for both;
https://pastebin.com/ZYUbVwtG

As per the issue guidelines;
- This error occurred on both plugin versions 1.20 and 1.20.1-SNAPSHOT
- No reloads were used, only full server restarts
- Debug output: https://pastebin.com/BBG9U4UR

**Comment by Vankka** [comment]
You removed or misformatted the DiscordCannedResponses config option
