### ISSUE TITLE
Placeholder dont work 1.20.0

### ISSUE THREAD

**Issue by Tylwen** [DiscordSRV/DiscordSRV#920]
Minecraft 1.16.3

alerts.yml

  - Trigger: CMIAfkEnterEvent
    Channel: global
    Embed:
      Color: "#00ff00"
      Author:
        ImageUrl: "{embedavatarurl}"
        Name: '{username} est désormais AFK'

![image](https://user-images.githubusercontent.com/26263998/100705263-3532aa80-33a7-11eb-9b39-9377c1c444d5.png)

Placeholder dont work, how its possible ?

**Comment by Tylwen** [comment]
- Trigger: CMIAfkEnterEvent
    Channel: global
    Embed:
      Color: "#ff0000"
      Author:
        ImageUrl: "https://minotar.net/helm/${#event.getPlayer().getName()}/32"
        Name: '${#event.getPlayer().getName() + " est désormais AFK"}'

![image](https://user-images.githubusercontent.com/26263998/100708551-ceb08b00-33ac-11eb-9775-f341829cbc1d.png)


It's good

**Comment by Vankka** [comment]
Can this be closed?
