### ISSUE TITLE
Webhook Issue

### ISSUE THREAD

**Issue by Zeldash** [DiscordSRV/DiscordSRV#922]
Hello! I'm curently planning to open my server as "offline mode", meaning that crack users can join my server. However, by foing this, all skins were deleted. The plugin SkinRestorer fix that issue, but the webhooks sent to my discord now all have a steve face...

Is there any way to block that ?

regards, 
zeldash

**Comment by Androkai** [comment]
DiscordSRV isn't sending the actual image to the Discord servers. Instead it's sending a [minotar](https://minotar.net) link. What you can do is changing `{uuid-nodashes}` to `{username}` in `Experiment_EmbedAvatarUrl` in config.yml
