### ISSUE TITLE
How does DiscordSRV manage linked accounts (JDBC)

### ISSUE THREAD

**Issue by BlueTree242** [DiscordSRV/DiscordSRV#924]
hi, just asking how does DiscordSRV manage linked accounts in the database. Just wanted to know the table name, and columns thats all

**Comment by Scarsz** [comment]
Plugin is open source

**Comment by BlueTree242** [comment]
Umm, I didn't find an answer

**Comment by BlueTree242** [comment]
Yeah, but I am not a discordsrv dev to know which class contains it

**Comment by GreemDev** [comment]
You don't have to be a developer of this plugin to be able to find the database class. The plugin is open source.
