### ISSUE TITLE
Voice Bug

### ISSUE THREAD

**Issue by JaHollYT** [DiscordSRV/DiscordSRV#929]
4 Players are standing close to each other and in a voice chat.
When now 2 Players of them going together away so much, that the to pairs are not in the voice range than all 4 Players still in the voice channel.
Normally then there should be 2 Voice channels.

Using the newest Update: https://www.spigotmc.org/resources/discordsrv.18494/updates

**Comment by Vankka** [comment]
Set `DebugLevel` to `1`, `/discord reload` have them get in range of each other then get far enough away from each other and then generate a debug report with `/discord debug` and paste the url here

**Comment by JaHollYT** [comment]
https://bin.scarsz.me/b497ce4c-b6fb-421d-a7f5-74769a9cb103#Nqmz3lwt3eymJSFkBuvJs94DbMZHxTvQ

-> so 5 People. 2 going away and out of voice range. alle people remain in same voice chat.
-> you will easy reproduce this with 4 Players :)

**Comment by Vankka** [comment]
Falloff was wrong, but that is now fixed - https://snapshot.discordsrv.com
Try again on this build and provide a new debug report if the issue persists, also going to note that having Falloff set to 0 is stupid

**Comment by Vankka** [comment]
Closing due to lack of response
