### ISSUE TITLE
Regex filters broken

### ISSUE THREAD

**Issue by Thornbush42** [DiscordSRV/DiscordSRV#931]
Regex Filters not working for console output. Attached is the regex code and the discord console output which displays this:
![image](https://user-images.githubusercontent.com/10698365/101998902-53fe3e80-3ccf-11eb-9aaf-7a298771f090.png)
![image](https://user-images.githubusercontent.com/10698365/101998900-48ab1300-3ccf-11eb-8578-80cbae2475ea.png)

**Comment by Vankka** [comment]
Are broken on the release, is fixed on snapshots, https://snapshot.discordsrv.com
