### ISSUE TITLE
Player Avatars in Discord Channel not updating

### ISSUE THREAD

**Issue by DereC4** [DiscordSRV/DiscordSRV#932]
As the title suggests, my player avatars in the channel the bot sends the embeds in are not updating and I'm not sure why. Only for certain skins it has updated their avatar but for others it just shows a steve head even though they don't have that skin. 
I'm fairly certain it isn't an issue with the website you get heads from

**Comment by Scarsz** [comment]
Blame Discord's image proxy/cache for that

Add `?{timestamp}` to the end of your avatar URL to force it to always update
