### ISSUE TITLE
VenturechatBungee Hook Permission Issue

### ISSUE THREAD

**Issue by NotAShelf** [DiscordSRV/DiscordSRV#933]
Basically, if Venturechat Bungee is enabled in config.yml, players are able to see channels from discord which they are not able to see in game.

For example
I have 2 chats, both bungee

Global (no perm required)
Staffchat (venturechat.staffchat required)

if I sent a message to Staffchat (from discord) players in-game are able to see the message, but messages that are sent to Staffchat in-game.

**Comment by Vankka** [comment]
When `VentureChatBungee` is enabled, VentureChat handles the messages and who they are sent to

**Comment by NotAShelf** [comment]
im sorry, but please test it out yourself before shrugging it off as invalid.

players have venturechat.staff set to false, thus they do not see the messages that are sent **in-game** however they DO see the messages that are sent from discord, which could possibly mean it is discordsrv related.

**Comment by Vankka** [comment]
What I'm saying is you should be reporting this to VentureChat, since they are handling every message that DiscordSRV forwards to in-game players when `VentureChatBungee` is enabled

**Comment by NotAShelf** [comment]
alright, thanks

**Comment by NotAShelf** [comment]
Hello again,
Sorry for the continious bother yet I was told by the author of Venturechat that it is in fact handled by DiscordSRV. I am not sure what the issue is supposed to be, so I can only provide limited information on how it is occuring and none on why as I am yet to learn why the issue present with bungee enabled.
