### ISSUE TITLE
Status update every minute

### ISSUE THREAD

**Issue by ccsliinc** [DiscordSRV/DiscordSRV#937]
No matter what I set the status update to it keeps updating the console channel every minute

**Comment by Scarsz** [comment]
Set the format to a blank string i.e. `Option: ""`

**Comment by ccsliinc** [comment]
Which option "StatusUpdateRateInMinutes:"?

I looked in the code and it defaults back to 1

**Comment by Scarsz** [comment]
I said to change the format, not the status update rate.

`DiscordGameStatus: ""`

**Comment by ccsliinc** [comment]
im sorry maybe im looking at the complete wrong place, pardon me as i tried to follow the code backwards.  I am trying to get the every minute to either stop or be spaced out

[Tue, 15. Dec 2020 01:17:00 UTC INFO] TPS from last 1m, 5m, 15m: 20.0, 20.0, 20.0
[Tue, 15. Dec 2020 01:18:00 UTC INFO] TPS from last 1m, 5m, 15m: 20.0, 20.0, 20.0

**Comment by Scarsz** [comment]
That... wouldn't have anything to do with the status. That's an artifact of your panel's server health monitor. If you're renting the server from a host, that's how the panel ensures your server hasn't crashed and isn't disableable on your end.

Add `.*TPS from last 1m, 5m, 15m.*` to your `DiscordConsoleChannelFilters`

**Comment by ccsliinc** [comment]
Thank you

**Comment by ccsliinc** [comment]
Im sorry to bother but i think something is wrong.  Those minute updates are coming from your messages.yml.

this particular variable below, this is why i was trying to change the interval.  I do not think its my server.

ChannelTopicUpdaterConsoleChannelTopicFormat
ChannelTopicUpdaterConsoleChannelTopicFormat: "TPS: %tps% | Mem: %usedmemorygb%GB used/%freememorygb%GB free/%maxmemorygb%GB max | %serverversion%"
