### ISSUE TITLE
Add ability to parse offline player placeholders

### ISSUE THREAD

**Issue by Insprill** [DiscordSRV/DiscordSRV#938]
I would love to see the ability to parse placeholders for offline players. I wrote some custom PAPI placeholders for offline players except DiscordSRV won't parse them haha. Specifically for `DiscordToMinecraftChatMessageFormat` in the `messages.yml`.

**Comment by Vankka** [comment]
Duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/904
