### ISSUE TITLE
Custom allowed commands per-role

### ISSUE THREAD

**Issue by xXBuilderBXx** [DiscordSRV/DiscordSRV#94]
Maybe you should implement a custom commands file (commands.json) so that specific roles can have access to run commands on discord such as !c kick

In the config section maybe have this
CommandsFullAccess: "ROLE ID, ROLE ID" -Anyone with this will have access to do any commands with !c
CommandsBlacklist: "op, ban" - Blacklist any commands if you need to
CommandsLinkedOnly: "true/false/yes/no" - Only linked accounts can use commands

In the commands.json have this
```
[
  {
    "command":"ban", - The commands to use
    "role":"ROLE ID", - The role id in discord that can use this command
    "output":"true/false/yes/no" - Output the results of the command to discord otherwise set it to say command done or use a reaction emoji for 👌 
  },
  {
    "command":"kick",
    "role":"ROLE ID",
    "output":"true/false/yes/no"
  }
]
```

**Comment by xXBuilderBXx** [comment]
Even better have the bot use a reaction when the command is done :)

**Comment by Scarsz** [comment]
#384
