### ISSUE TITLE
[Question] How to disable the users from mentioning a discord role from in game

### ISSUE THREAD

**Issue by Hona** [DiscordSRV/DiscordSRV#940]
If users type the plaintext: `<@&00000000000000>` with an actual ID, it will mention using the bot, is there a config option to block them from doing that?

**Comment by Scarsz** [comment]
Snapshots actually contain a change that allows which mentioning types are enabled, roles are off by default

https://snapshot.discordsrv.com

**Comment by Hona** [comment]
Thanks
