### ISSUE TITLE
Automatic kick when not joined in X amount of days

### ISSUE THREAD

**Issue by James-Bennett-295** [DiscordSRV/DiscordSRV#949]
Make it so when you have **not joined the server in X amount of days**, or have been on the discord and **not linked after X amount of days**, then it **kicks you** off of the discord. Here is a bad flowchart I made: https://cdn.discordapp.com/attachments/431848792828936192/792134599056293908/unknown.png

Im new to github so please let me know if im doing anything wrong. If you need to contact me, my discord name is **James Bennett#9534**

**Comment by James-Bennett25565** [comment]
Here is the Visio document
[Discord SRV.zip](https://github.com/DiscordSRV/DiscordSRV/files/5742430/Discord.SRV.zip)

**Comment by Vankka** [comment]
"Has the user been on the Discord" isn't a very measurable statistic. Discord has a purge feature to remove dead accounts, that may already cut out a lot of the user's that the 'isn't linked' side. The Minecraft side of when the player was last logged in sounds *somewhat* more reasonable (for implementation into DiscordSRV) however

**Comment by James-Bennett25565** [comment]
Sorry, I don't think I explained very well about that part, how long they were on the server for. I want it to look at when they joined the discord and then it can calculate how long they have been on the server for. I know MEE6 bot can see when members have joined even ones before the bot was added so it must be possible, I will try to research how you might be able to get that information

**Comment by Vankka** [comment]
I don't see why knowing how long a user has been in the server is relevemt for this future but that data is available.

**Comment by James-Bennett25565** [comment]
It is because if they have been on the server for X amount of days without linking, it kicks them.

**Comment by James-Bennett25565** [comment]
https://discord.com/developers/docs/resources/guild#guild-member-object

**Comment by James-Bennett25565** [comment]
I think the field is

joined_at? *

**Comment by Scarsz** [comment]
Any reason you closed this @James-Bennett-295
