### ISSUE TITLE
Server registration synchronization

### ISSUE THREAD

**Issue by musiciantishko** [DiscordSRV/DiscordSRV#950]
Idea for your project: **Register** on a Minecraft server via Discord

when you first log into the server, you need to write **/register password**. And it would be convenient to save the password in a separate file, for example, in a file with accounts related to disagreements in Minecraft. To be able to reset the password on the Discord server, for example with! Password reset command.

**Comment by Scarsz** [comment]
What would be the point of this

**Comment by musiciantishko** [comment]
I have a thought. Thought you might be interested in this function

**Comment by Scarsz** [comment]
We don't just add random features for no reason. There has to be a reason behind suggesting this

**Comment by musiciantishko** [comment]
Well, I have one reason to make it easier to **reset minecraft account password**, but if you think this is a useless feature, I agree with you.
