### ISSUE TITLE
I got this message in log from discord srv after the startup of the server

### ISSUE THREAD

**Issue by jobless-exe** [DiscordSRV/DiscordSRV#957]
HERE IS LOG

[

> 09:16:56] [Server thread/INFO]: [DiscordSRV] Enabling DiscordSRV v1.21.1
> [09:16:56] [Server thread/WARN]: [DiscordSRV] Config key ServerWatchdogMessage is missing from the messages.yml. Using the default value of `%date%` %guildowner%, the server room is on :fire::bangbang:
> [09:16:56] [Server thread/INFO]: [GriefPrevention] Enabling GriefPrevention v16.16.0
> [09:16:57] [Server thread/INFO]: [GriefPrevention] Finished loading configuration.
> [09:16:57] [Server thread/INFO]: [GriefPrevention] 7 total claims loaded.
> [09:16:58] [DiscordSRV - Initialization/WARN]: [DiscordSRV] Update check failed: null
> [09:17:02] [Server thread/INFO]: [GriefPrevention] Customizable messages loaded.
> [09:17:02] [Server thread/INFO]: [GriefPrevention] Finished loading data (File Mode).
> [09:17:02] [Server thread/INFO]: [GriefPrevention] Boot finished.
> [09:17:03] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
> [09:17:04] [Server thread/INFO]: Done (211.214s)! For help, type "help"
> container@pterodactyl~ Server marked as running...
> [09:17:10] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 5794ms or 115 ticks behind
> [09:17:15] [DiscordSRV - Initialization/INFO]: [DiscordSRV] [JDA] Login Successful!
> [09:17:18] [JDA MainWS-ReadThread/INFO]: [DiscordSRV] [JDA] Connected to WebSocket
> [09:17:21] [JDA MainWS-ReadThread/INFO]: [DiscordSRV] [JDA] Finished Loading!
> [09:17:22] [DiscordSRV - Initialization/INFO]: [DiscordSRV] Found server G:jobless_exe's server(778632983737401374)
> [09:17:22] [DiscordSRV - Initialization/INFO]: [DiscordSRV] - TC:spawn-point(786608898303197251)
> [09:17:22] [DiscordSRV - Initialization/INFO]: [DiscordSRV] - TC:assign-self_role(786624094614585435)
> [09:17:22] [DiscordSRV - Initialization/INFO]: [DiscordSRV] - TC:🔗invite-link🔗(788805900127174657)
> [09:17:22] [DiscordSRV - Initialization/INFO]: [DiscordSRV] - TC:📚📚rules📚📚(788811804021227530)
> [09:17:22] [DiscordSRV - Initialization/INFO]: [DiscordSRV] - TC:hah0(782985285352685599)
> [09:17:22] [DiscordSRV - Initialization/INFO]: [DiscordSRV] - TC:smp-chats(794466782130864150)
> [09:17:22] [DiscordSRV - Initialization/INFO]: [DiscordSRV] - TC:smp-console(793379315240009738)
> [09:17:22] [DiscordSRV - Initialization/INFO]: [DiscordSRV] Console forwarding assigned to channel TC:smp-console(793379315240009738)
> [09:17:22] [DiscordSRV - Initialization/INFO]: [DiscordSRV] Not using JDBC, one of host/port/database was default
> [09:17:23] [DiscordSRV - Initialization/INFO]: [DiscordSRV] Enabling LuckPerms hook
> [09:17:23] [DiscordSRV - Initialization/INFO]: [DiscordSRV] No chat plugin hooks enabled
> [09:17:53] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 12626ms or 252 ticks behind
> [09:17:57] [DiscordSRV - JDA Rate Limit/ERROR]: [DiscordSRV] System DNS FAILED to resolve hostname discord.com, switching to fallback DNS servers!
> [09:18:47] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 5121ms or 102 ticks behind
> [09:18:48] [DiscordSRV - JDA Rate Limit/ERROR]: [DiscordSRV] System DNS FAILED to resolve hostname discord.com, switching to fallback DNS servers!

LOOK at the last 4 lines of the log.
this message  :
"[DiscordSRV] System DNS FAILED to resolve hostname discord.com, switching to fallback DNS servers!" 
AND I am using the DISCORD SRV 1.21.2

**Comment by jobless-exe** [comment]
Is this is a bug or a problem from my side?
.................

**Comment by Vankka** [comment]
This is a issue with your server's internet/dns connection

**Comment by jobless-exe** [comment]
@Vankka  so what I can do?

**Comment by Vankka** [comment]
If you're using a "Minecraft server host", contact them. Otherwise make sure the internet connection of the server is working to begin with and that there's nothing blocking the server from connecting to dns servers and Discord
