### ISSUE TITLE
Bungee component issues "Don't know how to turn ... into a Component"

### ISSUE THREAD

**Issue by crashdemons** [DiscordSRV/DiscordSRV#961]
Hello, we're currently discussing the cause of a recent GSON exception on multiple servers (ref https://hub.spigotmc.org/jira/browse/SPIGOT-6056 )

while checking jars for conflicting namespaces, I noticed that DiscordSRV shades in multiple libraries that are shared by other plugins because they are shaded in at the same namespace,
this could cause conflicts and exceptions if there are version differences - so it's preferred that shaded libraries are 'relocated' to a plugin namespace (like com.google.gson -> discordsrv.com.google.gson or whatever)...

Anyway I thought I would bring this up and make the suggestion, feel free to ignore me if this is misinformed.

**Comment by granny** [comment]
there's already a PR that was opened up with the issue you mention in https://github.com/DiscordSRV/DiscordSRV/pull/960

**Comment by Scarsz** [comment]
#960

**Comment by crashdemons** [comment]
ah apologies, I had checked yesterday and didn't see the PR
