### ISSUE TITLE
Updating does resets some configs

### ISSUE THREAD

**Issue by Armoured-Monkey** [DiscordSRV/DiscordSRV#966]
Whenever I have updated the plugin, parts or all of linking.yml get reset. This is mainly noticeable by the first setting.

Require linked account to play: 
  Enabled: true

gets reset to

Require linked account to play: 
  Enabled: false

This breaks the security of the server, and should not happen.

**Comment by Vankka** [comment]
Duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/212
