### ISSUE TITLE
Playing: in description is not updated

### ISSUE THREAD

**Issue by QuillOmega0** [DiscordSRV/DiscordSRV#973]
The bot does not seem to be parsing the  DiscordGameStatus setting and replacing the flags

DiscordGameStatus: "Players: %playercount%"
Discord reports: Playing: Players: %playercount%"

**Comment by Scarsz** [comment]
`%playercount%` is not a valid placeholder for that, use PlaceholderAPI placeholders

**Comment by QuillOmega0** [comment]
> `%playercount%` is not a valid placeholder for that, use PlaceholderAPI placeholders

I see, I had the default placeholder from the configuration so I was confused when I double checked. Thanks!
