### ISSUE TITLE
Channel updater set to update only on server load

### ISSUE THREAD

**Issue by QuillOmega0** [DiscordSRV/DiscordSRV#974]
I believe there should be a way to set the channel updater to only refresh when the server first loads but not do a periodic refresh.

This will allow ChannelTopicUpdaterChannelTopicsAtShutdownEnabled: true to be set

While allowing a onetime update of an offline notification in the topic, as well as an online notification without flooding the audit log.

**Comment by Scarsz** [comment]
You can just set the refresh time to a large number, I don't really feel like this needs to be it's own feature

**Comment by QuillOmega0** [comment]
I see where you're coming from, what's the maximum value it can take. While setting the refresh duration to 0 in my opinion would be intuitive of a setting.

**Comment by Vankka** [comment]
Integer maximum, `2147483647`

**Comment by QuillOmega0** [comment]
Yep, that'll be a good workaround as it's in minute updates. I recommend updating the configuration template and specify a range of values that are able to be put in
