### ISSUE TITLE
Issue with DiscordSRV on multiple spigot instances

### ISSUE THREAD

**Issue by Fluxty** [DiscordSRV/DiscordSRV#976]
MC version: 1.8.9
Discord SRV: 1.21.2

Hello, when DiscordSRV is present on multiple Spigot instances and a user links their account, the linking player recieves a bunch of spam:

![image](https://user-images.githubusercontent.com/8310991/104488270-bdee5a00-5593-11eb-8c8c-981171816bfd.png)

There is also this error on every single Spigot instance that comes after the first:

https://gist.github.com/Fluxty/994617b6ec9a6434be4beb17f3c2e8f1

This seems fairly benign, but it results in the AccountLinkedEvent not firing on whatever servers this error happens on, which is blocking us from being able to reward users on the server they are online the very first time they link their account.

**Comment by Androkai** [comment]
Are you using the same application (BotToken) on every server? Because that is unsupported and would explain the error and multiple messages you get.

**Comment by Fluxty** [comment]
> Are you using the same application (BotToken) on every server? Because that is unsupported and would explain the error and multiple messages you get.

Yes, we are the Good Gaming network (Bungeecord) and have a Good Gaming Discord, but on the server itself we multiple instances of both SkyBlock and Prison. It would be a bit strange if there were multiple discord bots in the discord, and confusing for users to link their account. Is this functionality really unsupported? :(

**Comment by Scarsz** [comment]
DiscordSRV isn’t meant to be on a shared token, period. I’d love to change that but at this point it would be easier to just completely rewrite the plugin with it in mind.

Since you have the SQL account linking setup, people can message any of the DiscordSRV bots to link their account and it would work fine.

**Comment by Fluxty** [comment]
> DiscordSRV isn’t meant to be on a shared token, period. I’d love to change that but at this point it would be easier to just completely rewrite the plugin with it in mind.
> 
> Since you have the SQL account linking setup, people can message any of the DiscordSRV bots to link their account and it would work fine.

Thanks, but I suppose the accountlinkedevent would only fire for the server the bot they messaged is tokenized too. Regardless, I understand, thanks for clearing that up.

**Comment by Androkai** [comment]
> I suppose the accountlinkedevent would only fire for the server the bot they messaged is tokenized too

Correct, you need a small plugin on each server listening to the event and is for example adding a group to the player that is then propagated through the network or that is propagating it with own events etc. DiscordSRV is currently unable to do it.
