### ISSUE TITLE
DiscordSRV not reading PAPI correctly

### ISSUE THREAD

**Issue by QuillOmega0** [DiscordSRV/DiscordSRV#977]
Trying to set the Playing indicator:

DiscordGameStatus: "%playerlist_online,normal,yes,amount% players"

Per the example in the documentation but it reports 0 players playing at all time. I manually had papi parse it from the console and it reports the correct count of users. There are no errors in the console

**Comment by Vankka** [comment]
Have you checked that the game status is being updated properly?

**Comment by QuillOmega0** [comment]
Yep, game status is being updated properly otherwise and when I manually queried the papi plugin from the console it gave with the same variable it gave the correct number of players.

However it reports 0 players at all times in the DiscordGameStatus.

**Comment by Vankka** [comment]
Worked fine for me, cannot reproduce.

**Comment by mibby** [comment]
@Vankka I seem to also be experiencing DiscordSRV not reading placeholders properly. 

DiscordSRV-Build-1.22.0-SNAPSHOT-1611940157
PlaceholderAPI 2.10.10 dev 122


```
MinecraftChatToDiscordMessageFormat: "[%server_time_h%:%server_time_mm% %server_time_a%] **%javascript_prefix%** %displayname% &f» %message%"
MinecraftChatToDiscordMessageFormatNoPrimaryGroup: "%displayname% &f» %message%"
```

![link](https://i.imgur.com/FlD0Z7b.png)

The custom javascript
```
var prefix = "%deluxetags_tag%";

function hasPrefix()
{
  if (prefix == '')
  {
    return "&8<&7%vault_rank%&8>";
  }
   else {
       return "%deluxetags_tag%";
   }
}

hasPrefix();
```

It parses fine in-game when testing with ``/papi parse <name> %javascript_prefix%`` and displays fine used everywhere else.

This use to work fine for me but I assume broke in a recent update. Old channel message proof from a month old snapshot build.
![link2](https://i.imgur.com/t1xaHIN.png)

**Comment by Vankka** [comment]
@mibby Unrelated issue. Was caused by it being surrounded in < and >, issue is fixed on latest development build

**Comment by mibby** [comment]
Ah, I see. Well in any case, thanks for the quick fix!

**Comment by QuillOmega0** [comment]
After deleting and having the config recreated and performing a full update the issue has disappeared.
