### ISSUE TITLE
DiscordSRV receives 429 errors from Mojang API

### ISSUE THREAD

**Issue by Andre601** [DiscordSRV/DiscordSRV#981]
When using DiscordSRV, does the console constantly print out the following line whenever a player joins or leaves:
```
[22:38:59 WARN]: Bad response from Mojang API for Andre_601 -> 429 429 - Too Many Requests
```

After systematically removing plugins and checking again was the result that DiscordSRV is printing the above line. This was confirmed by running the server again with all Plugins except DiscordSRV and then with DiscordSRV again, which confirmed this problem.

My guess is, that the API used for retrieving head textures (Crafatar) may have been rate limited by the Mojang API and is probably returning this error now.

**Comment by Scarsz** [comment]
That would be the profile API which isn't associated with Mojang's API

Likely this is a shared server and someone else is abusing the API because DiscordSRV caches profiles retrieved from it

**Comment by Andre601** [comment]
It's an own dedicated VPS, so it can't be the cause of a shared host.
I just report what I found out which is, that the 429 error only appears once DiscordSRV is running and a player is joining or leaving the server.
