### ISSUE TITLE
Heads image in discord chat show up as different/old heads on PC vs Mobile

### ISSUE THREAD

**Issue by brobie1kanobi** [DiscordSRV/DiscordSRV#984]
Hey,
    There is an issue with player heads not showing up correctly on the PC in the "chat" channel setup to receive "joins and quits", yet it shows up normally on the mobile app.

**Steps to reproduce**:
1. Install the latest version of everything (paper, discordsrv, etc.)
2. Setup the forwarding chat channels and "join and quit" messages
3. Join the server and look at the channels output in both the PC version and mobile Discord apps
4. Disconnect from the server, change skins and rejoin
5. Check the output again and you will see the PC version does not show the same/updated skin.

Extra info:
 I'm running the latest build of SRV and the latest version of Paper. This seemed to happen when I changed skins, yet I assume it's an SRV issue as it works on the mobile app.

**Comment by Vankka** [comment]
This has already been fixed on development builds, https://snapshot.discordsrv.com
