### ISSUE TITLE
[Snapshot] &r is replaced with the top role color in discord->mc

### ISSUE THREAD

**Issue by saboooor** [DiscordSRV/DiscordSRV#992]
![image](https://user-images.githubusercontent.com/42164502/105655292-0a337700-5e7d-11eb-8e7e-decddf55a912.png)
the message color is the top role color when it should be white with &r, replacing &r with &f can be used as a workaround though
`DiscordToMinecraftChatMessageFormat: "%toprolecolor%%toprolealias% §x§5§5§7§7§9§9• %toprolecolor%%name% §x§5§5§7§7§9§9› &r%message%"`
https://bin.scarsz.me/ea438aeb-cdb5-49a9-9232-6fa89b308523#U9ZEFGrJ2bUZQpxjaAUaLQyRXl5PHwGB

**Comment by saboooor** [comment]
![image](https://user-images.githubusercontent.com/42164502/105656652-ed4c7300-5e7f-11eb-8601-be942eb37882.png)
this also happens with the reserialization since there's an &r in it
```
*test* test
**test** test
test > test
```

**Comment by Vankka** [comment]
Fixed on latest development build https://snapshot.discordsrv.com
