### ISSUE TITLE
[Snapshot] %toprolecolor% is broken when image/file is sent

### ISSUE THREAD

**Issue by saboooor** [DiscordSRV/DiscordSRV#993]
![image](https://user-images.githubusercontent.com/42164502/105655561-7f9f4780-5e7d-11eb-8fb6-cabd113475e6.png)
`DiscordToMinecraftChatMessageFormat: "%toprolecolor%%toprolealias% §x§5§5§7§7§9§9• %toprolecolor%%name% §x§5§5§7§7§9§9› &r%message%"`
https://bin.scarsz.me/ea438aeb-cdb5-49a9-9232-6fa89b308523#U9ZEFGrJ2bUZQpxjaAUaLQyRXl5PHwGB

**Comment by Vankka** [comment]
Fixed on latest development build https://snapshot.discordsrv.com
