### ISSUE TITLE
[Snapshot] Message is cut off after toprole

### ISSUE THREAD

**Issue by saboooor** [DiscordSRV/DiscordSRV#994]
![image](https://user-images.githubusercontent.com/42164502/105655827-1966f480-5e7e-11eb-8bef-0ce525840c66.png)

`DiscordToMinecraftChatMessageFormat: "%toprolecolor%%toprole% §x§5§5§7§7§9§9• %name% §x§5§5§7§7§9§9› &r%message%"`

Weirdly this doesn't happen if you add %toprolecolor% before %name% as well

**Comment by Vankka** [comment]
Fixed on latest development build https://snapshot.discordsrv.com
