### ISSUE TITLE
Slightly misleading information in the comment of DiscordInviteLink

### ISSUE THREAD

**Issue by Andre601** [DiscordSRV/DiscordSRV#998]
I've noticed that when I removed `DiscordInviteLink` that the plugin was reporting this and would use a default value.

However, this wasn't the case at all.
The comment for the DiscordInviteLink option is mentioning the following:
> # Invitation link shown to players when using /discord and on the message shown to unlinked players when linking is enforced

While I'm not sure about the second case (forced linking) is the first one wrong, as the setting has been a part of the messages.yml for several versions, making this comment incorrect.

If forced link actually also uses the messages.yml, which would make sense as it would otherwise be the same text twice, is the above option even pointless and no longer needed.

**Comment by Vankka** [comment]
The `DiscordInviteLink` option is used for `{INVITE}` in `DiscordCommandFormat` and `Not linked message` as is stated in their comments. Obviously if those options don't have that placeholder, the content of `DiscordInviteLink` wouldn't be added to those options.

**Comment by Andre601** [comment]
Yeah, no. The comment in the config.yml states that it is used for the `/discord` command, which actually is the job of the message.yml and does in no way mention that it would *only* be used for a placeholder there.

**Comment by Vankka** [comment]
With default configurations, the comment is correct. It's only if someone goes out of their way to remove the placeholder from one of the options (or upgraded from a old version, in which case it says to change the url in the messages.yml or linking.yml) is it incorrect. This is only really a issue if someone goes through trying to change the url in the config with one of previous conditions, which I find quite unlikely. If someone wants to PR a change to the language, they're free to do so - but I don't find this a necessary change

**Comment by Scarsz** [comment]
Closing this because inactivity, feel free to PR something to address it if you'd like
