### ISSUE TITLE
DiscordSRV is constantly causing my server to crash

### ISSUE THREAD

**Issue by Corbinator333** [DiscordSRV/DiscordSRV#999]
Hey so every couple hours or so, DiscordSRV causes my server to crash, and most of the time lose all of the progress made since the last time the server crashed/restarted, and I really don't want to get rid of this plugin. It's a lifesaver. Error: https://hatebin.com/iykcjqjjrc

**Comment by Scarsz** [comment]
Crash from this log has nothing to do with DiscordSRV as indicated by the main server thread waiting on something that isn't DiscordSRV
